### ISSUE TITLE
Self serve flow

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1115]
# Problem

Any open collective needs to have a host, a legal person or entity that holds the money on behalf of the collective.

We have created a host for Open Source Projects ([The Open Source Collective 501c6](https://opencollective.com/opensource), European Collectives (https://opencollective.com/europe), UK Collectives (https://opencollective.com/uk), collectives in Brussels (https://opencollective.com/brusselstogether) and collectives in Paris (https://opencollective.com/paris).

If your collective doesn't fall into any of those categories, you are out of luck and you cannot create a collective today.

Also, because the host is taking on some liabilities, there is an approval process which slows down the on boarding.

Last but not least, most collectives will have a yearly budget of less than $10k under which it may totally be fine for them to host personally a collective without having to report that as taxable income in their local jurisdiction. In those cases, the added value of having an external host that charges another 5% is not really worth it.

# Opportunity

The biggest opportunity is to enable anyone to create an open collective without having to have a host entity. We will also reduce the legal risk since there will be many more hosts.

# Risks

The bigger risk is that we can have hosts that are less trustworthy.
Since we do not control their bank account, we have no way to verify that they are good actors and that they are not using money meant for the collectives they host for other purposes.

# Mitigations

We need to make it super clear in the interface who is the host of the collective and give the user all the information they need to make an informed decision on whether or not the host is trustworthy.

For most collectives that operate in meat space, it won't matter much as people usually know one another and they are already operating today with one person designated to keep the money for the community.

In the ideal scenario, we can create a bank account on behalf of the host using MangoPay in Europe or Synapsefy in the US and keep full control of the money. But that's a much bigger project.

# Milestones

1. [ ] Turn an existing organization into a host

Since we already have a way to create an organization, the goal here is to allow to connect a stripe account to it.

2. [ ] Turn a user into a host

Right now we only allow organizations to be a host. But an individual should also be able to connect a Stripe account and host one or multiple collectives.

3. [ ] New flow to create a collective

By default, a new collective shouldn't have any host connected and we should ask the user if they want to apply to get it hosted by an existing host or if they want to create a new host.

![](https://d.pr/free/i/NwTdJS+)

**Comment by xdamman** [comment]
Here is a screencast of the flow when selecting an individual as the host:
https://d.pr/free/v/gcLhfY

**Comment by xdamman** [comment]
I have the flow for selecting an existing or a new organization as a host working. 
Screencast: http://recordit.co/X6E92fvbzU

**Comment by cuiki** [comment]
Hi Xavier, should I implement the new styles to all this flow after I finish "Back your Stack" or should I move on to Pledges?

**Comment by xdamman** [comment]
@cuiki After "Back Your Stack", it would be good to go back to the homepage to unblock @HipsterBrown  (the create collective section). Then, let's circle back after all that to see what's best to work on at that time. It will probably be Pledges. But let's see then.

**Comment by xdamman** [comment]
This has been deployed on August 6.

Here are some stats after one month:

New hosts:

1 June
1 July
8 August 
11 till September 14th

In terms of number of new collectives:
72 June
84 July
118 August 
53 till September 14th

**Comment by piamancini** [comment]
thanks @xdamman this is super useful! I don't think number of new collectives is a good metric but number of new hosts is super useful.
