### ISSUE TITLE
EPIC → Email Templates (Design update and normalization)

### ISSUE THREAD

**Issue by cuiki** [opencollective/opencollective#1187]
This issue is meant to list all existing (and new) email templates we send out, so we can prioritize their re-design.

@piamancini , when you have a chance would you help me out listing them here with a quick screenshot for each one of them in their current state, please?

—

- [ ] Normalize welcome email regarding the 2 types of collectives open source other initiatives.
- [ ] Explore the the option "Welcome email"related to on boarding of Github flow.
- [ ] Show a preview of invoice/receipt in "New expense".
- [x] change all typefaces to system font (Helvetica).
- [x] Organize Figma file by recipient.

- [ ] Normalize the email signatures (i.e)When signed by Pia herself or when signed by Open Collective Team.
All email templates will be added here:
https://invis.io/YXN6HZZKTRF

**Comment by cuiki** [comment]
Small update so issue doesn't get closed:


![sponsor report](https://user-images.githubusercontent.com/981188/48842619-509b6180-ed5a-11e8-8017-8c513db5db22.jpg)

![welcome email 2 days desktop](https://user-images.githubusercontent.com/981188/48842620-509b6180-ed5a-11e8-9e84-0ef317dc1b99.jpg)

**Comment by Mayekita** [comment]
I'll resolve this Issue, as I can see almost all of the templates are basically a copy that needs to be adjusted and change everything to the current design. 
I don't think this takes me so long, but I'll give it this week, to finish them and as soon as I finish them i'll be ping you @cuiki on Figma, so you can check on them and add feedback if needed.

**Comment by cuiki** [comment]
Please, let me know when you finish a batch of five to do a quick recap and review and then move on with the rest.

**Comment by alannallama** [comment]
@cuiki we updated the onboarding emails for new Open Source Collective Collectives, and for newly created Organizations. What still needs to be done? Should we roll out the changes made to OSC onboarding to the rest of the hosts? Are there any stats about if the new emails for OSC are showing improved engagement?
