### ISSUE TITLE
EPIC → Expense Flow (Design Revamp)

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1326]
This is a global issue for the expense flow revamp. The goal is to start a list of issues (bugs and requests) to link several issues opened on this topic as a first step. The second step should be a proposal for an MVP and a design spec issue as well as opening specific feature issues for the features. 

## Requests / New Features

- [x] Batch Upload: 
As an event organiser, I want to submit expenses en masse for categories of expense. https://github.com/opencollective/opencollective/issues/1324

- [x] Reject expense should force a comment explaining why the expense is being rejected. https://github.com/opencollective/opencollective/issues/1205

- [ ] Improve navigation. We should be able to go to next/previous expense in same collective (or if coming from the host dashboard, to the next/previous expense of the current selection, e.g. all approved expenses ready to be paid across all hosted collectives)

- [ ] Attach invoices to Thank You emails. It makes is easier for sponsors to forward without downloading it, saving and attaching. 

- [x] Submit an invoice in the currency of the expense and we take care of conversion. https://github.com/opencollective/opencollective/issues/101

- [x] Bot to submit an expense via email. This is particularly useful for uber/lyft and also recurring monthly expenses (server costs, etc) https://github.com/opencollective/opencollective/issues/1054

- [ ] An event admin / attendee submits an expense for reimbursement and wants to know if this should be submitted in the main collective or event collective. Feature Spec needed

- [ ] An event organizer wants to move funds in the main collective to the event collective to pay for event expenses. Feature Spec needed.

- [ ] A  host admin wants to add funds to an event collective. Feature Spec needed.

- [x] Add a category expense / reimbursement when submitting an expense for the W9 Bot. https://github.com/opencollective/opencollective/issues/1305

- [ ] Support for alternative payout methods https://github.com/opencollective/opencollective/issues/1217

- [ ] create an invoice for users on the fly https://github.com/opencollective/opencollective/issues/1167

- [ ] Allow for the paypal email to be edited after an expense has been submitted https://github.com/opencollective/opencollective/issues/1132

- [ ] Display an alert when an expense is the exact amount of the collective's budget (It can't be paid due to fees.) https://github.com/opencollective/opencollective/issues/1073

- [x] Activate w9 bot on expense submission instead of approval https://github.com/opencollective/opencollective/issues/1305

- [ ] Better search for expenses - Sometimes these need to be altered if PayPal returns the payment and it's impossible to find them https://github.com/opencollective/opencollective/issues/1149

- [ ] Automatically update the expense activity/status in the comments https://github.com/opencollective/opencollective/issues/1071 

## Bugs in existing flow:
- [ ] When we file invoices that are directly paid by the host, we are currently recording the CREDIT transaction from the perspective of the user who submits the expense. This is incorrect. Since the expense was paid directly to the vendor. https://github.com/opencollective/opencollective/issues/1284

- [x] Comments on expenses are sometimes not loading properly. https://github.com/opencollective/opencollective/issues/1206 Imho this is a caching issue they load but it takes a while. 

- [x] Pay With Donation has several issues. Imho as is it doesn't work and should be disabled. 
Examples: 
when making an in kind donation, the system checks if there's enough balance in the collective because it treats it as an expense. 
It also creates an double entry in the collective for the amount when in fact this transactions never happened. https://github.com/opencollective/opencollective/issues/1083

- [x] w9 bot is going to other hosts. This should be opt in and emails should go to the relevant host https://github.com/opencollective/opencollective/issues/1220

- [x] PayPal Balance is broken - it never updates when refreshing key https://github.com/opencollective/opencollective/issues/1061

## Design Improvements 
- [ ] Make attachments bigger to remove the need to open a new window

- [ ] Show the history of that user (previous expenses from same user, total expensed) (I think @xdamman was thinking of the particular expense page for this)  

- [ ] host dashboard dropdown is close to unusable for large hosts. https://github.com/opencollective/opencollective/issues/1070

- [ ] Show who approved an expense. WWcode would love to admins to approve expenses but they want to know who approved them. https://github.com/opencollective/opencollective/issues/705

- [ ] Make currency visible when submitting an expense. https://github.com/opencollective/opencollective/issues/478

- [ ] The system does not make it clear that attachments will not be visible publicly, causing users to be concerned about privacy https://github.com/opencollective/opencollective/issues/1222

- [ ] Copy changes in expense display screen #1077

- [ ] Improve Date Format  - It has a number for 
 a day and a number for a month and this varies across countries. https://github.com/opencollective/opencollective/issues/1072

**Comment by piamancini** [comment]
cc / @cuiki @alannallama @xdamman

**Comment by alannallama** [comment]
Has this list been prioritised? There's a whole list of improvements I've raised as issues that aren't on here.

**Comment by alannallama** [comment]
OK here are the other ones I don't think have been mentioned above:

* #1167 - system automatically creating invoices (design addresses #1222 #1132 #1073 as well)
* #1305 - tax from bot on submission instead of approval
* #1149 - connect paypal and OC transactions
* #1061 - paypal balance broken
* #1077 - wording changes
* #1072 - change date format
* #1071 - activity updates

**Comment by piamancini** [comment]
@alannallama All of the above are added in the main comment list. Thank you

**Comment by alannallama** [comment]
Another one @piamancini : the W9 bot currently tells people they have to submit a tax form even if they are are asking for an expense reimbursement, not invoicing for time, which is incorrect. The design in #1167 could fix this, as it differentiates expense types as part of the submission process.

**Comment by alannallama** [comment]
Added #1349 to improve experience for logged out users seeking to comment on expenses.

**Comment by cuiki** [comment]
A few more issues that fall into this:

- #1222 - Clarify privacy of attachments when expense is created.
- #1148 - Provide reason when expense is rejected.

Community ideas and feedback:
- #1379 - Invoice automation
-  #1182 - Select currency per event, expense, ticket & sponsor.

**Comment by xdamman** [comment]
Not sure if this is the right place but the more I work with collectives, the more I realize the importance of allowing anyone to submit an expense without having to register for an open collective account.

It has to be seamless. Let me upload an invoice/expense and *then* ask me for my email address. That should be the flow from the user perspective.

I understand the engineering challenge that this creates but this is what engineering is all about: solving problems for users :-)

**Comment by cuiki** [comment]
So if we do this, we should then offer small tools or features that'll encourage (assuming that submitting expenses is the level of interaction of these users) them to sign up. Things like saving their payout information and not having to enter it every single time (i.e. wire-transfer information).

It might not look like a big example but thinking about these actions might help opening the door to other opportunities to grasp with these users.

**Comment by xdamman** [comment]
Totally. I think a good example of that is Eventbrite (and many e-commerce websites). They let you checkout (or RSVP) without requiring you to create an account to make sure that there is nothing preventing you from completing that important user flow. But at the end they offer you to create an account to save your info for next time.

**Comment by alannallama** [comment]
It's fine to get them straight into submitting the expense and only later create their account once they give us their email, but how will we handle tax forms and if they need to edit the expense, both of which come up all the time?

**Comment by piamancini** [comment]
closing in favour of https://github.com/opencollective/opencollective/issues/2394
