### ISSUE TITLE
Internal communication

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1753]
Notes from the meeting in Lisbon with @piamancini and @znarf.

**Goal:** Have productive communications as we grow as a decentralized team

- stand up meetings don’t scale
- language issue: not everyone is comfortable in verbal communication in English: offer english lessons as a perk?
- Slack: we will always need a synchronous way to communicate
- email overload
    - expectation that people reply if put in To: (in Cc it’s FYI)
    - Not clear in threads who is reading it
- Use github issues more and [Octobox](https://octobox.io)
- Be respectful of other people’s time (to be added to "The Open Collective Way")
- Code review: expectation of 24h response time (outside of weekends)

- Friday open call
    - Maybe reconsider time (try different times, get feedback)
    - Record it and publish it (we can use Zoom for that)
    - Lacking structure:
        - Would be good to have slides (collaborative google slides)
        - Anyone should be able to add items to the agenda
        - New structure:
            - intro
            - 1-2 sentences to introduce yourself and say what you worked on that week
            - demo 1, demo 2 if any
            - Q & A
            - Closing remarks

## Protips

- Star Team channel and team members in Slack (https://slack.opencollective.com)
- create email filters

## TODOs
- [ ] send notifications not from info@opencollective but support@opencollective.com (so that people can reply directly to support and don’t overload info@)
- [ ] add to weekly report the latest active issue still open
- [ ] close forum
- [ ] Put the weekly meetings and monthly emails to git book
- [ ] Xavier: check gitbook api to automate some of that
- Improve weekly email:
    - [ ] remove non useful numbers
    - [ ] add github issues still open / updated
    - [ ] keep active collective / new collectives
    - [ ] tweet the 50 backers milestones

**Comment by piamancini** [comment]
some of the things here are done, some are still worth doing. 
automating a thank you tweet for 50 backers (currently is 10 and 100) is worth it
@znarf could that be a bounty?

**Comment by znarf** [comment]
@piamancini yes, someone needs to create the issue for it.
