### ISSUE TITLE
Remove markdown editor

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1805]
Following https://github.com/opencollective/opencollective/issues/1799#issuecomment-471007636

# Motivation

There are some drawbacks in having to maintain two different editors that can be changed by the user in settings:
- Bigger bug exposures
- Time consuming to maintain
- Experience is not unified: some rich-text fields use it, some doesn't
- We're duplicating data by having both `markdown` and `html` db columns

So there's some cost in supporting this and - in my opinion - little gain: as much as I like markdown, using a WYSIWYG editor doens't seems like be a blocker.

# Proposition

Remove the markdown editor to only keep the `HtmlEditor` that has a simple interface and is already used widely across the site.

![image](https://user-images.githubusercontent.com/1556356/54115697-4b3b5300-43ed-11e9-9df2-1dd1acfbf305.png)

We can also have a plan to migrate to https://github.com/sstur/react-rte which relies on `draft.js`, is strongly tested + maintained and comes unstyled which fits well with our styled-components approach. **That should however be part of another issue / PR.**

# TODO

- [ ] Ensure all db `markdown` columns are migrated to `html` and remove them
- [ ] Remove "editor" from settings
- [x] Remove all usages of the `MarkdownEditor`
- [x] Remove `react-mde` dependency

**Comment by znarf** [comment]
I don't think we have collected enough feedback or reached consensus on that one. Let's give it some time before moving forward with it.

**Comment by xdamman** [comment]
While I agree with the intent and all the arguments, I see a lot of updates from the open source community that include code blocks. 
We could have only one editor but it should support markdown. Maybe we can use markdown within an html editor?

Anyhow, I think that we should wait for v3 and the new messaging system. But curious if you have any recommmendations for a good editor that could handle both.

**Comment by Betree** [comment]
https://patleeman.github.io/quill-markdown-shortcuts/ is a plugin for `react-quill`, the editor that we already use today on OC. It makes typing faster if you know markdown, but anyone can actually use it.

**Comment by maddhruv** [comment]
@Betree @znarf any update on this? Are we going with the idea of removing the `MarkdownEditor` completely and use the `react-quill` editor with markdown support or any other solution you have?

**Comment by znarf** [comment]
This issue is up to date, it's not a priority but it's still on the table, nothing to add today.

**Comment by Betree** [comment]
All that's left to do to resolve this issue is:
- Remove all `markdown` columns from the DB
- Remove "editor" from settings
