### ISSUE TITLE
Use rich text editor for collective's description

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1806]
As of today, collective's long description supports markdown to build rich collectives descriptions. Users that don't know about markdown are not aware of this feature and in consequence they can't customize their profiles.

We should provide a rich text editor for everyone to be able to easily customize their description.

As per https://github.com/opencollective/opencollective/issues/1805, the rich editor used for this should be `HtmlEditor`, not `MarkdownEditor`.

## TODO

- [ ] Add the rich editor to the edit collective page
- [ ] Ensure all existing descriptions are properly migrated
- [ ] Ensure content is properly sanitized

**Comment by znarf** [comment]
I don't think we have collected enough feedback or reached consensus on that one. Let's give it some time before moving forward with it.

**Comment by Betree** [comment]
Closing this as the new collective page will address this issue by using an inline editor for the description. See https://github.com/opencollective/opencollective-frontend/pull/1870
