### ISSUE TITLE
Recap: User requested features

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1851]
Before we keep digging into the new collective page as is, I wanted to do a recap of all requests from users (and our ideas) that we didn't do yet to see if there aren't concrete things users ask for that we are forgetting about and we should include in the design. Some of these come from old issues, others from conversation with users, some were closed by stale bot, some we said at the time it wasn't a priority. 

This is not a list of things to do, is a way to make sure there's nothing we are inadvertently leaving behind and some of them relate to current Q2 priorities. 

### Tiers Management
- [x] Fundraise Goal Tiers (funding for our next event, or funding to pay for X) wit progression bar
- [ ] Option to edit questions asked when people register to an event https://github.com/opencollective/opencollective/issues/427
- [ ] Sponsors should be shown in the proper tier even when they used the /donate url https://github.com/opencollective/opencollective/issues/1406
- [ ] allow tiers to have both yearly and monthly options https://github.com/opencollective/opencollective/issues/1754
- [ ] Add the ability to request extra info from backers when purchasing a tier https://github.com/opencollective/opencollective/issues/1798
 
### Host Management 
- [ ] Let hosts edit the thank you email (collectives would be great too but it's more work since it requires hosts' approval 
- [x] Allow hosts to set themselves the host fee per collective https://github.com/opencollective/opencollective/issues/341
- [ ] Allow hosts to delete transactions that were manually entered - We get a fair bit of requests from WWCode to delete manual txns donde by mistake. => https://github.com/opencollective/opencollective/issues/4429
- [x] Improve error message when preapproval key needs to be refreshed https://github.com/opencollective/opencollective/issues/442 (and OC-Paris recently)
- [ ] Allow host to confirm reception of w9 https://github.com/opencollective/opencollective/issues/1200

###  Donations
- [ ] Automatically donate to projects you depend on https://github.com/opencollective/opencollective/issues/178 and https://github.com/opencollective/opencollective/issues/894
- [ ] Donations via Alipay (https://docs.google.com/document/d/1VVHZtCZquKat5eXZkoBzWEp3WMgy-K8XS87yo8XvkXQ/edit#heading=h.rfrjihugg90e)
- [ ] Have a donation budget collectives can set to give to other collectives https://github.com/opencollective/opencollective/issues/348
- [ ] Support importing donations from other platforms https://github.com/opencollective/opencollective/issues/882 and https://github.com/opencollective/opencollective/issues/1741 (plus several email requests)
- [x] Enable PayPal for more fiscal hosts https://github.com/opencollective/opencollective/issues/1655

### Expense flow 
- [ ] Let collectives decide if they want anyone to be able to submit an expense or only their contributors https://github.com/opencollective/opencollective/issues/261
- [ ] Include in expense flow a way for user to say if it's a reimbursement or an invoice (only send the w9 bot email in the case of an invoice)
- [x] Allow better view of actual date and time in expenses https://github.com/opencollective/opencollective/issues/357 (also requested again recently by fbopensource admin)
- [ ] recurring expenses https://github.com/opencollective/opencollective/issues/938
- [ ] Attach invoice to thank you email https://github.com/opencollective/opencollective/issues/932
- [x] Batch upload invoices #1324
- [ ]  Reject expense should force a comment explaining why the expense is being rejected. #1205 and https://github.com/opencollective/opencollective/issues/1148
- [ ] Submit an invoice in the currency of the expense and we take care of conversion. #101
- [ ] Bot to submit an expense via email. This is particularly useful for uber/lyft and also recurring monthly expenses (server costs, etc) #1054
- [x] create an invoice for users on the fly #1167
- [ ] Virtual Credit cards for Collectives https://github.com/opencollective/opencollective/issues/1038 and https://github.com/opencollective/opencollective/issues/1657
- [ ] Support for other payout methods https://github.com/opencollective/opencollective/issues/1217
- [x] Don't round monetary amounts https://github.com/opencollective/opencollective/issues/1773 and https://github.com/opencollective/opencollective/issues/1177

### Localization
- [x] Language selection https://github.com/opencollective/opencollective/issues/260

### Contact Collectives
- [x] Add a contact in collective page footer https://github.com/opencollective/opencollective/issues/292 and https://github.com/opencollective/opencollective/issues/1849

### Collective Page(s) Design
- [ ] Bring back showing github contributors to the collective page https://github.com/opencollective/opencollective/issues/282
- [x] Show a separate page for currently active subscriptions (https://github.com/opencollective/opencollective/issues/320)
- [ ] Event description should indicate markdown is supported https://github.com/opencollective/opencollective/issues/426
- [x] Better design of event list https://github.com/opencollective/opencollective/issues/430 (This should be solved in the new collective page, but double checking)
- [ ] Show sponsors as inactive in collective page when they stop contributing https://github.com/opencollective/opencollective/issues/1082
- [ ] Allow collectives to have a preview mode before launching https://github.com/opencollective/opencollective/issues/1706

### User Rights 
- [x] User editing of their email address #1711 
- [x] Give backers the option to show which company/org they belong to https://github.com/opencollective/opencollective/issues/518
- [ ] Allow organizations to include a Billing Address in the front end 
- [ ] Allow users to edit (some) content in invoices for certain tiers https://github.com/opencollective/opencollective/issues/1379

### Outreach Tools
- [ ] Sync events from an ics or Microformats2 feed https://github.com/opencollective/opencollective/issues/429 (this can be part of the helping collectives do outreach Q2 priority)
- [ ] Allow collective admins to share their updates on social media https://github.com/opencollective/opencollective/issues/465 (also Q2 priority)
- [ ] 3rd party use cases for consumption of API and documentation requests https://github.com/opencollective/opencollective/issues/464
- [ ] Beautiful twitter cards for sharing links https://github.com/opencollective/opencollective/issues/1108
- [ ] Automatically sync events from meetup.com https://github.com/opencollective/opencollective/issues/1515

### Sign in 
- [x] Add 2FA authentication login https://github.com/opencollective/opencollective/issues/459 and https://github.com/opencollective/opencollective/issues/1746
- [ ] Allow login with decentralized identifier https://github.com/opencollective/opencollective/issues/1749

### Other
- [ ] Accommodate links that are not open collective specific https://github.com/opencollective/opencollective/issues/476
- [x] Add an explanation of why we need those permissions when oauth w github https://github.com/opencollective/opencollective/issues/1034 (maybe this is done already)
- [x] Let users know their credit card is about to expire https://github.com/opencollective/opencollective/issues/1093
- [ ] Better analytics
- [ ] Review onboarding PR https://github.com/opencollective/opencollective/issues/1667

**Comment by Kilheure** [comment]
I would add for the host: 
Double ledger accounting. Aka collective transaction fee registered in host budget

**Comment by Betree** [comment]
@piamancini I think `Improve error message when preapproval key needs to be refreshed #442 (and OC-Paris recently)` gets solved in https://github.com/opencollective/opencollective-frontend/pull/1553

**Comment by znarf** [comment]
@piamancini Following up on https://github.com/opencollective/opencollective/issues/1857, you should reopen all the issues that were closed as stale and you think are worth having open.

**Comment by alannallama** [comment]
Add to this from our support stats:

* User can delete own account
* Core contributor can deactivate Collective
* Make it easier to cancel subscription
* Make it easier to contact Collective directly
* Improve the tax form process

**Comment by znarf** [comment]
Closing because it's old and mostly stale.
