### ISSUE TITLE
EPIC → Collective Page (Design Revamp)

### ISSUE THREAD

**Issue by lindatalu** [opencollective/opencollective#1928]
The collective page has a long overdue re-design. This issue tracks the design progress (wireframes, mockups, prototypes, etc.)

## Background (Parent Issues)
#1744 
#1745 
#1827 

## Stories 
- [x] Move membership tiers up at **Give & Receive** section.

- [x] Remove the follow feature for conversations.

- [x] Remove join workgroups, we're holding off on this for now.

- [x] Conversation detail page is limited to replies with attachments and reactions.

- [x] Open collective badge (Halo, verified, other) Explore the best way to do it.

- [x] In conversations remove the option of attached files.

## Referenced Issues
- [ ] #1428
- [ ] #1927 
- [ ] #1784

**Comment by cuiki** [comment]
@raulgrafico This is the recorded video of Friday's call
https://drive.google.com/file/d/13IwK__uwqppIlVvW3QqXqTsDx_8fJQf5/view?usp=sharing

Please post updates to the page here as well as the subtasks created from the feedback on Friday. @Betree this issue is where you can track the progress of the page's design delivery for dev.

**Comment by cuiki** [comment]
## Pending subtasks
- [ ] Smartphone view
- [ ] Tablet view
- [ ]

**Comment by cuiki** [comment]
## Feedback Round 10

- [x] Move membership tiers up at **Give & Receive** section.

- [x] Remove the follow feature for conversations.

- [x] Remove join workgroups, we're holding off on this for now.

- [x] Conversation detail page is limited to replies with attachments and reactions.

- [x] Open collective badge (Halo, verified, other) Explore the best way to do it.

- [x] In conversations remove the option of attached files.

**Comment by Betree** [comment]
As discussed previously, from the development perspective the tablet view is bonus. If we have a good desktop view and a good mobile view, tablet will fit automatically.

So ideally we should prioritize mobile.
