### ISSUE TITLE
Tier page

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1982]
This issue will track the progress for the first iteration of the new tier page.

# Files

- All components specific to this page will go to `components/tier-page`
- `index.js` will export the main content component

# Specs

- [x] Show tier goal => https://github.com/opencollective/opencollective/issues/1978, https://github.com/opencollective/opencollective/issues/1979
- [x] Show tier backgroundImage (with default image as fallback) => https://github.com/opencollective/opencollective/issues/1980
- [x] Show tier longDescription => https://github.com/opencollective/opencollective/issues/1981
- [x] Show buttons to share goal
- [x] Show Contribute button
- [x] Show all contributors
- [x] Responsiveness

# Design

- https://www.figma.com/file/e71tBo0Sr8J7R5n6iMkqI42d/OC.COM-07-%2F-Collectives?node-id=2587%3A39809

**Comment by xdamman** [comment]
Can we keep the current nomenclature of `CollectivePage`, and therefore `components/TierPage`?

In terms of priorities, I’d put the adding share buttons at the end.

**Comment by Betree** [comment]
As part of RFC https://github.com/opencollective/opencollective/issues/1942 and for the new collective page, we decided to start having subfolders for components with kebab-case namings.

The main reason is that we shouldn't expose components that will be used only on the tier page to the global scope. Having all components in the same directory makes it hard to navigate and as a sub-consequence we don't split the code enough and often end up with components that are 1000+ lines of code.

The idea is that the component will lay in `components/tier-page/index.js` and all the others components that are specific to it will rest in the same place, separated from the global scope.

**Comment by Betree** [comment]
Done in https://github.com/opencollective/opencollective-frontend/pull/1787
