### ISSUE TITLE
Collective Page → Get Updates (EPIC #1928) 

### ISSUE THREAD

**Issue by lindatalu** [opencollective/opencollective#2033]
## Best solution for this problem

**Get updates**
Follow Updates feature on Collective Page requires to resolve the following UI assets:
- [ ]  Modal with email field
- [ ]  Modal with confirmation
- [ ] All validations required

**Responsive Views**
All these needs to be resolved on the following responsive views:
- [ ] Desktop
- [ ] Tablet
- [ ] Smartphone

## Referenced Issues
#1928 
#1999
