### ISSUE TITLE
Centralize pdf generation on a common service

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2055]
There are three places where we generate PDFs:
- Invoices (has its [own repo](https://github.com/opencollective/opencollective-invoices))
- Printable gift cards (has its [own repo](https://github.com/opencollective/opencollective-giftcards-generator))
- ~~Events nametags (lives in [frontend](https://github.com/opencollective/frontend))~~ edit: removed

All these features have pretty much the same requirements and dependencies. For all of them, we render a page to HTML then convert the page to PDF. Having 3 repos to maintain for that means three times more dependencies updates, testing to ensure nothing's broken and code duplication.

We want to centralize all these features into a single service:

- Name: `opencollective-pdf`
- URL: https://pdf.opencollective.com
- Endpoints: `/receipts`, `/nametags` and `/gift-cards`

# Todo

- [x] Rename repo
- [x] Rename deployment
- [x] Rename env variables in frontend
- [x] Plug `pdf-staging.opencollective.com` domain
- [x] Plug `pdf.opencollective.com` domain
- [x] Update domains everywhere
- [x] Remove legacy domains

**Comment by znarf** [comment]
I would suggest:
- name: `opencollective-pdf`
- implementation strategy: start from the invoices service and rename it

**Comment by Betree** [comment]
This is mostly done, we just need to rename the domain `invoices.opencollective.com` -> `pdf.opencollective.com`

**Comment by Betree** [comment]
All done
