### ISSUE TITLE
Move publicMessage from Orders to Members

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2138]
We've re-added public message form on #1772 but we're still not surfacing them in the interface. We solved this question in #1784 and now have a proper design: this message is going to be surfaced on the new collective page and on the tier page directly on the contributor's cards:

![image](https://user-images.githubusercontent.com/1556356/59840381-846f5180-9352-11e9-88c2-3cbcacfc3633.png)

To make this happen in a coherent way we must move the public message out of `Orders`: my message is linked to my membership, not to my order. If I make 5 donations to the collective, only one public message will be displayed so I should only type it one time.

The good part about linking it to `Members` is that I'll be able to set a different message for each `Tier` I contribute to, which is good for the new tier page: we'll be able to set different messages for different goals.

# TODO

- [x] Add a migation to move the messages
  - [x] Create `publicMessage` on `Members`
  - [x] Copy `publicMessage` from `Orders` to their corresponding `Member` entry
- [x] Update frontend to retrieve message and edit it from order success page
- [x] Retrieve public message for contributors (require https://github.com/opencollective/opencollective-api/pull/2127) (collective +tier pages)

Showing the message on the card is not part of this issue, see https://github.com/opencollective/opencollective/issues/1784 for that part.

**Comment by znarf** [comment]
Maybe worth discussing that in a team meeting. I get the rationale but I have doubts on the move to the `Members` table.
