### ISSUE TITLE
EPIC → Home Page (Design Revamp)

### ISSUE THREAD

**Issue by lindatalu** [opencollective/opencollective#2264]
## Description
Current Open Collective's home page has a lot of communication issues; the goals are not clear, and by this moment is only talking to a single type of market and users.

The main message to communicate will be: Make your community sustainable, and our primary audience is all the people organizing initiatives, social movements, and open source projects.

**Values to transmit:**
   - Transparency (main value)
   - Diversity
   - Inclusiveness
  - Action

**Main Persona motivations:**

**- Organizers (OSS, Issue-oriented organizations, user groups/meetings)**

- ~~Be sustainable~~ Make your community sustainable. 
- Ask for help to do it.
- Make your community thrive
- ~~Be~~ Make your community resilient
- Be open/transparent
- Invite people to collaborate
- Tell your story
- Share your values
- Be the locomotive (Take the lead)

**- Supporters**

- Contribute to your community
- Cause I care, and I take action
- Thrive
- Be resilient

**- Enabler (Fiscal Hosts)**

- No specific message defined

**Actions behind the sprint:**

- [ ] Start defining final message structure inside the website layout
- [ ] Set all the visual language and style to be used inside the Home Page
- [ ] Wireframes to validate experience, writing, and message to use
- [ ] Implement UI to finish the design process for this page

**Referece whiteboard Screenshots link:**
https://paper.dropbox.com/published/Referece-Screenshots--Ahmu1VNOitdUt~9PDe0uKCSGBg-hp4d3qZdSIrYfOCEOft97xX

**Design documentation**
https://paper.dropbox.com/doc/OC-Design-OpenCollective.com-Homepage-Brief--AkFu9cK7sYNAmXAUJKgqWbndAQ-HPGU8DRNCWiBQQuvdhNVH

**Comment by alanna** [comment]
I think the Home Page design should align with our overall strategy (see #2168). We should be rethinking it to be aimed at fiscal hosts. At the same time, we should be really investing in great host pages, which become the Open Collective front page for their community. 

Each host community has different language, terminology, calls to action, etc. A big problem for us has been trying to serve all those different needs on one page. Instead, I think we should focus on our key customers (hosts), and support them to focus on their customers (Collective core contributors).

In the frame of the new strategy, what is Open Collective's role, and therefore what is the role of the main home page?

* Onboarding new fiscal hosts and explaining the product value to them.
* Guiding potential core contributors to the right host for them, where they will be given information about the product and service in their own language and context.
* Helping potential financial contributors find great Collectives to support - e.g. really improving discoverability and seeing it as the major value OC offers to Collectives, when all other value is really through the hosts.

**Comment by Memo-Es** [comment]
I agree with you @alanna, all of the efforts across teams should be aligned with the high-level strategy of both the product and business model... 

If we go ahead with the fiscal host scenario, the homepage should prioritize the messaging of the following outcomes of the strategy thread previously discussed:

" - Open Collective will aim to be a platform for all kinds of diverse fiscal hosts, with features that serve all of them.
- Our goal will be to bring on more fiscal hosts and help them thrive, and those hosts will bring their communities and networks of Collectives."

Apart from this main goal, we intend to channel the different users of the platform (Collective creators, contributors, organizations, etc.) to their specific "rooms" inside the platform...

We (design) will have a call on Monday with @piamancini and @xdamman to work on the definition of the specific goals for the homepage... And leave the discussion open until Friday to make sure everyone has the opportunity to give their opinion on this matter.

@znarf @lindatalu @cuiki @raulgrafico @Betree

**Comment by piamancini** [comment]
> We should be rethinking it to be aimed at fiscal hosts. At the same time, we should be really investing in great host pages, which become the Open Collective front page for their community.

Yes, absolutely. Please also note that the agreement is a vertical agnostic platform, which means that we should also consider self-hosted collectives which in essence are collectives with a corporate or individual stripe account. I want to make sure we are not only speaking to non profit legal entities that provide fiscal sponsorship services, but also to communities where are member or a member's company/association acts as a host. 

We need to ensure we speak to community organizers who have a goal , a mission and are trying to figure out how to organize themselves, how to make it happen, how to sustain their community. Connecting to a fiscal host is a huge part of that and we need to make sure this process is clear and smooth. 

> Our goal will be to bring on more fiscal hosts and help them thrive, and those hosts will bring their communities and networks of Collectives.

As well as bringing communities and help them connect with these hosts. 

Our main audience is people with a mission, doers who have a cause, organizers and those enabling them Fiscal Hosts + Contributors.

**Comment by xdamman** [comment]
Quick note on the values to transmit:
- Transparency
- Inclusiveness / diversity (those are not distinct values, they are pretty much the same idea)
- Action -> Participation / Contribution / Collaboration (which is the reason why you need transparency)

**Comment by Memo-Es** [comment]
As a result of the call of today, we established the next steps to follow for the homepage project:
1. The CTA's and personas must be really clear
1. We should have a rough content draft of the copywriting 
1. Then the first approach in a sketch level of how those messages are displayed


##Messages
- The main message to communicate will be: Make your community sustainable, and our primary audience is all the people organizing initiatives, social movements, and open source projects.
- The secondary message is then How can I make my community sustainable? which should start by explaining fiscal hosts and their role and benefits for themselves and the community. (I understand this as a description of a set of tools to help people make their community sustainable in or outside OpenCollective


##Values to transmit:
- Transparency (main value)
- Diversity
- Inclusiveness
- Action -> Participation / Contribution / Collaboration (which is the reason why you need transparency)
Personas
- (Possible) Fiscal host admins
- Collective core contributors
- Individual financial contributors
- Organizational financial contributor

##Main Persona motivations:

- Organizers (OSS, Issue-oriented organizations, user groups/meetings)
    - Be sustainable Make your community sustainable. 
    - Ask for help to do it.
    - Make your community thrive
    - Be Make your community resilient
    - Be open/transparent
    - Invite people to collaborate
    - Tell your story
    - Share your values
    - Be the locomotive (Take the lead)
- Supporters
    - Contribute to your community
    - Cause I care, and I take action
    - Thrive
    - Be resilient
- Enabler (Fiscal Hosts) *The fiscal host needs further definition*
    - What is useful about being a fiscal host?

**This discussion will remain open the current week Jul 29 - Aug 2**

**Comment by piamancini** [comment]
Thanks Memo! 

Some feedback: 

> (Possible) Fiscal host admins
> Collective core contributors
> Individual financial contributors
> Organizational financial contributor

these are not values.

> Be Make your community resilient

Remove Be.

> Enabler (Fiscal Hosts) 

Motivations: 
Make their communities sustainable 
Grow their communities
Support their communities 
Create value by removing complexity for their communities 
Manage the overhead of receiving and disbursing funds across different groups

**Comment by Memo-Es** [comment]
Thank you, Pia, there were a few errors in the markdown formatting.

Also, there is a discussion opened by @xdamman that directly relates to this discussion 👉 #2295

**Comment by xdamman** [comment]
First wireframes for feedback: #2417.
Closing this issue.
