### ISSUE TITLE
Apply new design to the transactions page

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2434]
The transactions page currently look like this:

![image](https://user-images.githubusercontent.com/1556356/65156768-ef065b00-da2f-11e9-937f-a7f40a9266c9.png)

With the new collective page with have a new way to present transactions that can easily be replicated everywhere thanks to the `DebitCreditList` component:

![image](https://user-images.githubusercontent.com/1556356/65157146-8ff51600-da30-11e9-9c11-ebd1f1ca2e87.png)

We should make the design for it consistent. **The only things that are missing from design are** a design for an **expended view**, when users click on `View Details` and **a pagination system**.

With that implemented, the change should be fairly simple.

## Todo

- [x] Get design for contributions and expenses expended views
- [x] Get design for pagination on transactions page
- [ ] Update `BudgetItemsList` component and use it on transactions page

**Comment by piamancini** [comment]
@Betree are we waiting on design for this? We can probably get that done today and implement after release tomorrow?

**Comment by Betree** [comment]
@piamancini Yep, no emergency but this would be a good one to tackle. The part we need design for is the expended view (when you click on View details).

**Comment by Betree** [comment]
@lindatalu I'm re-opening, we need an input from design on this issue but it's also an engineering task and we'll loose track of it if we close it.

**Comment by JoyLubega** [comment]
Hey @Betree  Any word from design on this. I would like to give it a try.

**Comment by Betree** [comment]
@JoyLubega Unfortunately we still need an input from @opencollective/design before we can move on with this one.

**Comment by Memo-Es** [comment]
### Design update

Consolidated design for this is [here](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC.com-Production-Ready-%E2%9C%85?node-id=3572%3A1), along with pagination.

P.D. About View details expanded view, I think the one that is applied now to transactions in the Collective page is ok
@Betree

**Comment by Betree** [comment]
@Memo-Es I think there was more than this in what Raul initially showed us. In particular, there are 3 things that we must not break when switching to the new design and that are not included in the design you linked:

- Refund button
- Download invoice button
- Tooltip to download refceipts
- Tooltip to download a CSV export of all transactions

![image](https://user-images.githubusercontent.com/1556356/81786924-97f25080-9500-11ea-8de1-adc01b4e57ef.png)

**Comment by piamancini** [comment]
I agree - I have the feeling that we had a more complete design

**Comment by Memo-Es** [comment]
🎨 [Final design](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC.com-Production-Ready-%E2%9C%85?node-id=4359%3A330) with dropdowns and exports

**Comment by Betree** [comment]
Also mentioning a small difference that we should implement with the re-design: currently the button to download a transaction receipt is only displayed on DEBIT transactions. The reason is probably that a receipt is mainly dedicated to the payee, but we had the case recently for hosts willing to download some of these receipts.

So we should display this button on CREDIT and DEBIT transactions alike.
