### ISSUE TITLE
Contributors grid: improve display order

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2459]
The current version of the contributors grid displays contributors on up to 3 lines. The way contributors are organized today is:
1. Order them to put most important ones (admins, biggest contributors) first in list
2. Get the correct contributor index from the list thanks to the `getIdx` function https://github.com/opencollective/opencollective-frontend/blob/bb2bf261c1d0c9d67f42528e455ba7d29482bb37/components/ContributorsGrid.js#L77

The current formula is:
> index = rowIndex * nbCols + colIndex;

![image](https://user-images.githubusercontent.com/1556356/65782526-24a4f580-e14e-11e9-9443-9ef4245c36fc.png)

**Problem**: when the grid is full, you need to scroll to the right to see some of the highest contributors. This is not fair to them.

We want to change this formula so that the grid will be filled first from the left: 

![image](https://user-images.githubusercontent.com/1556356/65783298-d09b1080-e14f-11e9-9760-ea94d36de07e.png)

## TODO

- [ ] Rename the function to `getContributorIdx`
- [ ] Update the formula
- [ ] Ensure it works with a variety of collectives, you can use
    - (small) https://staging.opencollective.com/styled-icons
    - (medium) https://staging.opencollective.com/vis
    - (big) https://staging.opencollective.com/webpack

Feel free to add the `nbRows` parameter to the `getIdx` function if you think it is required.

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$50** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $50 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by Rexben001** [comment]
@Betree I want to work on it

**Comment by Rexben001** [comment]
How can I get to the page on the screenshot?

**Comment by Betree** [comment]
It's the collectives page. You can either activate the `NCP_IS_DEFAULT=true` flag or add `/v2` at the end of the url (ex: https://opencollective.com/babel/v2). Please note that because this issue has a minimal complexity, the allowed time frame to complete it is only one week.

**Comment by jeffin143** [comment]
>Please note that because this issue has a minimal complexity, the allowed time frame to complete it is only one week.

@Betree , Since this is the last day and also @Rexben001  hasn't made the changes after almost 3 days and hence I went ahead an raised the PR. Please review it 

Thanks :)

**Comment by Betree** [comment]
@Rexben001 Sorry, time was almost out and @jeffin143 came up with a working solution. We'll continue with https://github.com/opencollective/opencollective-frontend/pull/2749 instead

**Comment by Betree** [comment]
:trophy: This issue is now completed by @jeffin143  

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

---

For more info about the bounty process and how to format your invoice, please read https://docs.opencollective.com/help/developers/bounties

If you have any feedback on how we could improve the bounty process or how to better onboard new developers please [share it with us](https://slack.opencollective.com/), we're always eager to improve :slightly_smiling_face:
