### ISSUE TITLE
[PROJECT] SPAM and moderation

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2741]
## Purpose
We want to provide tools for Collectives and internal use to better handle spammers, and more generally to be able to moderate the content submitted on the platform. This targets multiple types of content, as experience has proven that malicious users were spamming Collectives through multiple techniques. This project aims to provide a moderation framework for the ones that we've seen the most so far:
- Spamming through expenses
- Spamming through orders
- Spamming through comments
- Spamming with profiles (user/org/collective)

We need to acknowledge that Collectives will have different definitions about what is an acceptable content. As much as possible, **the moderation job should thus be in the hands of the Collectives**, they need tools to block a user from their collective.

At a higher level, some content are (by law) never acceptable on the platform (ie. hate speech, cross-collectives spams...etc). We thus need tools to **moderate and block users at the platform level**.

### Collectives moderation

- [ ] [Ability for collective admins to edit members](https://github.com/opencollective/opencollective/issues/2097)
- [ ] [Ability for collective admins to ban a user](https://github.com/opencollective/opencollective/issues/2737)
- [ ] [Ability for admins to cancel/reject financial contributions](https://github.com/opencollective/opencollective/issues/2006)
- [ ] [Collective admins should be able to hide comments](https://github.com/opencollective/opencollective/issues/2740)

### Platform moderation

- [x] [Ability to limit user account](https://github.com/opencollective/opencollective/issues/2695)
- [x] [Ability to ban users from the platform](https://github.com/opencollective/opencollective/issues/2739)
- [ ] [Ability to report undesirable comments, expenses, orders and profiles](https://github.com/opencollective/opencollective/issues/2694)
- [x] [Document new monthly job: search & destroy spammers](https://github.com/opencollective/opencollective/issues/2738)
- [x] [Notify platform admins when a suspicious value is set in collective data](https://github.com/opencollective/opencollective/issues/2750)

## Owner
@Betree - I'm comfortable with leading this project.

## Prioritization

- Does this serve our mission?

> We are on a mission to help collaborative groups collect and spend money transparently.

Yes, moderation is an essential building block to help groups collaborate.

- Will this help to make us financially sustainable within a year?

The impact of this project on our financial sustainability is probably very limited.

- Is it feasible to build and maintain with our team and runway?

We have a lot on our plate, but a lot of issues described here can be tackled incrementally. 

- Can this make us move faster?

Yes, by reducing the number of support requests to remove contributions, contributors, expenses... that we receive. **SPAM issues were the 1st reason for tickets in November**.

- Does this increase quality and not technical debt?

This project should not create any technical debt. 

- Will this bring us more Collective and financial contributors?

Probably not, but the opposite may happen: our inability to handle SPAM properly may frustrate some Collectives. Having SPAM on the platforms may also be a downer for Contributors - who wants to put their credit card info on a website with casino ads?

## Roadmap & Timeframe

Github project: [SPAM & Moderation · GitHub](https://github.com/opencollective/opencollective/projects/27). Priorities are set in 3 phases:
1. Priority > High
2. Priority > Medium
3. Priority > Low

## Success metrics

- Fewer support requests regarding SPAM
- Number of users limited
- Number of profiles banned
- Number of contents reported on the website

**Comment by sbinlondon** [comment]
Just dropping a note here as I realise we'll be talking about this today but I think the most important bit which @Betree says nicely in the original post is that

> **the moderation job should thus be in the hands of the Collectives**, they need tools to block a user from their collective.

The frustration we saw this weekend on social media and have received sometimes through support is that people don't like the process being so manual (i.e. emailing to remove spammers). In the end the power of a platform comes from giving the users a basic thing we can allow them to do (Open Collective lets you collect donations for your project) and then trusting our users to tailor the rest for themselves. 

It's important to empower them to be able to do what they feel is right in terms of their Collective - whether that's configuring the sections they display on their Collective page (a recent feature) or having the moderation tools needed to curate who can interact with their Collective (i.e. comments + moderation, which we've done, or allowing/denying certain donors, which we haven't).

I think the main pain points we've seen from the feedback this weekend are:

- [ ] ability to approve payments (all - something to toggle on/off in menu? or just some if a donor becomes spammy?) before they are accepted/displayed
- [ ] ability to block certain donors
- [ ] ability to hide certain donors/payments

Additionally, and this is less a user control but something on our side, I think it could be worth looking at adding an additional filter to our 'top contributors' or for the contributors displayed in the OC widget on i.e. the Babel page, to filter out many contributions from similar companies (Spam & Pineapple EU, Spam & Pineapple UK, Spam & Pineapple US, so on...)

**Comment by bnb** [comment]
>  moderation job should thus be in the hands of the Collectives

I disagree with this. While this is relatively the status quo of any kind of online space right now (think Discord, Facebook, LinkedIn Groups, etc.) this should probably not be the case when it comes to OpenCollective - or, at least, it should be the last resort. Forcing collectives to do this adds maintenance burden to - at least of your most successful and notable collectives - groups that are already overburdened by maintenance. This ends up setting people up for failure and burnout since there'll inevitably be something that slips through _or_ they'll have to have people actively monitoring it.

I think @sbinlondon's suggestions are good. I would like to recommend extending them into some kind of categorization - for example, I wouldn't really want money from gambling or casinos going into a collective I run or participate in. Similarly, I wouldn't want cryptocurrency money going in. I would, however, be okay with money from companies that enable sex work in a way that is not harmful to the people practicing it. Giving these kinds of categorical controls (yes / require approval / allow) would be ideal in reducing that burden IMO.

Additionally, ensuring that collectives can back off on sponsorships they've previously accepted without issue would be ideal.

**Comment by Betree** [comment]
@bnb As a first step, I really think we need to empower collectives because they're the one in position to make the judgment. Having categories can be helpful (and I'm all in for opening an issue to spec that), but not sufficient because:
- You can't categorize everything. You may be ok to receive funding from tech companies, but not the ones that work with ICE.
- Casinos and alike will play with these categories to counter the rules.

I however believe that, by making the UX to manage this simple, we can greatly reduce the maintenance work for them. We were discussing last Thursday about something really similar to what @sbinlondon [proposed](https://github.com/opencollective/opencollective/issues/2741#issuecomment-674768280), the idea was to have a `Reject contribution` button on the transactions page that will refund the contributions and open a modal for you to confirm if you want to:
- Remove the member from your collective
- Prevent them from contributing again in the future
- (Optional) Add a small message to explain why you're rejecting their contribution

Such solution is, in my opinion, the fundamental block that we must start with. We can think about better ways to do this in the future, more automation, but we will still need this one feature.

**Comment by bnb** [comment]
@Betree I agree that categories aren't going to solve every problem, but it *does* chip away at the burden. Having to accept/reject every single contribution is a lot of work. Having to retroactively do that when you see a contribution you don't want is also work, and generally the same problem that already exists.

The problem is abuse of the platform, which isn't a burden that should be placed on Collective organizers. Categories are one path to solving it, but there are others. The current suggestion still places that burden on Collective organizers without giving meaningful leverage to the platform to do something about it. That's not a knock on the suggestion - I agree that it's a foundational feature - but I don't think it actually solves the problem in a meaningful way.

Individuals shouldn't be *forced* to control spam in their slice of the platform. If Babel blocks a sponsor, the sponsor can just go to webpack who may not choose to block them. When people talk about it on Twitter next time this comes up, then webpack will block them and they'll just go to some other project when the platform should have cut them off well before that. 

> We can think about better ways to do this in the future, more automation, but we will still need this one feature.

This is effectively what my suggestion around categories is aimed at. If you know this isn't the final solution, why not actually think about what that looks like now when we're having this discussion?

**Comment by Betree** [comment]
> Individuals shouldn't be forced to control spam in their slice of the platform. 

The problem is that the definition for SPAM will change from one collective to another. For some it's ok to get contributions from casinos, for others it's not. In the case of Babel, the amount they got from casinos is > $20K. Saying no to that money may be a difficult decision, and it's not Open Collective's responsibility to take it as long as there's nothing illegal in there.

That being said, I agree that collective admins shouldn't have the burden of moderating every single contribution that they receive, and we must provide tools to automatize that. The needs that I've specified on this issue so far are based on the support requests for SPAM that handled in the past year. Most of the time, these requests are collectives reaching out with a list of sponsors to remove. It's time consuming for them and time consuming for the team, which is why I really think that a `Reject contribution` is so important right now. It's also a contained feature that we can confidently implement in a reasonable time frame.

> If you know this isn't the final solution, why not actually think about what that looks like now when we're having this discussion?

I don't think there's one final solution but - as often with SPAM - rather a multitude of small steps to make spammer's lives harder.

Apart from what has already been suggested here, I can think of having a `reputation` score for all contributors on the platform, with the ability for collective admins to define a minimum reputation score to contribute to their Collective. We could automatically adjust this score based on things like:
- The domain reputation for their website (if provided)
- Their activity on the platform (were they marked as SPAM in the past?)
- Is it a verified account? (ie. we could mark big contributors like Google as "verified")
- IP reputation of the person creating the org
- How long have they been on the platform

The project has been put on the priorities list for the next weeks, and @sbinlondon will be leading further specifications & implementation on the topic of **spammy contributions**. We'll make sure to not only implement moderation tools, but to make sure we don't add a new burden on Collective admins by doing so.

**Comment by sbinlondon** [comment]
Please see our updated project for Q3/Q4 2020 [here](https://github.com/opencollective/opencollective/issues/3461) for further discussion
