### ISSUE TITLE
[PROJECT] Create Collective Flow (implementation)

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#2872]
## Purpose
We want to make it easier for collectives to find the right path for them, thus aligning this with our new business model for fiscal hosts.

## Owner

Project: @piamancini 
Technical: @sbinlondon & @znarf

## Prioritization

- Does this serve our mission?

Yes, it aims to help us become more *sustainable* 

- Will this help to make us financially sustainable within a year?

Yes, it will hopefully have a direct impact on revenue by aligning new collectives with the new business model.

- Is it feasible to build and maintain with our team and runway?

Yes, it is mostly creating a new flow using already created components with some new image design and a minimal amount of new components being created.

- Can this make us move faster?

Yes, by taking away ambiguity in the signup process and decreasing the amount of people who get in touch.

- Does this increase quality and not technical debt?

Yes, it will increase quality of the create collective flow and we'll aim to implement it in a sustainable way that won't increase technical debt.

- Will this bring us more Collective and financial contributors?

Yes, hopefully, if they find it easier to sign up and figure out which path is correct for them.

- Is this already solved elsewhere or is it our unique contribution?

Our unique contribution 😊 

## Roadmap & Timeframe

- [x] Design (see #2366)
- [x] Implementation of the final design
- [x] Migrate Create Collective to GraphQL API v2
- [x] Feedback round
- [x] Making changes based on feedback round
- [x] Final implementation
- [x] Staging
- [x] Last bug fixes
- [x] Söft delivery date: end of Q1 2020 (March 31)

## Success metrics

* More self-hosted Collectives created
* Increase per-Collective revenue

**Comment by sbinlondon** [comment]
Pending:

* review and merge tests from @jeffin143 for the onboarding modal
* finish tests for updated CCF by @sbinlondon 
* finish new tests for AFC flow by @sbinlondon
