### ISSUE TITLE
Review buttons to process expenses

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2936]
_In the context of #2394 and #2896_

# User story 

As a collective or host admin, I'm confused by the number of call to actions for each expense, up to 4 of them. I sometimes refereed as the "Christmas tree" issue for this, because the buttons use alternatively red (danger), blue (primary), greed (success) and white (standard) styles which doesn't create a hierarchy between them.

![image](https://user-images.githubusercontent.com/1556356/75437436-7ac4d180-5956-11ea-992d-31e6b81a816c.png)

# Solutions

## Proposal 1: Limit actions based on expense status

Some actions that we show today are not required. For example, on approved expenses, we show both `Unapprove` and `Reject`. It seems confusing to me, and unnecessary: if you already approved the expense then it's fine to first unapprove before rejecting.

![image](https://user-images.githubusercontent.com/1556356/75438308-01c67980-5958-11ea-888f-306f8991c389.png)

I would suggest limiting the actions to **3 maximum**, never more. To achieve that, these are the actions that we should display at each stage:
- `PENDING`: Approve, Reject, Delete
- `APPROVED`: Unnapprove, Pay
- `REJECTED`: Approve, Delete
- `PROCESSING`: *No action*
- `ERROR`: *Same as `APPROVED`*
- `PAID`: *No action*

## Proposal 2: Merge the "Pay" strategies

We currently have two buttons that can be used to mark an expense as paid.
- `Pay with PayPal` (or `Pay with Transferwise`)
- `Mark as paid`

Because they share the same purpose, I'd suggest merging them under a single `Pay` button. When clicked, it should open a modal or a tooltip where you can either pick `Pay with Paypal` **or** `Mark as paid`.

The option for `Mark as paid` should include two inputs to set the transaction fees. **This is important because this part is missing from the expense page in the new design**, which means that we currently cannot add the `Mark as paid` button on it.

![image](https://user-images.githubusercontent.com/1556356/75438098-ab593b00-5957-11ea-85a2-9a4adbdeb2bf.png)

We need @opencollective/design for this one.

# Todo

- [x] Implement in the new collective flow
- [x] Use new buttons on new expense page
- [ ] Use new buttons on legacy expense pages (host dashboard)

**Comment by piamancini** [comment]
We should do both proposals: 

I think having one button that says PAY and have a modal or tooltip is a good idea. It needs to be resolved for mobile though. Not sure how a modal would work, but maybe a dropdown menu would. 

It makes sense limiting the number of buttons on a need-only basis. A simpler idea - that makes less assumptions about how collective and host admins might want to use this -  would be to have a Change Status buttons with the same dropdown menu or modal as for PAY that let's you toggle between all these status options. 


@raulgrafico @Memo-Es let's chat.

**Comment by Betree** [comment]
@raulgrafico @Memo-Es @piamancini what's the resolution for this one?

FYI I can't implement the buttons on the expense page yet because `Mark as paid` would miss the fees inputs. I made a suggestion that could be related here: https://github.com/opencollective/opencollective/issues/2702#issuecomment-566946071

Is having the admin buttons (Mark as paid, Pay with PayPal, Approve...etc) a blocker for the public release?

**Comment by alanna** [comment]
What about a pattern of one main button for the most common action, and then an "actions" dropdown with all available actions? I think this comes up in many places besides expenses, for example on host page nav bars.

<img width="1440" alt="Screen Shot 2020-05-28 at 2 00 01 PM" src="https://user-images.githubusercontent.com/5498878/83214534-e8cc9f00-a1b8-11ea-932c-bffc1324038d.png">

**Comment by Betree** [comment]
This one has been resolved by never showing more than two actions at the same time and unifying all the pay actions (Pay with Paypal, pay manually...etc) under a single `Pay` button. The change hasn't been dispatched to the host dashboard, but the new dashboard will have them.

@alanna could you open a followup issue for the screenshot you shared? This doesn't look good and we should address it as part of the collective page enhancements
