### ISSUE TITLE
[PROJECT] PayPal Payouts

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#3131]
## Purpose
- Bypass the existing payout limit.
- Reduce how much collectives pay in fee costs when paying expenses using PayPal.
- Implement asynchronous transactions for PayPal Payouts.

## Owner
@kewitz

*Note: Project owner responsibilities include coordinating all the different people that need to contribute to the project, defining specs and goals, communicating project progress, being the point person for decisions, QA, documentation, and a plan for ongoing maintenance. If the project owner can't continue, they need to hand the role over to another person explicitly.*

## Prioritization

- Does this serve our mission?
Yes, we need to provide good solutions for money to get out of the platform.

- Will this help to make us financially sustainable within a year?
Not directly since we don't charge for this feature.
But having good payout methods will increase the capacity of money to flow within our platform reducing the weight of processing payouts for collectives and hosts.

- Is it feasible to build and maintain with our team and runway?
Yes. We already have this feature, we want to make it better.

- Can this make us move faster?
Yes. This will reduce the time spent processing payouts in our collectives.

- Does this increase quality and not technical debt?
Yes. This an iteration on the existing PayPal payout method.

- Will this bring us more Collective and financial contributors?
Yes, a better payout method will decrease the perceived value spent on fees.

- Is this already solved elsewhere or is it our unique contribution?
Yes. It is an iteration on our own feature.

## Roadmap & Timeframe
The idea behind this implementation is to make it backward compatible with our existing structure.
That will be achieved by allowing host admins to schedule expenses for payment that will be asynchronously be paid in daily batches by a background worker.
This gives us a way to fork the existing flow without deprecating the previous implementation.
In the near future, this will also allow us to implement payout approvals and scheduled payment cancelations if we wish to.

![image](https://user-images.githubusercontent.com/2119706/81827233-f292a900-950e-11ea-9ee9-4b326ee2c700.png)

1) Connecting to PayPal
    - [x] Update Host "Sending Money" menu to connect to PayPal.
    - [x] Take care of token lifecycle.
    - [x] Set up Webhook.
2) Scheduling Expense for Payment
    - [x] Add new "Scheduled for Payment" status.
    - [x] Add new button to schedule Expense for payment.
    - [x] Update `Collective.getBalance()` function to consider expenses scheduled for payment.
3) Worker
    - [x] Daily cron worker to check pending Expenses.
      - Create transactions if the transaction succeeded.
      - Update Expense if it fails.
4) Webhook
    - [x] Webhook endpoint to receive transaction updates from PayPal
      - Create transactions if the transaction succeeded.
      - Update Expense if it fails.
    - [x] Update documentation with instructions on how to connect the webhook.

## Success metrics
Subjective: Time spent processing PayPal payouts.
Quantitative: Decrease in the total amount of fees on expenses being paid using PayPal.
Quantitative: Increase in the number of expenses and the total amount being paid using PayPal.
