### ISSUE TITLE
[PROJECT] Collective page iteration

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3136]
## Purpose
The purpose of this project is to iterate on the collective page. There are some important issues that were part of the initial design that haven't been able to tackle yet.

## Owner
@Betree 

## Prioritization

- Does this serve our mission?

The collective page is the entry point for many contributors. By offering more customization options and making it better, faster, we will try to increase the conversion rate of people financially contributing to collectives.

- Will this help to make us financially sustainable within a year?

An increase in the conversion rate would help us, but the issues listed in this project are not a game-changer regarding our revenue. 

- Is it feasible to build and maintain with our team and runway?

Issues are scoped and complexity already estimated, this shouldn't add any debt.

- Can this make us move faster?

By adding new patterns like the one for [drag & drop](https://github.com/opencollective/opencollective/issues/2183), we'll make sure that implementing similar features in the future will be easier.

- Does this increase quality and not technical debt?

It should!

- Will this bring us more Collective and financial contributors?

The nicer the collective page looks, the more projects will be willing to use it as their vitrine.

## Roadmap & Timeframe

- [ ] [New collective page: Contribute cards images ](https://github.com/opencollective/opencollective/issues/2121)
- [ ] [Improve contribute cards hero gradient ](https://github.com/opencollective/opencollective/issues/2435)
- [ ] [Resize hero background image on collective page ](https://github.com/opencollective/opencollective/issues/2709)
- [x] [New collective page: edit sections ](https://github.com/opencollective/opencollective/issues/2424)
- [x] [Collective admins to sort contribute cards ](https://github.com/opencollective/opencollective/issues/2183)
- [x] [GraphQL endpoint to fetch collective's features ](https://github.com/opencollective/opencollective/issues/2807)

## Success metrics
- Enhancements delivered
- Time spent: we don't want to invest too much time in this

**Comment by Betree** [comment]
Closing this project as we now have other priorities. Issues will be worked on individually.
