### ISSUE TITLE
[PROJECT] Allow Hosts to manage a budget

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#3161]
## Purpose

Today, Hosts (User or Organization) can't manage their budget:
- they can't raise money directly
- they can't accept expenses
- they can't receive the remaining balance for collectives being deleted or archived
- they can't properly manage their "Host Fees"

The current alternative is for them to setup an "Host Collective", 23 collectives have done that so far. However, it's not intuitive and there is no documentation nor proper interface for this feature. Hosts have to first face the problem then contact support to learn about the feature and set it up.

## Owner

François

## Prioritization

- Does this serve our mission?

Yes. This is simplifying the platform.

- Will this help to make us financially sustainable within a year?

No impact.

- Is it feasible to build and maintain with our team and runway?

Yes.

- Can this make us move faster?

Yes, less support and easier onboarding.

- Does this increase quality and not technical debt?

It's slightly increasing the complexity for the benefit of users.

- Will this bring us more Collective and financial contributors?

We can expect more financial contributions to the Hosts.

- Is this already solved elsewhere or is it our unique contribution?

It's a problem unique to us.

## Roadmap & Timeframe

1) MVP, activate for test Hosts
1) Beta, activate for key Hosts (OSC, Foundation)
1) Enabled on demand, No "host collective" for new Hosts
1) Enabled by default for new Hosts
1) All "Host collectives" migrated

## Success metrics

 - Less support
 - Amount of money directly raised by the hosts organizations
 - Amount of expenses directly paid by the hosts organizations

## Checklist

Checklist:
- [x] Hosts organizations should be able to manage tiers
- [x] Hosts organizations should be able to manage events
- [x] Contributors should be able to donate to Hosts organizations
- [x] Contributors should be able to submit expenses Hosts organizations
- [x] Hosts organizations should be able to pay expenses
- [x] Hosts organizations should be able to "Add Funds" to their own budget
- [x] Hosts organizations (that have activated their budget) should receive their "Host Fees" on a monthly basis https://github.com/opencollective/opencollective/issues/1723
- [x] Hosts organizations should be able to send Updates https://github.com/opencollective/opencollective/issues/2314
- [x] Emptying balance should go to the Organization budget, not the "Host Collective" (just need to update `hostCollective` for now)
- [ ] Download receipts doesn't work for hosts with budget https://github.com/opencollective/opencollective/issues/3360
- [ ] Migrate previous "Host Collectives"
- [ ] Check if "Add Funds" should add a `DEBIT` entry

**Comment by znarf** [comment]
This is released and activated for https://opencollective.com/foundation/

Todo:
- [ ] Check navigation bar
- [ ] Check Transferwise availability when submitting expense

**Comment by znarf** [comment]
It appears as Financial Contributor to itself:

<img width="901" alt="Screenshot 2020-05-28 at 14 18 05" src="https://user-images.githubusercontent.com/806/83140264-1862a500-a0ee-11ea-824b-c0effae635b3.png">

**Comment by alanna** [comment]
Related: #1723

**Comment by alanna** [comment]
I don't see reports mentioned as part of this spec. We will need to include a monthly and annual report that's similar to a Collective budget report within the host report. Or in addition.

**Comment by znarf** [comment]
@alanna could you specify a minimal version that would be included in the current Host Report?

**Comment by alanna** [comment]
Probably just add a section of the monthly report called "Host Budget", showing the current balance, total contributions that month (e.g. host fees earned), and a list of the expenses. I'm basing this on a simplified version of what's in the current Collective monthly reports.

**Comment by znarf** [comment]
@alanna I looked at it and I think it's easier to additionally send the "Collective Report" to these Hosts. PR coming
