### ISSUE TITLE
[PROJECT] Update the static pages to the new design

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#3176]
## Purpose
We have an updated design for the homepage, so what's more logical is to update the rest of the static marketing pages to the new design. 

## Owner
@Memo-Es and @piamancini 

*Note: Project owner responsibilities include coordinating all the different people that need to contribute to the project, defining specs and goals, communicating project progress, being the point person for decisions, QA, documentation, and a plan for ongoing maintenance. If the project owner can't continue, they need to hand the role over to another person explicitly.*

## Prioritization

- Does this serve our mission?
Yes, consistency in our language and graphic style is vital to communicate trust and reliability. 

- Will this help to make us financially sustainable within a year?
Not directly, but together it helps us maintain a consistent brand and improves our public image.

- Is it feasible to build and maintain with our team and runway?
We are planning this project to be undertaken by a member of the open design network. Thus, it sill consume less internal resources. 

- Can this make us move faster?
It can make us evolve our brand better, which helps us to have more time and focus on meeting our sustainability goals in less time.

- Does this increase quality and not technical debt?
Since these are static pages, it requires less development work and could be a candidate of a bounty.

- Will this bring us more Collective and financial contributors?
Yes, the more consistent our brand looks, the more trustworthy it becomes, this means more people will place their trust in Open Collective to manage their community project's operations, hence more donations flowing inside the platform.

- Is this already solved elsewhere, or is it our unique contribution?
N/A

## Roadmap & Timeframe (Aprox)
(Key milestones or phases and estimated delivery dates, including specs, design, feature development, feedback, marketing/comms, and documentation)
1. Documentation and negotiation with designer May 28 - June 1
2. Design kick-off 1st-2nd June 
3. Homepage modifications and Become a sponsor mockup - June 5
4. [Become a sponsor](https://opencollective.com/become-a-sponsor) and [How it works](https://opencollective.com/how-it-works) - June 12
5. [Become a fiscal host](https://opencollective.com/become-a-fiscal-host) and Feedback - June 19
6. [Gift cards](https://opencollective.com/gift-cards) and feedback - June 26
7. Final feedback and wrap up production files - July 3

Note: I suggest to include a design of a better [support page](https://opencollective.com/support), that works like a "help center", feedback about this most welcome.

## Success metrics
(What we will judge outcomes of the project by)
It should help the new users understand the global OC context better so it should add more Collectives created and better use of the platform, but a close tracking is very hard.

**Comment by Betree** [comment]
@Memo-Es What's the actionable for this issue? Is there a list of the static pages that are left to update on the dev side?

**Comment by Memo-Es** [comment]
@Betree The only one missing is https://opencollective.com/gift-cards, but since it's not featured on the footer I'm not sure about the priority of this task

**Comment by Memo-Es** [comment]
Also, there is a collection of static pages we uploaded some time ago from which we just received the illustrations:

<img width="1670" alt="Screen Shot on 2022-04-27 at 22-49-02" src="https://user-images.githubusercontent.com/49539954/165672643-fdbba005-2ab5-4957-9340-fe5f7710375f.png">

@Betree tell me if it makes more sense to move these new pages to a new issue

**Comment by Betree** [comment]
> Also, there is a collection of static pages we uploaded some time ago from which we just received the illustrations:
> 
> <img alt="Screen Shot on 2022-04-27 at 22-49-02" width="1670" src="https://user-images.githubusercontent.com/49539954/165672643-fdbba005-2ab5-4957-9340-fe5f7710375f.png">
> 
> @Betree tell me if it makes more sense to move these new pages to a new issue

Ow these look amazing!
This has a higher chance of being tackled if we split it into smaller, well-contained issue because they're easier to parse and assign to external contributors. I think we should split this one into 3 issues:
- [ ] Update the error pages to the new design (_not found, unexpected error_)
- [ ] Update the gift cards marketing page to the new design
- [ ] Update the sign-up success page with the latest design (*though we may want to treat this one as part of https://github.com/opencollective/opencollective/issues/5399?)

I can take care of creating these issues, but I'll need the Figma links.
