### ISSUE TITLE
Remove react-boostrap dependency

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3223]
In our [code guidelines](https://docs.opencollective.com/help/contributing/development/best-practice-guidelines), we say that we're getting rid of bootstrap and ask to don't use it for new developments. To complete this rule, we should have a plan to completely remove it. This will prevent some confusion for new contributors (happened recently), reduce technical debt, and improve the consistency of our design (see https://styleguide.opencollective.com).

# Todo

- [x] Replace all `Button` by `StyledButton`
- [x] Replace all `ButtonGroup` by `StyledButtonSet`
- [x] Replace all `Col` / `Row` by `Flex` / `Box` components
- [x] ~~For `Popover`, we can build (a) custom component(s) with `react-popper`~~
- [x] Finally: Remove [custom bootstrap's CSS](https://github.com/opencollective/opencollective-frontend/blob/b9cf4219ca23f29a693a783bc9c3956727efbe40/pages/_app.js#L16) and `boostrap` / `react-bootstrap` dependencies

**Comment by Betree** [comment]
This issue can be tackled step-by-step, if someone from the community is interested in tackling only one bullet point (ie. replacing all bootstrap's buttons) this will already be a great help!

**Comment by snitin315** [comment]
@Betree I will help with this.

**Comment by SudharakaP** [comment]
@snitin315 : #3059 is dependent upon this. And therefore would you be okay with me taking it ?

**Comment by snitin315** [comment]
Sure no problem.

**Comment by SudharakaP** [comment]
@snitin315 : Thanks a lot. 👍

**Comment by Betree** [comment]
@SudharakaP https://github.com/opencollective/opencollective/issues/3059 doesn't depend on this. My feedback was about not using it for new developments, but we don't have to remove it right away and the two issues are unrelated.

**Comment by Betree** [comment]
@SudharakaP Since this issue is not a priority and is not blocking anything, I'd recommend to rather focus on https://github.com/opencollective/opencollective/issues/3059.

**Comment by SudharakaP** [comment]
@snitin315 : Hi Nitin, if you'd like please feel free to take this back since I was misunderstood. This is not a blocker for #3059. :smiley_cat:

**Comment by SudharakaP** [comment]
@Betree : If there's no objection; I'll work on this. 😄

**Comment by SudharakaP** [comment]
@Betree : I've made a PR that removes `react-bootstrap` completely. I'll do another PR separately that removes `bootstrap`; as it seems we use bootstrap classes such as `text-decoration` so can't remove `bootstrap` just after removing `react-bootstrap`. 🤔

**Comment by SudharakaP** [comment]
@Betree : Also I should note that we don't use `Popover` (at least I couldn't find it anywhere being used); so I just edited the original post to remove that point. Let me know otherwise. 😄

**Comment by SudharakaP** [comment]
@Betree : I've just remove `bootstrap` dependency as well in the same PR as it wasn't as tricky as I thought it would be. Just added a few global css rules so that the pages looks exactly as they were before (some bootstrap styles were coming from their internal `.less` classes it seems).
