### ISSUE TITLE
Refact fees on top to create a separated donation Transaction

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#3259]
## User story
As a donor, I want to be charged only once for the contribution to the collective and the donation to the platform.
As a donor, I want to have a clear distinction between my contribution to the collective and the platform on my page.
As a collective, I don't care if the contributor donates to the platform and I don't want to see any trace of that in my transactions.
As the platform, I want to recognize the donations through fees on top as contributions to Open Collective Inc.

## Best solution for this problem
The platform creates multiple transactions when the contributor adds fees on top.
There should be 4 transactions created after a single order:
- Contribution credit to the Collective.
- Contribution debit to the Contributor.
- Donation credit to Open Collective Inc.
- Donation debit to the Contributor.

## Implementation
1. Flag order and transactions with `data.isFeesOnTop: boolean` to indicate a clear distinction between fees and feesOnTop.
1. Process order and payment normally.
1. Refactor `Transactions.createFromPayload` to zero `platformFees` in the main transaction and create another pair of transactions between the contributor and Open Collective Inc.

### Existing order flow
![image](https://user-images.githubusercontent.com/2119706/85058220-28fbbd80-b178-11ea-920e-d4cfffb75af7.png)

### Caveats
Since we'll remove the platform fee from the main transaction, we'll need to update how we charge hosts when the `feeOnTop` was paid manually or through PayPal.

### TODOs
- [x] Donation should be charged as platform fee in the contribution charge.
- [x] Separate contribution to collective from platform donation transactions.
- [x] The Contributor page should display two separate transactions.
- [x] Open Collective should list the donation transaction.
- [x] Fees on top should work with subscriptions.
- [x] Create user contributor membership
    - [x] The Contributor page should display user as a Financial Contributor of Open Collective.
    - [x] Open Collective page should display user as a Contributor. 
- [x] Success page displays only the amount donated to the collective.
- [x] Deal with exchange currency, use Stripe FX rate.
- [x] Update email notifications.
- [x] Add migration to fix past transactions.
- [x] Track "isFeesOnTop" even when "platformFee = 0".
