### ISSUE TITLE
[Project] Host can require minimum number of admins

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3593]
## Overview
Open Collective Foundation and Open Source Collective require two admins to have access to Collectives in their eligibility criteria, SCA requires four ([section 4.3](https://docs.google.com/document/d/1_ucGOnfnvCJuJqqu1s5qFbgIeEJV6G-ZegcdXHk049M/edit) this reduces strain on hosts as collectives are more able to resolve issues themselves. 

## Ownership

Lead: @Benjam

## Roadmap

**Estimated delivery date** Q4S1 (Oct to Mid-Nov)

* Scope Q3S2
* Implement and release Q4S1

## Prioritization

- Does this serve our mission: Our mission is to build strong, sustainable communities. This does limit the ability for smaller communities to form but it does force communities to become stronger before being accepted. 
- Will this help to make us financially sustainable within a year? No
- Can this make us move faster? It will lower support load for hosts (inc. our own)
- Does this increase quality? No
- Does this add technical debt? Outside of implementation it should not.
- Is it feasible to build and maintain with our current team and runway? Yes
- What insight or research is this project based on? Feedback and alignment with process
- Is this problem already solved elsewhere? Manual support intervention.
- How will we measure our success? Do we have a baseline today that we can compare this against? How much time is spent on this in support.
- How well do we understand the complexity of the problem, feature to be added or user need to be addressed? Needs scoping. 
- What is the estimated timeframe for delivering this project? Inside of one sprint. 

### Problem

> Requesting a setting at the host level to require a certain number of admins per Collective (e.g. 2 or 3). This has been requested by multiple hosts.
> * Require the minimum when applying to a Host with this set - enable users to add additional admins in the application flow.
> * If the minimum is 2, do not allow removing the second to last admin, instead requiring adding a new one first (same as now we don't allow removing the last one, just one more increment).
> According to @piamancini it used to be that when a Collective used Github to verify when signing up with OSC, it required at least two admins. This seems to have disappeared. OSC would like to have a policy of requiring at least two admins, so if we could bring this back that would be good. Is it broken or was it removed?

### Proposed solution

@benjam's [run-through of current process](https://www.figma.com/file/AFkJxxTEnKTefFWbSu8pID/Untitled?node-id=0%3A1) [and proposal](https://docs.google.com/document/d/1GYg_N3TF-mYq3St8gkanJaCDwGE6BXl0FvA61Vk2vjk/edit#heading=h.yg69tslxalot)

### Measuring success

Goal: Reduction in time processing requests for collectives to join Open Source Collective and Open Collective Foundation.
Baseline: 

### Documentation

- Which aspect(s) of the platform does this change impact? Onboarding, admin management, host settings.
- Which group(s) of users will benefit from this change? Hosts
- Is this project in response to a user-requested feature? If so who requested it (link to feature request if available)? host requested feature.
- Is this project related to any similar work we have done, or are planning on doing in the next three months? Setting a minimum number of approvals required to pay an expense https://github.com/opencollective/opencollective/issues/3081 

## Next steps

- [ ] Open up any appropriate project issues
- [ ] Open a documentation issue, link it to this one
- [ ] Open a release issue, link it to this one
- [ ] Create a project board, add this issue to the description, add any issues created above 

## Project Closure

- Close all relevant project issues
- Open up issues for improvements 
- Post comm's according to comm's plan (most likely in release issue)
- Post project screencast on documentation slack channel 
- Post project closure in newsletter slack channel 
- Celebrate!!

**Comment by Betree** [comment]
I suppose it was removed, because in the current Github flow you create your collective inline and there's no way to add another admin. This could be implemented by adding a step in the Github flow.

**Comment by tydazzz1** [comment]
0363553362

**Comment by alanna** [comment]
Bumping this issue and making it more broad. OCF requires two admins per Collective and we spend a lot of time chasing this up manually. Other hosts [report a similar need](https://hackmd.io/@kaylarep/SyWa0CB1F). It's also very central to our philosophy that OC is for *communities* so having a BDFL individual as the only admin is not aligned.

**Comment by Betree** [comment]
> If the minimum is 2, do not allow removing the second to last admin, instead requiring adding a new one first (same as now we don't allow removing the last one, just one more increment).

This part would be quite easy to set up as we already check the number of admins to make sure the last one is never removed.

**Comment by BenJam** [comment]
spent the day running through onboarding processes, briefly described in https://www.loom.com/share/9a6d3e49d7e3432186869ce560b99351 

I'll organise a run through later in the week but please jump in with comments /cc @Memo-Es @aminakazi @znarf

**Comment by BenJam** [comment]
@aminakazi's design https://www.loom.com/share/f59ade7e795f4d509a4d4089ed971c3e

**Comment by aminakazi** [comment]
Final Figma Files can be [found here](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=15981%3A272131)
Please [watch the loom](https://www.loom.com/share/f59ade7e795f4d509a4d4089ed971c3e) for understanding the flow.

**Comment by kaylarep** [comment]
looks great!! :heart_on_fire:  I'm so excited for this :sweat_smile:

in the 1st flow:
- could we add a note either in the tooltip or the blurb below, about permissions? (e.g. You will be able to edit roles/permissions later from within your collective's 'Settings' Menu)
- 2nd page, why does it ask 'do you have a website?'  (//how will this info be used?/where will it be published? can it be edited later on? why are we asking this here?)

also, just thinking for whitelabeling purposes, the 'Read More' link will go to where? would that link be customizeable? (...should we consider adding an 'eligibility' section to fiscal host profiles?)

**Comment by kaylarep** [comment]
@aminakazi also, this is a canned reply I have to send out quite frequently (troubleshooting adding admin)

>I still only see 1 admin on your page here: https://opencollective.com/sacfoodnotbombs 
​
> - The first thing to check is that the added admins need to accept their emailed invitation 
>     - (They might need to check their spam folder.)
>- If there is still no invite email, follow [these instructions](https://docs.opencollective.com/help/collectives/collective->settings/core-contributors#re-send-email-invitations) above to resend.  
>- Make sure you clicked 'Save' at the bottom of the Add Admin page.



Can we make it really clear- after the admin has been added: that **they will need to accept their emailed invitation** in order for those added admins to appear on the page.  I think this is the main pain point in the 'adding admin' flow. (let me know if you need help with copy)

**Comment by BenJam** [comment]
@aminakazi is going to arrange a kick-off conversation to review the current design for this. Based on the complexity we can choose to pull in amendments to the automated GitHub sign up too.

**Comment by kewitz** [comment]
Things I would like to nail down in the kick-off conversation:
- [ ] Since this is a limitation enforced on the collective/user side, are we OK with not allowing exceptions to the minimum amount of admins rule? We need to make sure we want to enforce this rule, otherwise, it will only generate a new set of support tickets.
- [ ] I think this issue introduces a new set of security issues related to user authenticity. This means we need to have a process to verify users, otherwise, we can end up with a single user acting as multiple admins. How do we plan to fix this issue in the future without scaling inefficiency?

**Comment by alanna** [comment]
Please include @kaylarep in the kickoff meeting if possible

**Comment by kewitz** [comment]
### Technical Specs
- [ ] Add Host policy settings
  - [ ] Field to specify the minimum amount of Admins
- [ ] Onboard flow:
  - [ ] Add MessageBox about the minimum amount of admins policy and admin counter in the "Add administrators" popup.
- [ ] Collective Page
  - [ ] Add notification Banner if number of admins < minimum amount. Link to policy.
  - [ ] Prevent Collective from receiving contributions if number of admins < minimum amount
  - [ ] Prevent Collective from paying expenses if number of admins < minimum amount
- [ ] Collective Settings
  - [ ] Prevent collective from deleting admins if the number of existing admins <= minimum amount of admins.
  - [ ] Add MessageBox on Team Page if number of admins < minimum amount.

@aminakazi @BenJam as discussed on our kick-off meeting, can you confirm we're blocking collectives without the minimum amount of admins instead of blocking them from signing in?

**Comment by kaylarep** [comment]
Sorry I missed the kickoff, still have some thoughts- please disregard if redundant.

- I'm a bit confused about what the changes will be, but just in considering how the onboarding happens, individuals usually create their collective page before applying to a fiscal host, (is that correct?)
- if so, then the minimum admin requirement wouldn't apply until they select which fiscal host they want to apply to.  Then _after _that__ is where they would be pinged with something like "This fiscal host requires a minimum of 2 admin per collective. In order to submit this application, please add at least_ additional admin (+link)".

**Comment by BenJam** [comment]
Notes on conversation re github flow.

Current flow

| create collective | create open source project | apply to OSC | verify using GitHub | Pick a repository | complete application | 
| ---- | ---- | ---- | ---- | ---- |  ---- |
![Screenshot 2022-05-12 at 15 26 24](https://user-images.githubusercontent.com/158833/168098504-31e82d71-0810-45e9-8415-d6b13e45c41e.png) | ![Screenshot 2022-05-12 at 15 26 27](https://user-images.githubusercontent.com/158833/168098585-2b34e1a9-6793-4d4b-8d4d-30a0ab230798.png) | ![Screenshot 2022-05-12 at 15 26 32](https://user-images.githubusercontent.com/158833/168098627-4381131c-d92d-4bb5-a5f5-cec67dffb40c.png) | Skipped |  ![Screenshot 2022-05-12 at 15 27 32](https://user-images.githubusercontent.com/158833/168098699-24e659a3-7752-41a5-aa88-69f747a3ce6e.png) | ![Screenshot 2022-05-12 at 15 27 36](https://user-images.githubusercontent.com/158833/168098740-90876c82-2a10-43fd-ba12-a4fa8b940be3.png) | 

This flow _does not_ apply if you apply directly through opencolelctive.com/opensource/apply. Nor does it address any of the concerns outlined in https://github.com/Open-Source-Collective/osc/pull/4 but it does serve a purpose

- it pre-fills some of the Collective's information
- it validates that the user does have the right permissions on the repo/org to apply on its behalf

so we're keeping it.

For the moment we'll add the 'invite admins' process to the 'complete application' step to make it consistent with the generic application process, applying the same (frozen) restrictions if the host has enabled a minimum number of admins in their host settings.

**Comment by BenJam** [comment]
adding on behalf of @aminakazi because I dont like doing this in Slack :) 

>Here is a [link to the document](https://docs.google.com/document/d/140DjIO4QTE3HDOqYhs11KaRVzg0naOMUTt2l4cqeUPY/edit?usp=sharing) with all the discussion points listed out.
Here is a [link to the loom ](https://www.loom.com/share/363b1bf274e4461fbe658cd354e63937)which shows the ux and UI
> Here is a [link to the figma file](https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/?node-id=15574%3A218615) which has the screens from the

Feedback from me is

- Fiscal host settings look okay to me, may want to ask someone at SCA to check how they understand it
- changes to the application form(s) look great, I like the separation between the 'information' and the application itself. 
-  I like that the forms are consistent, I think you might want to follow the lead on the application to Open Collective Foundation with conversational language like 'Who will be inviting and approving expenses?' or similar.

**Comment by BenJam** [comment]
- [x] implement settings
- [ ] implement contribution block 
- [ ] finish sign up flow

**Comment by BenJam** [comment]
- [ ] review prs for sign up flow/settings
- [ ] fingers crossed for freeze implementation :)

**Comment by znarf** [comment]
Review and merge.

**Comment by alanna** [comment]
We are prepping for this at OCF. Can someone please explain...

* What happens to Collectives with a single admin when this is turned on for the first time?
* Are Collectives prevented from removing their second to last admin, or is it only enforced at the time of application?

@BenJam what's OSC's migration plan around this? Maybe we can copy your plan.

**Comment by kewitz** [comment]
> * What happens to Collectives with a single admin when this is turned on for the first time?

Nothing will happen for now. Later on, you'll be able to pick the option to automatically suspend contributions to these collectives.

> * Are Collectives prevented from removing their second to last admin, or is it only enforced at the time of application?

Yes. Once collectives have enough admins, they won't be able to have less than the required number of admins.
