### ISSUE TITLE
Collective Navigation v2: section updates

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3670]
Some things need to be moved around from where they are currently to match the new Collective navigation design:

- [x] move `${collective} is all of us` Contributors section into Contribute section - https://github.com/opencollective/opencollective-frontend/pull/5567
- [x] move Events from Contribute into its own section
- [x] create Connect section and put Updates and Conversations sections in it
- [x] add Recurring Contributions subsection to Contribute section
- [x] ~add core contributors "Team" subsection to About section~ see https://github.com/opencollective/opencollective/issues/3754
- [x] ~move "Connected Collectives" subsection from Contribute to About section~ see https://github.com/opencollective/opencollective/issues/3754
- [x] ~change how About section looks (no dark background, new left aligned section header, etc)~ see https://github.com/opencollective/opencollective/issues/3754
- [x] move Goals from Budget section back into own widget
- [x] move Top Financial Contributors ~from Budget section back~ into own widget

**Comment by sbinlondon** [comment]
@Betree Can I please assign you things here relating to the About section?

- [ ] add core contributors "Team" subsection to About section
- [ ] move "Connected Collectives" subsection from Contribute to About section
- [ ] change how About section looks (no dark background, new left aligned section header https://github.com/opencollective/opencollective/issues/3638, etc)

**Comment by sbinlondon** [comment]
> ### Section not yet changed/moved
> 
>     * [ ]  move `${collective} is all of us` Contributors section into Contribute section (but only displays financial contributors)
> 
> ### Section changed/moved but behind feature flag
>
>     * [x]  move Goals from standalone section into Budget section
> 
>     * [x]  move Top Financial Contributors from standalone widget into Budget section

If I understand correctly, these are going to all be widgets and so "all of us" just needs to stay in its own `Contributors` section; and then `Goals` needs to be removed from `Budget` and "top financial contributors" also needs to be removed from `Budget` and put back in its own widget? @Betree

**Comment by Betree** [comment]
> Goals needs to be removed from Budget

Yes

> "top financial contributors" also needs to be removed from Budget

I'm not sure which category makes more sense for it. Intuitively I would say "Contributors", but we can make this a widget if we want to keep some freedom.

**Comment by sbinlondon** [comment]
I think keeping "top financial contributors" as a widget makes sense. We have an "all contributors" section in the Contributors section category. But I think people would appreciate the "top financial contributors" as a widget so they can highlight it at the top or even hide it if they feel "all contributors" is enough.

**Comment by Betree** [comment]
We also need to define the default sections order. @Memo-Es Should we assume that the design in https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC.com%5D-Production-Ready-%E2%9C%85?node-id=6564%3A416 is reflecting the default sections order for newly created collectives?
