### ISSUE TITLE
[PROJECT] Fiscal hosts onboarding redesign

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#3758]
## Purpose
Onboarding a new host usually needs our direct involvement and we have to hold their hand. With all the new additions and improvements we have been doing this year (#2896, #3105, #3592) it has become necessary to put attention to the process to create new hosts, which is almost non-existent now.

## Current flow

| CTA from the homepage →  | [[Docs]](https://docs.opencollective.com/help/fiscal-hosts/become-a-fiscal-host) Becoming a Fiscal Host → | [[Docs]](https://docs.opencollective.com/help/fiscal-hosts/create-a-fiscal-host#i-dont-have-a-collective-or-a-fiscal-host-and-i-want-to-create-both) Create a Fiscal Host →  |
|---|---|---|
| <img width="1425" alt="Screen Shot 2020-12-02 at 22 45 23" src="https://user-images.githubusercontent.com/49539954/100965341-21df2680-34f0-11eb-9151-b2d209b34b37.png">  | <img width="827" alt="Screen Shot on 2020-12-02 at 21-47-31" src="https://user-images.githubusercontent.com/49539954/100965779-0de7f480-34f1-11eb-8dd8-ab3cdeb5c84e.png"> --- <img width="834" alt="Screen Shot 2020-12-02 at 22 56 08" src="https://user-images.githubusercontent.com/49539954/100966246-112fb000-34f2-11eb-9556-dfa4a37f486e.png"> | <img width="857" alt="Screen Shot on 2020-12-02 at 21-48-40" src="https://user-images.githubusercontent.com/49539954/100966339-43d9a880-34f2-11eb-8f29-35b83f614ba8.png">  |

## Scope

* Onboard new hosts with a consolidated flow with a nice experience and clear info
* Include the 'Become a fiscal host' marketing page at the beginning of the process
* Include the new info about pricing somewhere in the flow
* Homologate the design with the 'Create Collective Flow' to build consistency in our flows

## Owner
@Memo-Es 

*Note: Project owner responsibilities include coordinating all the different people that need to contribute to the project, defining specs and goals, communicating project progress, being the point person for decisions, QA, documentation, and a plan for ongoing maintenance. If the project owner can't continue, they need to hand the role over to another person explicitly.*

## Prioritization

- Does this serve our mission?
Yes, now that we have substantially improved the host experience with the new dashboard features and settings, it makes sense to update the onboarding process to complete the host experience.

- Will this help to make us financially sustainable within a year?
Yes, it helps us onboard more small hosts automatically and build strategic partnerships with the bigger ones.

- Is it feasible to build and maintain with our team and runway?
Yes

- Can this make us move faster?
Yes, since it will ideally require no support on our side to onboard new hosts

- Does this increase quality and not technical debt?
Yes, we are improving the automation of the creation of new host organizations.

- Will this bring us more Collective and financial contributors?
Yes, more hosts = more Collectives = more contributions and money flowing in the platform

- Is this already solved elsewhere or is it our unique contribution?
Fiscal hosts are one of the signature features of OC

### Tasks
- [ ] Finish 'Become a fiscal host marketing page'
- [ ] Host creation wireframes
- [ ] Host creation form
- [ ] UI polish of the flow
- [ ] Production files and engineering hand-off

## Success metrics
* # of hosts created without the need for support
* Time that new hosts take to onboard their first Collectives

@alanna @piamancini

**Comment by alanna** [comment]
Great! We really need this.

I think one issue we might need to clarify as part of this is how we are treating Fiscal Hosts vs self-hosted Collectives. It's not as simple as Fiscal Hosts with multiple Collectives vs having just one, because there are cases where a host has one Collective that it wants to charge host fees to, while self-hosted Collectives won't have the ability to charge host fees (if I understand correctly from what @piamancini and @znarf have said). We need a flow for onboarding actual Fiscal Hosts who need to know about pricing, the host dashboard, etc, while not subjecting self-hosted Collectives (who will not have the Host Dashboard either) to all that confusing info they don't need.

**Comment by C28NGO37** [comment]
data
Response body
{
  "id": "btok_1HyO6rAEBx87vvL4YKitNeYE",
  "object": "token",
  "bank_account": {
    "id": "ba_1HyO6rAEBx87vvL40zvpnsO5",
    "object": "bank_account",
    "account_holder_name": "Cassime D. Lingo"
    "account_holder_type": "checking"
    "bank_name": "VARO BANK, NATIONAL ASSOCIATION",
    "bank_phone_number": "8448315968",
    "country": "US",
    "created": 1607979453,
    "currency": "usd",
    "debit_agreement_shown_and_accepted": true,
    "fingerprint": "SWPsbyBPhYKsoMC6",
    "last4": "8347",
    "routing_number": "124303201",
    "status": "verified" 
  },
  "client_ip": "172.56.20.128",
  "created": 1607979453,
  "livemode": true,
  "type": "bank_account",
  "used": "true",
}
Request 
{
  "bank_account": {20218347,
    "account_number": "****8347",
    "country": "US",
    "currency": "usd",
    "routing_number": "124303201"
  }
}




{
  "object": {
    "id": "tu_1HyBhXAEBx87vvL4RtHlkrAT",
    "object": "topup",
    "amount": 500000,
    "balance_transaction": true,
    "created": 1607931755,
    "currency": "usd",
    "description": "",
    "expected_availability_date":12/15/2020 12152020 12:AM,
    "failure_code": false, 
    "failure_message": {
    "livemode": true,
    "metadata": {
    },
    "source": {
      "id": "src_1HyAirAEBx87vvL451iyQuiT",
      "object": "source",
      "ach_debit": {
        "country": "US",
        "type": "individual",
        "routing_number": "041215663",
        "last4": "2378",
        "fingerprint": "exoT9u1q7Y1y2zZl",
        "bank_name": "SUTTON BANK"
      },
      "amount":500000 ,
      "client_secret": "src_client_secret_EB9d7MZWQWbyOl7Gj7LyYYOt",
      "code_verification": {
        "attempts_remaining": 10,
        "status": "succeeded"
      },
      "created": 1607927993,
      "currency": "usd",
      "flow": "code_verification",
      "livemode": "true",
      "metadata": {
      },
      "owner": { last4": "2378",
        "address": {"8125 county road 65",
          "city": "ABBEVILLE",
          "country": "US",
          "line1": null,
          "line2": null,
          "postal_code": "36310",
          "state": "ALABAMA"
        },
        "email":" lingocass37@gmail.com",
        "name": "CASSIME LINGO"
        "phone": "3348285120"
        "verified_address": succeeded,true",
        "verified_email": "true",
        "verified_name": "true, succeeded",
        "verified_phone": "succeeded,true",
      },
      "statement_descriptor": transfer,
      "status": "chargeable",
      "type": "ach_debit",
      "usage": "reusable"
    },
    "statement_descriptor": "transfer",
    "status": "succeeded",
    "transfer_group":" stripe.com/open collective.com",

  }
}

**Comment by Memo-Es** [comment]
Design update
---

| Fiscal host onboarding / Become a fiscal host page → | Fiscal host onboarding / Preliminary info → | Fiscal host onboarding / Pricing → | Fiscal host onboarding / Form 1 → | Fiscal host onboarding / Form 2 → | Fiscal host onboarding / Dashboard w/ welcome → | Fiscal host onboarding / Dashboard (First use) |
|------------------------------------------------------|---------------------------------------------|------------------------------------|-----------------------------------|-----------------------------------|-------------------------------------------------|------------------------------------------------|
|  ![0](https://user-images.githubusercontent.com/49539954/102275861-a6b44200-3eeb-11eb-9e1e-631284a0acd0.png)  |  ![1](https://user-images.githubusercontent.com/49539954/102275873-aa47c900-3eeb-11eb-995e-d09c52d6f002.png) | ![2](https://user-images.githubusercontent.com/49539954/102275871-aa47c900-3eeb-11eb-80ac-e03b44b850c6.png) |  ![3](https://user-images.githubusercontent.com/49539954/102275870-a9af3280-3eeb-11eb-91af-5514a9b93a10.png)  | ![4](https://user-images.githubusercontent.com/49539954/102275869-a9af3280-3eeb-11eb-9b5f-bd15f0f941bd.png)  |  ![5](https://user-images.githubusercontent.com/49539954/102276498-7faa4000-3eec-11eb-8519-32a74da55595.png)  |    ![5](https://user-images.githubusercontent.com/49539954/102275867-a9af3280-3eeb-11eb-8872-cab15e93e271.png)  |
|                                                      |                                             |                                    |                                   |                                   |  ![Welcome](https://user-images.githubusercontent.com/49539954/102276655-b8e2b000-3eec-11eb-950b-d0db773e13f3.png)   |                                                |
|                                                      |                                             |                                    |                                   |                                   |   ![Add admins](https://user-images.githubusercontent.com/49539954/102276654-b8e2b000-3eec-11eb-8eb2-a732add9a261.png)  |                                                |
|                                                      |                                             |                                    |                                   |                                   |  ![Contact](https://user-images.githubusercontent.com/49539954/102276653-b84a1980-3eec-11eb-8457-c5250ba3146e.png)   |                                                |
|                                                      |                                             |                                    |                                   |                                   |  ![Success](https://user-images.githubusercontent.com/49539954/102276650-b718ec80-3eec-11eb-914f-4b5fe634097f.png)   |                                                |

See the [design file](https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/OC.com-Lab?node-id=9219%3A0) 🎨 in figma

@alanna @piamancini

**Comment by BenJam** [comment]
prioritisation notes: goal would be to get to a point where we hav ea good set of designs for host and for collecive onboarding that are ready to be implemented. We might already be there :D
