### ISSUE TITLE
[PROJECT] Merge settings and host dashboard 

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3880]
## Background
**Edit by Memo Esparza**
Last year, when we designed the host dashboard features: Paying an expense, manage collectives, adding funds, managing contributions, among some others... We realized the experience of entering the dashboard and navigating between the dashboard, the public profile page, and the settings were quite scattered, we saw the need for a consolidated space to have all these things.

The priority and main motivations always were to improve the hosts' experience, still, we realized this new admin dashboard will become the new pattern to keep access to settings and management features for all users.

In addition to the redesign, we should make sure:
- That the old links still work (a redirect is ok)
- That emails, docs and frontend are updated with the new links
- To properly update the documentation with new screenshots

## Project goal

1. Implement the new design for an admin dashboard for hosts, merging the host dashboard features with the settings page.
2. Implement the admin dashboard design experience for the rest of the users.

## Preview

![Large (Desktop)-1](https://user-images.githubusercontent.com/49539954/116900875-e069b900-abfe-11eb-9b46-6a5f1246a23f.png)
![Large (Desktop)](https://user-images.githubusercontent.com/49539954/116900880-e19ae600-abfe-11eb-8e82-f9479bb4a4e2.png)

| Tablet | Mobile |
|--------|--------|
|  ![Tablet Portrait](https://user-images.githubusercontent.com/49539954/116901438-89181880-abff-11eb-80a5-280d5b01e5c9.png)   |  ![Large (Desktop)-1](https://user-images.githubusercontent.com/49539954/116901390-7ac9fc80-abff-11eb-9abb-e1e141f0bedb.png)  |
|   ![Large (Desktop)](https://user-images.githubusercontent.com/49539954/116901393-7b629300-abff-11eb-89aa-f46bf2efc98e.png)  |    ![Large (Desktop)-2](https://user-images.githubusercontent.com/49539954/116901385-7a316600-abff-11eb-9084-fd552a4cb326.png)    |

## Project priorities

- Merge the settings page with the host dashboard in a new admin dashboard experience
- Implement the design of the sidebar navigation (Including a new button pattern of the navigation elements)
- Implement the design of the page headers and subheaders and the top navbar for mobile
- Implement the admin dashboard for all users (Collectives, organizations, and individuals)

### **Notes:**
- The widget 'Your new dashboard' is part of the sidebar but linked to a different project #4213 we can implement this particular widget from the other project's implementation issue.
- The 'Reports' section design is not part of this project's scope but is important to understand the context of the dashboard structure, we can leave what's under the 'Host metrics' section of the current Settings page for hosts.
-  The 'Overview' section of the dashboard is not part of this project's scope, it will be addressed in a future issue.

### **Implementation file:**
https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC-Design-Production-Ready-%E2%9C%85?node-id=10902%3A0

**Related issues:** #2665 #3894 #2896 https://github.com/opencollective/opencollective/issues/3395

### Milestones (@Betree can you help me with this section?)
- [x] Request feedback from hosts
- [x] Finalize the production-ready files
- [ ] Milestone 3
- [ ] Milestone 4
- [ ] 🚀 Review and launch

@shannondwray

**Comment by Memo-Es** [comment]
@BenJam I linked this issue with the roadmap project

**Comment by piamancini** [comment]
Review Call: 
In production, ready to implement.
It was a smooth project. Feedback loops were substantial because we involved the hosts. 
Gift certificates for hosts --

**Comment by kewitz** [comment]
Created a project: https://github.com/opencollective/opencollective/projects/64

**Comment by Betree** [comment]
This is done and released for everyone. Followups are listed in https://github.com/opencollective/opencollective/projects/64
