### ISSUE TITLE
Host Fee Share Percent for Foundation

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#4106]
### Problem

Foundation is working with Platform Tips for Credit Cards and PayPal. As part of their custom plan, the host fee is 5% and we don't want to  have it shared following `hostFeeSharePercent`.

## Solution

We need to  implement custom settings `credidCardHostFeeSharePercent` and `paypalHostFeeSharePercent` and set them to `0` for the Foundation host.

## Todo

- [x] support `credidCardHostFeeSharePercent` and `paypalHostFeeSharePercent`
- [x] update foundation settings with `credidCardHostFeeSharePercent` and `paypalHostFeeSharePercent`
- [x] update Transactions in March for foundation `hostFeeSharePercent=0` `isSharedRevenue=false`, delete `settled`
- [ ] verify that `hostFeeShare` and `pendingHostFeeShare` metrics are accurate for foundation
- [ ] calculate how much is owed to foundation
- [ ] add the owed money to foundation settlement invoice on April 1st

**Comment by alanna** [comment]
Let's talk about this in our meeting on Wednesday. The exceptional setup for OCF came about because of all the experimentation we were doing. Now we've clarified how platform tips and fees will work for all the other hosts, and it could be worth it to discuss if OCF should actually be treated as such an exception, or should just go on a much simpler option of the regular host plan with a 50% rev share instead of 15%. If we keep going with the unique plan where OCF has different fees depending on payment method, we should be clear about our justification for why that is.

**Comment by znarf** [comment]
Based on this morning discussion, we're moving forward with the original plan. Specs are up to date.

**Comment by kewitz** [comment]
To calculate the amount owed to Foundation this month.
```
SELECT
  t."HostCollectiveId",
  DATE_TRUNC('month', t."createdAt") AS "month", 
  SUM("hostFeeInHostCurrency" * CAST(t."data"->>'hostFeeSharePercent' AS NUMERIC) / 100) AS "owed"
FROM
  "Transactions" t
WHERE
  t."createdAt" > '01-03-2021'
  AND t."HostCollectiveId" = 11049
  AND t."data"->>'isSharedRevenue' = 'true'
GROUP BY
  t."HostCollectiveId", "month"
```
