### ISSUE TITLE
Platform Tip Share of Payment Processor Fees

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#4107]
### Problem

For transactions with Platform Tips, we introduced the notion of share of Payment Processor Fees.

Unfortunately:
- for third party Hosts, the Payment Processor fee is not gonna match what is reported on Stripe
- for most Hosts we don't have the opportunity to invoice it back, because there is no settlement invoice

### Solution

For now, it seems it's more future proof to remove this complexity and move to a simpler model that is easier to maintain.

### Todo

- [ ] Merge and deploy on March 31th
- [ ] Add a metabase query to show the numbers
- [ ] Check which transactions would be problematic ($1 + $10 platform tip, does this exists?)

**Comment by alanna** [comment]
I have noticed the `refunding processor fees on tips` transactions and I agree that's confusing and most hosts won't really understand what's going on. What would a simpler model be like? OC just covers the processing fees?
