### ISSUE TITLE
[PROJECT] Platform changelog page + Updates modal

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#4138]
## Background

We have been building up the intention to improve our product communication with users. Starting with an experiment about the communication of new features or improvements, I designed a modal to display 'What's new?' on the platform:

<img width="600" alt="What's new" src="https://user-images.githubusercontent.com/49539954/113229628-95056900-9254-11eb-80b5-d5b1013842f3.png">

It features a shortlist of new additions and fixes to registered users that log in to the platform, including space for visual media to convey new features more engaging. Plus, a link to go to our [changelog page.](http://changelog.opencollective.com/)

Furthermore, we realized that this project could also help us with our internal design and development process. It provides a clear goal-line to consider a project finished, including a basic form of documentation for each feature or addition.

## Project goal

Redesign the changelog page to display the product updates with a blog-like experience, with each new entry being the entry point for each feature. It will also include the 'What's new?' modal to pop out every time a registered user login into the platform and there's something new.

## Team

@Memo-Es (Owner)
@Aminakazi (Design)
???? (Engineering)

## Project priorities

- Redesign the http://changelog.opencollective.com/ page for it to be a display of our new features and additions.
- Include the design of the 'What's new?' modal to the new features discovery experience.

## References and links

- https://github.blog/changelog/
- https://changelog.shopify.com/
- https://support.zoom.us/hc/en-us/articles/360059076931-Release-notes-for-March-29-2021
- https://developer.amazon.com/docs/login-with-amazon/release-notes.html
- https://developer.apple.com/documentation/macos-release-notes

**Related issues:** #4134 

### Basic observations

- Most are textual, no imagery. (Except Github, which has screenshots and screen recordings)
- Most of them link to documentation related to the log entry
- Some of them have a search option to search the release notes
- All of them have a ‘title’ and a body copy giving the overview of the update along with miscellaneous other details (need dev input in understanding what KIND of details)
- A rich text input field should do the trick if we include additional multimedia options of adding images, code snippets, videos, etc.
- Some of them have a ‘share’ on social media option.
- Navigation is in a dated format, along with some ‘categories (e.g., admin, funds, features’ etc.) which can be added to the update while creating it. 

## Progress tracking (Design)

We will start by defining each new entry's content, the publishing process, and possible automation. Following with the design of the changelog page and the final version of the modal. When we'd be done with the feedback rounds, we will start implementation.

### Milestones
- [ ] Changelog content definition
- [ ] Changelog entry design
- [ ] Changelog page layout
- [ ] Final proposal
- [ ] Mobile versions
- [ ] Design in production

@BenJam @Betree

**Comment by Betree** [comment]
The current version of https://changelog.opencollective.com/ is still useful to display the full list of changes, so I think we should keep it somewhere for people who want to dig more precisely.

Some constraints that seem important to me:
- Anyone in the team should be able to post to this changelog - updates are often non-technical (eg. announcing new pricing).
- Related to the previous: posting to the changelog should be fast & easy, it shouldn't require any deployment
- (Not MVP) In the "What's new" widget presented above, we may want some news to only notify some specific audiences (eg. host admins)

Technically, the best solution that I see to achieve what you describe in the issue would be to re-use the Updates feature:
- Pros: 
  - easy to build on it
  - easy to fetch updates and create automation
  - anyone in the team can publish/edit
  - full control over the content
  - eating our own dog food
- Cons:
  - the editor might not be as rich as what you'll find on a typical blogging platform

**Comment by Memo-Es** [comment]
Closed in favor of https://github.com/opencollective/opencollective/issues/4213
