### ISSUE TITLE
[PROJECT] Projects Release

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#4204]
## Overview
> We're adding a way for collectives to manage finances for a project. 

Projects are a means for a collective to allocate and manage funds for a specific initiative within a wider context of all the work happening within a collective. We see communities creating new collectives or using 'events' to do this today. 

We have already created a pathway for projects, based on the code that powers events. This is probably best seen in action with the Digital infrastrcuture Grants at https://opencollective.com/di-grants. The use cases to be provided here are:

- the collective should have a single space for collective-wide budget, contribution, contributors, about, team and updates.
- the collective can then create 0-N projects which have their own budget, about section, contributors, contribution and expense workflows and updates

Initially we would like to uncover 'quick wins' that will enable us to push projects out to more collectives. From there we will open the doors for feedback, iterate and if it wors out roll into a release as an option for all collectives. 

## Owner/resources

- **Owner** **Second**
- [Project](https://github.com/opencollective/opencollective/projects/56?add_cards_query=is%3Aopen)

**Secondary Developer on project:** 

## Prioritization

- Does this serve our mission

Projects will help collectives better earmark and manage funds for speicfic efforts and initiatives transparently. It will encourage communities to think more about how they allocate funds and enable financial contributors to vote for specific proposals with their contributions.

- Will this help to make us financially sustainable within a year?

There is no strong link between projects and an increase in contributions to projects, but it does allow projects to reflect the maturity of decision making and as such that might incrase the confidence in the community from contributiors. 

- Can this make us move faster?

No

- Does this increase quality? 

No

- Does this add technical debt?

There may be additional technical debt added as the relationships between projects, parent budgets etc aren't clear at the moment with respect to how they should be accounted. 

- Is it feasible to build and maintain with our current team and runway?

TBD

- What insight or research is this project based on?

Users are already working around the Open Collective platform to implement project budgets using events and new collectives. 

- Is this problem already solved elsewhere?

See above. 

- How will we measure our success? Do we have a baseline today that we can compare this against?

- How well do we understand the complexity of the problem, feature to be added or user need to be addressed? 

There are a few areas of complexity that need to be ironed out in my opinion:

    - How do budgets relate to parent budgets, what flows need to be supported?
    - What permissions are needed for project vs. parent expense workflows
    - Should projects be able to offer contribution tiers and benefits?
    - Could projects be used to create funding proposals for contributors?

- What is the estimated timeframe for delivering this project? 

TBD

### Roadmap & Timeframe

- **May 14th** Unblock current Projects feature for collectives to enable and release announcement
- **Jun 18th** Gather feedback, judge success (see metrics)
- **Jun 25th** Prioritise development for next iteration

### Success metrics

- no. of projects created
- no. of projects with funds
- no. of active rpojects (contribution or expense within the last month)
- %age/total amounts managed with projects (vanity metrics)

### Release planning

**May 14th** 

- Which aspect(s) of the platform does this change impact?

All cllectives

- Which group(s) of users will benefit from this change?

Collectives that want to manage a portion of their budget separate from the main collective's budget, wihtout creating another collective.

- Is this project in response to a user-requested feature? If so who requested it (link to feature request if available)?

Users area already abusing Events to do this, some are creating 'realted' collectives. We are using projects for funds like https://opencollective.com/di-grants

- Is this project related to any similar work we have done, or are planning on doing in the next three months?

Events is a sucessful feaure in its own right, projects is a cut-down version of this feaure without ticket sales or end dates. 

### Next steps

- [x] Open up any appropriate project issues
- [x] Open a documentation issue, link it to this one
- [x] Open a release issue, link it to this one
- [x] Create a project board, add this issue to the description, add any issues created above 

## Project Closure

- Close all relevant project issues
- Open up issues for improvements 
- Post comm's according to comm's plan (most likely in release issue)
- Post project screencast on documentation slack channel 
- Post project closure in newsletter slack channel 
- Celebrate!!

**Comment by BenJam** [comment]
First step here is to kick off with @znarf et al to map out those low-hanging fruit. Please feel free to drop any useful issues/PR's that reference the initial development done 🙇‍♂️

**Comment by alanna** [comment]
Woo! Big +1 to this. I think it's going to really unlock potential. 

For me the concept of project is closely linked to tiers. A tier is how money comes in for a specific purpose or budget (not all tiers, some just go to the general budget, but many have their own goals and purpose), and a Project is how a Collective would manage that budget, submit expenses against it, etc. 

For an example of a Collective that would use this right away, see https://opencollective.com/ehf-collective. The tier goal based campaigns each have their own budgets and it would be great to give them their own admins.

**Comment by kaylarep** [comment]
This is another group that asked specifically for this feature: https://opencollective.com/solidaridad-inquilina

**Comment by BenJam** [comment]
Communities using projects already:

- Digital Infrastructure Grants https://opencollective.com/di-grants
- Modulo Learning https://opencollective.com/modulo
- Internet Freedom Fund https://opencollective.com/internet-freedom-support-fund

**Comment by BenJam** [comment]
## Kick off

> Release a small, constrained feature set that enabled folks to earmark and manage budgets for projects

Specifically this release will enable collectives to start a project, which can raise funds separate from its parent collective and spend money from that budget through the expense workflow. All user access and permissions will be inherited from the parent collective for the initial release. 

> Allocating budget to a project from a collective and via verse is currently supported, but could be improved

The current contribution flow can be (ab)used in order to transfer budget from a collective into a project, by contributing to the project *as* the collective. This is werid and the flow is confusing, but it does work. Initially we'll support users through this flow with good documentation, if we see folks doing this then we will improve this workflow.

> We'll go straight to general avaialability, but have projects as an opt in from collective settings

We want to enable projects for all collectives, but while we're finding our way with the correct feature set and permissions we'll add it as an opt-in from the `collective-page` settings. We'll use the number of folks who enable this as one of our primary goals. 

> There are a lot of places we could take projects, but we need to be thoughtful about what we *choose* to support

Tiers, goals and budgets all suffer from cross talk here. If I want to raise funds for a specific initiative should I start a tier with a goal, or a project with a goal? We need to be _opinionated_ here in order to create clear rails for users, reduce confusiona nd support requsts. 

## Goals

Immedaitely (this sprint) our goals are

1) Unblock collectives who need to allocate budgets to projects from existing collectives
2) Document how to use projects and how to transfer budgets to/from projects
3) Monitor usage and look to make improvements bacsed on feedback

## Next steps

- Ben will update the project issue with the outcome of the kickoff (ie. this comment)
- Ben will create a GH project and add issues for the work to unblock the release
    - [ ] Unblock current 'projects' feature
    - [ ] Adding 'projects' to settings   
    - [ ] Changelog/market/release plan
    - [ ] Documentation
- @znarf will take a look at the development work needed to unblock the feature release
- We'll find some time this sprint to get that done 🙌

## Later

Once we have a feel for how communities are using projects we can chart a course toward a roadmap that

- improves the 'transfer funds' steps for admiinistrators to move funds bewtween collectives and their projects — tweaking interfaces to better suit use-cases despite using generic platform constructs is something we often do, and we can make improvements here 'when you want to sell a t shirt maybe the feature should be called something else'
- clarifies the approach to take when raising funds for a specific cause (using tier goals vs projects)
- clarifies the boundaries between hosts, collectives and projects either explicitly through guidance and docuemntation or implicitly through feature set limitations — which might extend to creating on ramps for users to grow a project into a collective or visa versa. Better support for 'related collectives' might ease some of the tensions here.
- makes clear the distinction between budgets at the collective and the project(s) level: collective budgets are currently separate from the individual budgets of projects, which are first class objects also. This might be appropriate for some projects (for example the DI Grants collective may hold it's operating budget seprate from funds for sub-grantees) but may be less so for others. 

## Notes
You can find my raw, unadulterated notes over in this gist: https://gist.github.com/BenJam/a4abd8638c96266a171b46a9a2872c3b

**Comment by BenJam** [comment]
quick catchup with @znarf today on where this is at:

- [ ] need to add the 'free' donation tier to projects when created
- [ ] eed to link projects to their pages (i.e. add the 'see more' links
- [ ] need to ensure the correct url is presented in the 'create project' form 
- [ ] need to add explainer text to the project and event sections of the collective profile page
- [ ] need to update the banner to the new toast notificatio when creating a project

**Comment by BenJam** [comment]
Just adding the follwoing from https://github.com/opencollective/opencollective/issues/4074#issuecomment-816296189

> I would be really keen to be in the beta for this for EHF Community because we're raising a series of crowdfunding campaigns and I need to keep all their budgets and expenses straight. I am 100% fine if it's a bit rough and there's no different admin permissions, etc.

**Comment by piamancini** [comment]
Review Call: 
We ended up launching projects as they were for everyone. 
Release blogpost to be posted @BenJam 
Docs are published 
@znarf to collect metrics & close issue.
