### ISSUE TITLE
[PROJECT] Product Communication Improvements

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#4213]
## Background

We have been building up the intention to improve our product communication with users. This issue is to merge https://github.com/opencollective/opencollective/issues/4134 and https://github.com/opencollective/opencollective/issues/4138 into one initiative that can encompass these and other future efforts to improve our product lifecycle and make it more transparent and open to feedback from our users and community in general.

## Project goal

Integrate the new changelog with the standardization of user feedback for our platform. And set the next steps towards a better feature lifecycle for evolving our product.

## Team

@BenJam (Product)
@Memo-Es (Design)

## References and links

- https://github.blog/changelog/
- https://github.com/github/feedback/discussions

**Related issues:**  

### Primary ideas

- Design the changelog page as a forum-like experience for communicating updates and improvements in the platform and gathering feedback connected directly with a feature.
- Design a pattern to include small nudges in the experience of new features to go to that specific entry in the changelog forum and comment/give feedback/ask questions
- Integrate the 'What's new?' modal to the aforementioned experience.

### Milestones
- [x] Update the 'Updates' feature design
- [x] Changelog publishing flows and logic
- [x] Changelog page redesign (Including entries and threads)
- [x] Design for receiving feedback nudges
- [x] Project review and QA
- [x] Work on production files

@BenJam @piamancini @znarf

**Comment by Betree** [comment]
Regarding `Update the 'Updates' feature design`, I would keep that as simple as possible. Given that only the core team will be able to publish changelog entries, it's ok if the way we do so is not perfectly designed - at least for the MVP (like just adding "Changelog entry" in the select where you target the audience sounds enough to me).

The only page that users will really face from the existing update feature is the update page itself (where you can comment and add reactions, eg. https://opencollective.com/open-web-docs/updates/introducing-open-web-docs).

**Comment by alanna** [comment]
I really like the motivation behind this project, and absolutely think we should be more proactively seeking user feedback earlier in the design stage, and especially doing a better job of helping users be aware of features they aren't using. I just think we need to be careful not to overengineer this, because we could simply, you know, ask people what they think about things, which we don't. If this is a separate link people have to know about and go to, it's not going to work. I would prefer we copy good designs other apps have to let people know about new stuff, like the little dog who pops up in Trello to tell you things, or other contextual moments within the app.

**Comment by BenJam** [comment]
thanks for picking this up @Memo-Es. Maybe I shouldl I close out the #4134 in favour of this issue instead?

**Comment by piamancini** [comment]
Review Call Update: 
Work for changelog and update to updates was done. 
During the project we discovered the need to update comments. 
Still pending: Build prototype of modal pop-ups / behaviors. We need consensus. 

@Betree to propose specs for this project. 
Two phases: hack something to deploy quickly for the changelog to work. 
Future iteration: fixes to updates and changelog. 

Include implementation of changelog in the prioritization. 
Make changelog an option for all collectives?

**Comment by Betree** [comment]
Below is a proposal for some specs, based on the [design prototypes](https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/%5BOC-Design%5D-Lab?node-id=10194%3A672) and demos **that are still being iterated on**. These specs are meant to list the technical changes implied by this project, but my main goal here is really to propose an MVP for this feature, which I believe could be implemented pretty quickly.

# 1. Changelog MVP
The goal here is to hack the first version very quickly, with only the blocks that are really required to start using this feature. The feature shouldn't take more than a day or two to implement for someone familiar with the codebase.

## Ability to publish a changelog entry

- When creating a new update (or editing a draft) from https://opencollective.com/opencollective/updates/new, show a button set at the top to let the author pick between `Changelog Entry` and `Normal Update`. "Changelog Entry" should probably be the default since, on this URL, this form will mainly be used to publish changelog entries.
- If "Changelog Entry" has been selected, store this info in a new `isChangelog` column on `Updates`
- When editing an update that has `isChangelog` true, don't show the notification audience
- When publishing an update that has `isChangelog` true, do not send any email

<details>
<summary>Preview</summary>

![image](https://user-images.githubusercontent.com/1556356/118662353-3722e580-b7f0-11eb-8797-b6ded341e870.png)
</details>

## Implement the "What's new" modal

- On the GQLV2 `updates` query, add a `isChangelog` boolean filter
- Implement the icon/button that will trigger the modal
- In the modal, show the last 𝑥 (5?) changelog entries from `opencollective`

<details>
<summary>Preview</summary>

![image](https://user-images.githubusercontent.com/1556356/118663910-5b32f680-b7f1-11eb-821d-fa06c3fd4c31.png)

</details>


# 2. Changelog-specific features & enhancements

_These items still need to be reviewed, specified, and prioritized before we can move on to implementation._

- Subscribe to the changelog: users should be able to receive new changelog entries by email
- Link a Github issue to changelog entries, surface them in the list
- Add a toggle in the form to define if the changelog entry should be displayed in the changelog modal
- Add a specific page for changelog entries (ie. https://opencollective.com/updates)
- Track watched changelog entries (to notify users in the interface when there's a new one)

# 3. Update enhancements

_These items still need to be reviewed, specified, and prioritized before we can move on to implementation._

- Tags (with custom styles for "Bug fixes", "Enhancement" and "New feature")
- Cover image (https://github.com/opencollective/opencollective/issues/4098)
- Add emoji reactions on updates (https://github.com/opencollective/opencollective/issues/4185)
- Move drafts out of the main list, to a separate (admin-only) page (ie. https://opencollective.com/opencollective/updates/drafts)
- Add search for updates (by title, author, tags, etc)
- Publish update as a collective (as "Open Collective Engineering")
- New "Sign in to comment" design
- Add share button
- Update the overall design to match the new design

**Comment by BenJam** [comment]
> More especially, I propose to implement the first element (1. Changelog MVP) from #4213 (comment): Ability to publish a changelog entry + Implement the "What's new" modal.

> While the rest of the design is still being iterated on, this first block would give us the ability to beta-test the feature, which will help to prioritize further issues for this project. Plus, it should be fairly easy to implement, my estimate is around one or two days of work.

**Comment by Betree** [comment]
According to the latest design demo, this button in the host dashboard would trigger the changelog modal with only host-related news. Tags will be really helpful to implement that, as we would be able to write something like:

```jsx
<ChangelogModal show tags={['host']} />
```

![image](https://user-images.githubusercontent.com/1556356/119147940-528a2c80-ba4c-11eb-98c0-d5088be5c8c7.png)

**Comment by SudharakaP** [comment]
As discussed at Q2S2 priorities I'll be working on this and therefore I am assigning this myself. 😄

**Comment by BenJam** [comment]
# Kick off notes (implementation)

## Proposed implementation (this sprint)
For first release we will have a simplified version with a breakout from profilt dashboard, which is highlighted when there is new content, but always avaiaible for news and updates. 
![Large (Desktop)](https://user-images.githubusercontent.com/158833/120348671-4aa47500-c2f5-11eb-8818-84a0cfff366c.png)

prompted from the profile, which is shown only once. 
![Large (Desktop)](https://user-images.githubusercontent.com/158833/120348755-627bf900-c2f5-11eb-85a1-0b650c32b3a9.png)

this opens the modal with recent updates
![Desktop](https://user-images.githubusercontent.com/158833/120348927-8e977a00-c2f5-11eb-812d-6074df03496c.png)

These updates can also be accessed from the callout in the experience, which we initially add in PRs with feature releases (which links directly to the appropriate post).
![Desktop](https://user-images.githubusercontent.com/158833/120349242-d9b18d00-c2f5-11eb-9bc4-1ff0bca106ff.png)

## Proposal (linked above)
- MVP (this sprint) is the chagelog modal and publishing mechanics with a simple notice 
- later we can add drafts, targeting etc.

## Success metrics
- Would like to understand uplift in new feature usage from baseline
- Currently lacking ability to track user behaviour within browser
- Do have some ability to track in app to stop users from seeing same updates

**Comment by SudharakaP** [comment]
Thanks everyone for joining and sharing your ideas on the kickoff and thanks @BenJam for summarizing. 👍🏽 

So, I've created the project board at, https://github.com/opencollective/opencollective/projects/58. I'll update this as I go along. So as a starting point I'll be working on https://github.com/opencollective/opencollective/issues/4325 and https://github.com/opencollective/opencollective/issues/4326 and hopefully by the time we are done we can decide more solidly on the notification system as well. 🐨 🐼

**Comment by BenJam** [comment]
I'm cool closing this issue if you are @Memo-Es ?

**Comment by Memo-Es** [comment]
We can close this and open another one to track the implementation of the ['What's new?' page](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC-Design-Production-Ready-%E2%9C%85?node-id=12788%3A155434)
@BenJam

**Comment by BenJam** [comment]
let's add it to the stack of 'design ready to roll' things...
