### ISSUE TITLE
[PROJECT] Join a Host Page

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#4240]
## Background

This project started with the redesign of the OC website discovery page https://opencollective.com/discover focusing on the experience to find a host, or "host-shopping." 

During the discussion, we realized that most Collectives joining the platform already know what host they are going to join. For this reason, and to simplify the experience of using the platform, we are considering deprecating https://opencollective.com/discover and substitute it with a better search experience.

Adding also a page specifically to join a host, where we can showcase the host organizations that are partnering with us

## Project goal

1. Design a page to join a fiscal host
~~2. Design a better search experience to find profiles from anywhere on the platform~~

## Team

@Memo-Es (Owner)

## Project priorities

~~- Substitute the discovery page with a better search experience~~
- Design a dedicated page to find a fiscal host, showing our main host partners and a list of hosts with basic filters
- Edit the 'Create Collective Flow' according to the new Collective<>Host logic
Include the 'What's new?' design in the new features discovery experience. https://docs.google.com/document/d/1VcO_mQDsbPC0foW_WZ7a-L337I3VJVRHCQIPSLYNqrY/edit?usp=sharing

**Related issues:** #3892 

### Milestones
- [x] New search experience proposal (Wireframes)
~~- [ ] Search feedback loop and adjustments~~ Moved to search experience redesign issue
- [x] Join a host page proposal (Wireframes)
- [x] Join a host page feedback loop
- [x] High definition UI development
- [x] Mobile versions
- [x] Design in production

**Comment by BenJam** [comment]
Added to the roadmap for this sprint, ty @Memo-Es !

**Comment by Betree** [comment]
Also related: #2970

**Comment by piamancini** [comment]
Review Call Notes: 
search improvements is a continuation of this project. New issue to be opened by @Memo-Es 
Next steps: close the project.

**Comment by Memo-Es** [comment]
## Design proposal

We designed a page for collectives to choose and apply to a fiscal host; this page is adapted to be a part of the flow to accept financial contributions (Part of the create collective flow) and from the settings page of the collective.

| Create collective flow | Settings (New admin dashboard) |
|------------------------|--------------------------------|
|    ![accept-financial-contributions-host](https://user-images.githubusercontent.com/49539954/118573415-20c14f00-b748-11eb-8f8a-4135a22e7e8f.png)     |    ![Settings-accept contributions](https://user-images.githubusercontent.com/49539954/118573622-8a415d80-b748-11eb-9e6d-7a63a3305ee5.png)    |
|     ![accept-financial-contributions-host-2](https://user-images.githubusercontent.com/49539954/118573417-2159e580-b748-11eb-94a1-81902c09323b.png)    |      ![Settings-accept-contributions-2](https://user-images.githubusercontent.com/49539954/118573617-88779a00-b748-11eb-8a36-4bdac7098424.png)      |
|                        |                                |

- First, we have a small information box with the main info to get as much of the host context for OC
- We have a section of 'Featured hosts' to display our hosts and partner hosts more prominently
- It features a basic set of filters by:
    * Country
    * Fee structure
    * Currency
    * Services available
- We included a secondary CTA to know more about becoming a host and the possibility to join

cc @alanna @kaylarep

**Comment by Memo-Es** [comment]
### Feedback from slack

 Looking good! It’s such a big improvement.
- I think the key categories for fiscal hosts are location (currency is implied from this), fees, entity type (charity/nonprofit, company, co-op, etc) and services/focus area (likely tags, like open source, mutual aid, etc)
- In the screen where someone is selecting self-hosting, I don’t think there’s a big choice between Stripe account or Bank account - (many?) most people will connect both. So visually it doesn’t need to be designed as this big choice moment. The big choice is between self-hosted or fiscal host.
- I agree this page can live at opencollective.com/hosts - it can mainly function as a ‘find a host’ tool, but also serve the purpose of people just wanting to see and understand the diversity of hosts (maybe they are thinking of starting one, donating, etc).
- The ‘what is fiscal hosting’ page is so great and right now we don’t highlight it or link to it well, so let’s make sure we link from this page to that one, if people want to learn more about what hosting is about.

By @alanna

**Comment by Memo-Es** [comment]
https://www.loom.com/share/343a86026d1648a6bd264017b5f0e55c

**Comment by madhums** [comment]
This is great! I think this will help a lot! Thank you so much for this! And looking forward for this interface!

**Comment by BenJam** [comment]
Just to summarise the discussion I've had with @znarf @Memo-Es @Betree et al

We should take another run at the design above, taking a more opinionated view on what 'the happy path' is. i.e. that there are hosts that we are very close to 'incubate' hosts that we know and trust and other host that we know little to nothing about. There is still the option to manage your own money but we need to make it obvious that this is at your own risk. 

Some more detailed points:

- on the 'join a host' page we could organise the page to make hosted the obvious path.
- the 'other host' search could be replaced with the search that we already have (in terms of filters and the card content), but we would need to add a filter for hosts that are accepting applications and an option to remove 'featured' hosts as they'll most likely be hard coded in the top section.

**Comment by kaylarep** [comment]
I'm personally not feeling like this is scoped enough... We don't have a great enough understanding of exactly what people search for when they're trying to find a host (and I don't think we're currently gathering that information from hosts in a streamlined way that makes it easy to surface the important details.)

If these are the filters we're using
>It features a basic set of filters by:

> Search
> 'Sort By' Options (with option of Ascending or Descending)
> Budget
> Number of Backers
> Year Formed
> Alphabetical
> Recently Active (as in when someone was last active on their page either by donation, update, expense, etc.)
> Location (We can expand this filter later to include region→city, but for now, I think it is enough to display countries only)
> Fee structure (No host-fee and Host fee)
> Currency
> Services available
> Accounting
> Taxes
> Invoicing
> Payments
> Liability
> We included a secondary CTA to know more about becoming a host and the possibility to join


We need a lot more here... 
1) We need to be gathering this specific information from any group who onboards into OC as a 'Fiscal Host'. 
2) These questions are not granular enough to be truly helpful in 'finding a host'

Some context: There's "What country are you located in?"(Which needs to be asked to Collectives _and_ fiscal hosts. But there's also "What countries can you host groups from?" e.g. OCF is located in the USA, but can host international groups as long as they follow our International Activity Policy.  Because of all this nuance, the 'location' filter is not helpful, and could actually filter _out_ some eligible groups.

Also, I'm not certain about the goal of this project, as we don't have a large number of fiscal hosts to select from. Also also, just of the top of my head, I imagine that Collectives may want to know 'Mission' details when selecting a host (e.g. a lightweight fiscal sponsor vs. an 'arts-based' fiscal sponsor. )

Or are we trying to educate/promote to collectives better about the offerings of the select 'verified/1st party' fiscal hosts? I don't think the 'Filter' suggestions are a good enough representation of what hosts offer/collectives look for. (e.g. accepts Government grants, virtual cards, how often are expenses processed - a few more off the top of my head, but I imagine there's even more/better ones)

Since our offerings to fiscal hosts are not currently quite comprehensive, this might not really be a useful tool in its current proposal.

Who is the audience for this project?
- Groups who join OC wanting transparent finance, but not sure which host to use?  How many fiscal hosts are currently using OC, that this would truly be a beneficial sampling to a lost collective
   - (Then, if they aren't eligible for our main hosts, we direct them to IC, which there is not much support for. So we end up with a lot of abandoned collectives, who wasted some of their time setting up a collective/learning the platform when they cant even be hosted by a Host using the platform)
- Groups who join OC thru their host (they don't need this feature then)

**Comment by Betree** [comment]
Is this a duplicate of https://github.com/opencollective/opencollective/issues/5672?

**Comment by Betree** [comment]
This was implemented
