### ISSUE TITLE
[PROJECT] Virtual Cards

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#4276]
## Overview
Project board: https://github.com/opencollective/opencollective/projects/49

## Owner
@kewitz 

*Note: Project owner responsibilities include coordinating all the different people that need to contribute to the project, defining specs and goals, communicating project progress, being the point person for decisions, QA, documentation, and a plan for ongoing maintenance. If the project owner can't continue, they need to hand the role over to another person explicitly.*

**Secondary Developer on project:** 

## Prioritization

- Does this serve our mission

- Will this help to make us financially sustainable within a year?

- Can this make us move faster?

- Does this increase quality? 

- Does this add technical debt?

- Is it feasible to build and maintain with our current team and runway?

- What insight or research is this project based on?
- Is this problem already solved elsewhere?

- How will we measure our success? Do we have a baseline today that we can compare this against?

- How well do we understand the complexity of the problem, feature to be added or user need to be addressed? 

- What is the estimated timeframe for delivering this project? 

### Roadmap & Timeframe
(Key milestones or phases and estimated dates. Consider including further scoping, discovery, and prototyping. Include as a minimum: planning, design, development, documentation, feedback, iteration and, marketing)

### Success metrics
(What we will judge outcomes of the project by)

### Release planning

**Estimated delivery date**

- Which aspect(s) of the platform does this change impact?
- Which group(s) of users will benefit from this change?
- Is this project in response to a user-requested feature? If so who requested it (link to feature request if available)?
- Is this project related to any similar work we have done, or are planning on doing in the next three months?

### Next steps

- [x] Open up any appropriate project issues
- [x] Open a documentation issue, link it to this one
- [x] Open a release issue, link it to this one
- [x] Create a project board, add this issue to the description, add any issues created above 

## Project Closure

- Close all relevant project issues
- Open up issues for improvements 
- Post comm's according to comm's plan (most likely in release issue)
- Post project screencast on documentation slack channel 
- Post project closure in newsletter slack channel 
- Celebrate!!

**Comment by piamancini** [comment]
Review Call: 
We did a good spec issue at the beginning which made the implementation smoother. 
It was quite easy to implement, it was a greenfield so everything had to be built. 
There are more features that we'll be able to implement in the future. For example other vendors. 

It felt weird putting all the effort and not seeing so many people asking for it. It is useful for some people, and now we got to test it out. We now need to see how it plays along. 

Maybe we put in too much time for something that we still needed to test acceptance and need. 

@BenJam We need to make this as discoverable as possible and see how users pick it up. The unknowns are not technical they are operational / accounting.  

@kewitz Add metrics to dashboard. 

@Memo-Es to use example for changelog

**Comment by alanna** [comment]
I think people not using it is simply a subset of the problem we have announcing features and making users aware of features of the platform, not an issue with virtual card specifically. 

I think the best way to increase uptake would be to ask @alinamanko to note down every Collective she's processing expenses for that could be a virtual card (mainly monthly online subscriptions), and then we should reach out to those Collectives directly and ask them to switch. I think this would be worth it to reduce Alina's expense processing burden on its own, but will also help spread the word about virtual cards.

It's honestly an amazing feature that no one else would ever offer - we just don't do a good enough job of marketing. People have no idea about this and other features that would cause them to choose us over GitHub Sponsors or Patreon or whatever.

**Comment by BenJam** [comment]
++ I've got a list of our most active projects on metabase, I'll filter them for most recurring expenses and reach out to them first. 

_/me adds above to his todo list_

**Comment by znarf** [comment]
This project was completed I think.
