### ISSUE TITLE
[PROJECT] Improve events

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4280]
## Overview
I'm reposting similar content to #4129 as a proper project issue.

> Events is something we only ever implemented a basic version of and haven't had capacity to improve. But it's a feature that's used a lot and appreciated a lot by users. There is basically no one else combining events functionality with any of the stuff we offer: transparent budget, expenses against the event, fiscal hosting, crowdfunding. It's a really unique and valuable thing.

> If we decide to work on it, there is so much low hanging fruit. We already surface the events feature prominently in the interface and events are the first impression a lot of people have of the OC platform as event attendees. But there are many things that are not great about the user experience, and many missing features (many pretty simple ones).

@Betree 
> I agree that we have many low-hanging fruits for events. Dedicating a day or two to work on them could greatly benefit users. I've updated https://github.com/opencollective/opencollective/projects/29 to add all the event's issues that I found. A good way to prioritize this as a project would be to list what we want to achieve, to have a clear estimate of how long it will take. I suggest that we move all the issues that we want to tackle with this project into the "To do" column.

## Owner
I would love to be involved but I'm not sure I have capacity to lead the project right now.

## Prioritization

- Does this serve our mission
It's a well-loved feature of many Collectives and their Contributors. I think it engages people with the platform and does a lot to enrich the communities we serve. Events can help make communities sustainable in a variety of ways, financial and social.

- Will this help to make us financially sustainable within a year?
A while back we ran some numbers on how much money comes in via Events. We could run those again but I think it would be misleading because events have been mostly shut down during the pandemic (we only recently introduced a feature for online events). Looking at the pre-pandemic stats shows pretty healthy ticket sales, and if we improved the feature I think that would increase.

- Can this make us move faster?
It's a big selling point for many of the groups I onboard, and Collectives who use events often see more engagement from attendees with the platform, because they've already been introduced to it and signed up to go to an event. I think it can help us grow.

- Does this increase quality? 
Yes. Events are probably the least polished public-facing area of the platform, and the rough experience users have leaves an overall low-quality impression. We should bring it up to par with the higher quality of other features.

- Does this add technical debt?
Events are kind of infamous for producing bugs and problems, but I'll leave it to the devs to answer this one. I hope if we spent time to fix events up, they would create fewer technical issues.

- Is it feasible to build and maintain with our current team and runway?
Yes. We could achieve a lot of improvement with a relatively small investment of time and capacity.

- What insight or research is this project based on?
User feedback and evidence of use of the current events feature. Also the fact that a lot of groups have to use third party events platforms because our events aren't good enough, then send us the money manually (which causes admin overhead) - the number of groups who have done this indicates events is important to them but our offering isn't good enough.

- Is this problem already solved elsewhere?
No one combines events with crowdfunding and fiscal sponsorship, and no fiscal sponsor offers events functionality. I think it's really powerful. So while lots of other platforms do events, that integration of the budget is unique. Maybe we could consider integrating with a third party provider, but that seems like more work than just improving what we've got.

- How will we measure our success? Do we have a baseline today that we can compare this against?
Usage of events, money coming through events.

- How well do we understand the complexity of the problem, feature to be added or user need to be addressed? 
We know a lot about all the little problems. If we're just focusing on those, it's pretty clear. If we want to take this opportunity to really redesign events, that's more unknown.

- What is the estimated timeframe for delivering this project? 
I think "how far could we get in one six week sprint" is a pretty good starting place.

## Kick-off meeting
?

### Roadmap & Timeframe
- Review existing events related issues
- Decide if we're just going to fix things here and there or do a proper redesign
- ????
- profit

### Success metrics
If people host more events and raise money through events more. Less use of third party events platforms.

### Release planning

**Estimated delivery date** End of next sprint

- Which aspect(s) of the platform does this change impact?
Not sure

- Which group(s) of users will benefit from this change?
Collective admins and contributors, event attendees

- Is this project in response to a user-requested feature? If so who requested it (link to feature request if available)?
Yes, heaps of user-requested events improvements are in the backlog

- Is this project related to any similar work we have done, or are planning on doing in the next three months?
Kind of similar to projects

### Next steps

- [ x ] Open up any appropriate project issues
- [ ] Open a documentation issue, link it to this one
- [ ] Open a release issue, link it to this one
- [ ] Create a project board, add this issue to the description, add any issues created above 

## Project Closure

- Close all relevant project issues
- Open up issues for improvements 
- Post comm's according to comm's plan (most likely in release issue)
- Post project screencast on documentation slack channel 
- Post project closure in newsletter slack channel 
- Celebrate!!

**Comment by alanna** [comment]
We have also discussed integrating with an existing events tool instead of rolling our own. If we're looking into that https://alf.io is a Collective and an open source events tool.

**Comment by timfong888** [comment]
I am planning on making events part of projects funded and I would prefer a way to integrate with our events tools. 

Events is complex and I saw first hand both sides: building your own or being captive by a legacy vendor. 

However, the events space has heated up and so many options available that integrate ticketing as well as hosting. 

Could MVP be exploring the available APIs for third parties and then come up with what's the minimum point of integration?

Even if we were building our own, we would need to go API first anyway and so having a contract definition would be critical path. 

I can share the tools that have emerged and see if there are APIs for those.

**Comment by timfong888** [comment]
That being said, there are definitely some things I saw with open source events where a tight integration would be assume.  This was especially around Finders and Sponsors:

- Coupons based on the tier of funding or sponsorship
- Discounts based on tier of funding or sponsorship
- Discounts on sponsorship based on funding
- Coupons tied to contribution levels

In this case, the integration of the data based on financial data to basically shape the pricing of events can be compelling

**Comment by kaylarep** [comment]
User feedback:

>  we have a two day event but the confirmation email after folks get their ticket the text says the event is ‘being held on’ the first day only - might be nice to have that change to ‘between xxx and yyy’ for multi-day events

**Comment by RCheesley** [comment]
We ran our online event ticketing last year [entirely on OC](https://opencollective.com/mautic/events/mauticon-2020-aa109fa5) (300+ attendees, $18k raised) and are [doing the same this year](https://opencollective.com/mautic/events/mautic-conference-global-2021-46e0bcff). 

Happy to help with user feedback as we have bumped into a few challenges along the way and have some ideas that may be useful :)

**Comment by johav** [comment]
How can I use an event as a template for a recurring event? I want to offer an online workshop on a regular basis and can’t see how I can choose from an existing event to create a new one, or by just duplicating an existing event
(see https://docs.opencollective.com/help/collectives/events#create-an-event Event TEMPLATE does not seem to exist / I cannot find it)

**Comment by Betree** [comment]
@johav Thanks for this feedback, https://docs.opencollective.com/help/collectives/events#create-an-event seems outdated: the template field does not exist anymore (ping @shannondwray). 

We do want to bring back such feature in some way: https://github.com/opencollective/opencollective/issues/3707

**Comment by shannondwray** [comment]
Template option removed 😊

**Comment by johav** [comment]
oh... I didn't mean to suggest getting rid of it, but instead actually get templates up that are functional... is that an option for anytime soon / to easily schedule recurring events?

**Comment by shannondwray** [comment]
Have just removed this in our docs so that it doesn't confuse our users currently. If our devs want to work on bringing this feature back I will ensure it is documented :)

**Comment by Betree** [comment]
> oh... I didn't mean to suggest getting rid of it, but instead actually get templates up that are functional... is that an option for anytime soon / to easily schedule recurring events?

@johav you can track the progress for this feature on https://github.com/opencollective/opencollective/issues/3707. It has not been prioritized yet.

**Comment by BenJam** [comment]
pulled together a little dashboard for events showing what I think looks like events are starting to go up in usage again: https://opencollective-metabase.herokuapp.com/dashboard/58

**Comment by SudharakaP** [comment]
@BenJam : I am a bit confused on the relationship of this scoping project vs the prioritized Events Card mentioned here; https://github.com/opencollective/opencollective/projects/54#card-64273187. I put a link from the project card to here, but wasn't quite sure if this is the relevant project issue? Or is this a more generic scoping project for events and should we need another new project for the implementation of the two items mentioned in that project card? 🤔 😄

**Comment by BenJam** [comment]
@SudharakaP apologies, my poorly timed leave means that I wasn't able to copy the scope mentioned there here. But yes, we decided to focus on the things in the card rather than open the floodgates to _all_ the things that we could do to support events. This is due to the fact that, although there has been some growth, we still raise a small volume of funds through events.

**Comment by SudharakaP** [comment]
@BenJam : No worries. 😄 Thanks for the info. So I'll use the same project to track these issues; https://github.com/opencollective/opencollective/projects/29. 

The two issues mentioned in the card isn't very clear to me. But we have identified some issues that might be connected to this which we've put in the to-do section of the aforementioned project board. Specifically I think what you mean by "improve transfer of budgets from events/projects to collectives" is https://github.com/opencollective/opencollective/issues/4360? Or am I wrong? 🤔 Also for the second point in the card I think we need some more information, maybe we'll arrange a small call to discuss. 😄

**Comment by BenJam** [comment]
I think #4360 will probably be addressed in https://github.com/opencollective/opencollective/issues/4426 I was thinking about: 

For context, everything here is to support users to _use_ the ~150k sitting in event budgets. So we are trying to ease the process for maintainers to move money from events (we may as well do projects too) into parent collectives and visa versa. 

At the moment the process for moving money looks like this: 

| contribute as collective | confirm budget |
| --- | --- | 
 | ![Screenshot 2021-07-12 at 15 38 47](https://user-images.githubusercontent.com/158833/125309181-71f55580-e329-11eb-8bb0-36ed91ccd51f.png) | ![Screenshot 2021-07-12 at 15 38 59](https://user-images.githubusercontent.com/158833/125309207-77eb3680-e329-11eb-967d-68713e604632.png) | 

I think we might want something a little more obvious that encourages administrators to make a conscious decision to keep funds in an event/project budget (note i am not a designer):

| Before | After | 
| --- | --- |
| ![Screenshot 2021-07-12 at 16 06 1](https://user-images.githubusercontent.com/158833/125312550-47f16280-e32c-11eb-8ec9-a82d80413a0e.png) |  ![Frame 1](https://user-images.githubusercontent.com/158833/125312640-5f305000-e32c-11eb-8635-e5c0642b7ca4.png) | 

from here I think we can notify users (manually if needed) who have budgets in events with a balance that they should transfer them, with a link to this box on their budget pages. From there it's one click and poof, money is in the collective.

**Comment by SudharakaP** [comment]
@BenJam : Thanks for the detailed explanation Ben. I've created an issue for this at, https://github.com/opencollective/opencollective/issues/4446. I'll try to scope things related to this and but would like to wait for Benjamin before proceeding forward with the development. 😄 🤝

**Comment by alanna** [comment]
That's actually not the process... There's a banner and people just click the button.

![Screen Shot 2021-07-13 at 9 09 25 AM](https://user-images.githubusercontent.com/5498878/125356237-0a3b1b00-e3ba-11eb-8d43-5dc0d0881175.png)

You can't actually move money from an event another way, as far as I know. If you go to make a contribution, events don't show up on the options for the funding source.

I would highly encourage anyone working on the events feature to try to get involved in a real event and understand our product through that lens. 

To my mind, there are much more important issues than features for transferring money back to the main budget (although I do think that's a problem). For that, we could start really simply with an email out to all events with balances saying "click this button by X date to keep the funds in this event, or these funds will be automatically moved to your main budget", and then follow through.

**Comment by BenJam** [comment]
I think this issue is actually causing some confusion so I'm going to close this out in favor of https://github.com/opencollective/opencollective/issues/4469

**Comment by BenJam** [comment]
Just realised that this is linked to the main project page, and that it's quite possibly useful for that. I do think that https://github.com/opencollective/opencollective/issues/4469 should be the only events thing that we have prioritised this sprint (with a mod that as @alanna mentions it should be about improving the workflow for moving budgets between events/projects and their parent collectives) other than _contacting_ maintianers with a budget held in events — [I've added card for this](https://github.com/opencollective/opencollective/projects/29#card-65468766) —

**Comment by kaylarep** [comment]
do we want to edit the auto-reply sent out? At least to say : "New event attendee" instead of 'financial contributor' in both places?
![image](https://user-images.githubusercontent.com/64920686/126716799-8680a5cd-decb-4ab9-a934-3bf1018e56a8.png)

**Comment by kaylarep** [comment]
Also, after completing registration for an event, is it possible to include those buttons that allow you auto-import it into your gcal/ical/etc.? (do you know what I mean by this? I can find an example somewhere if not)

**Comment by carolineawoolard** [comment]
@BenJam this seems like a bug - the time zone in the body of the event email is different than the time for the event. 
![Screen Shot 2021-08-03 at 9 36 41 AM](https://user-images.githubusercontent.com/88373348/127986004-2ece1de5-366a-4370-9797-7210a9186abb.png)

**Comment by carolineawoolard** [comment]
Events UI/UX issue -- events appear in the order that they are created, not soonest first.

**Comment by BenJam** [comment]
@carolineawoolard @kaylarep I think maybe we should break these issues out separate from this project issue. So I'll do that now.

**Comment by alanna** [comment]
More events issues:

#4521 #4480 #4469 #4474 #4382

**Comment by kaylarep** [comment]
a couple more Events suggestions:
![image](https://user-images.githubusercontent.com/64920686/132589793-97de53ef-31a2-4071-a342-14b0c2868734.png)

- Events should appear in the frozen header (or at least as a drop-down under 'Connect')
- Past events should have much less prominence (either greyed out; or not appearing at all, but have a link somewhere to 'View Past Events')

**Comment by SudharakaP** [comment]
> a couple more Events suggestions:
> ![image](https://user-images.githubusercontent.com/64920686/132589793-97de53ef-31a2-4071-a342-14b0c2868734.png)
> 
>     * Events should appear in the frozen header (or at least as a drop-down under 'Connect')

@kaylarep : Are you taking about all the events appearing in the drop-down so that you could select any event related to the collective there? Currently one can navigate to events using the `Contribute` section drop-down. 🤔 

![Screenshot from 2021-09-09 06-56-25](https://user-images.githubusercontent.com/12435965/132699240-6bc44d8e-f7e7-48e7-8119-188e38c1d86d.png)

>     * Past events should have much less prominence (either greyed out; or not appearing at all, but have a link somewhere to 'View Past Events')

@Betree @Memo-Es : I am okay with greying out the past events if this is something agreed on?

**Comment by kaylarep** [comment]
> @kaylarep : Are you taking about all the events appearing in the drop-down so that you could select any event related to the collective there? Currently one can navigate to events using the Contribute section drop-down. thinking

@SudharakaP ah! good catch, my mistake...wonder if it fits better in the 'Connect' section? but also, since its a method of 'contributing', makes sense to keep it there too.

**Comment by alanna** [comment]
Having Events in the Contribute section causes a lot of issues (like #4480 ) - I think it should be its own section. Same with Projects.

**Comment by Betree** [comment]
> Having Events in the Contribute section causes a lot of issues (like #4480 ) - I think it should be its own section. Same with Projects.

Events and projects already are their own sections. You can selectively disable them in the settings.

**Comment by kaylarep** [comment]
some data about how much OCF initiatives use Events

![image](https://user-images.githubusercontent.com/64920686/135916859-be123bcc-55f7-4d9f-b8bb-6d042df616d8.png)

**Comment by kaylarep** [comment]
https://github.com/opencollective/opencollective/issues/4784

**Comment by petervaldaz** [comment]
Hi
🪴🪴❤️🪴🪴

**Comment by kaylarep** [comment]
just to repeat this: really don't like 'Events' being in the 'Contribute' section. I never remember to look for it there. it should either be standalone or in 'Connect'

**Comment by kaylarep** [comment]
> do we want to edit the auto-reply sent out? At least to say : "New event attendee" instead of 'financial contributor' in both places? ![image](https://user-images.githubusercontent.com/64920686/126716799-8680a5cd-decb-4ab9-a934-3bf1018e56a8.png)

is this one tough to do?  I think it's a bit necessarily confusing.

**Comment by Betree** [comment]
@kaylarep The best way to get small bugs prioritized is to create dedicated issues. This one is great as a catch-all to get feedback but things get lost and fixes will probably not come before we prioritize the entire project.

**Comment by kaylarep** [comment]
From [a user](https://opencollective.slack.com/archives/C0429NTTABF/p1670242836737709):
> a couple of bugs/difficulties in the process - 1) inaccurate count of the registrations, 2) no possibility of deleting the registrations.
