### ISSUE TITLE
[PROJECT] All Your [Meta]base: Using Metabase to inform our strategy

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#4282]
## Overview
I have a bit of a data blind spot at the moment as I haven't had the chance to spend a significant amount of time with metabase. I do however suspect that we lack some answers to some o the questions that we need to answer to better understand how Open Collective is  growing and what we can do to accelerate it. 

![metabase](https://user-images.githubusercontent.com/158833/118118666-2552d400-b3e5-11eb-8d44-4fc254615226.png)

Copied from https://github.com/Open-Source-Collective/board/issues/6

**Finance**
- [ ] How much money are we holding on behalf of collectives right now, and how has that changed?
- [ ] Why has the balance changed? are we getting fewer donations or more expenses?
- [ ] How much did we see in contributions this month
- [ ] What was the spread of contributions and how is that changing?
- [ ] What was the proportion of one off vs. recurring contributions
- [ ] How are users contributing (payment provider, currency)

**Ops** 
- [x] [what is this user associated with (collectives, admins, etc)](https://opencollective-metabase.herokuapp.com/question/335)
- [x] [find a user given their email](https://opencollective-metabase.herokuapp.com/question/335)
- [x] [find orders and associated transactions to check the status](https://opencollective-metabase.herokuapp.com/question/336)
- [x] [find donations made as an org for a user (check associations)](https://opencollective-metabase.herokuapp.com/question/336)

**Stats**
- [x] [What does the distribution of funds look like for collectives](https://opencollective-metabase.herokuapp.com/question/345)
- [ ] How many zero collectives are there that are inactive, that we could delete?
- [ ] How many non zero collectives are there, that we might want to reengage?
- [ ] What does the distribution of contributions look like for indiivduals vs. orgs

**Usage**
- [ ] How many daily and monthly active contributors do we have? (contributed to a collective)
- [ ] How many daily and monthly active community builders do we have? (approved an expense, added a collective, added a project, added an event, filed and update) 
- [ ] How many daily and monthly active collectives are there this month (where active means an expense was filed, approved, etc a project, event or update was created or someone) compared to last month

**Growth**
- [ ] How many new collectives did we see?
- [ ] How many new collectives received a contribution?
- [ ] How many new collectives paid an expense?
- [ ] How many new backers did we see and what's the split (individual vs. org)?
- [ ] Did these backers make a single donation, or donate to more than one project?
- [ ] Is the average user contrbuting more or less over their lifetime, what changes this?
- [ ] How many collectives does an individual/org contribute to and how are they changing over time?

## Owner
@BenJam

**Secondary Developer on project:** 

## Prioritization

- Does this serve our mission
Without understnading our data and having confidence in it we're unable to set priorities. 

- Will this help to make us financially sustainable within a year?
See above.

- Can this make us move faster?
We should be able to use metabase to answer questions abot the sucess of projects we deliver and on our business as a whole. If we're able to see, objectively, whether something is working as inteded or not, then we should be able to adjust faster.

- Does this increase quality? 
As above.

- Does this add technical debt?
Metabase is designed to inherit changed in the databse, but views ('questions') stored in Metabase may need updating if we make changes. So this actively creates technical debt of a sort yes. 

- Is it feasible to build and maintain with our current team and runway?
Yes.

- What insight or research is this project based on?
A lack of (personal) insight into some of the core questions I have about Open Source Collective and Open Collective's products and services. 

- How will we measure our success? Do we have a baseline today that we can compare this against?
We're able to answer most of the questions listed in https://github.com/Open-Source-Collective/board/issues/6 (coipied above also)

- How well do we understand the complexity of the problem, feature to be added or user need to be addressed? 
I do not understand the complexity of some of the questions asked, some of them are inevitably already answered, but it's difficult to navigate. 

- What is the estimated timeframe for delivering this project? 
I'm happy to dedicte at least a full week to this, working with someone who understnads the ledger and the queries that are already avaiaible.

**Comment by alanna** [comment]
Massive +1 from me.

Can training the team (read: me) to use and navigate Metabase better be a part of this? I get so lost, even finding queries I know I've looked at before. Designing some dashboards we can access and iterate on, which are more accessible.

**Comment by BenJam** [comment]
> Can training the team (read: me) to use and navigate Metabase better be a part of this?

YES. I will fully pick up the 'training' part if I can level up to the degree that i understand the data as well as the means to query it. In the meantime i would recommend runnign through some of the SQL tutorials at:

https://www.sqlteaching.com/#!select

https://cwiki.apache.org/confluence/plugins/servlet/mobile?contentId=38572242#content/view/38572242

https://pgexercises.com/questions/basic/

**Comment by BenJam** [comment]
from @alanna in https://github.com/opencollective/opencollective/issues/4224

>It would be interesting to look at data about how people are using invited expenses:

> - How much detail are inviters putting in (of what we allow them to input) and how much at they leaving for invitees?
> - How many invitations are completed vs ignored/failed?
> - How many invitations result in individuals or orgs submitting the expense?
> - How many of the individual ones actually should be orgs (profile name does not match payout account owner)?

**Comment by BenJam** [comment]
Another issue that it might be worth digging into https://github.com/opencollective/opencollective/issues/4265#issuecomment-847721298

**Comment by BenJam** [comment]
Just summarising a conversation with @piamancini last week practical needs

- checking associations for a user when someone is emailing support
- finding a collective for a given user
- updating an email if the user has login problems
- deleting debit transactions
- looking up orders and associated transactions if someone hasn't seen money in their collective
- donations as an org, but meant to do it as an individual 
- adding ourselves as admins to troubleshoot
- updating expenses, contributions, etc to remove personal details
- Checking pending orders
- checking who is the admin of an org
- submitting expenses on behalf of an org instead of individual
- checking which collectives are active 
- fixing the revenue dashbaords
- checking total revenue for USD/source (tips, host etc)
- checking volumes to get a better deal from transferwise

**Comment by BenJam** [comment]
I'm going to close this out as I feel confident that I can answer most of the questions above now within minimal support. Loom video series for folks looking to use metabase over at https://www.loom.com/team-videos/Metabase
