### ISSUE TITLE
[Project] Search Experience Redesign

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#4295]
## Overview
During the scoping discussion of the project to design a new experience to search for a host and join a host #4240, we realized that we could improve the discovery page and search in open collective experience to provide better search capabilities from anywhere in the platform (#2970). Last sprint Q2S1, we tackled the join a host page and a preliminary design approach to this new search experience:

| Search mode=Off | Search mode=On | Search mode=On, Results=True |
|-----------------|----------------|------------------------------|
|   ![Large (Desktop)-1](https://user-images.githubusercontent.com/49539954/118583511-cf6e8b00-b75a-11eb-9209-31d8cce7dc6a.png)     |   ![Large (Desktop)](https://user-images.githubusercontent.com/49539954/118583517-d09fb800-b75a-11eb-8db2-73adb50fdeca.png)     |  ![Large (Desktop)-2](https://user-images.githubusercontent.com/49539954/118583506-ce3d5e00-b75a-11eb-9e73-cd143f219d3f.png)     |

We are introducing some main improvements to the current version:
* Deprecating the 'Discovery' page www.opencollective.com/discover
* The search function is now under a 'search mode.'
* The user can search for different profiles (Hosts, collectives, organizations, and users) by just typing or click enter for every new search

## Ownership [following edited by @benjam]
*Product* @benjam
*Design* @memo-es 
*Engineering* @SudharakaP @znarf 

*Note: Project owner responsibilities include coordinating all the different people that need to contribute to the project, defining specs and goals, communicating project progress, being the point person for decisions, QA, documentation, and a plan for ongoing maintenance. If the project owner can't continue, they need to explicitly hand the role over to another person.*

## Problem statements
> as a community I want to find a host for my project (including country/currency and cause) i.e. supporting open source projects based in europe

> as a supporter I want to find communities in my area to support i.e. example food banks in the pacific north west 'PNW'

> as a host I want to share examples of successful communities that we support in a certain area/domain i.e. all our mutual aid collectives based in NY

## Narrowing down the problem
- the current search criteria does include name, slug, about, and tags but the results can be poor specifically showing inactive projects and pledged collectives
- there's an issue with certain types of active organisations clunking up search results (casinos et al) that are against our ethical policy
- collective can tag their projects to improve search but rarely do, some hosts encourage collectives to tag as part of their onboarding process
- it's difficult to search by location (country, or region) some hosts are encouraging collectives to use tags to do this
- it's difficult to know what to search by, some examples of search criteria (a tag cloud was mentioned) could be useful  

## Shaping a solution
- [x] replacing the discover page with the search results, deciding what needs to be ported over and what can be removed #2970
- [x] reviewing the problem statements above and identifying example search criteria to inform design and engineering (above)
- [ ] identifying areas where search results do not match expectations and addressing them (engineering)
    - searching for `opensource` should return open source projects and hosts dedicated to supporting open source projects, ordered by 'activity' (credits on collectives)
    - searching for a `organisation name` should return organisation ordered by activity (debits to collectives and projects)
    - search for a `host+country` should return hosts ordered by number of collectives supported
    - searching for `cause+region` should return projects associated with `causes` (a tag) and `region` (a tag) ordered by activity (credits)
- [ ] ~~addressing unwanted but valid results in search results (i.e. casinos, escort agencies etc)~~
- [x] updating the design to provide the necessary filters and controls to construct queries to answer the cases (design+engineering)
    - searching by string should provide results based on `name`, `slug`, `tag`, `description`, `country`
    - users should be able to filter by `type` (host, collective, organisation, event, project, fund) 
    - users may want to further filter results by `country`, and `tag`
    - if the user is filtering by host they may want to additionally filter by `host currency`
    - user may want to order results ASC/DESC by `activity` as defined above
- [ ] addressing the lack of usage of country/tags, and how to include them in a sign up flow

## Setting the appetite 
(i.e. which problems we'll address this sprint)
- removing the discovery page in place of search
- improving search results for with current architecture for specific types of query (above)
- updating search page to construct queries that answer the cases above 

not addressing currently
- improving adoption of tags
- cleaning up inactive/unwanted search results
- moving to a new architecture for search 

## Roadmap/timescales

 - [x] Intial design
 - [x] Design review
 - [x] Production files
 - [x] Change the way of working to integrate designs nd engineering into one process
 - [x] Reprioritise project
 - [x] Scoping week
     - [x] Identify and validate problem statements
     - [x] shape solutions and compartmentalize into problem spaces
     - [x] set the appetite and decide what we're going to deliver this sprint
 - [ ] Development weeks 
 - [ ] Release week

**Comment by BenJam** [comment]
just jumping in to +1 this as I have a collective I'm having to decline and I would *love* to be able to provide a flow for them to find (or create) a more appropriate host.

**Comment by kaylarep** [comment]
as a user experience, I often can't find what I'm looking for in our Search bar and end up googling `Open Collective _collective name_ ` to locate it instead, and have better success this way.

**Comment by kaylarep** [comment]
also note these suggestions: https://github.com/opencollective/opencollective/issues/2232

**Comment by kaylarep** [comment]
would be amazing if the search bar also searched in the 'About' section of a group's page

**Comment by Betree** [comment]
> would be amazing if the search bar also searched in the 'About' section of a group's page

That was previously the case but we stopped doing it in https://github.com/opencollective/opencollective-api/pull/6879, mostly for performance reasons. We can probably bring that back if we move to a more performant system in the future (ElasticSearch, Algolia, etc)

**Comment by kaylarep** [comment]
Another User Case:
A donor (financial contributor) has written to OCF:

**Comment by kaylarep** [comment]
https://github.com/opencollective/opencollective/issues/4759

**Comment by kaylarep** [comment]
A couple other thoughts/questions:
- remove 'Pledged Collectives' from the Search/Discover page -(unless this is frequently used. I don't fully understand the 'Pledged Collectives' option, but I don't know that it needs special spotlighting on the Discover page - there would be other categories I would prefer to be spotlighted-especially groups that are already on the platform)
![image](https://user-images.githubusercontent.com/64920686/156050967-06493985-01de-413a-8208-9f2534987be7.png) 
- if someone searches 'community garden', and we've tagged it as 'garden' (will it still be findable this way) , will it still come up? + if someone searches 'free fridge', and we've tagged in 'fridge' will it show up?
    - maybe we add a page to the docs describing "Discoverability" - within the Customize your collective sections?
        - describing what the search searches (e.g. From your page's Info within Settings: Display Name, tags, Short description, ___"; Spelling must be exact on your page and in the search to be found; does not search the About section, though sometimes it can still be found thru a Google search...some things like this) 
- maybe to add to header of new search page: "This search is used to find groups who are using Open Collective to transparently manage their finances. If you're looking for help using the Open Collective platform, check out [our Documentation](www.docs.opencollective.com), our Case Studies, Our How-To sections in our Blog & Our Youtube Channel, or ask in #community-support on Slack (+links)
- if nothing comes up for a search result, maybe the page can display a message like "Didn't find what you were looking for? Try searching [our Docs](www.docs.opencollective.com). "

**Comment by alanna** [comment]
I had a recent discussion with Accountable and they said they were keen on this for sure, especially in relation to searching by tags.

**Comment by kaylarep** [comment]
@Memo-Es can you please post the figma files here?


**Some notes from today's meeting:**

What are we trying to solve? 
- "Hosts that are not findable"
- "individuals who are seeking support in their sector/region"
- "financial contributors who are seeking groups to support"
- "collective members who are trying to find like-minded groups"
- ____ (what else?)
- _This is a bigger question, would likely need a separate project to redo our algorithim/search structure_
- _This project will focus on simple fixes that don't change how our search operates_

A sample of a search experience with category buttons/filter dropdowns options that I really like:
![image](https://user-images.githubusercontent.com/64920686/157278176-19ae2cc1-617a-4e6e-a75b-c3103a9c2bed.png)

Edits that can be made that would improve the Search experience (maybe get comms input for best copy to use):
+ add a tag cloud
+ Search instructions: e.g. "Separate search terms with spaces, commas. Search using tags" -- maybe even provide examples? ("Try searching 'garden' instead of 'community garden' to get better search results" or something like this)
+ somewhere, provide this info:
    + What is being searched (Results are fetched only from: tag, slug, name, description) -- 
      + hopefully, being clear about this info on the search page will empower users to tag their collectives/edit their descriptions accordingly
    + Please use exact spelling (typos will not turn up accurate results)
+ 'Sort by' options (that @Betree said are possible & won't slow don't the search): 
    + creation date (Newest/Oldest)
    + most accurate (am a little confused about this. Would 'Relevancy' be a good word?)

MVP:
- Merge 'Search' and 'Discover' pages
- Identify criteria for finding profiles
- as a user, I would like to be able share a clear results page if (for example), someone asks for : "groups in Oregon doing grocery delivery" or "any groups in the Phillippines" -- or make it easier/clearer for them to do this search themselves
- as a collective admin, I would like to find a fiscal host I am eligible for (+location), that aligns with my mission

**Comment by SudharakaP** [comment]
Thanks for the detailed notes @kaylarep 🤗 Leaving some thoughts on the notes we took based on today's meeting especially regarding the MVP and the next steps,

### Goals and Needs of the project

Here we are only focusing on the revamping the search experience design aspects and adding some more filtering capabilities (filter by tags and location). We are **not** digging into the search algorithm itself or trying to make it smarter. Some pain points currently,

- Cannot search for fiscal hosts in Discover page
- Cannot filter collectives by a region; i.e: Cannot find "all collectives from Portland". 

### For the MVP we decided on,

- Merging search and discovery pages (or removing discover page and replace that with search); https://github.com/opencollective/opencollective/issues/2970
- Basic filtering criteria (host, organization, collective and event); part of https://github.com/opencollective/opencollective/issues/3892
- Add secondary filters to search by location (country) and tags; part of https://github.com/opencollective/opencollective/issues/4759
- Have a simple "sort by" options with creation date

### Pending Design discussions

- See what to do when there's no result returned by filters
- Finalize what filters we want to include

## Next steps

@kaylarep @BenJam come up with some example of queries and anticipated results
@memo to look at design(tagging, sorting) creation date, accuracy,
meeting tomorrow with @znarf  

### Some other useful things to think/talk about; 

- Making tag creation more front and center; https://github.com/opencollective/opencollective/issues/4764
- Killing pledges completely.

**Comment by kaylarep** [comment]
Not sure if we can do anything about this, but a [user example](https://opencollective.slack.com/archives/G013S279X63/p1646694320287139) of a pain point provided by @alinamanko :
> I was looking to share privately collectives hosted that people can support if during this time.  If we [didn't have these casino's showing up in the search page](https://opencollective.com/search?q=ukraine), it would have been a good one to share but right now it doesn't look right

maybe could be slightly remedied by the 'Sort By' : 'Accuracy/Relevancy' option?

**Comment by kaylarep** [comment]
if the search turns up no results, the page should display a link to the docs (+maybe a good place to put some of the search tips):

e.g. :

> Couldn't find what you were looking for? A couple things to try:
> - Make sure your spelling is correct
> - Broaden your search (e.g. search 'garden' instead of 'community garden')
> - Search [our Docs](https://docs.opencollective.com) for more info about using the Open Collective platform
> 
> Still no luck? Contact support@opencollective.com or find us in Slack (+link)

**Comment by BenJam** [comment]
notes following demo from @Memo-Es (who i'm sure will drop a link to latest)

- need to think a little more about the 'finding a host' story as users may not be successful is searching by currency or country, what we need to address is how hosts communicate where they're able to support projects (i.e. Open Collective Foundation in US only, OCEU across the EU)
- need to think about the default (empty) search as activity is a complex notion when including hosts, collectives, etc
- when updating the search criteria we should bear in mind that the current search powers the collective picker.

**Comment by kaylarep** [comment]
'Currency' could be a good drop-down filter! (thoughts?)

**Comment by Memo-Es** [comment]
## Design update

| Filters hidden  | Filters expanded  |  Different sets of filters per entity  | Showing results   |  No results  |
|---|---|---|---|---|
| ![mockup](https://user-images.githubusercontent.com/49539954/158094753-a2bc0481-503a-48a2-a8c3-fbe02daf4133.png)  | ![mockup-3](https://user-images.githubusercontent.com/49539954/158094748-b04ba440-4dc7-4aa5-a6f3-31c730e11df1.png)  |  ![mockup-4](https://user-images.githubusercontent.com/49539954/158094750-ac6c46ed-0438-4055-b0c7-9cde2f2f0f41.png)  | ![mockup-1](https://user-images.githubusercontent.com/49539954/158094743-a8835028-1f5c-4b1f-b3fb-8383add35947.png)  | ![mockup-2](https://user-images.githubusercontent.com/49539954/158094745-160a3c4e-01b8-4047-86e0-499ef9e6b030.png)  |

 **Still need to be defined:**
* Sorting criteria: Define what 'Activity' means. PLus, what to show on the search landing page (Last active profiles?)
* Define 'Location' filter. It might not be by country but rather by region

**[Figma working file](https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/%5BOC-Design%5D-Lab?node-id=10984%3A0)** 

@SudharakaP @BenJam @znarf @kaylarep

**Comment by Memo-Es** [comment]
Regarding the 'Sharing results' note it is at the end of the page under the navigation:

<img width="834" alt="Screen Shot on 2022-03-14 at 21-45-55" src="https://user-images.githubusercontent.com/49539954/158302538-30e04eac-ca94-411b-bc16-7246c5e8fd10.png">

@kaylarep wdyt?

**Comment by kaylarep** [comment]
@Memo-Es looks nice!

Is there any plan to do a 'Show __(20/50/100) Results on this page'  -- is this possible?

**Comment by BenJam** [comment]
> @Memo-Es: Define what 'Activity' means. 

added https://github.com/opencollective/opencollective/issues/5329 for this

> @Memo-Es: PLus, what to show on the search landing page

Added https://github.com/opencollective/opencollective/issues/5328 for this

**Comment by SudharakaP** [comment]
Goals for Q1 Sprint 2 Week 2:

- [ ] Add country filter to the search page (https://github.com/opencollective/opencollective/issues/5332)
- [ ] Work on adding tags in search page (https://github.com/opencollective/opencollective/issues/4759)

**Comment by kaylarep** [comment]
is it possible to add another 'Sort by' option? : Alphabetical

**Comment by BenJam** [comment]
- [ ] double check docs for reference to Discover (update or create as necessary)
- [ ] fix current design so that it works on mobile
- [ ] work on responsive design for future sprint

**Comment by natehn** [comment]
Not sure if this is the right place to mention this, but I'm having an issue with the search for a few specific collectives where when I type in their exact name, it doesn't come up. For example:

- "data umbrella" does not show Data Umbrella as one of the top options, instead showing OSC and OCF as the top two...but "data-umbrella" returns it as the first option... "umbrella" is slightly better, with Data Umbrella as the fourth option
- "ridgewood community garden" and "ridgewood community" do not return Ridgewood Community Garden as one of the top options either, but "ridgewood" shows it as one of the top options
- "womanist working collective" does not show The Womanist Working Collective as one of the top options

"babel" shows Babel, and "google" shows Google, so it isn't everything, but sometimes the search is off somehow, and I hope the above examples are helpful.

I'm wondering how difficult it is to weight unique words more than common ones? Or perhaps collectives that match the whole string could be prioritized over those which only meet part of it? Anyway, I just wanted to share some of the issues I've seen.

**Comment by alanna** [comment]
More discussion of the above on slack here: https://opencollective.slack.com/archives/C035S573ZD2/p1650703042630149 (and scroll down to see response from @znarf )

**Comment by BenJam** [comment]
hey folks, just fyi we're making some changes to the search experience following the feedback above:

- Using placeholders to convey loading state for long-running queries https://github.com/opencollective/opencollective-frontend/pull/7731
- Re-adding 'relevancy' to the search ordering options, because our definition of 'activity' is exposing us to spammy profiles with large, single transactions. (we'll modify our definition of activity to include 'frequency' as well as the volume of transactions)
- Adding some serverside performance tracking to search query results
- Replace the discover page with a cached or static empty search result

We'll also look at optimising search in general, caching pages/results on the front/back end respectively.

**Comment by BenJam** [comment]
by way of a mini-retrospective, what happened here...

I think we started off with the right intentions research query results:

> - [x] updating the design to provide the necessary filters and controls to construct queries to answer the cases (design+engineering)
    - searching by string should provide results based on `name`, `slug`, `tag`, `description`, `country`
    - users should be able to filter by `type` (host, collective, organisation, event, project, fund) 
    - users may want to further filter results by `country`, and `tag`
    - if the user is filtering by host they may want to additionally filter by `host currency`
    - user may want to order results ASC/DESC by `activity` as defined above

i.e. that we should, in the first instance, provide search results by string matches (we called this relevancy). This conversation moved to #5329 and we ended up promoting this to the default sorting method. I don't think this was ever the intention. We're reinstating the 'relevancy' filter to fix this. 

On search performance, @znarf and I had a conversation and I think we made a bad call not to include some query optimisation around ordering by activity in the MVP. This has hit us hard with an empty search (ordering everything on the platform by every transaction is the longest query we can run) and for search results that cover a broad range of collectives (i.e. `opensource`, `community`, `collective`). @Betree is looking at some performance tracking and some improvements for ordering by activity. We also need to adjust our definition to account for spammy profiles. 

In general, I think this work has resulted in what we expected, search is exposing poor-quality collectives that need cutting and we're finding out what needs to be improved in our onboarding process.

**Comment by SudharakaP** [comment]
Just to give some information, 

>     * Re-adding 'relevancy' to the search ordering options, because our definition of 'activity' is exposing us to spammy profiles with large, single transactions. (we'll modify our definition of activity to include 'frequency' as well as the volume of transactions)

This is being worked on at, https://github.com/opencollective/opencollective/issues/5492

>     * Replace the discover page with a cached or static empty search result

One thing I would suggest is that we could use tags for this purpose. It's my thinking that pages like `/discover` or `/hosts` are pages which we want to showcase some collectives. For example in the `/discover` page ideally we want the top results to be collectives which are popular or have lots of activity in recent history. I feel that no sorting filter we define will give us the perfect result. 

However what we could do is create a tag (say `featured-collectives`) and add this tag to some collectives which we want to showcase, then redirect the `/discover` page to the `/search` filtered by these tag. This way we would have the search page with some collectives we would like to showcase. This solution will also work for `/host` page where we can then add hosts like OSC, OCF etc at the top.

**Comment by alinamanko** [comment]
Related problem I just stumbled upon - https://github.com/opencollective/opencollective/issues/5493

**Comment by Betree** [comment]
> However what we could do is create a tag (say featured-collectives) and add this tag to some collectives which we want to showcase, then redirect the /discover page to the /search filtered by these tag. This way we would have the search page with some collectives we would like to showcase. This solution will also work for /host page where we can then add hosts like OSC, OCF etc at the top.

One problem is that collectives can edit their tags, so a spammy one could easily move among the "featured collectives" just by adding it. 

I still have on my to-do to optimize this empty query by caching activity. Let's maybe wait to see the results before implementing further optimizations.

**Comment by SudharakaP** [comment]
> One problem is that collectives can edit their tags, so a spammy one could easily move among the "featured collectives" just by adding it.

That makes sense. 🤔 Maybe a separate flag in `data` field to indicate this is a featured collective and based on that show the collectives might work. So basically if the search query is empty we show these featured collectives. Same goes for `/hosts` page a flag such as `featuredHost: true` set in data can be a simpler change to tackle this. 🤔

**Comment by znarf** [comment]
Sprint Week 2:
- https://github.com/opencollective/opencollective-frontend/pull/7745
- https://github.com/opencollective/opencollective-frontend/pull/7740

**Comment by kaylarep** [comment]
just brainstorming what i'd love for our search to end up looking like, if we ever take on redesigning the whole thing. please excuse this draft, can draw a neater one eventually, but basically I like the structure of Google Shopping's Search:
- having the filter options all on the left, 
- with options to select multiples, 
- clearly see what you've selected, even as you scroll, 
- Filters like 'Accepting Applications' would appear if you select 'Hosts' as a filter
    - the filter categories may change/new ones appear as you select different options
        - e.g. US regions might appear if you select 'Location -> USA', but otherwise would not

this makes the most sense to me 
![image](https://user-images.githubusercontent.com/64920686/167003951-07b5e18c-5674-4335-af56-02ec8f10ef5e.png)

**Comment by BenJam** [comment]
Q2S1W3

- [ ] @znarf review https://github.com/opencollective/opencollective-frontend/pull/7745
- [ ] Search query performance @Betree

**Comment by Betree** [comment]
The performance update is live. There are more details in https://github.com/opencollective/opencollective/issues/5329#issuecomment-1125747873, but the TLDR is: empty search page loads in less than 1s, searching for something usually replies in less than 1-2 seconds.

On the other TODOs left, I think we have:
- The default sort: some team members suggested that we should default back to "Relevancy" (rather than Activity). I'd advocate for keeping "Activity" as the default when there's no search term, as relevancy only makes sense when you're searching for something. We'd be breaking the Discover experience if we don't take that into account. We can also decide to not show the "Relevancy" sort option when there's no search term.
- On the search page, pressing "Enter" on the empty search bar currently does nothing. I think this should be supported.

Also personal feedback for @opencollective/design: I think we should provide a button to submit the search. The only way to submit is currently to press "Enter", which is not great for accessibility and might not be intuitive for some users. See https://meta.stackexchange.com/questions/51057/no-search-button-accessibility-problem.
My suggestion would be to move the glass icon to the end of the input and make it clickable:
![image](https://user-images.githubusercontent.com/1556356/168236581-720d7eea-3c35-45a2-9bd0-98d5480313bf.png)

**Comment by SudharakaP** [comment]
> On the other TODOs left, I think we have:
> 
>     * The default sort: some team members suggested that we should default back to "Relevancy" (rather than Activity). I'd advocate for keeping "Activity" as the default when there's no search term, as relevancy only makes sense when you're searching for something. We'd be breaking the Discover experience if we don't take that into account. We can also decide to not show the "Relevancy" sort option when there's no search term.
> 
>     * On the search page, pressing "Enter" on the empty search bar currently does nothing. I think this should be supported.

I've extracted these to a new issue at, https://github.com/opencollective/opencollective/issues/5559

**Comment by BenJam** [comment]
- [ ] implement 'active tag' when linking from tag on a collective page (link modification) 
- [ ] @znarf review https://github.com/opencollective/opencollective-frontend/pull/7745
- [ ] doucment follow-on issues

**Comment by SudharakaP** [comment]
@BenJam : I don't think there's any pending tasks left on this project and thus propose closing this issue? 🤔

**Comment by Memo-Es** [comment]
@SudharakaP @znarf @BenJam Are we ok to close this issue and register any follow-up issues on a different track?

**Comment by SudharakaP** [comment]
> @SudharakaP @znarf @BenJam Are we ok to close this issue and register any follow-up issues on a different track?

Yes I've mentioned this previously as well; https://github.com/opencollective/opencollective/issues/4295#issuecomment-1152638862. I think almost all issues here has been addressed so any further improvements could go in followup issues so that we don't make this thread too long and convoluted. 

Some things that we could think about iterating in the future are (composed this list from previous comments and some followup issues),

- Surface specifying the country for collectives at more places like the signup flow; https://github.com/opencollective/opencollective/issues/4295#issuecomment-1065162600, https://github.com/opencollective/opencollective/issues/4295#issue-893907557
- Identifying further where search results do not match expectations and addressing them; https://github.com/opencollective/opencollective/issues/4295#issuecomment-1109029077
- https://github.com/opencollective/opencollective/issues/5675
- https://github.com/opencollective/opencollective/issues/5622
- https://github.com/opencollective/opencollective/issues/5449
