### ISSUE TITLE
[PROJECT] Contribution Flow Update

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#4299]
## Overview

One year ago, we worked on an update for the contribution flow that included a new header, clearer contribution selection, and the platform tips section. At that time, we updated the existing components only (Header, contribution form, and FAQ sidebar) without modifying the layout:

| Old version | After the first update |
|-------------|--------------------|
|   <img width="1426" alt="Screen Shot on 2021-05-18 at 07-53-58" src="https://user-images.githubusercontent.com/49539954/118696160-9d4d3f80-b7d3-11eb-854c-caa682296165.png">   |    <img width="1156" alt="Screen Shot on 2021-05-18 at 07-51-37" src="https://user-images.githubusercontent.com/49539954/118696170-9faf9980-b7d3-11eb-9474-50ac9525d48d.png">    |

Now we have enough feedback and plans to bring this design to the next level, making sure we are communicating the breakdown of each transaction transparently, including the communication and behavior for the platform tips, and including some other improvements we have wanted to tackle recently (ex. #4169)

## Owner
@Memo-Es 

**Secondary Developer on the project:** 
It will be decided after the kick-off call

## Prioritization

- Does this serve our mission
Totally, this flow is probably the most important we have in our platform. To be financially healthy and thrive, we must ensure we nail down how this checkout process works for our specific context and goals. As we advance, allowing projects to use the contribution flow as a tool for them to be successful in more and more flexible ways sounds like something we should maintain with the highest quality criteria.

- Will this help to make us financially sustainable within a year?
Yes, it is essential to have the best flow possible to improve the money flowing in the platform.

- Can this make us move faster?
If it has the success we need, it will allow us to have more resources and have faster feedback loops and release cycles.

- Does this increase quality?
Yes, this project's main focus is to increase the quality of contributing using the platform capabilities.

- Does this add technical debt?
I'm not sure

- Is it feasible to build and maintain with our current team and runway?
Yes

- What insight or research is this project based on?
#4268 #4169 #3897 https://github.com/opencollective/opencollective/issues/3438

- Is this problem already solved elsewhere?
Yes, a couple of references have been popping out in previous discussions, some of the main beings: 
   * [Hello Asso](https://www.helloasso.com/) - [Reference](https://github.com/opencollective/opencollective/issues/4268#issuecomment-838001399)
  * [Gofundme](https://www.gofundme.com/)
  * [Donorbox](url)

- How will we measure our success? Do we have a baseline today that we can compare this against?
Ummm, amount of money being contributed? 🙂

- How well do we understand the complexity of the problem, feature to be added, or user needs to be addressed? 
We have been gathering feedback to improve our contribution flow along this time, which makes us confident to propose a new series of improvements. 

- What is the estimated timeframe for delivering this project? 
I foresee three main chunks of work under this project:
   * **Platform tips** Design how we handle the communication for platform tips
   * **Contribution form** Redesign the contribution form to be more versatile and adaptative, including the issue to connect the contribution flow to a tier or project and, probably, including in the process the question of how it can be embedded in third-party websites to add to the white-labeling efforts
   * **Layout** How we display the summary and FAQs

### Roadmap & Timeframe
- [x] First discussion and scoping
- [x] Design proposal for platform tips #4268
- [x] Design proposal for tier redesign https://github.com/opencollective/opencollective/issues/4346
- [x] Design proposal for new layout
- [x] Ask for feedback and improve the design
- [x] Wrap up final proposal

### Release planning
- [ ] TBD

**Estimated delivery date**
* The final proposal should be up by the end of this sprint (Late June), we could spend a week of the next sprint to nail down production details and mobile versions.

### Next steps

- [x] Open up any appropriate project issues
- [ ] Open a documentation issue, link it to this one
- [ ] Open a release issue, link it to this one
- [ ] Create a project board, add this issue to the description, add any issues created above 

## Project Closure

- Close all relevant project issues
- Open up issues for improvements 
- Post comm's according to comm's plan (most likely in release issue)
- Post project screencast on documentation slack channel 
- Post project closure in newsletter slack channel 
- Celebrate!!

**Comment by BenJam** [comment]
Prioritisation notes: looking to improve the design to better communicate platform tips, and the possiblity to connect a contribution with a tier or event. Small design update. Get to a design to implement either at the end of the sprint or following sprint.

**Comment by SudharakaP** [comment]
@opencollective/design : Just a small suggestion; maybe we should include https://github.com/opencollective/opencollective/issues/4314 to the design as well since we are redesigning the contribution flow. 😄

**Comment by Memo-Es** [comment]
[Definition and follow-up document](https://docs.google.com/document/d/170RaWCW-HlNa4mFYS1fwmmw0Peq7TkW9LVdUbBsScb0/edit?usp=sharing)

**Comment by Memo-Es** [comment]
## Production-ready files

| Components | Check-out page | Success |
|------------|----------------|---------|
|   ![❖ Contribution Flow](https://user-images.githubusercontent.com/49539954/132587663-0c73d86d-aed1-40bc-8fa0-86a80b552a58.png)   |   ![Desktop](https://user-images.githubusercontent.com/49539954/132587675-cf3af751-30da-4788-ab00-233cdb4340b0.png)      | ![Desktop (1)](https://user-images.githubusercontent.com/49539954/132587677-0baf7235-69a7-433b-a1f8-66fff7dae308.png)   |

[Link to figma file →
](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC-Design-Production-Ready-%E2%9C%85?node-id=13575%3A211640)

**Comment by Betree** [comment]
@Memo-Es From the design above, is my understanding correct that we're getting rid of the steps in the contribution flow to instead offer a single, one-page form? Do we have a design that includes the summary step (used for taxes) like in https://staging.opencollective.com/captainfact_io/contribute/tshirt-10355/checkout/summary?

**Comment by Betree** [comment]
Also @Memo-Es, can you confirm that this background on the success page is to be removed entirely?

**Comment by Betree** [comment]
The work for this issue is now separated into these smaller issues:
- https://github.com/opencollective/opencollective/issues/4692
- https://github.com/opencollective/opencollective/issues/4895
- https://github.com/opencollective/opencollective/issues/4896
- https://github.com/opencollective/opencollective/issues/4897
- https://github.com/opencollective/opencollective/issues/4898

Waiting for the feedback in https://github.com/opencollective/opencollective/issues/4299#issuecomment-957503602 and https://github.com/opencollective/opencollective/issues/4299#issuecomment-957535716 two eventually create two others:
- Revisit the layout of the success page (+ remove background)
- Make the contribution flow a single-step process

**Comment by Memo-Es** [comment]
@Betree 
> From the design above, is my understanding correct that we're getting rid of the steps in the contribution flow to instead offering a single, one-page form? Do we have a design that includes the summary step (used for taxes) like in https://staging.opencollective.com/captainfact_io/contribute/tshirt-10355/checkout/summary?

Do you think we can integrate the [summary step](https://d.pr/i/Gs6sBo) you mention into the live summary featured on the check-out page?
![Annotation on 2021-11-02 at 18-32-55](https://user-images.githubusercontent.com/49539954/139969910-9a6b1362-b098-48f1-8d38-2984ce7f8c81.png)

You are correct to assume we're getting rid of the steps from the current flow for a single check-out page instead.

**Comment by Memo-Es** [comment]
> can you confirm that this background on the success page is to be removed entirely?

Yes, I confirm. I know we all love the watercolor texture backgrounds everywhere but 

1. We will most likely see it as the default tier card hero image:
<img width="1114" alt="Screen Shot on 2021-11-02 at 18-36-01" src="https://user-images.githubusercontent.com/49539954/139970247-282e7597-ba5b-400a-a08b-e8267851221a.png">

And 2. If the collective changed the hero image, it would be closer to 'their' brand, which is something I think we want for groups to be closer to their communities.

**Comment by Betree** [comment]
> Do you think we can integrate the [summary step](https://d.pr/i/Gs6sBo) you mention into the live summary featured on the check-out page? ![Annotation on 2021-11-02 at 18-32-55](https://user-images.githubusercontent.com/49539954/139969910-9a6b1362-b098-48f1-8d38-2984ce7f8c81.png)

@Memo-Es It's tricky because there are form fields in there; mostly for people to type in the tax id number (VAT number). I'm afraid they could miss it if we move it two the right, especially since the right column is pretty much hidden on mobile

**Comment by Memo-Es** [comment]
> It's tricky because there are form fields in there; mostly for people to type in the tax id number (VAT number). I'm afraid they could miss it if we move it two the right, especially since the right column is pretty much hidden on mobile

After doing some analysis today, we think this deserves further work, especially for mobile. So we are leaving it as a priority for next sprint

@Betree

**Comment by Betree** [comment]
As mentioned in https://github.com/opencollective/opencollective/issues/4299#issuecomment-957547489, this is now split into smaller issues.
