### ISSUE TITLE
[PROJECT] Admin Dashboard - Reports Section

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#4300]
## Overview
We are implementing the new admin dashboard, which merges dashboard features like budget management with settings in a single admin management space. One of the sections I showed during the finalization of the design phase was this 'Reports' section:

![Large (Desktop)](https://user-images.githubusercontent.com/49539954/118741726-9266cf00-b814-11eb-96ea-d60b49616162.png)

During the user feedback calls I had with hosts, it was one of the sections to caused more expectation; it looks like something beautiful for hosts to have visibility on how their collectives and the host organization are doing from one place, using clear visualizations of the most important data to help them make better decisions in less time. 
The version I showed is a preliminary one; we need to nail down the information we are displaying and design how it will look and how it will be exported to use with other software.

## Owner
@Memo-Es 

**Secondary Developer on the project:** 
Most probably @Betree 

## Prioritization

- Does this serve our mission?
Yes, it is aligned with one of our current priorities: to scale the adoption of the platform by third-party hosts (and strengthen the relationship with our main hosts)

- Will this help to make us financially sustainable within a year?
It is probably not through a direct impact, but if it indeed helps us onboard new hosts and facilitates the platform adoption of current hosts, then indirectly by having more communities having their money in OC.

- Can this make us move faster?
Again, if it helps us facilitate the adoption, then yes.

- Does this increase quality? 
In the experience of managing a budget, data visualizations are always a quality indicator for top-notch products.

- Does this add technical debt?
Not sure

- Is it feasible to build and maintain with our current team and runway?
Yes

- What insight or research is this project based on?
https://github.com/opencollective/opencollective/issues/3998, https://github.com/opencollective/opencollective/issues/3917

- Is this problem already solved elsewhere?
There are lots of data dashboards out there. I can't think of one focused on community and networking though.

- How will we measure our success? Do we have a baseline today that we can compare this against?
Less support related to access to data, faster adoption, and increase of active hosts over time?

- How well do we understand the complexity of the problem, feature to be added, or user needs to be addressed? 
Based on the current production and constant insights from host admins, I would say we have enough information to launch something fast and iterate.

- What is the estimated timeframe for delivering this project? 
Within a 6-week sprint, maybe less.

### Roadmap & Timeframe
- [x] Proposal for key data visualizations to include
- [x] Wireframes and feedback
- [x] HD UI design
- [x] Quality assurance and feedback with hosts
- [x] Production ready file

### Release planning
TBD

**Estimated delivery date**
TBD

### Next steps

- [ ] Open up any appropriate project issues
- [ ] Open a documentation issue, link it to this one
- [ ] Open a release issue, link it to this one
- [ ] Create a project board, add this issue to the description, add any issues created above 

## Project Closure

- Close all relevant project issues
- Open up issues for improvements 
- Post comm's according to comm's plan (most likely in release issue)
- Post project screencast on documentation slack channel 
- Post project closure in newsletter slack channel 
- Celebrate!!

**Comment by Betree** [comment]
Sharing here a conversation we had about which graph library to use since they've been used as examples to build the design and are probably the most suited to implement something as close as possible visually: 
> The most likely is that we'll use https://www.chartjs.org, it's the best compromise for us (simplicity, package size, popularity, license). You can see examples for most graph types on https://www.chartjs.org/samples/latest/
Another alternative is https://visjs.org/, examples on https://visjs.github.io/vis-timeline/examples/graph2d/
And https://apexcharts.com/ is another candidate

**Comment by BenJam** [comment]
Prioritisation notes: goal to decide on MVP/initial release. Which metrics to showcase, what the design would look like, validate with hosts etc. predominantly design. Create production-ready files.

**Comment by Memo-Es** [comment]
[Kick-off call document](https://docs.google.com/document/d/1ihXL_NKXjwqW1bD1hBiLQNxivNuEUpmtEoXNlSBRIp8/edit?usp=sharing)

**Comment by Memo-Es** [comment]
Reports section design proposal https://www.loom.com/share/590e2b010a7647a7ad75d7a8ff779aea

**Comment by SudharakaP** [comment]
Project board created at https://github.com/opencollective/opencollective/projects/65

cc: @Betree

**Comment by Betree** [comment]
The base project is now implemented and released for everyone, with some sections still to be merged and deployed. Followup issues are listed in https://github.com/opencollective/opencollective/projects/65.
