### ISSUE TITLE
[PROJECT] Digital Wallet Payment

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#4327]
Project: https://github.com/opencollective/opencollective/projects/59

## Overview
Open Collective already supports payments using PayPal (including recurring contributions) alongside all major credit and debit cards through Stripe and, we continue to manually support bank transfers. But we can do more.

With providers like Google, Apple, Alibaba, and Amazon all offering established digital wallet services that we know our users prefer when online it is time we started supporting them.

So this sprint we will prototype adding Digital Wallets (Apple Pay, Google Wallet, AliPay, Amazon Pay, etc) through Stripe's Digital Wallet support, starting with AliPay. This will be a simple prototype that enables us to de-risk future development and provide a format for us to roll out other wallet providers.

## Owner

**Secondary Developer on the project:**
@kewitz

## Prioritization

- Does this serve our mission
Yes, it is in sync with our strategic priority of facilitating more contributions to Collectives.

- Will this help to make us financially sustainable within a year?
Yes. It will increase access to new donations.

- Can this make us move faster?
I don't think it applies.

- Does this increase quality?
I don't think it applies.

- Does this add technical debt?
I don't think it applies.

- Is it feasible to build and maintain with our current team and runway?
Yes.

- What insight or research is this project based on?

- Is this problem already solved elsewhere?
No.

- How will we measure our success? Do we have a baseline today that we can compare this against?
Donations using the newly added payment method.

- How well do we understand the complexity of the problem, feature to be added or user needs to be addressed? 
We already use Stripe and we have an established contribution UX, implementing wallets shouldn't affect the flow very much but we this will be the first time we implement a digital wallet payment method.

- What is the estimated timeframe for delivering this project?
The first step is to implement AliPay

### Roadmap & Timeframe
- [ ] Implement AliPay support for one-time payments and refund
- [ ] Implement Apple Pay support for one-time payments and refund

### Release planning

**Estimated delivery date**

- Which aspect(s) of the platform does this change impact?
- Which group(s) of users will benefit from this change?
- Is this project in response to a user-requested feature? If so who requested it (link to feature request if available)?
- Is this project related to any similar work we have done, or are planning on doing in the next three months?

### Next steps

- [ ] Open up any appropriate project issues
- [ ] Open a documentation issue, link it to this one
- [ ] Open a release issue, link it to this one
- [ ] Create a project board, add this issue to the description, add any issues created above 

## Project Closure

- Close all relevant project issues
- Open up issues for improvements 
- Post comm's according to comm's plan (most likely in release issue)
- Post project screencast on documentation slack channel 
- Post project closure in newsletter slack channel 
- Celebrate!!

**Comment by kewitz** [comment]
https://github.com/opencollective/opencollective/projects/59?add_cards_query=is%3Aopen

**Comment by BenJam** [comment]
Just leaving some feedback here from Leen (All 4 Climate) and JF (Open Collective Brussels/Europe)

> everyone in Belgium uses Postconiq/Bancontact for bank transfers

**Comment by jfdh** [comment]
Hi @kewitz,

Is there anything I could do for you to facilitate the implementation of Bancontact/Payconiq into the payout flow of open collective? Happy to have a look at the documentation if needed to make this happen.

Thanks!

**Comment by BenJam** [comment]
status update on the above: 

We have support for Alipay working, but Stripe have had to stop supporting that service for us because AliPay have a policy problem with us...

**Comment by BenJam** [comment]
@kewitz is there anything left to do other than the policy issue? and how much effort might it be to roll out support for apple, google and amazon digital wallets?

**Comment by znarf** [comment]
This issue is about Wallets https://stripe.com/docs/payments/wallets Here is the current list:

- [ ] Alipay
- [ ] Apple Pay
- [ ] Click to Pay
- [ ] Google Pay
- [ ] GrabPay
- [ ] Microsoft Pay
- [ ] WeChat Pay

Anything else should be tracked a a separate issue.

**Comment by BenJam** [comment]
goals for this week

- [ ] look at digital wallet support vs 'elements' https://github.com/opencollective/opencollective/issues/4974
- [ ] select a lower risk payment provider to release

**Comment by piamancini** [comment]
goals for this week

- [ ]  look at digital wallet support vs 'elements' [PROJECT] More Payment Methods using Stripe Elements #4974

- [ ]  select a lower risk payment provider to release

**Comment by hdiniz** [comment]
We have added support for Google and Apple Pay wallets behind a feature flag `stripePaymentIntent` (the same as SEPA and ACH, covering the new Stripe Payment Element integration). Enabling the feature requires support ATM to change the value in the DB.

Both wallet types are made available based on some criteria:
- Google Pay: Chrome Browser with Google account.
- Apple Pay: Safari on macOS or iOS with a configured card.

For Apple Pay, an additional step is required on the Host Stripe Dashboard.
1. Host has to visit https://dashboard.stripe.com/account/payments/apple_pay
![image](https://user-images.githubusercontent.com/5448927/214459856-8e49c314-6aa5-47e0-b31d-68dedd65af1d.png)


2. Add `opencollective.com` in `Web domains`
![image](https://user-images.githubusercontent.com/5448927/214459933-606886cb-a7f5-4078-a2af-408ba2c9200f.png)

**Comment by shannondwray** [comment]
Support request for us to implement Amazon Pay, please let me know if this should be commented on a different issues

**Comment by BenJam** [comment]
closing as complete, follow-ups in #7027
