### ISSUE TITLE
Contribution tier - Design update

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#4346]
## Context

This initiative is part of the project to redesign the contribution flow #4299; we decided to bundle up a handful of issues related to the contribution flow to unify all these small efforts in a coherent frame.

These are the issues related to tier cards we will tackle this sprint:
https://github.com/opencollective/opencollective/issues/3432, https://github.com/opencollective/opencollective/issues/3438, https://github.com/opencollective/opencollective/issues/3897, https://github.com/opencollective/opencollective/issues/4169, https://github.com/opencollective/opencollective/issues/4200

## Tasks

- [ ] Tier card design proposal for donations with crypto and stocks
- [ ] Design update of the standalone tier page
- [ ] Contribution form redesign to include tier/event/project information
- [ ] Flesh out the corresponding settings page considering the updates made

**Comment by Memo-Es** [comment]
## Design updates

| Tier card design update | Tier card settings / Hosts | Tier card settings / Collectives |
|-------------------------|----------------------------|----------------------------------|
|     ![❖  Source Components](https://user-images.githubusercontent.com/49539954/127568444-d948de0f-f5c5-4ff3-b319-daeb8c9083ef.png)             |   ![Main + Flexible + Custom Payment (1)](https://user-images.githubusercontent.com/49539954/127568501-0e79ddd3-765e-4cc3-91c1-e29c5a7e7858.png)   |    ![Main + Flexible + Custom Payment](https://user-images.githubusercontent.com/49539954/127568496-2ef2f190-4541-4bdd-b70b-d9be341f2b06.png)     |


cc @Betree
