### ISSUE TITLE
PayPal synchronization issues

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4368]
We have a few synchronization issues with PayPal that we'll need to tackle. They are common to the legacy and the new implementation, so we may need to look at old data. 

1. We're not watching the payment refund webhook events. If for any reason (e.g. host admin refunds from PayPal's interface, the user opened a dispute or PayPal automatically reverts the transaction) then it's not accounted for in our ledger. 
2. It seems that the capture API can sometimes return a PENDING capture. We're currently not looking at this status, so we've been recording transactions for captures that have never been confirmed.

# Todo
- [x] In `createOrder`, check `capture.status` to not create the transactions if they have not been confirmed yet
- [x] Look at the webhook event to create the transactions when the capture status changes to `CONFIRMED`
- [ ] Look at the webhook event to mark transactions refunded on PayPal side as refunded on our side
- [ ] Create a script to fix old data:
  - [ ] Should refund transactions that are marked as refunded on PayPal but not in our ledger
  - [ ] Fetch all transactions where we recorded a pending capture and compare their status with PayPal. If they're marked as cancelled, delete the transactions in the ledger.

**Comment by znarf** [comment]
I just noticed we have many PayPal Orders that are inserted twice in the Ledger. I fixed entries for August but we'll need to dig in the past.

**Comment by Betree** [comment]
All implemented
