### ISSUE TITLE
[PROJECT] Revamp CSV reports

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4426]
## Overview
Initially proposed in https://github.com/opencollective/opencollective/discussions/4405#discussioncomment-942132

As part of what was mentioned in #4124, we think it's a good time to review the CSV reports that haven't really been refactored in years, both to clean the code and to surface the new information that we have. What we want to achieve:
- Surface host fee share
- Merge the code to generate CSV between frontend (transactions list) and API (emails)
- Show transactions groups
- Update descriptions for host fees (+ shares) - eg. "Host Fee share for transactions group #xxxxx-yyyy-zzzz-aaaa"

The design phase should also take into consideration https://github.com/opencollective/opencollective/issues/3983 and https://github.com/opencollective/opencollective/issues/4396. We should also keep in mind the designs proposed for the host dashboard metrics, where it is possible to create custom exports with column selections.

## Owner
@Betree or @znarf 

*Note: Project owner responsibilities include coordinating all the different people that need to contribute to the project, defining specs and goals, communicating project progress, being the point person for decisions, QA, documentation, and a plan for ongoing maintenance. If the project owner can't continue, they need to hand the role over to another person explicitly.*

**Secondary Developer on project:** @Betree or @znarf 

## Prioritization

- Does this serve our mission
Yes, being able to export accurate financial data is key for transparency and interoperability. 

- Will this help to make us financially sustainable within a year?
Probably not

- Can this make us move faster?
Yes, by reducing the technical debt that has grown way too much on this part of the code.

- Does this increase quality? 
Definitely, today's code is an accumulation of quick fixes that look quite hacky.

- Does this add technical debt?
No, as it's not introducing any new feature

- Is it feasible to build and maintain with our current team and runway?
It's a well-contained project, that shouldn't take too long

- What insight or research is this project based on?
Mostly the experience of working with and fixing these scripts over time, and more recently with the ledger refactor project.

- Is this problem already solved elsewhere?
N/A

- How will we measure our success? Do we have a baseline today that we can compare this against?
  - Ability to re-use the code for other features (exports from the frontend)
  - Code quality
  - Test coverage

- How well do we understand the complexity of the problem, feature to be added or user need to be addressed? 
The problem is well understood, however, we still need to decide on implementation details: where is this going to live, API, REST?

- What is the estimated timeframe for delivering this project? 
Between 2-10 days, we still need to scope more precisely to give a proper timeframe.

### Roadmap & Timeframe
(Key milestones or phases and estimated dates. Consider including further scoping, discovery, and prototyping. Include as a minimum: planning, design, development, documentation, feedback, iteration and, marketing)

### Success metrics
(What we will judge outcomes of the project by)

### Release planning

**Estimated delivery date**

- Which aspect(s) of the platform does this change impact?
- Which group(s) of users will benefit from this change?
- Is this project in response to a user-requested feature? If so who requested it (link to feature request if available)?
- Is this project related to any similar work we have done, or are planning on doing in the next three months?

### Next steps

- [ ] Open up any appropriate project issues
- [ ] Open a documentation issue, link it to this one
- [ ] Open a release issue, link it to this one
- [ ] Create a project board, add this issue to the description, add any issues created above 

## Project Closure

- Close all relevant project issues
- Open up issues for improvements 
- Post comm's according to comm's plan (most likely in release issue)
- Post project screencast on documentation slack channel 
- Post project closure in newsletter slack channel 
- Celebrate!!

**Comment by BenJam** [comment]
just a quick note to say that we should consider including transactions from child projects/events when exporting a budget https://github.com/opencollective/opencollective/issues/4360

**Comment by BenJam** [comment]
Just to note, goals fromt he last sprint for this were:

- [ ] update to work with the new ledger
- [ ]  check compatibility with the previous format, double check formats that work best for hosts (Open Source Collective/Open Collective Foundation)
- [ ]  Take into mind the new host dashboard design with respect to customisation [with an eye on supporting platforms like QuickBooks](https://github.com/opencollective/opencollective/issues/4396).

**Comment by BenJam** [comment]
note: may also consider tackling https://github.com/opencollective/opencollective/issues/4360 as part of this.
