### ISSUE TITLE
[PROJECT] Open Stocks

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#4557]
## Overview
As part of our effort to help collectives raise more funds, we are piloting a way for people to use their public stock to make a donation. This is convenient for donors because the don't pay taxed on selling that stock. Since many of the big tech companies have gone public, many devs / tech workers have now stock they could potentially use for good. 

## Owner
@piamancini 

*Note: Project owner responsibilities include coordinating all the different people that need to contribute to the project, defining specs and goals, communicating project progress, being the point person for decisions, QA, documentation, and a plan for ongoing maintenance. If the project owner can't continue, they need to hand the role over to another person explicitly.*

**Secondary Developer on project:** 
@BenJam 

## Prioritization

- Does this serve our mission
Yes it's a way for communities to be sustainable

- Will this help to make us financially sustainable within a year?
More funding options can mean more money in the hands of maintainers and more revenue for OC and OSC. The goal is to expand do OCF as well. 

- Can this make us move faster?
Not necessarily but we are thinking about it as an experiment separated from the platform to be minimally disruptive. 

- Does this increase quality? 
No. 

- Does this add technical debt?
Not in this iteration. It's unclear if it'll work. If it does we can then consider how we add it to the main platform. 

- Is it feasible to build and maintain with our current team and runway?
yes

- What insight or research is this project based on?
stocks are hot now and the whole GMS saga brought to the surface a lot of communities that buy and hold public stock. These can be tapped into for support.  

- Is this problem already solved elsewhere?
Not for open source and at our scale. 

- How will we measure our success? Do we have a baseline today that we can compare this against?
Baseline is 0 at the moment and it's a cheap experiment. 

- How well do we understand the complexity of the problem, feature to be added or user need to be addressed? 
user need is unclear, it's a small gamble. We'll see if it gains traction. 

- What is the estimated timeframe for delivering this project? 
Website is done 
Checkout is live 
We just need to connect and launch. 

## Kick-off meeting
A bit late in the game for this one, but we can organize. 

### Roadmap & Timeframe
(Key milestones or phases and estimated dates. Consider including further scoping, discovery, and prototyping. Include as a minimum: planning, design, development, documentation, feedback, iteration and, marketing)

Add checkout to website 
Connect brokerage account to dashboard
Test 
Marketing materials --> bring on the memes!
Reach out to collectives / contacts so they are aware of this opportunity
Ship 

### Success metrics
(What we will judge outcomes of the project by)
Dollars raised through this mechanism

### Risks

- Risk: that it fails and no one gives $
- Mitigation: marketing efforts 

- Risk: that it's a raging success we end up with a ton of stock we need to manually sell and add to the collectives
- Mitigation: meh 

### Release planning

**Estimated delivery date**
First half of September

- Which aspect(s) of the platform does this change impact? none
- Which group(s) of users will benefit from this change? open source maintainers on OSC
- Is this project in response to a user-requested feature? If so who requested it (link to feature request if available)? yah.. no. I'll take this as Pia driven experiment. 
- Is this project related to any similar work we have done, or are planning on doing in the next three months? related to #4457 and all other Crypto issues

### Next steps

- [ X] Open up any appropriate project issues
- [ ] Open a documentation issue, link it to this one
- [ ] Open a release issue, link it to this one
- [ ] Create a project board, add this issue to the description, add any issues created above 

## Project Closure

- Close all relevant project issues
- Open up issues for improvements 
- Post comm's according to comm's plan (most likely in release issue)
- Post project screencast on documentation slack channel 
- Post project closure in newsletter slack channel 
- Celebrate!!

**Comment by piamancini** [comment]
Website: https://openstocks.co/
Stock giving Page: https://app.overflow.co/opensourcecollective

**Comment by piamancini** [comment]
blogpost done

**Comment by BenJam** [comment]
> blogpost done

![where](https://user-images.githubusercontent.com/158833/132029927-12e57cbc-30ee-4641-a5f8-e161e43a9a96.gif)

**Comment by BenJam** [comment]
@piamancini let's scheudle some more marketing time on this before we close it out.

**Comment by BenJam** [comment]
closing, let's pick up the marketing conversation elsewhere.
