### ISSUE TITLE
Expenses V2

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#478]
List of nice to have when refactoring expenses 
- [ ] At the very least show currency when submitting expenses. Ideally user can choose currency and we convert. From https://github.com/opencollective/opencollective/issues/477
- [ ] invoices in different currencies see #101 
- [x]  Expense details showing "undefined" where the backer name should be. 
- [x] enable comments on expenses so users can see why an expense is not being paid (and everyone learns!) Useful design issue #229 
- [x] expenses still show as anonymous or undefined. #254 
- [ ] clarify that it needs a real receipt and that without one submission fails. 
- [ ] if you are logged in and try to submit with another username it overrides the username. Also check if it overrides paypal email.
- [ ] bring back request money #293
- [ ] design a cover button to let anyone make a donation to cover an expense designed already proposed in #279 
- [x] Confusing button for already reimbursed expenses #324
- [x] Better expense design #329

**Comment by piamancini** [comment]
From user: 
- [ ]  Ability to close invalid expenses that were not processed yet.
- [ ]  Ability to know ahead of time the fee cost of paying an expense if using a concrete payment gateway (Paypal, Stripe...). The current UX flow is a bit confusing. You think everything is OK when it's not.
- [ ] Flag expeses as "queued" or something if they are OK until processing them every Friday (or show somewhere why they are not valid, if required).

**Comment by piamancini** [comment]
adding @xdamman since he has been working on bringing expenses to the front end

**Comment by piamancini** [comment]
@xdamman is there anything from the top list that you want to work on (except comments) or should we close this?

**Comment by xdamman** [comment]
Yeah, still a bunch of good things here that should be implemented. Let's keep this open.

**Comment by alannallama** [comment]
I checked off a couple that have already been done, but the rest are still issues. I have also raised several separate issues related to expenses since I didn't know they were tracked on this one.

- https://github.com/opencollective/opencollective/issues/1222
- https://github.com/opencollective/opencollective/issues/1167
- https://github.com/opencollective/opencollective/issues/1132
- https://github.com/opencollective/opencollective/issues/1073
- https://github.com/opencollective/opencollective/issues/1149
- https://github.com/opencollective/opencollective/issues/1072
- https://github.com/opencollective/opencollective/issues/1071
- https://github.com/opencollective/opencollective/issues/1061
