### ISSUE TITLE
[PROJECT] Add Virtual Card Issuing with Stripe

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#4807]
## Overview 
Collectives are using Virtual Cards to spend their community's budget directly,  without relying on members to cover costs in the first instance. Our current provider (Privacy.com) blocks our entire account when transactions fail, impacting all our collectives, so we'd like to expand the current prototype to include issuing with Stripe.  

## Roadmap

Status: 💚 On track

- [x] Iteration 1:
    - [x] Create a card manually in Stripe dashboard 
    - [x] Assign a card (find it in the Card list) and insert in the database
    - [x] Refactor to allow multiple Virtual Card providers
    - [x] Display Provider in the Interface  
- [x]  Iteration 2:
   - [x] Receive the transaction (webhook if possible)
   - [x] Sync transactions and insert in the ledger (cronjob)
- [x] Iteration 3:
    - [x] Receive and process authorization
    - [x] Sync process for card limit?
    - [x] Handle name on Open Collective side
- [x] Iteration 4:
    - [x] Create Card directly with Stripe API (including spending limit)
    - [x] Add “Create a Card” in the interface (keep “Assign a Card” for Privacy)
- [x] Iteration 5:
    - [x] #4982
- [x] Small Fixes:
  - [x] Pass card `name` to metadata
  - [x] Make sure we send an email to assignee when a card is created (similar to what we have when a card is assigned)
- [x] Iteration 6:
    - [x] Currency aware refactoring, support EUR for Open Collective Europe
    - [x] Create a Card from the Collective menu (similar to "Assign a card")
- [x] Iteration 7:
  - [x] Edition: name, monthly limit, assignee (Host Only, Need Design Input)
  - [x] Deletion (Pause? Unpause?) (Collective or Host, Need Design Input)
- [ ] Backlog:
    - [ ] https://github.com/opencollective/opencollective/issues/5004  
    - [ ] Ability to pause and unpause Cards (as a Collective or Host feature?)
    - [ ] Ability for Collective/Host to delete a card from UI
    - [ ] Ability for Collective admins to create cards themselves?
    - [ ] Admin interface to Accept Cards request
    - [ ] Mechanism to clean non-completed Transactions

## Ownership

**Owner:** @znarf 
**Developer:** @Forster-Groux,  @znarf 

## Prioritization
We want projects to spend their budget. After a brief into 1% of transactions are carried out using virtual cards, there is a need here.

## Measuring success
Increased usage of virtual cards, as measured by an increase %age of transactions using virtual cards rather than %age of value of transactions, as virtual cards are intended to be used for small, recurring costs. 

## Next steps
- [x] onboard with Stripe to check that our use case is supported
- [x] confirm costs for provisioning and using virtual cards for stripe are acceptable
- [x] [Kickoff](https://docs.google.com/document/d/1mmWaw2cvQGDIr1Pd7ScKlEWHtXJB2-WtgiYXaKkcTQ0/edit#)

**Comment by BenJam** [comment]
Created this issue to cover the work to move virtual cards off of privacy and onto Stripe. 

An initial chat with Stripe re. OSC's usage was positive. We have a contact that can help us through the process. Generally, the setup would look like:

- Create a single card-holder (Open Source Collective, Open Collective Foundation)
- Add funds to Stripe's Issuing balance 
- Create a card for each Collective that requests/currently uses a card

On initial investigation, it looks like Stripe have better controls than privacy and at the same time more freedom for card users (multiple merchants supported etc). So they should support us better. 

Costs are detailed over in https://stripe.com/issuing#pricing (0.2% +20c per transaction 10c per card issued).

**Comment by BenJam** [comment]
Just dropping a quick status update based on the itereation plan in the kickoff document:

- [ ] Iteration 1:
    - [ ] Create a card manually in Stripe dashboard 
    - [ ] Assign a card (find it in the Card list) and insert in the database
    - [ ] Refactor to allow multiple Virtual Card providers
    - [ ] Display Provider in the Interface  

- [ ]  Iteration 2:
   - [ ] Receive the transaction (webhook if possible)
   - [ ] Sync transactions and insert in the ledger (cronjob)

- [ ] Iteration 3:
    - [ ] Receive and process authorization
    - [ ] Sync process for card limit? 

- [ ] Iteration 4:
    - [ ] Create Card directly with Stripe API
    - [ ] Add “Create a Card” in the interface (keep “Assign a Card” for Privacy)

**Comment by BenJam** [comment]
next steps 

- [ ] this thing
- [ ] that thing

**Comment by BenJam** [comment]
quick comment re. naming. we need to add some metadata when creating a card to identify the card on the stripe issuing interface. There's no naming etc. so I've added `collective:<slug>` for the cards that I've created manually. It would be good to line up the policy with the code here.

**Comment by piamancini** [comment]
- [ ] Iteration 4:  push to prod
- [ ] Iteration 5: get started

**Comment by znarf** [comment]
Check list for Fiscal Hosts

1) Ask Stripe to enable Issuing on your account
2) Create a generic Card Holder and make sure it's the only one (if you have more, contact us)
3) Top Up the Issuing balance with a reasonable amount
4) Configure webhook and enable for all `issuing_authorization.*` and `issuing_transaction.*` (5 events) `https://api.opencollective.com/webhook/stripe`
5) Configure default authorization process and webhook (deny or allow) `https://api.opencollective.com/webhook/stripe`
6) Create new dedicated Restricted Secret Key, select `write` for all Issuing features
7) Contact Open Collective team to configure Restricted Secret Key production (update-connected-account-stripe-token)
8) Contact Open Collective team to configure Webhook Signing secret to connected account (stripeEndpointSecret)
9) Ask Open Collective team to enable feature in Collective settings (privacyVcc)

**Comment by BenJam** [comment]
Plan for this week is to complete iteration 6

**Comment by znarf** [comment]
- [ ] Edition: name, monthly limit, assignee (Host Only, Need Design Input)
 - [ ] Deletion (Pause? Unpause?) (Collective or Host, Need Design Input)
 - [ ] #5004

**Comment by piamancini** [comment]
- [ ] Merge Edition & Deletion
- [ ] Add remaining tasks on a new issue for feedback and improvements

**Comment by znarf** [comment]
Follow up issue: https://github.com/opencollective/opencollective/issues/5059
