### ISSUE TITLE
Host Dashboard Reports - Add Tests to API

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4821]
We need to add tests on the API level for the host dashboard reports section; the following tasks needs to be done. 

- [x] Add tests for verifying amounts returned by the Total Money Managed section
  - [x] Chart/Expanded View (depends on https://github.com/opencollective/opencollective/issues/4606)
  - [x] Summary View
- [x] Add tests for verifying amounts in Host fees section
  - [x] Summary View (depends on https://github.com/opencollective/opencollective/issues/4657)
  - [ ] Chart/Expanded View @Betree 
- [ ] Add tests for verifying amount in the Transactions section (depends on https://github.com/opencollective/opencollective/issues/4658)
  - [ ] Summary View
  - [ ] Chart/Expanded View 
- [ ] Add tests for verifying amounts in the Platform Tips section 
- [ ] Add tests for verifying that the api responses in the downloads section; particularly on the downloading of the report.
