### ISSUE TITLE
Expense flow updates

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#4874]
## Design update

We are updating the expense flow based on feedback from different channels, the support metrics, and a couple of pending issues from the last time we updated the expense flow.

**Mainly, we are updating these aspects:**
- [ ] [Layout improvements, better use of the columns from our grid system, and alignment with the navbars](https://github.com/opencollective/opencollective/issues/4874#issuecomment-1005373439)
- [ ] [Step order: Expense details > Payee info > Summary](https://github.com/opencollective/opencollective/issues/4874#issuecomment-1005381829)
- [ ] [Addition of a new stepper component for the new form layout](https://github.com/opencollective/opencollective/issues/4874#issuecomment-1006282857)
- [ ] [Title field improvements / Subheading addition](https://github.com/opencollective/opencollective/issues/4874#issuecomment-1006287874)
- [ ] https://github.com/opencollective/opencollective/issues/4715

**🎨 [Production-ready file](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=15757%3A202404)**

### Loom recording
https://www.loom.com/share/68b10c4251b94a7ca791ee17d7c08b43

cc @alanna @Betree

**Comment by Betree** [comment]
This one is a complex project that we'll need to prioritize properly

**Comment by Memo-Es** [comment]
[→ Link to production file](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=15757%3A202404)

**Comment by Memo-Es** [comment]
## Layout improvements, better use of the columns from our grid system, and alignment with the navbars

### Revisit the layout, margins, and spacing

Example:
| Version in production | Design proposal |
|-----------------------|-----------------|
| <img width="807" alt="Screen Shot on 2022-01-04 at 22-18-24" src="https://user-images.githubusercontent.com/49539954/148160466-6d7fcabc-af68-4d8e-881d-2559eb18be0b.png">   |   ![Annotation on 2022-01-04 at 22-25-17](https://user-images.githubusercontent.com/49539954/148160464-90b9990a-6ce2-4c9a-a52f-bf6449fafa3c.png)  |
|        Current version is 728 px on desktop          |     784 px new version     |

**Comment by Memo-Es** [comment]
## Step order

| | Version in production | Design proposal |
|-----------------------|-----------------------|-----------------|
| **Step 1** | <img width="1127" alt="Screen Shot on 2022-01-04 at 22-34-16" src="https://user-images.githubusercontent.com/49539954/148161238-cad0d1bf-e08a-4245-8949-e2d5f6df4e8c.png"> Current version welcomes you with a blank page, until you choose either invoice or reimbursement   |   <img width="1018" alt="Screen Shot on 2022-01-04 at 22-36-10" src="https://user-images.githubusercontent.com/49539954/148161326-0cb33cba-bace-4c1b-92ff-1189cc747333.png"> We removed the invoice/reimbursement selector from step 1, having only the payee information instead    |
| **Step 2** |   <img width="779" alt="Screen Shot on 2022-01-04 at 22-37-38" src="https://user-images.githubusercontent.com/49539954/148161446-eba13b0a-2c13-424d-9249-3dbb26c5399a.png"> You need to select the title field and start typing for the rest of the form to show    |    <img width="583" alt="Screen Shot on 2022-01-04 at 22-42-52" src="https://user-images.githubusercontent.com/49539954/148161725-7bd47664-43ac-4ab2-8c0a-311630a3b14c.png"> The form is displayed entirely, we are also implementing a new behavior showing the resting state for the next button but not letting you move forward until you complete the required fields
| **Step 3** |   Step 3 stays pretty much the same     |                 |

**Comment by Betree** [comment]
@Memo-Es This format with screenshots before/after and the description are super helpful :pray: 

Everything looks good, except I think we're going to face an issue with `We removed the invoice/reimbursement selector from step 1, having only the payee information instead`: the fields that we ask the payee to complete depend on the expense type. The payee's address is required for invoices, but not for receipts.

**Comment by Memo-Es** [comment]
## Addition of a new stepper component for the new form layout

We designed a new linear stepper component that helps in making more explicit the step you're in

<img width="1280" alt="Screen Shot on 2022-01-05 at 22-44-58" src="https://user-images.githubusercontent.com/49539954/148329824-b73dc812-ec80-4ed1-b700-1a33c05fb7fa.png">


🎨 [Design reference](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=15761%3A244482)

**Comment by Memo-Es** [comment]
##  Title field improvements / Subheading addition

### Title field

We redesigned the title field to bring it closer to the rest of our new form fields, with a focus state, and an error state.

<img width="474" alt="Screen Shot on 2022-01-05 at 22-59-25" src="https://user-images.githubusercontent.com/49539954/148330818-55938678-8635-40d5-acbd-7d0d75b37bfb.png">

---

### Section title

We updated the section title component to be able to indicate when all fields in a section are optional, or private. 

<img width="574" alt="Screen Shot on 2022-01-05 at 22-59-39" src="https://user-images.githubusercontent.com/49539954/148331058-23a52953-7ed8-4122-8865-6e70678c2c21.png">

**Example:**
![Annotation on 2022-01-05 at 23-04-27](https://user-images.githubusercontent.com/49539954/148331184-207575db-ab0c-42b8-8fcb-282802746b84.png)

🎨 [Design reference](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=15761%3A244482)

**Comment by Memo-Es** [comment]
@Betree 

> Everything looks good, except I think we're going to face an issue with We removed the invoice/reimbursement selector from step 1, having only the payee information instead: the fields that we ask the payee to complete depend on the expense type. The payee's address is required for invoices, but not for receipts.

I did the corresponding changes and documented everything on this issue

**Comment by alanna** [comment]
@Memo-Es this looks great, but I'm a bit overwhelmed so can you let me know if you have specific questions?
