### ISSUE TITLE
Payment Processor Fee Tracker

### ISSUE THREAD

**Issue by abitrolly** [opencollective/opencollective#4878]
## User story 
_As person donating, I can see the payment processor fees upfront so that I can know exactly who and how much is paying them_

_As maintainer, I can see the payment processor fees so that I can zero out the balance in order to deactivate or switch costs (https://github.com/opencollective/opencollective/issues/1073#issuecomment-461179690)_

## Best solution for this problem

* [ ] For each payment processor figure out the structure of payment fees and document them
* [ ] Create table that will hold predicted fees and actual fees
* [ ] Setup public alerts when predicted fees are different from actual
* [ ] Export table via public API for analysis

For Wise see https://github.com/opencollective/opencollective/issues/1073#issuecomment-944170809

## MVP

Transaction API returning payment provider, predicted and actual fee.

## Metrics 

When https://github.com/opencollective/opencollective/issues/1073 is solved.

## Documentation 

* https://github.com/opencollective/opencollective/issues/1073#issuecomment-876961402
* https://docs.opencollective.com/help/contributing/development/dev-contribution-guide#project-structure
* https://docs.opencollective.com/help/contributing/development/architecture

<details>
  <summary>Triage Template (team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

/spent 1h

**Comment by wenzeslaus** [comment]
Another user perspective is that as person donating, I know I need to add more to cover processor fees so that the collective gets the money I want them to get. I think a checkbox "help cover processing fees" with some amount would at least notify me that there will be those fees involved even if the amount suggested is an estimate.

As as a person reviewing donations (maintainer or donor), I need to see if the collective is getting their goals met, but some important places now show amounts without payment fees subtracted (/contribute/my-tier page). The table with transactions for download would ideally contain all four numbers involved here, i.e., payment processing, OC tip, fiscal host fee, and the final contribution (or total or both).

I originally posted this to support (ticket 200371).
