### ISSUE TITLE
Design V2

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#502]
Design
- [x] goals #460
- [ ] show currency in front end. It's still unclear what currency a collective is operating on. We need to show the sign both on front page and expenses. related to #477 
- [ ] design proposal for followers #233 
- [ ] let users manage the tags of their collective #291 (this already happens for open source from the onboarding flow)
- [ ] bring back request money #293

**Comment by piamancini** [comment]
closing since the items we'll be working on have separate issues
pledges: https://github.com/opencollective/opencollective/issues/1020
https://github.com/opencollective/opencollective/issues/1056
