### ISSUE TITLE
[PROJECT] Multi-currency expenses

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5146]
## Overview 
Open-source projects / Open Collective team members have contributors worldwide that get paid in their own currency. Some service providers also need to be paid the exact amount invoiced, they can't accept losing a single cent in currency conversion (see https://github.com/opencollective/opencollective/issues/4731).

**For these reasons, we would want contributors to be able to submit expenses using a different currency than the one of the payer account/host.**

This project is also seen as a requirement to later implement [recurring expenses](https://github.com/opencollective/opencollective/issues/5144), as such feature would be mostly useless for the team if we're not able to submit it using a different currency.

## Ownership

**Owner:** TBD

**Product:** TBD
**Design:** @aminakazi 
**Engineering:** @Betree, @SudharakaP 
**Documentation:** TBD

*Note: Project owner responsibilities include coordinating all the different people that need to contribute to the project, defining specs and goals, communicating project progress, being the point person for decisions, QA, documentation, and a plan for ongoing maintenance. If the project owner can't continue, they need to hand the role over to another person explicitly.*

## Prioritization

**Impact**
- User-requested feature
- Will facilitate things for Open Collective's core team
- Will facilitate things for distributed teams
- Will unlock new powers when combined with https://github.com/opencollective/opencollective/issues/5144
- Will unlock some blocking situations that are time-consuming to solve otherwise (eg. provider [expecting a precise amount](https://github.com/opencollective/opencollective/issues/4731))

**Alignment**
- Aligned with https://github.com/opencollective/opencollective/issues/5141

**Effort**
_TBD depending on research and specs_

## Measuring success
_TBD_

## Next steps

See https://github.com/opencollective/opencollective/issues/5146#issuecomment-1023321220

## Templates
_Sections below to be completed_

<details>
<summary>Further Prioritization </summary>
<pre>
- How does this serve our mission
- Will this help to make us financially sustainable within a year?
- Can this make us move faster?
- Does this increase quality? 
- Does this add technical debt?
- Is it feasible to build and maintain with our current team and runway?
- What insight or research is this project based on?
- Is this problem already solved elsewhere?
- How will we measure our success? Do we have a baseline today that we can compare this against?
- How well do we understand the complexity of the problem, feature to be added or user need to be addressed? 
- What is the estimated timeframe for delivering this project?
</pre>
</details>

<details>
<summary>Roadmap</summary>
<pre>
## Roadmap & Timeframe   
- Scoping
- Prototyping/validating
- Development
- Release prep (documentation, marketing etc.)
- Release
- Retrospective
</pre>
</details>

<details>
<summary>Success Metrics</summary>
<pre>
## Measuring success 
Measure: What is the measure?
Current baseline: What is the baseline that we see today?
Target: how do we want to see that move?
Link: link to query on Metabase
</pre>
</details>

<details>
<summary>Risks</summary>
<pre>
## Risks
If this project is going to go wrong, what's the most likely cause and what can you do to derisk upfront?
- Risk:
- Mitigation:
</pre>
</details>

<details>
<summary>Documentation & Release</summary>
<pre>
## Documentation & Release Brief
**Estimated delivery date: **
- Which aspect(s) of the platform does this change impact?
- Which group(s) of users will benefit from this change?
- Is this project in response to a user-requested feature? If so who requested it (link to feature request if available)?
- Is this project related to any similar work we have done, or are planning on doing in the next three months?
</pre>
</details>

<details>
<summary>Next Steps</summary>
<pre>
## Next up
- Create a project board, add this issue to the description
- Open up any issues to de-compartmentalize the project, add them to the project board
- Open a documentation issue, add it to the documentation project board, reference this issue. 
above 
</pre>
</details>

<details>
<summary>Closing this Issue</summary>
<pre>
- Close all relevant project issues
- Open up issues for improvements 
- Post comm's according to comm's plan
- Post project screen-cast on #documentation slack channel 
- Post project closure in #newsletter slack channel 
- Celebrate!! 
</pre>
</details>

**Comment by Betree** [comment]
Here are the notes from today's meeting laying down a first overview of what's needed to complete this project, along with a release plan in 3 steps.

## Things to update in the interface

<details>

1. In the expense flow, for the accounts that have it enabled, show a currency selector
    - @opencollective/design will work on a selector. All currencies have a code, but some don't have a symbol. We should always display (at least) the code. We should also have a search. Look at https://wise.com/fr/currency-converter/gyd-to-usd-rate for inspiration.
    - Engineering can start hacking this with a simple select if the design is not ready
 
![image](https://user-images.githubusercontent.com/1556356/151017469-25affe8d-1dfc-4230-9d39-4c360137187c.png)

2. In the expenses list, expense page, and on the host admin, always show the expense amount with its target currency along with an estimate of the fees (need @opencollective/design)

![image](https://user-images.githubusercontent.com/1556356/151018545-aa12e6c6-0ab4-4b2e-a010-d33d71d5b92d.png)

3. Adapt the pay expense modal

![image](https://user-images.githubusercontent.com/1556356/151332540-924e6ff9-07d2-412b-991e-f47f17895c56.png)

4. Adapt the transaction details (bonus)

</details>

## Technical overview

<details>

- Payout methods
  - Wise API
    - Play with quote `sourceCurrency` / `targetCurrency`
  - PayPal API
    - Set the [batch item currency](https://developer.paypal.com/api/payments.payouts-batch/v1/#definition-payout_item) to expense.currency 
    - It seems that our code already supports cases where the payout currency is not the currency of the host
      - See [PayPal documentation](https://web.archive.org/web/20210421103754/https://developer.paypal.com/docs/payouts/features/currency-conversion/)
      - See [our code](https://github.com/opencollective/opencollective-api/blob/c64a88d085594abe34e26be5d6cea873b99bc798/server/lib/transactions.js#L133)
  - Manual payouts
    - Surface a way to account for the fxRate either by asking directly for it or by asking the target amount that was actually received
  - Internal transfers (e.g. Babel reimbursing Webpack for an expense in EUR)
    - We can skip this as a start. If there's demand for it, we'll use our own `fxRate`
  - Don't allow for other payout methods (account balance)
- When paying 100% of the balance, we should adapt conditions
- Ignore cross-host expenses
- We'll need to update API & frontend validations regarding amounts (check balance)
- Ledger 
  - DEBIT  
    - `hostCurrency` to the host currency
    - `currency` to the collective currency
  - CREDIT
    - Opposite account is financially active (`isActive=true`) => convert to the currency of their host (supposedly automated)
    - Otherwise (user, inactive org) => same as debit?
- Discuss https://github.com/opencollective/opencollective/issues/3102

</details>

## Release phases
- Phase 1: Core team
  - Add a special feature flag at the host level and enable it on `opencollective`
  - We can keep out manual payouts for multi-currency expenses (disable the button)
- Phase 2: Enable on more hosts/collectives
  - Add support for manual payouts
  - Find interested users (probably in the opensource world)
- Phase 3: Public release

**Comment by Betree** [comment]
For the current sprint, we plan to tackle **Phase 1 (core team)**:
- Add a special feature flag at the host level and enable it on `opencollective`
- The feature will only be enabled for **automatic** payments with PayPal and Transferwise
- We expect the core team to be able to submit expenses in their home currency and get paid for the exact amount they defined
- We expect both the amount in expense currency and collective currency to be reflected in important places of the interface (expense page, expenses list, host admin, pay expense modal)

**Comment by piamancini** [comment]
- [ ] Split specs into smaller issues 
- [ ] Tackle them

**Comment by znarf** [comment]
Goals for Q1 Sprint 1 Week 3:
- [ ] Show both amounts in the Pay Expense modal
- [ ] Trigger the payment with the right currency when paying with Wise
- [ ] Bonus: Show both amounts also on the Expense page

**Comment by znarf** [comment]
Goals for Q1 Sprint 1 Week 4:

- [ ] Trigger the payment with the right currency when paying with Wise
- [ ] Trigger the payment with the right currency when paying with PayPal

**Comment by znarf** [comment]
Goals for Q1 Sprint 1 Week 5:

- [ ] Test paying with Wise on staging. Enable it for limited audience if it works @Betree
- [ ] Follow up and Finish https://github.com/opencollective/opencollective/issues/5177 @SudharakaP @Betree

**Comment by znarf** [comment]
Goals for Q1 Sprint 1 Week 6:
- [ ] Iterate on Wise @Betree
- [ ] Polish data structure in the Ledger @Betree
- [ ]  Enable it for limited audience

**Comment by znarf** [comment]
This project will be carried over next sprint for completion.

**Comment by piamancini** [comment]
- [ ] fix small glitches 
- [ ] enable for other collectives
- [ ] loom for documentation

**Comment by flaki** [comment]
If you are looking for beta testers, would be happy to give this a go at `baytech`!

**Comment by Betree** [comment]
Things to document:
- [ ] Basic flow to create a multi-currency expense
- [ ] Which currencies are supported (depending on the payout method)
- [ ] How do we get/compute our FX rates

**Comment by piamancini** [comment]
- [ ] fix ux issue 
- [ ] close issue and create follow up issues

**Comment by Betree** [comment]
This project is considered done. We have some follow-up issues for the leftovers:
- https://github.com/opencollective/opencollective/issues/5367
- https://github.com/opencollective/opencollective/issues/5272
- https://github.com/opencollective/opencollective/issues/5206
- https://github.com/opencollective/opencollective/issues/5384

**Comment by alanna** [comment]
Are we close to being able to switch this on for OCF? We have at least one Collective who would use it immediately.

**Comment by Betree** [comment]
@alanna We're in the beta phase, enabling on a per-collective (preferred approach) or per-host basis is possible. Just ping me with the collective and I'll enable it.
