### ISSUE TITLE
[PROJECT] API completeness

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#5150]
As part of our strategic focus on [API, Open Collective as a Platform ](https://github.com/opencollective/opencollective/issues/5140), we would like to prepare a re-launch of our GraphQL API v2 and assess and document its completeness. What is already implemented? What's missing?

After this assessment, we would like to work on the missing parts and implement the missing features.

As it will certainly not be possible to do everything, we would like to focus and unlock the following ideas/projects:
- Let user people create their Open Source Collective as part of GitHub Sponsors on-boarding (GitHub as API client)
- Create a CLI tool (as API client) to help Open Source Collective admins import monthly GitHub Sponsors transactions, see https://github.com/opencollective/opencollective/issues/3903

**Comment by znarf** [comment]
For 2022 Q1 Sprint 1, we prioritized the following:

- Get Organization, Fund, Project & Event for consistency
- Create Collective: check and enhance to support GitHub use case
- Create Event
- Create bounty to move Tiers to v2
- More editAccount properties. If needed, case by case basis.

**Comment by piamancini** [comment]
- [ ] Create issues for items on the list 
- [ ] Test API Script with GitHub Sponsors for adding funds to collectives

**Comment by znarf** [comment]
Goals for Q1 Sprint 1 Week 4:

- [ ] Extend Create Collective to support "GitHub" use case https://github.com/opencollective/opencollective/issues/5189

**Comment by znarf** [comment]
Goals for Q1 Sprint 1 Week 4:

- [ ] Extend Create Collective to support "GitHub" use case https://github.com/opencollective/opencollective/issues/5189 Merge and Deploy
- [ ] Ability to Create Event. https://github.com/opencollective/opencollective/issues/5190 Merge and deploy.

**Comment by znarf** [comment]
Goals for Q1 Sprint 1 Week 6:

- [ ] Document and create a new repository for API use cases

**Comment by znarf** [comment]
https://github.com/opencollective/api-examples
