### ISSUE TITLE
[PROJECT] Setting up a user testing process

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#5155]
## Context

We have been discussing for quite some time now the possibility of having a proper user testing process to help us identify issues with our product before the feature(s) get implemented. This is a crucial feature for our design approach to be really top-notch, and we have to focus the right amount of focus to make it part of our natural flow while designing the platform (and not only).

**This is a series of initial thoughts to get our user testing program on track. We should strive for a process that remains alive and changing**

## Methodology
* Who is our subject? Description of the persona behind a superficial 'user' treatment
* Set up the goal for each test **What are the key assumptions we are focusing on with this test?**
* Design a low-res prototype to test that fundamental assumption
* Define if the test is meant to be either structured (With a script) or unstructured (Thinking out loud)
* Make sure to have short sessions and **record them**
* Write a **visual** report at the end
   * Summary of key findings
   * Who was the subject? (Persona)
   * Results (Usability issues, main feedback)
   * Other feedback or notes
   * How we should measure our success? How to keep track of that?

## Tasks
 - [x] Demo of the process
 - [x] Test process with 1 or 2 projects
 - [x] Design template in figma for report
 - [x] Collect feedback and document adjustments

## Additional notes
- We need to create a fund named 'User testing fund' or something to pay people for their time. So both the users participating in the testing sessions and the additional staff or resources needed for any testing effort have efficient funding.
- How much are we giving as a reward for users? (10-15 USD per hour?)

**Comment by piamancini** [comment]
- [ ] have calls with team members to validate this process 
- [ ] structure a methodology to user testing 
- [ ] test case: expense government

**Comment by znarf** [comment]
Goals for Q1 Sprint 1 Week 3:

- [ ] Demo the process

**Comment by Memo-Es** [comment]
Goals for Q1 Sprint 1 Week 4:

- [ ] Work on document accessibility
- [ ] Project communication

**Comment by Memo-Es** [comment]
Goals for Q1 Sprint 1 Week 5:

- [ ] Set up public link

**Comment by Memo-Es** [comment]
Publishing a wrap-up later today and closing the issue.

**Comment by BenJam** [comment]
@Memo-Es can we close this issue down, should we update the project templates etc. to ensure people are aware of these resources?

**Comment by Memo-Es** [comment]
@BenJam closing this issue, I will make sure to have it mentioned in a "Design resources" section in slack and the design system

**Comment by kaylarep** [comment]
@Memo-Es is this also in the internal docs? I couldn't locate it.

**Comment by Memo-Es** [comment]
@kaylarep, not yet, I just tried to go to the internal docs link, and it says "unauthorized" can you help me add it and/or give me access to the internal docs in GitBook?
