### ISSUE TITLE
[Project] Collective activity log

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5195]
## User story 
We are getting into the territory of governance tooling and seek to continue developing how transparency works on the platform. One important missing aspect of transparency, which certainly relates to governance, is being able to see what's happening in a Collective. Right now when someone changes a setting, creates a project, adds a new admin, there's not really a good way to make that visible. We should strive for transparency beyond simply financial.

## Best solution for this problem
A Collective activity log, similar to what we have for Expenses, showing who took what action when over time.

![Screen Shot 2022-02-04 at 1 50 51 PM](https://user-images.githubusercontent.com/5498878/152454083-89807d4b-47b3-4568-a644-8b4bc811131d.png)

Actions I can think of...

* Collective created
* Admin added or removed
* Joined Host, changed Host
* Info change (description, website URL, cover image, etc)
* Settings change (e.g. policy updated)
* Event or Project created or archived
* Tier created or updated
* Goal set, goal reached

This would eventually tell the story of a Collective over time, and provide important transparency into governance-related changes.

I'm not sure where this changelog should be displayed.... probably similar to how Transactions work now, where the most recent are shown on the front page and you click through to another page to see all.

I think this also complements the integration work going on and we should consider this in the API. For example, a Collective links to Loomio via Metagov, and decides that admins are to be added or removed based on a Loomio vote. They could run that process, the change would be made, and the changelog would record what happened.

## MVP
@kewitz mentioned starting with the backend code to make it possible for us to track such actions without yet building the front end of displaying them yet.

**Comment by Betree** [comment]
Yes for this! We actually have a lot of data already recorded on the API side waiting to be displayed (eg. member invited, invitation accepted). By adding some complimentary events (e.g. member removed) and being able to generate diffs when editing the settings we'd be able to provide really useful info.

As an example, Github has something like this:

![image](https://user-images.githubusercontent.com/1556356/152750992-67cf8977-36c8-49e3-a239-6b42a20a1025.png)

**Comment by shaunagm** [comment]
This looks great. Several of the collectives we've worked with have wanted improve transparency in addition to having tooling for collective decision-making, so I think this will be popular.

On Metagov's roadmap are monitoring & oversight tools for activity—so a searchable log of activity, but also things like flagging & tagging, discussions, etc. If the activity log is part of the OC API that will make it easier for us to provide those tools to OC users.

**Comment by jfdh** [comment]
Here is another great design from the platform YouSign

![Screenshot 2022-04-28 144613](https://user-images.githubusercontent.com/30813303/165755479-0d9044a0-35ff-449f-a892-6011e972dc73.png)

**Comment by alanna** [comment]
notes from kickoff meeting
 
* important not to include updates about certain security updates (e.g. 2FA turned off)
* most activity should be public, but there are some private things and also don't want an overwhelming list
* the main focus of this feature is Collectives, but we could imagine also having it for Hosts and Individuals
* should there be one view for admins and another that's public?
* could think of it like Expenses activity, some is public, some private
* could also include stuff like 'event created' 'project created' 'project archived' 'Update published' etc, with links to those things
* need some kind of filters or ordering on the activity interface so we can include lots of info and it will be useable
* should we include all project and event activity in parent activity log?
* talk to @EdaSCN and @shaunagm about their requirements
* when we designed expense activity updates we thought about "telling the story of the expense" - same for this
* activity log entries should have: date, who took the action, what happened, link if relevant (e.g to an expense)
* activity log should live on its own page: /collective/activity -> accessible through action menu to Collective and Host admins, and ideally a section Host Admin dashboard called "Collective Activity", where they can filter by Collective

**Comment by Memo-Es** [comment]
### Kick-off notes

**Transparency?**
 - Some updates should be public
 - Some updates though should remain private to admins only

**Elements included**
 - Date
 - Who took the action
 - Source (link)
 - Details of the event

**MVP**
 - Start private and think about how we can display it publicly
 - Include a view from the host admin dashboard to display all activities from the Collectives they host with the option of filtering by Collective

**Comment by kewitz** [comment]
Technical Issues:
API:
- [ ] Activity resolver for Accounts
  - [ ] Create a permission system based on activity type and user access
  - [ ] MVP can be restricted to only AdminOfCollective.
Frontend:
- [ ] Start i18n library for Activities
- [ ] Implement collective admin panel Event viewer
  - [ ] Add toggle to include/exclude children collective events
- [ ] Implement host admin panel Event viewer
  - [ ] Enable filtering by collective

**Comment by Betree** [comment]
Feel free to look at https://github.com/opencollective/opencollective-api/blob/59a598b9d7d935cc4c52be388ae26ea24ca57309/server/graphql/v2/object/Expense.js#L321 for the implementation as the `Expenses` GQLV2 object supports returning its associated `Activities`.

**Comment by Betree** [comment]
Just discovered today that we don't log who made changes to the admin. Doing so sounds really important in itself and should probably be a requirement for this issue: https://github.com/opencollective/opencollective/issues/5519

**Comment by Memo-Es** [comment]
@alanna What do you think should be the next step for this? Talk with SCN and WWC? If so, can you make some intros?

**Comment by alanna** [comment]
Yep! I will intro you to the two main users I think it would be good to speak to (Accountable and Metagov)

**Comment by BenJam** [comment]
- [ ] summarise feedback form metagov/scn (and alanna, i assume)

**Comment by Betree** [comment]
We should try to implement this activity log with components as generic as possible. I can see us willing to exploit this feature in different places, for example:
- A `/me/admin/activity` to see my personal activity log
- A `/opencollective/root-actions/user` page for root admins to get a list of all actions initiated by a given user (to investigated SPAM, suspicious activity, etc).

**Comment by Memo-Es** [comment]
## Design notes

Key concepts | Requirements | Actions
-- | -- | --
Governance | Live view with filters (Report) | Collective created
Transparency | Notifications when changes occur | Admin added or removed
Tooling for Collective decision making | Activity log for Collectives, hosts, individuals | Joined host, changed host
Assessing risk to scale | Include links to expenses, updates, or projects | Information update (Description, website URL, cover image, avatar)
Ongoing due-dilligence process | Date/Who did it/Source/Details | Settings update (e.g. expense policy updated)
  | Share an activity | Event or project created or archived
  |   | Tiers activity (New tier, amount updated)
  |   | Goal set, goal reached
  |   | Update published
  |   | Expenses activity

### Notes
 - Some updates should be for admins only for security reasons (e.g. 2FA turned off)
 - The right way to show this in the interface should start at an admin level and a follow-on project can be to show it publicly
 - Shall we display events + projects activity?
 - Can we think of graph visualizations for the future? (Goal: Identify trends)
 - We can use the [UI from the changelog project](https://d.pr/i/gzs9qT) we did last year

@alanna Any comments or additions?
cc @Betree

**Comment by alanna** [comment]
Looks good to me!

> Shall we display events + projects activity?

Yes. Similar to how we deal with financial activity currently, where Projects show their own activity only, and parent Collectives show both their own activity and that of their Projects and Events.

**Comment by piamancini** [comment]
- [ ] Start design (@Memo-Es)

**Comment by piamancini** [comment]
Start design (@Memo-Es)

**Comment by Memo-Es** [comment]
Q2S2 Update (Week 4):
 - [ ] Design proposal 
 - [ ] Circle proposal back with Alanna
 - [ ] Present demo

**Comment by kaylarep** [comment]
> should there be one view for admins and another that's public?
yes!

> It would be especially helpful if we could filter the report e.g. by type of action.
big +1.  this would help with the amount of information this log would contain. could even have a time filter (e.g. 'Last 30 days; Last 6 months; All time)

**Comment by Memo-Es** [comment]
Q2S2 Update (Week 4):

 - [ ] Design update based on the first round of feedback (Slimer design, other small tweaks)
 - [ ] Publish update in issue

**Comment by kaylarep** [comment]
> We then have two choices:
> 
> 1. Show something like `by Deleted account`. That's, I believe, Github's strategy.
> 2. Use the info stored in the activity or force load the user to retrieve only the name, and show something like `by Thomas Anderson (deleted)`

@Betree I vote for #1

**Comment by alanna** [comment]
I'd vote for #1 for public view and #2 for admin view. Admins need to be able to determine accurate historical activity.

**Comment by Memo-Es** [comment]
## Design update

The design proposal is finished. Here it is:

Fiscal hosts' view | Collectives view
-- | --
![Fiscalhosts-1](https://user-images.githubusercontent.com/49539954/179443589-7a6755d8-fb77-46a2-9fec-864d7d227838.png)  |  ![Collectives-2](https://user-images.githubusercontent.com/49539954/179443596-f4d729b0-cbc2-49dd-8bbd-b9e1f21d60cc.png)

**Comment by Betree** [comment]
Use case: the other day @alinamanko rejected an expense by mistake, but was unable to find out which one and had to ask an engineer to look at the database. With an activity log at the user or host level, she could have looked there.

**Comment by Betree** [comment]
Some personal concerns:
- I don't see any use case for the public page, and there's a risk in letting anyone stalk the admin's activity (when do admins approve expenses? when are they offline?)
- Let's make sure we build this in a generic way, this will be helpful for individual and host accounts as well. Great if we can deliver like that from the start.

**Comment by alanna** [comment]
I really support a pared down version of the log for public visibility - but I think we should push and do that next step for transparency. Once we release this admin only first version, we can gather feedback from admins about what info they would or wouldn't like to be public and make some decisions.

**Comment by Betree** [comment]
> I think having 'Activity Log' be an optional public Page Section would be useful to a viewer to see how active a group is without having to dig. If it's possible to have a very pared-down version, would be ideal, for the reasons above.

The budget section already provides a quick preview of the financial activity (expenses + contributions). That's, in my opinion, what transparency is really about for random visitors. An activity log would add the ability to know when the admins edit the settings, the description, etc. I still fail to see which value it adds to surface it publicly.

> a use-case: when a restaurant 'changes management', they often publicize this. It's good for transparency to display when organizers have changed - Again, having this optionally displayed

Knowing that the admins changed for a collective is good public info indeed, so far the only one I find worth surfacing to the world.

> they receive a large grant

Already surfaced in the budget section and on the transactions page.

> they publish an Update about these new funds

Already surfaced in the Updates section.

> they begin to disburse the funds

Already surfaced in the budget section, on the transactions page, and on the expenses page.

> I really support a pared down version of the log for public visibility

@alanna I again fail to see real use cases for a public view -except for the one mentioned by @kaylarep above (changes in admins) - and am wondering whether this is not a case of projecting our own wishes to the rest of the world.

- I see a benefit for us, the internal team, to have such page to debug and monitor groups activity easily
- I see a benefit for admins, to monitor what's happening on their accounts
- I see a benefit for individuals, to make sure their account hasn't been hijacked and have a history of their actions
- I see no benefit for random visitors so far, knowing that a collective edited their settings won't motivate them to contribute and won't solve a lack of transparency either. Plus, there's a risk in letting random people stalk all admins' activity.

> Once we release this admin only first version, we can gather feedback from admins about what info they would or wouldn't like to be public and make some decisions.

That would be my conclusion as well. I feel that what we'll want to ship for the public view will be nothing like what we're currently designing for this project. @iamronen was sharing this [feedback](https://opencollective.slack.com/archives/C020ZQSLM5M/p1657873558749179?thread_ts=1657597166.811609&cid=C020ZQSLM5M) too on Slack, mentioning that "The vertical timeline is a nice touch but I think it is not a justified investment of engineering resources for a screen that is basically a platform "debugging" tool.". I strongly resonate with his analysis that what we should try to design here is a debugging tool.

**Comment by kaylarep** [comment]
I agree that it feels overly repetitive. For a public viewer though, perhaps the 'Sections' aren't as accessible as a chronological timeline of events. For 'telling the story' of a group, a timeline is very helpful.  

I'm thinking perhaps a better way to consider this "public activity log" project would be framing it as different options for viewing a Collective's page: a 'Section' view or 'Timeline' view. However, yes that feels like a separate, less urgent project.

**Comment by Betree** [comment]
@kaylarep I agree with your analysis, re-framing this as a "Timeline" adds a lot clarity. It could be part of rethinking how we display profiles. It's definitely worth opening the discussion, especially as @opencollective/design is currently looking into #5680

**Comment by alanna** [comment]
Yes this for me very much about "telling the story" - in the same way the status updates on the expense page tell the story of an expense, the activity log tells the story of a Collective over time.

Like I mentioned, I think we should progress the admin view of the activity log, as planned, then reassess the need for and purpose of a public view. So that's fine.

But I do see many potential uses of a public view...

* I'm a host admin and I need to see when a Collective that we used to host left my host
* I was an admin of a Collective and got removed - I want to see who kicked me out and when
* I'm a journalist writing an article about a Collective and I want to see when it started and it's milestones
* I'm a volunteer who gets reimbursed from a Collective, and I need to see when the expense policy changed and who changed it

I'm sure there are many others.

**Comment by iamronen** [comment]
@alanna I resonate with the narrative of "telling the story" but I don't think a long filterable data-dump table (with a timeline next to it) addresses this.

Perhaps a more pertinent question is: if we have capacity for only one large project and you had to choose between activity log and financial visualizations #5704 - which would you prioritize? (this algorithm can be repeated and applied to any two projects!)

As for the four sample scenarios you mentioned:

### 1: Collective leaving host

1. When do you need to see that a collective that you used to host left your host?
2. How often does this happen?
3. What do you do with this information once you have it?

My guess is that you would want to be notified about this when it happens ... and if that is the case I don't see how an activity log helps you ... unless you schedule a manual task of eg: checking once a month the activity log for "departed collectives" during the last  month.

If this is a compelling usecase, would it not, at least for now, be addressed by a notification letting fiscal host admins know that a collective has departed when it happens?

### 2: Removed admin
Wouldn't this be solved with a priority notification (=you cannot disable it) letting you know that you have been removed as an admin from CollectiveA by AdmiinB?

### 3: Milestones / Storytelling 
This feels like an interesting scenario with latent potential.
In the context of OSC we are exploring a need for roadmaps ... and that resonates with milestones.
I look forward to exploring more about this potential with the quality of story-telling.

However, again, I don't think that an automated activity log will address milestones and/or a coherent narrative.

### 4: Expense Policy Change
1. When does this happen?
2. Why does this happen? What causes me as a volunteer to suddenly become interested in the expense policy?
3. Do collectives have an explicit expense policy that is publicly available, that volunteers know about and can reference and to which collectives are held  - some kind of governance mechanism?

If this is a valuable need and the answers to q3 are "yes" ... then having an activity log data infrastructure may be valuable, because a user experience can be added to the "collective expense policy"  to 1) reference older versions of the policy and 2) highlight what has changed.

But, again, the activity log as a user experience does not address this well. I am imagining the work it would take a person to find, extract and compare two versions of an expense policy through the activity log ... and I find myself wondering:
- how offended does this person need to be to put in all this effort?  
- will any "discoveries" lead to meaningful outcomes? assuming this offended volunteer figures out what has changed - what can they do about it?
- leading me to think, yet again, that this an effort to "put out fires" and that it would be better to try to avoid (to the extent this is possible) the fires through affective governance (eg: an open, documented discussion about changing expense policies + notification to the community and especially everyone who has volunteered during the last 6 months that a change is being made) 

### Summary
While these may be valid scenarios, I don't think (taking into consideration that we haven't explored any of them in depth) that the activity log addresses any of them effectively.

I also think that scenarios 1,2 & 4 exemplify us getting lost in the weeds ... they don't seem to me like things that can generate substantial impact to the growth and well-being of the platform as a whole. Maybe, if OpenCollective was an international platform where hundreds of  ACTIVE fiscal hosts supported tens of thousands of ACTIVE collectives then maybe (maybe!!)  the scale would endow these issues with more urgency and value. I don't think we are there yet ... I prefer we focus on work that can get us there :)  I look forward to facing these problems at scale :)

**Comment by Betree** [comment]
Reading at the comments, we seem to agree that the need for a public Timeline is very different from the needs of the project we're addressing here - an activity log for admins - both in what we're going to display and how we're going to display it. I would therefore suggest that we move the conversation to https://github.com/opencollective/opencollective/issues/5767.

**Comment by iamronen** [comment]
Two things came up during yesterday's retrospective that may inform our decision on if/how to approach this project: 
1. I learned that back-end work has already been done on this - that the logging capacity itself is already built. If that is the case and we already have a log in our database, it may be enough for now to use metabase to query this dataset in the rare cases where some kind of conflict resolution is required.
2. @znarf also brought up the subject of "appetite" and indicated that different appetites can create different results. There can be different implementations of activity log depending on what appetite we assign to it. So there can be a "papercut" , a "2 week" or a "4 week"  activity log implementation. If this is indeed the case, then if we still want to prioritize this, we can assign it a smaller appetite.

**Comment by alanna** [comment]
Just discussed a use case for this in the OCF team meeting - we actually have no way of knowing right now when a Collective leaves. They can just unhost themselves quietly. So it will be very useful to have the activity log to be able to develop an offboarding process proactively. Thanks to everyone working on this feature! We're looking forward to it.

**Comment by iamronen** [comment]
@alanna 
While  the activity log may reveal this event (if someone remembers to regularly check the logs), if you want to delve further into this scenario, here are some questions I would ask:

1. What does "unhost themselves quietly" mean? what do they actually do on the platform to make this happen?
2. If it is important for you to know this can we not make it more "noisy"? Instead of manually searching for it in the activity log, why would you not want to simply be notified when it happens? why would you want to have to manually hunt this down in the activity log?
3. How frequently does this happen? Has this happened with collectives that still have unspent funds? 
4. What will "offboarding" include? what would you want to do that you are not currently doing?
5. What are the ramifications of "offboarding" not happening?

attn @poohlaga

**Comment by alanna** [comment]
Yes we would find this out by regularly checking the logs, which we will absolutely be doing once this feature exists, and other hosts will too (we all do these functions manually now).

1. Unhosting as explained [here](https://docs.opencollective.com/help/collectives/change-fiscal-host#what-is-the-process-for-changing-fiscal-hosts).
2. We get 1000x too many notifications as it is. They would be lost in the noise. Much better to just be able to search/filter the activity logs in the app.
3. Not possible to unhost with unspent funds.
4. Ensure we have a recent Update closing out their project - the auditors may come along and say "hey what did the Collective do with this money?" and if their gone with no reporting we can't answer beyond looking at expense records. Also ask them for any feedback, etc.
5. We need to understand what's up with all our Collectives to some extent. If someone leaves without a word and we don't have any context, that's less good than being able to know the status of a project.

**Comment by iamronen** [comment]
re: 2 - Notifications
It this true even after the recent release of [email notification settings](3357)?
If this continues to be true, then I would like to inquire if this is an organizational issue (eg: OCF overloaded / under-resourced) or a platform issue (eg: still sending out too many notifications). 
**A chronic state in which a host is unable to receive a critical signal from the platform is, in my mind, a problem.**
 
While I understand the solution of checking activity logs, it seems to me like a negative feedback loop - basically adding yet another task (more work - regularly being on the lookout for something that may not have even happened!) to an already overloaded group.

**Comment by alanna** [comment]
Notifications are just not effective at OCF or OSC's scale really. They go to all admins and there's no way to track if someone has followed up on a team with like 8 admins. The only way we're able to make use of notification now is routing them to freshdesk so we have a ticketing system to track them (e.g. expense comments). Because we need to keep notifications on for things like expense comments, even with the new notifications settings options, it's too noisy to use for things at a slower pace like a Collective leaving. We need data sources to engage with that we can filter, sort, download, and use according to how we can set up regular compliance check processes. Otherwise we'd just have to set up another layer, like freshdesk, to sort and track notifications of e.g. Collectives leaving, and have a system for regularly identifying those, and moving them to a spreadsheet to track basically re-creating in a messy way the solution we will get directly from the activity log. We could do it, sure, but what's the point when we will have the activity log to accomplish the same thing?

**Comment by BenJam** [comment]
update w2 

going to punch out an MVP asap based on what we already have from an engineering perspective i.e. we'll display collective filter but perhaps not the type filters. Updates that we can already support are the same that we use to generate notifications (i.e. we could run the type filter from that). 

- @betree and @suds to review spec and make a start

**Comment by Betree** [comment]
Doesn't have to be this sprint, but I believe https://github.com/opencollective/opencollective/issues/5808 will be an important requirement for this project to have a meaningful impact.

Why? If we just roll out the feature with our current data model, an activity like `Collective application approved` will only be displayed on the host's activity log. But it actually makes sense to also surface such activity in the **Collective's** activity log (_if I review my collective's history, I want to see when I applied to a given host and when was the application approved_).

https://github.com/opencollective/opencollective/issues/5808 states that there are usually two parties involved in an activity (that can be referred to as the _author_ and the _target_) and we should record both of them properly.

**Comment by kaylarep** [comment]
The log should have (IMO):
- Collective created on -date-
- Collective applied to host -name of host-
- Collective approved by host -name of host-

- perhaps also : Collective application rejected by -host- ?

**Comment by Betree** [comment]
@kaylarep I agree. All these are great example of events we can 9nly surface if we tackle https://github.com/opencollective/opencollective/issues/5808

**Comment by Betree** [comment]
Identified another issue that we'll have to tackle to make the data meaningful for this project: https://github.com/opencollective/opencollective/issues/5822. In short: many activities are not properly linked to an account (e.g. when a collective gets created, when a contribution gets rejected, etc). We need to fix that behavior on the API and make sure we update past activities for them to be surfaced in the activity log when we'll release it.

**Comment by BenJam** [comment]
update: we have a pr behind a feat flag that presents activities form the activities table. @betree has reviewed and iterated. Would like to roll this PR out to the team as a first iteration/MVP

- [ ] take a look at #5808 #5822 to see whether we can tackle them this sprint
- [ ] roll out pr to the team from candidate

**Comment by Betree** [comment]
We just had a call with @SudharakaP to document some of the next steps for this project. Things we're about to do:

Ben:
- [ ] Create issue for Add an activity for `collective.edited` (or updated?)
- [ ] Create issue for system activities
- [ ] Create issue for "Translate missing event types"
  - COLLECTIVE_EXPENSE_MISSING_RECEIPT
  - VIRTUAL_CARD_CHARGE_DECLINED
  - COLLECTIVE_CORE_MEMBER_REMOVED
  - COLLECTIVE_VIRTUAL_CARD_SUSPENDED
  
Suds:
- [ ] Create project board (or a tag?) to group all activity log issues
- [ ] Implement pagination
- [ ] Enable for fiscal all profile types
- [ ] Filtering (date, type)

**Comment by kaylarep** [comment]
Oh, also what about also:
- 'Virtual Card Created'
- 'Virtual  Card Paused' (this would be either manual or because no receipt was uploaded, might be helpful to include _who_ froze the card) -- maybe this is what you mean by SUSPENDED?
- 'Virtual Card Deleted'?

**Comment by Betree** [comment]
> Oh @Betree , what about also:
> 
>     * 'Virtual Card Created'
> 
>     * 'Virtual  Card Paused' (this would be either manual or because no receipt was uploaded, might be helpful to include _who_ froze the card) -- maybe this is what you mean by SUSPENDED?
> 
>     * 'Virtual Card Deleted'?

@kaylarep These events already have associated activities, and thus will be displayed in the activity log by default. For a full list of already supported events, please check: https://github.com/opencollective/opencollective-frontend/blob/b08286c4c79e1f4f0cbd1954f46784ccce821708/lib/constants/activities.js

**Comment by BenJam** [comment]
- [ ]

**Comment by Betree** [comment]
For this week:
- [ ] Finish & merge filters (date, type)
- [ ] Finish & merge pagination
- [ ] Start implementation for https://github.com/opencollective/opencollective/issues/5808 / https://github.com/opencollective/opencollective/issues/5822 (we looked at it last week and wrote some specs)

**Comment by SudharakaP** [comment]
Week 5: 

- [ ] [Add an activity for collective edited](https://github.com/opencollective/opencollective/issues/5864)

**Comment by Betree** [comment]
Feedback issue: https://github.com/opencollective/opencollective/issues/5912

**Comment by Betree** [comment]
Current status: internal beta with selected accounts, iterating on feedback and small issues.

The only real blocker left for a public release is https://github.com/opencollective/opencollective/issues/5959.

**Comment by alanna** [comment]
@shannondwray this will be ready for docs and announcement soon

**Comment by Betree** [comment]
All blockers are now solved, and the project is enabled on multiple internal collectives & trusted hosts. It can also be tested by manually adding `/activity-log` to the admin URL of any profile, for example: https://opencollective.com/opencollective/admin/activity-log.

Everyone can give feedback at https://github.com/opencollective/opencollective/issues/5912. We'll let a week go by to make sure everyone has the time to review this and **if no blocking feedback then we'll release it publicly on the 24th of October** and will close this issue.

cc @shannondwray let me know if you need anything for the docs or announcement.

**Comment by Betree** [comment]
We're delaying a bit the release to focus the end of the sprint on other projects and make sure we address the important feedback from https://github.com/opencollective/opencollective/issues/5912. I propose the new date of **7th of November**.

**Comment by Betree** [comment]
Releasing the activity log today.
