### ISSUE TITLE
[Roadmap] Sprint Facilitation Checklist: Q1S1 -> Q1S2

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#5273]
### During previous Sprint

- [x] Launch prioritization discussion https://github.com/opencollective/opencollective/issues/5159

### On previous Sprint closing week (last week)

- [x] Schedule prioritization meeting

In prioritization meeting:

 - [x] Pick 4 to 6 Projects
   - [x] Pick 2 to 4 regular Projects
   - [x] Pick 2 to 4 smaller Projects
 - [x] Pick 1 or 2 Paper-cuts Topics

After prioritization meeting:

- [x] Create Projects issue (basic skeleton is fine) for each prioritized project if it's not already created.
- [x] Make sure Engineering and Design people assigned to projects.
- [x] Create sprint meta-issue
  - [x] Pin the issue.
  - [x] Update GitHub homepage
- [x] Communicate prioritization to a wide audience:
  - [x] internally: OC, OSC, OCF teams
  - [x] externally: Slack General channel, ...

### On Sprint scoping week (first week)

Each day:
- Make sure that scoping is happening, that team members speak to each others, are meeting each others
- Make sure that scoping is being documented 
- Make sure that scoping are properly written and can be presented on Friday

On Friday after demos:
 - [ ] Communicate specifications to a wider audience and ask for final feedback
