### ISSUE TITLE
[PROJECT] Recurring Expenses

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#5305]
## Overview 
Many users have recurring expenses that they need to submit at a regular interval. Some examples:
- All Open Collective employees need to submit their invoices each month for the same amount
- Many projects have recurring bills (hosting, domain, rent, etc). For online services, this need is now covered by virtual cards (but they're not available to all fiscal hosts).

## Ownership
**Owner:** @kewitz 

*Note: Project owner responsibilities include coordinating all the different people that need to contribute to the project, defining specs and goals, communicating project progress, being the point person for decisions, QA, documentation, and a plan for ongoing maintenance. If the project owner can't continue, they need to hand the role over to another person explicitly.*

## Prioritization

- Initially requested in https://github.com/opencollective/opencollective/issues/938
- Alternative to https://github.com/opencollective/opencollective/issues/3686
- Alternative / related to https://github.com/opencollective/opencollective/issues/1862

**Impact**
- Partially automating the repetitive invoicing process for people receiving payments through our platform.
- Making it easier/faster for a collective/organization to be invoiced at the beginning of the month.

**Alignment**
- https://github.com/opencollective/opencollective/issues/5141

**Effort**
This project should fit one sprint frame of our existing plan structure.

## Measuring success
- [ ] Number of expenses submitted based on RecurringExpenses
- [ ] Volume disbursed through RecurringExpenses
- [ ] Number of Collectives using RecurringExpenses through time

## Roadmap and Timeframe
1. Prototype: Recurring Expense based on Submit on Behalf flow and Expense.data fields.
2. Development: Create proper Data abstractions, Worker and update the Frontend following MVP specification.
3. Internal Test: Enabled for Open Collective collectives under feature flag.
4. Validation: Enabled for interested users. (Babel and more)
5. Release: Deprecation of feature flag.

## Technical MVP Specifications
- Add recurring Expense option on new Expense form, including necessary fields: Interval, End Date.
- First recurring Expense is immediately created and also creates the RecurringExpense record.
- Cron job will process RecurringExpense records and send the following Expenses as a Draft based on previous Expense for the author to review, update and submit.
- The recurring expense draft email contains a button to "Edit and Submit" and also one to "Delete Draft and Cancel Future Submissions"
- Draft recurring expense form contains "Delete Expense and Cancel Future Submissions" button

## Tasks
- [x] Design and UX
  - [x] Add recurring expense checkbox to existing create Expense flow
  - [x] Add recurring expense input fields (interval, end date) to existing create Expense flow
  - [x] Add "Cancel Recurring Expense" button to existing edit Draft Expense flow
  - [x] Implement Designed components
    - [x] Hidden behind feature flag on the Collective level
- [x] Data
  - [x] Create RecurringExpenses model
  - [x] Create associations between RecurringExpenses, Expenses, Collective
  - [x] Update "merge accounts" script to update RecurringExpenses
  - [x] Update "ban collectives" to delete RecurringExpenses
  - [x] Update "mark expense as SPAM" mutation to delete RecurringExpenses
- [ ] Worker
  - [x] Create daily cron job to process RecurringExpenses and draft necessary Expenses
  - [x] Draft new expenses based on last submitted expense related to this RecurringExpenses record
  - [x] Send email requesting author to edit/review Draft and submit
    - [ ] Include "Delete and Cancel Recurring Expense" button in the email 
- [x] Documentations
  - [x] Add a chapter on Recurring Expenses in the [Submitting Expenses page](https://docs.opencollective.com/help/expenses-and-getting-paid/submitting-expenses).

## Next steps

- [ ] create (and link) to metabase dashboard for success metrics
- [ ] Include "Delete and Cancel Recurring Expense" button in the email

**Comment by kewitz** [comment]
Concerns:
- People usually unsubscribe from email, so they might miss the recurring expense email.
  - User needs a place in the platform to see and finish the draft new Expenses.
  - **Decision**: Implement email-based MVP and after that implement "Pending Drafts" based on the "Pending Invitations" modal.
- Perhaps the DRAFT step should be optional.
  - After the implementation of templating to Expense fields we should move Expense straight to Pending.
- Collective admins should also be able to list and manage RecurringExpenses.

**Comment by piamancini** [comment]
W2
- [ ] Design Wireframe 
- [ ] Prototype using submit on behalf 
- [ ] Create recurring expenses data Models & associations

**Comment by piamancini** [comment]
- [ ] Wireframes for submit on behalf 
- [ ] worker (cron job)
- [ ] email template 
- [ ] stretch goal: implement front end & ship

**Comment by piamancini** [comment]
- [ ] record demo of email template 
- [ ] wrap up front end development 
- [ ] release under a collective level flag

**Comment by piamancini** [comment]
- [ ] test in engineering 
- [ ] cleaning up design prod file 
- [ ] implement front end tweaks 
- [ ] documentation 
- [ ] enable for more collectives after testing

**Comment by BenJam** [comment]
draft 🔥 update at https://opencollective.com/opencollective/updates/submit-expenses-using-your-own-currency

**Comment by Betree** [comment]
> draft fire update at https://opencollective.com/opencollective/updates/submit-expenses-using-your-own-currency

@BenJam This link appears to be for multi-currency (not recurring)

**Comment by aminakazi** [comment]
Final production-ready files can be [found here ](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/?node-id=16313%3A250158)

**Comment by alanna** [comment]
q?

**Comment by Betree** [comment]
@kewitz Should we close this since it's released publicly?

**Comment by Betree** [comment]
Feedback issue: https://github.com/opencollective/opencollective/issues/5671

**Comment by Betree** [comment]
Closing since this is now released
