### ISSUE TITLE
[Roadmap] 2022 Q2 Sprint 1 

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#5437]
## Context & Strategic Focus

Open Collective builds our platform in 6-week sprints, with a week-long break every two sprints to review our strategic objectives: 

- #5486 
- #5487 
- #5488 

If you'd like to know more about how we work check out [this document](https://www.figma.com/file/WJev8P6o4zS7NExfAPVhrg/Product-%26-Sprint-Process?node-id=0%3A1) and [this video explainer](https://www.loom.com/share/fd24bf7a664945e0ba577e91f93776bb). 

## Prioritisation

Every six weeks we [invite members of the team to share ideas](https://github.com/opencollective/opencollective/issues/5330) that are high impact and aligned with the strategic objectives. We discuss these ideas together as a team prior to running a [final prioritisation call](https://us06web.zoom.us/rec/share/hYr660OiNWJsrqn8nl5ELMl9I6X3QdiD56Wbg5r4pvOPS3CGxfeISRLtM8au3zFA.aMXlLRxdNypWaMAQ) where we commit to projects for the next sprint. 

During this process we noted:

- We should try to dedicate time in each sprint to improve our operations, marketing, experience and security and make an active decision not to do this especially if we have not dedicated time and effort to these things in a previous sprint. 
- We can make the decision to invest some time in a sprint to scope bigger projects for future sprints without dedicating a 'big project' slot to it initially
- We should give adequate time between MVP releases and follow-on projects to ensure that our MVP is hitting home before continuing to invest our time.
- The proposals submitted were very well aligned and communicated, and this makes the prioritisation process all the more difficult
- That we could easily have spent an entire sprint working on contributions and expense flows
- That we may wish to put some strategic focus on security, compliance and quality (i.e. errors) in a future sprint. 

When prioritising we found
- That our work on OAuth enables integrators like MetaGov to extend our platform that aligns with our strategic priorities (governance, growth) and such should be prioritised. 
- There was an overlap between improving bank transfer contributions and adding PayPal as a host, we chose Paypal as users can hook their bank details into this. 
- There were a set of issues related to our notifications that need to be scoped together so they can be prioritised later. 
- The work we have done on the search experience last sprint has left some aspects of the Open Collective site in a weird place, and we should fix those experiences (navbar)
- The work we're doing on experience and marketing (homepage, onboarding) are well-scoped and that we can continue to incrementally deliver these changes
- That we will dedicate time to address the biggest headaches for support, which are currently adding a second admin, and tracking expenses that are pending more information

## Roadmap and tracking 

Based on this discussion we decided to prioritise the following issues.  You can follow progress on each of the issues above [using our project board](https://github.com/orgs/opencollective/projects/5/views/20).

### Large Projects (4 weeks)

- #1660 (API/Governance)

### Small Projects (4 weeks) In order of priority

- #4829 (User experience)
- #5033 (including #4953) (Contributions and expenses)
- #3593 (Governance)

- #4356 (User experience)
- #5251 (Ops and administration)
- Scoping and designing a solution to #5195 (Governance)
- Scoping #4210 to prepare for future sprint (Contributions and expenses)
- Scoping solutions to #4699 and #5382 (to include and tackle #5368 and #3357) (Marketing, comm's and compliance) 
### Papercuts (half a day, pick up as available)

- #4518 (Ops and admin)
- #4689 (@flickz to lead development on this) (Marketing and comm's)
- #5325 (Contributions and expenses)
- #5360 (Contributions and expenses)
- #5422 (Community growth)
- #4165 (Community growth)
- #5436 (User experience)

## Things that we said no to 

- #3438 has good alignment, tiers are a mess, and the approach is reasonable. I'd happily reconsider prioritizing this but honestly I can't say there's anything in the above I would prefer this to.  
- #5410 virtual cards now account for 3% of our total transactions, we should prioritize this in a future sprint 
- #3106 (and non critical security issues in general) we _should_ tackle these issues as part of our general process. That we dont have time in the current scope of the sprint is an issue we should address. 
- #5245 #5372 we would rather review the host dashboard in its entirety than address the individual issues now.
- #2734, we chose to expand our PayPal services instead.
- #4221, #5020, #5222, #5429, #5183 are all contributions and expense quality fixes, and it felt like we had a good distribution of improvements in this area. 
- #4295, #5431 we should spend a sprint taking time to asses whether our MVPs are landing before continuing to work on these
- #3422 felt like it goes against our principles, the conversation continues in this thread. 
- #1738 has been a long running conversation and, once we've implemented oAuth for apps we could use parts of that code to offer oAuth for login. 

## Checklist

This sprint is being facilitated by  @benjam. 

After prioritization meeting:

- [x] Create/review Projects issue (basic skeleton is fine) for each prioritized project if it's not already created.
- [x] Make sure Engineering and Design people assigned to projects.
- [x] Create sprint meta-issue
  - [x] Pin the issue.
  - [x] Update GitHub homepage
- [x] Communicate prioritization to a wide audience:
  - [x] internally: OC, OSC, OCF teams
  - [x] externally: Slack General channel

scoping week (first week)
- [x] Make sure that scoping is happening, that team members speak to each others, are meeting each others
- [x] Make sure that scoping is being documented 
- [x] Make sure that scoping are properly written and can be presented on Friday

On Friday after demos:
 - [x] Communicate specifications to a wider audience and ask for final feedback

**Comment by fwolfst** [comment]
> If you'd like to know more about how we work check out [this document](https://www.figma.com/file/WJev8P6o4zS7NExfAPVhrg/Product-%26-Sprint-Process?node-id=0%3A1) and [this video explainer](https://www.loom.com/share/fd24bf7a664945e0ba577e91f93776bb).

figma link is outdated, its https://www.figma.com/file/uCwmTBwNC6Y9sronWds1TN/Sprints-processes?node-id=1101%3A68 now.

**Comment by payephyoeaung87** [comment]
> ## Context & Strategic Focus
> Open Collective builds our platform in 6-week sprints, with a week-long break every two sprints to review our strategic objectives:
> 
> * [[Strategic Focus] Simplification  #5486](https://github.com/opencollective/opencollective/issues/5486)
> * [[Strategic Focus] Communication #5487](https://github.com/opencollective/opencollective/issues/5487)
> * [[Strategic Focus] Interoperability  #5488](https://github.com/opencollective/opencollective/issues/5488)
> 
> If you'd like to know more about how we work check out [this document](https://www.figma.com/file/WJev8P6o4zS7NExfAPVhrg/Product-%26-Sprint-Process?node-id=0%3A1) and [this video explainer](https://www.loom.com/share/fd24bf7a664945e0ba577e91f93776bb).
> 
> ## Prioritisation
> Every six weeks we [invite members of the team to share ideas](https://github.com/opencollective/opencollective/issues/5330) that are high impact and aligned with the strategic objectives. We discuss these ideas together as a team prior to running a [final prioritisation call](https://us06web.zoom.us/rec/share/hYr660OiNWJsrqn8nl5ELMl9I6X3QdiD56Wbg5r4pvOPS3CGxfeISRLtM8au3zFA.aMXlLRxdNypWaMAQ) where we commit to projects for the next sprint.
> 
> During this process we noted:
> 
> * We should try to dedicate time in each sprint to improve our operations, marketing, experience and security and make an active decision not to do this especially if we have not dedicated time and effort to these things in a previous sprint.
> * We can make the decision to invest some time in a sprint to scope bigger projects for future sprints without dedicating a 'big project' slot to it initially
> * We should give adequate time between MVP releases and follow-on projects to ensure that our MVP is hitting home before continuing to invest our time.
> * The proposals submitted were very well aligned and communicated, and this makes the prioritisation process all the more difficult
> * That we could easily have spent an entire sprint working on contributions and expense flows
> * That we may wish to put some strategic focus on security, compliance and quality (i.e. errors) in a future sprint.
> 
> When prioritising we found
> 
> * That our work on OAuth enables integrators like MetaGov to extend our platform that aligns with our strategic priorities (governance, growth) and such should be prioritised.
> * There was an overlap between improving bank transfer contributions and adding PayPal as a host, we chose Paypal as users can hook their bank details into this.
> * There were a set of issues related to our notifications that need to be scoped together so they can be prioritised later.
> * The work we have done on the search experience last sprint has left some aspects of the Open Collective site in a weird place, and we should fix those experiences (navbar)
> * The work we're doing on experience and marketing (homepage, onboarding) are well-scoped and that we can continue to incrementally deliver these changes
> * That we will dedicate time to address the biggest headaches for support, which are currently adding a second admin, and tracking expenses that are pending more information
> 
> ## Roadmap and tracking
> Based on this discussion we decided to prioritise the following issues. You can follow progress on each of the issues above [using our project board](https://github.com/orgs/opencollective/projects/5/views/20).
> 
> ### Large Projects (4 weeks)
> * [oAuth support #1660](https://github.com/opencollective/opencollective/issues/1660) (API/Governance)
> 
> ### Small Projects (4 weeks) In order of priority
> * [[PROJECT] Improve our onboarding experience #4829](https://github.com/opencollective/opencollective/issues/4829) (User experience)
> * [Extend "Pay 100% of expense amount" to PayPal #5033](https://github.com/opencollective/opencollective/issues/5033) (including [PayPal payouts not considering payment processor fees #4953](https://github.com/opencollective/opencollective/issues/4953)) (Contributions and expenses)
> * [[PROJECT] Host can require minimum number of admins #3593](https://github.com/opencollective/opencollective/issues/3593) (Governance)
> * [Platform Navbar Design Enhancements #4356](https://github.com/opencollective/opencollective/issues/4356) (User experience)
> * [Provide a way to identify expenses that are pending additional info #5251](https://github.com/opencollective/opencollective/issues/5251) (Ops and administration)
> * Scoping and designing a solution to [Collective activity log #5195](https://github.com/opencollective/opencollective/issues/5195) (Governance)
> * Scoping [Enable new PayPal integration for all hosts #4210](https://github.com/opencollective/opencollective/issues/4210) to prepare for future sprint (Contributions and expenses)
> * Scoping solutions to [In-platform messaging #4699](https://github.com/opencollective/opencollective/issues/4699) and [In-OC app notification management #5382](https://github.com/opencollective/opencollective/issues/5382) (to include and tackle [Receipts for non-tax-deductible payments #5368](https://github.com/opencollective/opencollective/issues/5368) and [Add a page to manage email subscriptions #3357](https://github.com/opencollective/opencollective/issues/3357)) (Marketing, comm's and compliance)
> 
> ### Papercuts (half a day, pick up as available)
> * [Order ready to pay expenses by oldest first #4518](https://github.com/opencollective/opencollective/issues/4518) (Ops and admin)
> * [[PROJECT] New opencollective.com homepage #4689](https://github.com/opencollective/opencollective/issues/4689) (@flickz to lead development on this) (Marketing and comm's)
> * [Expense invited to Collective should default to Collective as payee #5325](https://github.com/opencollective/opencollective/issues/5325) (Contributions and expenses)
> * [Require address when creating new org as invoice expense payee #5360](https://github.com/opencollective/opencollective/issues/5360) (Contributions and expenses)
> * [Show Tags on a collective's page #5422](https://github.com/opencollective/opencollective/issues/5422) (Community growth)
> * [Move from "githubHandle" to "repositoryUrl" #4165](https://github.com/opencollective/opencollective/issues/4165) (Community growth)
> * [Sync `/search` Page with the Current Header and Filter Designs #5436](https://github.com/opencollective/opencollective/issues/5436) (User experience)
> 
> ## Things that we said no to
> * [Redesign the page to edit tiers #3438](https://github.com/opencollective/opencollective/issues/3438) has good alignment, tiers are a mess, and the approach is reasonable. I'd happily reconsider prioritizing this but honestly I can't say there's anything in the above I would prefer this to.
> * [Virtual Cards Edits #5410](https://github.com/opencollective/opencollective/issues/5410) virtual cards now account for 3% of our total transactions, we should prioritize this in a future sprint
> * [Message sent through contact form triggering gmail phishing warning #3106](https://github.com/opencollective/opencollective/issues/3106) (and non critical security issues in general) we _should_ tackle these issues as part of our general process. That we dont have time in the current scope of the sprint is an issue we should address.
> * [Move Export CSV to top of Export page #5245](https://github.com/opencollective/opencollective/issues/5245) [Host Reports and added funds #5372](https://github.com/opencollective/opencollective/issues/5372) we would rather review the host dashboard in its entirety than address the individual issues now.
> * [Enable recurring bank transfer contributions #2734](https://github.com/opencollective/opencollective/issues/2734), we chose to expand our PayPal services instead.
> * [Enabling update of bank account payout method #4221](https://github.com/opencollective/opencollective/issues/4221), [Improve validations when inviting expense payee #5020](https://github.com/opencollective/opencollective/issues/5020), [Mandatory fields not marked when inviting organization to submit an expense #5222](https://github.com/opencollective/opencollective/issues/5222), [Unable to cancel editing expense #5429](https://github.com/opencollective/opencollective/issues/5429), [Provide Payout Method and Account context when Approving/Paying Expenses #5183](https://github.com/opencollective/opencollective/issues/5183) are all contributions and expense quality fixes, and it felt like we had a good distribution of improvements in this area.
> * [[PROJECT] Search Experience Redesign #4295](https://github.com/opencollective/opencollective/issues/4295), [Feature: Manage pending Expenses and Charges #5431](https://github.com/opencollective/opencollective/issues/5431) we should spend a sprint taking time to asses whether our MVPs are landing before continuing to work on these
> * [Incognito payouts #3422](https://github.com/opencollective/opencollective/issues/3422) felt like it goes against our principles, the conversation continues in this thread.
> * [Allow usual username/mail + password login #1738](https://github.com/opencollective/opencollective/issues/1738) has been a long running conversation and, once we've implemented oAuth for apps we could use parts of that code to offer oAuth for login.
> 
> ## Checklist
> This sprint is being facilitated by @BenJam.
> 
> After prioritization meeting:
> 
> * [ ]  Create/review Projects issue (basic skeleton is fine) for each prioritized project if it's not already created.
> * [ ]  Make sure Engineering and Design people assigned to projects.
> * [x]  Create sprint meta-issue
>   
>   * [x]  Pin the issue.
>   * [x]  Update GitHub homepage
> * [x]  Communicate prioritization to a wide audience:
>   
>   * [x]  internally: OC, OSC, OCF teams
>   * [x]  externally: Slack General channel
> 
> scoping week (first week)
> 
> * [ ]  Make sure that scoping is happening, that team members speak to each others, are meeting each others
> * [ ]  Make sure that scoping is being documented
> * [ ]  Make sure that scoping are properly written and can be presented on Friday
> 
> On Friday after demos:
> 
> * [ ]  Communicate specifications to a wider audience and ask for final feedback

**Comment by payephyoeaung87** [comment]
I am responsible for my shortcomings.

**Comment by payephyoeaung87** [comment]
မင်္ဂလာပါခင်ဗျ

**Comment by payephyoeaung87** [comment]
Let me first apologize.

**Comment by payephyoeaung87** [comment]
Hello, Mr. BenJam, please give me some suggestions.
