### ISSUE TITLE
[PROJECT] Notifications and Attention Management

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#5501]
## Overview 
Notifications and attention management is not well-managed on Open Collective, as a result, users are simultaneously annoyed about receiving [too many low-value communications](https://github.com/opencollective/opencollective/issues/5382
) (collective updates) while important actions (approving an expense, responding to a comment on an invoice) are missed. 

## Problems statements

> [I'm in admin role on several organisations and collectives and the amount of OC emails I'm receiving is overwhelming](https://github.com/opencollective/opencollective/issues/5382)

> [I am very wary to send messages using the platform, instead preferring to move into email, because I will have no record of having sent a message, and might needlessly duplicate communications](https://github.com/opencollective/opencollective/issues/4699)

> [The majority of contributions to a host like OCF or GC are tax-deductible. The problem is, sometimes payments are in exchange for good and services. A charity cannot issue a tax deductible receipt for a non-deductible payment.](https://github.com/opencollective/opencollective/issues/5368)

>  [I want to be able to set custom text, ideally using smart templating capable of inserting data like the contributor's name, the amount, and other relevant information](https://github.com/opencollective/opencollective/issues/2682)

## Narrowing down the problem

There are a few areas here that need to looked at individually

- A lot of conversation around open collective happens outside of Open Collective, what kinds of conversations are happening and which of these conversations would we like to bring into the platform? Which notifications need to remain outside?
- There's no segregation or management of communication for end-users on Open Collective, as a result it's left to their email filters to filter out what's important.
- Where can we provide more feedback within the UX that we have today, to help users understand where they have activities/tasks awaiting. 
- Where do we have overlaps in features today that we might want to consolidate? (i.e. conversations vs. updates)
- There no customisation of communications generated by Open Collective, which aspects of communication should be customizable by end-users

## Previous efforts

This notifications management panel https://github.com/opencollective/opencollective/issues/3357 
Bundling contribution emails https://github.com/opencollective/opencollective/issues/2864

**Comment by Memo-Es** [comment]
Goals for Week 2:

 - [ ] Schedule the 2nd part of the notifications conversation, this time focused on categorizing types of notifications in a workshop-like activity

**Comment by Betree** [comment]
# Platform notifications summary

## In-app

| Notification                   | Audience                                 | Description                                                                                                    |
| ------------------------------ | ---------------------------------------- | -------------------------------------------------------------------------------------------------------------- |
| News posted on Open Collective | Logged in users                          | ![image](https://user-images.githubusercontent.com/1556356/166411560-ff9f4557-c027-4371-86ba-a7ec71f5ac0f.png) |
| Member invitation              | Logged in users with pending invitations | ![image](https://user-images.githubusercontent.com/1556356/166411390-90c28394-fa66-4e5d-9096-ec3a60f7e69b.png) |
| Ad banner on homepage          | Everyone                                 | ![image](https://user-images.githubusercontent.com/1556356/166411473-73cbe08f-e4ee-46bf-9472-2c98582aca13.png) |

## Emails

| Notification                                                                                                                                                                     | Audience                                                                                                                                                        | Description                                                                                   |
| -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------- |
| [Activated Collective As Host](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/activated.collective.as.host.hbs)                                 | Host admins                                                                                                                                                     |                                                                                               |
| [Activated Collective As Independent](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/activated.collective.as.independent.hbs)                   | Independent collective admins                                                                                                                                   |                                                                                               |
| [Announcement](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/announcement.hbs)                                                                 | All Users                                                                                                                                                       | Notification about updated TOS. Sent manually.                                                |
| [Archived Collective](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/archived.collective.hbs)                                                   | Collective admins                                                                                                                                               |                                                                                               |
| [Authorization Declined](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/authorization.declined.hbs)                                             | Financial contributors                                                                                                                                          | Warns about a failed payment (credit card expired, collective balance too low, etc.)          |
| [BackYourStack Dispatch Confirmed](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/backyourstack.dispatch.confirmed.hbs)                         | BackYourStack financial contributors                                                                                                                            | Probably deprecated                                                                           |
| [Collective Apply For Host](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.apply.for.host.hbs)                                       | Host admins                                                                                                                                                     |                                                                                               |
| [Collective Apply](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.apply.hbs)                                                         | Collective admins                                                                                                                                               | Confirms your application to fiscal host                                                      |
| [Collective Approved](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.approved.hbs)                                                   | Collective admins admins                                                                                                                                        | Collective application approved by fiscal host                                                |
| [Collective Approved Foundation](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.approved.foundation.hbs)                             | -                                                                                                                                                               | -                                                                                             |
| [Collective Approved The-Social-Change-Nest](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.approved.the-social-change-nest.hbs)     | -                                                                                                                                                               | -                                                                                             |
| [Collective Comment Created](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.comment.created.hbs)                                     | People subscribed to the thread                                                                                                                                 | Works for update comments, expense comments, conversations comments                           |
| [Collective Contact](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.contact.hbs)                                                     | Collective admins                                                                                                                                               | Someone contacted the collective using the contact form                                       |
| [Collective Conversation Created](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.conversation.created.hbs)                           | Collective admins                                                                                                                                               |                                                                                               |
| [Collective Created](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.created.hbs)                                                     | Collective admins                                                                                                                                               |                                                                                               |
| [Collective Created Opensource](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.created.opensource.hbs)                               | -                                                                                                                                                               |                                                                                               |
| [Collective Expense Approved For Host](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.expense.approved.for.host.hbs)                 | Host admins                                                                                                                                                     |                                                                                               |
| [Collective Expense Approved](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.expense.approved.hbs)                                   | Collective admins                                                                                                                                               |                                                                                               |
| [Collective Expense Created](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.expense.created.hbs)                                     | Collective admins                                                                                                                                               |                                                                                               |
| [Collective Expense Error For Host](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.expense.error.for.host.hbs)                       | Host admin                                                                                                                                                      | Scheduled expense payment failed                                                              |
| [Collective Expense Error](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.expense.error.hbs)                                         | Payee                                                                                                                                                           | Scheduled expense payment failed                                                              |
| [Collective Expense Invite Drafted](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.expense.invite.drafted.hbs)                       | Payee (invited)                                                                                                                                                 |                                                                                               |
| [Collective Expense Missing Receipt](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.expense.missing.receipt.hbs)                     | Collective admins                                                                                                                                               | Virtual card pending receipt                                                                  |
| [Collective Expense Paid For Host](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.expense.paid.for.host.hbs)                         | Host admins                                                                                                                                                     |                                                                                               |
| [Collective Expense Paid](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.expense.paid.hbs)                                           | Payee                                                                                                                                                           |                                                                                               |
| [Collective Expense Processing](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.expense.processing.hbs)                               | Payee                                                                                                                                                           |                                                                                               |
| [Collective Expense Recurring Drafted](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.expense.recurring.drafted.hbs)                 | Payee                                                                                                                                                           |                                                                                               |
| [Collective Expense Rejected](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.expense.rejected.hbs)                                   | Payee                                                                                                                                                           |                                                                                               |
| [Collective Frozen](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.frozen.hbs)                                                       | Collective admins admins                                                                                                                                        |                                                                                               |
| [Collective Member Created](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.member.created.hbs)                                       | Collective admins                                                                                                                                               | New financial contributor                                                                     |
| [Collective Monthly report](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.monthlyreport.hbs)                                        | Collective admins                                                                                                                                               |                                                                                               |
| [Collective New member](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.newmember.hbs)                                                | Invited collective admin                                                                                                                                        | Sent after the invitation gets accepted                                                       |
| [Collective Rejected](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.rejected.hbs)                                                   | Collective admins                                                                                                                                               | Host has rejected the application                                                             |
| [Collective Unfrozen](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.unfrozen.hbs)                                                   | Collective admins                                                                                                                                               |                                                                                               |
| [Collective Update Published](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.update.published.hbs)                                   | Update audience (core contributors, financial contributors and/or hosted collectives). In the future we want everyone to be able to subscribe to this one #1445 |                                                                                               |
| [Collective Virtualcard Added](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.virtualcard.added.hbs)                                 | Collective admins                                                                                                                                               |                                                                                               |
| [Collective Virtualcard Missing Receipts](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.virtualcard.missing.receipts.hbs)           | Collective admins                                                                                                                                               |                                                                                               |
| [Collective Virtualcard Suspended](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.virtualcard.suspended.hbs)                         | Collective admins                                                                                                                                               |                                                                                               |
| [Confirm-Guest-Account](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/confirm-guest-account.hbs)                                               | Guest profile admin                                                                                                                                             | Guest contributor clicks on "Verify account"                                                  |
| [Contribution Rejected](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/contribution.rejected.hbs)                                               | Financial contributor                                                                                                                                           | Usually for casino & other spammers, when collective admins reject/refund their contributions |
| [Deactivated Collective As Host](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/deactivated.collective.as.host.hbs)                             | Host admins                                                                                                                                                     |                                                                                               |
| [Event Reminder 1d](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/event.reminder.1d.hbs)                                                       | Event attendees                                                                                                                                                 |                                                                                               |
| [Event Reminder 7d](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/event.reminder.7d.hbs)                                                       | Event attendees                                                                                                                                                 |                                                                                               |
| [Fund Approved Foundation](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/fund.approved.foundation.hbs)                                         | Collective admins                                                                                                                                               |                                                                                               |
| [Fund Created Foundation](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/fund.created.foundation.hbs)                                           | Collective admins                                                                                                                                               |                                                                                               |
| [Host Application Contact](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/host.application.contact.hbs)                                         | Collective admins                                                                                                                                               | Host has replied to an application by sending a message (from the admin dashboard)            |
| [Host Report](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/host.report.hbs)                                                                   | Host admins                                                                                                                                                     |                                                                                               |
| [Member Invitation](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/member.invitation.hbs)                                                       | Invited member                                                                                                                                                  |                                                                                               |
| [Onboarding Day21 No Twitter](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/onboarding.day21.noTwitter.hbs)                                    | Collective admins                                                                                                                                               |                                                                                               |
| [Onboarding Day2 Foundation](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/onboarding.day2.foundation.hbs)                                     | Collective admins                                                                                                                                               |                                                                                               |
| [Onboarding Day2](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/onboarding.day2.hbs)                                                           | Collective admins                                                                                                                                               |                                                                                               |
| [Onboarding Day2 Opensource](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/onboarding.day2.opensource.hbs)                                     | Collective admins                                                                                                                                               |                                                                                               |
| [Onboarding Day2 Organization](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/onboarding.day2.organization.hbs)                                 | Collective admins                                                                                                                                               |                                                                                               |
| [Onboarding Day35 Active](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/onboarding.day35.active.hbs)                                           | Collective admins                                                                                                                                               |                                                                                               |
| [Onboarding Day35 Inactive](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/onboarding.day35.inactive.hbs)                                       | Collective admins                                                                                                                                               |                                                                                               |
| [Onboarding Day3 Foundation](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/onboarding.day3.foundation.hbs)                                     | Collective admins                                                                                                                                               |                                                                                               |
| [Onboarding Day3](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/onboarding.day3.hbs)                                                           | Collective admins                                                                                                                                               |                                                                                               |
| [Onboarding Day3 Opensource](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/onboarding.day3.opensource.hbs)                                     | Collective admins                                                                                                                                               |                                                                                               |
| [Onboarding Day7](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/onboarding.day7.hbs)                                                           | Collective admins                                                                                                                                               |                                                                                               |
| [Onboarding No expenses](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/onboarding.noExpenses.hbs)                                              | Collective admins                                                                                                                                               |                                                                                               |
| [Onboarding No expenses Opensource](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/onboarding.noExpenses.opensource.hbs)                        | Collective admins                                                                                                                                               |                                                                                               |
| [Onboarding No updates](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/onboarding.noUpdates.hbs)                                                | Collective admins                                                                                                                                               |                                                                                               |
| [Order Crypto Processing](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/order.crypto.processing.hbs)                                           | Financial contributor                                                                                                                                           |                                                                                               |
| [Order New Pending financial contribution](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/order.new.pendingFinancialContribution.hbs)           | Host admins                                                                                                                                                     |                                                                                               |
| [Order Processing](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/order.processing.hbs)                                                         | Financial contributor                                                                                                                                           | Bank payments instructions                                                                    |
| [Order Reminder Pending financial contribution](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/order.reminder.pendingFinancialContribution.hbs) | Financial contributor                                                                                                                                           |                                                                                               |
| [Organization Created](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/organization.collective.created.hbs)                                      | Organization admins                                                                                                                                             |                                                                                               |
| [Organization New member](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/organization.newmember.hbs)                                            | Organization admins                                                                                                                                             |                                                                                               |
| [Payment Creditcard Confirmation](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/payment.creditcard.confirmation.hbs)                           | Financial contributor                                                                                                                                           | Payment requires a confirmation (3D secure)                                                   |
| [Payment Creditcard Expiring](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/payment.creditcard.expiring.hbs)                                   | Financial contributor                                                                                                                                           | Credit card will expire soon                                                                  |
| [Payment Failed](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/payment.failed.hbs)                                                             | Financial contributor                                                                                                                                           | Payment attempt failed                                                                        |
| [Subscription Canceled](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/subscription.canceled.hbs)                                               | Financial contributor                                                                                                                                           |                                                                                               |
| [Tax-Form-Request](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/tax-form-request.hbs)                                                         | Payee                                                                                                                                                           |                                                                                               |
| [Thankyou](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/thankyou.hbs)                                                                         | Financial contributor                                                                                                                                           | Financial contribution succeeded (either a new one or a recurring payment processed)          |
| [Thankyou Foundation](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/thankyou.foundation.hbs)                                                   | -                                                                                                                                                               | -                                                                                             |
| [Thankyou Fr](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/thankyou.fr.hbs)                                                                   | -                                                                                                                                                               | -                                                                                             |
| [Thankyou Opensource](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/thankyou.opensource.hbs)                                                   | -                                                                                                                                                               | -                                                                                             |
| [Thankyou Wwcode](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/thankyou.wwcode.hbs)                                                           | -                                                                                                                                                               | -                                                                                             |
| [Ticket Confirmed](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/ticket.confirmed.hbs)                                                         | Event attendee                                                                                                                                                  |                                                                                               |
| [Ticket Confirmed Fearlesscitiesbrussels](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/ticket.confirmed.fearlesscitiesbrussels.hbs)           | -                                                                                                                                                               |                                                                                               |
| [Ticket Confirmed Open-2020](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/ticket.confirmed.open-2020.hbs)                                     | -                                                                                                                                                               |                                                                                               |
| [User Gift Card Claimed](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/user.card.claimed.hbs)                                                  | Individual                                                                                                                                                      |                                                                                               |
| [User Gift Card Invited](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/user.card.invited.hbs)                                                  | Individual                                                                                                                                                      |                                                                                               |
| [User Change email](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/user.changeEmail.hbs)                                                        | Individual                                                                                                                                                      | Link to confirm email change                                                                  |
| [User Monthly report](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/user.monthlyreport.hbs)                                                    | Individual                                                                                                                                                      |
| [User New Token](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/user.new.token.hbs)                                                             | Individual                                                                                                                                                      | Sign in/up email                                                                              |
| [User Yearly report](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/user.yearlyreport.hbs)                                                      | Individual                                                                                                                                                      |
| [Virtualcard Requested](https://github.com/opencollective/opencollective-api/blob/main/templates/emails/virtualcard.requested.hbs)                                               | Host admins                                                                                                                                                     |

**Comment by iamronen** [comment]
Thank you for that @Betree  :)
1. How did you generate this list?
2. Is it possible to generate for it a metabase view similar to the one you made for activities?
3. Is there a traceable relationship/mapping between activities and email notifications?

**Comment by Betree** [comment]
> 1. How did you generate this list?

For In-App, I just listed the all the places I could think about - and can't guarantee I haven't forget some.

For emails, I went to https://github.com/opencollective/opencollective-api/tree/main/templates/emails, listed all the files, filtered out the unused ones then formatted everything into a table and added some metadata (mainly, the email targets) by looking at the code & the contents of the emails.

> 2. Is it possible to generate for it a metabase view similar to the one you made for activities?

Metabase is mostly dedicated to query the database, these templates in the codebase. We could hack something, but I'm not sure to understand the benefit of having this in metabase, or what additional data we would get from it?

> 3. Is there a traceable relationship/mapping between activities and email notifications?

Many [activity types](https://github.com/opencollective/opencollective-api/blob/main/server/constants/activities.js#L12) can be linked to their [email notification](https://github.com/opencollective/opencollective-api/tree/main/templates/emails) using the name, example: `collective.approved` => `templates/emails/collective.approved.hbs`.

But other conditions to choose the right template are often applied from https://github.com/opencollective/opencollective-api/blob/main/server/lib/notifications.js. It's a verbose code that's as old as the platform and that we'd like to revamp at some point as it creates unnecessary complexity.

**Comment by iamronen** [comment]
I've assimilated the information gathered so far in this spreadsheet:
https://docs.google.com/spreadsheets/d/1XcAhQbVAh7KvgAAR6H2aHEpzl1Ey50G7n1kmn_nr9s0/edit?usp=sharing

The Activities table is currently sorted in descending order: from activities with the most instances in the last 60 days to activities with the least instances.

I have been playing with a "attention vocabulary" that currently includes:
- Curious: agent doesn't need to know but can subscribe if interested
- Sensing: agent doesn't need to know but can sense into the space by being attentive
- Acting: agent is called to take action
- Confirming: agent may expect and may need to be informed

I've been going over the events and trying to apply this vocabulary to them ... everyone is welcome to jump in and shape this thinking.

**Comment by Memo-Es** [comment]
## Notifications categorization session summary:

- We based the discussion on [this commen](https://github.com/opencollective/opencollective/issues/5501#issuecomment-1115878477)t by @Benjamin Piouffle In the issue, listing all notifications, audiences, and description
- @iamronen crunched the info in this [spreadsheet](https://docs.google.com/spreadsheets/d/1XcAhQbVAh7KvgAAR6H2aHEpzl1Ey50G7n1kmn_nr9s0/edit?usp=sharing) to add more insights (‘Triggered by,’ ‘Attention levels,’’ Who receives an email?’)
- During the discussion w talked about the best way to make sense of all the data around notifications. It makes sense to have a better overview of the emails we send
- Some keywords to define this structure are: 
  - Activity/Business event e.g., ‘collective.member.created’
  - Trigger or trigger agent, e.g., ‘Collective admin’ or ‘Day 2 after creating collective.’
  - Notifications. Right now, materialized in emails [(Full list here)](https://docs.google.com/spreadsheets/d/1XcAhQbVAh7KvgAAR6H2aHEpzl1Ey50G7n1kmn_nr9s0/edit#gid=1818914790&range=A1)
  - Notifications type. Sort of like “tagging,” bundling similar notifications, e.g., ‘Expenses notifications.’'
  - Recipients. Who receives a notification
- We agree that notifications settings should be managed by each user, with an interface [similar to this one](https://github.com/opencollective/opencollective/issues/3357)
- Next steps are: Complement the spreadsheet with a visualization that helps us define the rules and mechanics of these notifications. [Figma file to be updated](https://www.figma.com/file/iBmRm8wTs7ymsPNaOgsWRW/Notifications-Categorization?node-id=2%3A37)

[🎥 Recording in around ](https://around.co/playback/0548d572-24e2-4a5a-afd0-abaa55c94c68?s=myMeetingRecordings&sharedKey=e331195f-e42b-49e1-9182-fdd1309709a6)

cc @BenJam

**Comment by BenJam** [comment]
Annoyingly I can find the one presentation with the competitor analysis so I'm rebuilding my analysis of how others manage notifications

## GitHub
 
I worked on GitHub's notification service, at the moment it's pretty much as I left it with some general customisation and per-product customisation all in one page. Users can get an overview of where they get notifications from specifically in the '/watching' area and can manage notifications for a specific repository, team or org on entity pages:

| Notification settings | Subscription management | per repo management | granular config | 
| --- | --- | --- | --- | 
|  ![Screenshot 2022-05-13 at 13 34 14](https://user-images.githubusercontent.com/158833/168284382-adc37a9f-71e6-4666-bedf-2abc2b7b4a15.png) | ![Screenshot 2022-05-13 at 13 36 50](https://user-images.githubusercontent.com/158833/168284515-553f62f1-d4e1-41b4-83af-653fa9049271.png) | ![Screenshot 2022-05-13 at 13 37 43](https://user-images.githubusercontent.com/158833/168284683-73e54e29-66a0-4ac9-b734-fd53e5611c60.png) | ![Screenshot 2022-05-13 at 13 37 47](https://user-images.githubusercontent.com/158833/168284716-a3981cfa-e0f3-4798-ae37-2abde1d787e0.png) |

## GitLab

Notifications can be managed at a 'global' level, project or 'group'. Within each of these areas you can decide what level of notifications you want to received (watch, participate, mention, disabled), you can further customise these settings to individual event types:
| Settings | Broad customisation | Detailed customisation | In project/group |
| --- | --- | --- | --- | 
| ![Screenshot 2020-10-16 at 15 48 39](https://user-images.githubusercontent.com/158833/168280821-fbf07cae-46fa-4c57-8c47-a73d33c34716.png) | ![Screenshot 2020-10-16 at 15 48 51](https://user-images.githubusercontent.com/158833/168280866-952c1150-f90f-4d53-984a-fd8a7eb0af4f.png) | ![Screenshot 2020-10-16 at 15 49 16](https://user-images.githubusercontent.com/158833/168280905-45c9df9d-ad7c-422c-8aab-03c0af1d25c5.png) | ![Screenshot 2020-10-16 at 15 53 21](https://user-images.githubusercontent.com/158833/168281017-834c3abf-8167-4755-9bc4-1117a023e882.png) | 

## Bitbucket

BitBucket follows the pattern established by GitHub, using a similar watch/participating/ignore pattern with some additional functionality to further customise what to be notified about (this was later rolled into GitHub by my team). I like that their settings provides an overview of what you're subscribed to i.e. you are watching 40 repositories. Witha. quick management interface.

| notification settings | management | custom settings | 
| --- | --- | --- | 
| ![Screenshot 2020-10-16 at 15 56 38](https://user-images.githubusercontent.com/158833/168281823-2a779f65-8b5a-4b1f-8b49-86671ddb9420.png) | ![Screenshot 2020-10-16 at 15 57 03](https://user-images.githubusercontent.com/158833/168281895-6621eb66-db45-438b-99bf-c41f6429c17e.png) | ![Screenshot 2020-10-16 at 15 58 21](https://user-images.githubusercontent.com/158833/168281965-98c53bee-4656-449f-9acc-c01172c340f4.png) | 

## Slack

Slack has a simple approach to managing notifications by channel/device:

| Notification settings | in channel settings |
| --- | --- |
| ![Screenshot 2020-10-16 at 16 28 56](https://user-images.githubusercontent.com/158833/168283015-57d25acb-4439-4c34-b748-dfae3bd250b7.png) | ![Screenshot 2020-10-16 at 16 27 51](https://user-images.githubusercontent.com/158833/168283321-042369fb-0758-452a-ace8-3a756868fd43.png) | 

## Teams

MSFT Teams includes a lot of per-channel features 

| notification settings | device customisation | channel customisation |
| --- | --- | --- | 
| ![Screenshot 2020-10-16 at 16 33 45](https://user-images.githubusercontent.com/158833/168283526-d0cdc163-5c43-41bd-ab7e-3a9745aec791.png) | ![Screenshot 2020-10-16 at 16 33 45](https://user-images.githubusercontent.com/158833/168283616-c100d350-0e93-4005-83d6-ea05c66c8093.png) | ![Screenshot 2020-10-16 at 16 36 29](https://user-images.githubusercontent.com/158833/168283749-28e40f73-b42c-4d86-994b-ce1281809858.png) |

**Comment by BenJam** [comment]
- [ ] possibly also scope out a roadmap of focus areas to look at over the coming sprints
- [ ] @Memo-Es looking at a visual classification system for notifications as they are today (vs. potential ideal path)

**Comment by BenJam** [comment]
I've just updated the issue here with some future focus areas and I've come to the conclusion, for the moment at least, that *focussing on and improving our use of email will be the least effort an biggest benefit for our users*. 

I do not think that we should be implementing a generic messaging system within Open Collective, replicating the view that users have _today_ in their email inboxes. Instead we should improve what we have now (email) and provide proper prompts for users when there are actions that they need to take that are relevant (small audience) and timely (inaction has a negative impact on others). 

With that in mind I will propose that we make some quick fixes to email-based communication:

- [ ] Event tickets should send an event receipt, not a contribution receipt
- [ ] send appropriate receipts #5368 for non tax deductible *purchases*
- [ ] Allow admins to set a specific email address for contact requests #2263
- [ ] [include email to host admins when contacting a pending collective](https://github.com/opencollective/opencollective/issues/4699#issuecomment-1041527950)

and start to tackle #3357 by

- [ ] introducing one overall setting (maybe essential, recommended, all)
    - ESSENTIAL (payment receipts, payouts, card payments, actions)
    - RECOMMENDED (confirmations of actions taken by others, platform drip onboarding) 
    - ALL (inc updates and conversations)*

**Comment by piamancini** [comment]
Dev / Product meet about how templates work and assess impact @BenJam

**Comment by natehn** [comment]
Not sure if this is the right place, but I wanted to throw in a notification that I would like as a Host Admin: https://github.com/opencollective/opencollective/issues/5652

**Comment by Betree** [comment]
Some admins would like to receive an email whenever there's a new contribution: https://github.com/opencollective/opencollective/issues/5682

**Comment by Memo-Es** [comment]
Q2S2 Update (Week 6) 

 - [ ] Write up a summary of what's next

**Comment by kaylarep** [comment]
apologies if this isn't helpful, would it be possible to give a user the option to batch all their notifications into a single email of 'Daily Summary of Activity on Open Collective' - to get 1 email per day, with all that's days notifications (the one's they enabled) together? Perhaps divided into sections, either by `Notification Type` (e.g. Expense Approvals, Pending Invitations etc.) or by `Collective/Host` , or perhaps `Essential` `Recommended` `All`.

like letting them have the options of receiving singular notifications or batched summaries.

**Comment by Betree** [comment]
Feedback issue for the Notification Settings already implemented: https://github.com/opencollective/opencollective/issues/5867

We'd like to iterate on the blocking parts of the projects (bugs) quickly to get to a position where we can release it for everyone.

**Comment by Betree** [comment]
I stumbled upon https://novu.co, an open-source notification management system. It seems quite popular, and the features are very well aligned with the goals we've been discussing:
- Support for multiple channels (inline on the website, email, slack, etc)
- Tracking for whether a notification has been viewed or not
- Digests (bundle multiple notifications in a single email)
- Priority management (define which notifications are urgent)
- API for managing user preferences (subscribe/unsubscribe)
- Internationalization
- Monitoring

**Comment by Betree** [comment]
From @kaylarep:
![image](https://user-images.githubusercontent.com/64920686/194063208-81f535ea-da79-408f-83f6-1555fc13b471.png)

**Comment by kaylarep** [comment]
From Mike:
> Fiscal hosts should also have front-end visibility to anyone in their communication list who has unsubscribed from communications as this is the only targeted way that we can actually reach admins across 400 projects and other methods that I have tested such as YAMM are inadequately scalable solutions.

**Comment by kaylarep** [comment]
Collectives should **not** be able to unsubscribe from their host’s updates - this is the main, most reliable channel for a Fiscal Host to contact/send important updates to their hosted Collectives. (and perhaps the only channel where we KNOW that hosted collectives definitely engage with
