### ISSUE TITLE
[Roadmap] Sprint Facilitation Checklist: Q2S1 -> Q2S2

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#5626]
### During previous Sprint

- [x] Launch prioritization discussion https://github.com/opencollective/opencollective/issues/5496

### On previous Sprint closing week (last week)

- [x] Schedule prioritization meeting

In prioritization meeting:

 - [x] Pick 4 to 6 Projects
   - [x] Pick 2 to 4 regular Projects
   - [x] Pick 2 to 4 smaller Projects
 - [x] Pick 3 to 5 Paper-cut Issues

After prioritization meeting:

- [x] Create Projects issue (basic skeleton is fine) for each prioritized project if it's not already created.
- [x] Create project board for the sprint
- [x] Make sure Engineering and Design people assigned to projects.
- [ ] Create sprint meta-issue
  - [ ] Pin the issue.
  - [ ] Update GitHub homepage
- [ ] Communicate prioritization to a wide audience:
  - [ ] internally: OC, OSC, OCF teams
  - [ ] externally: Slack General channel, ...

### On Sprint scoping week (first week)

Each day:
- Make sure that scoping is happening, that team members speak to each others, are meeting each others
- Make sure that scoping is being documented 
- Make sure that scoping are properly written and can be presented on Friday

On Friday after demos:
 - [ ] Communicate specifications to a wider audience and ask for final feedback
