### ISSUE TITLE
[Roadmap]  2022 Q2 Sprint 2

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#5666]
## Context & Strategic Focus

Open Collective builds our platform in 6-week sprints, with a week-long break every two sprints to review our strategic objectives: 

- #5486 
- #5487 
- #5488 

If you'd like to know more about how we work check out [this document](https://www.figma.com/file/WJev8P6o4zS7NExfAPVhrg/Product-%26-Sprint-Process?node-id=0%3A1) and [this video explainer](https://www.loom.com/share/fd24bf7a664945e0ba577e91f93776bb). 

## Prioritisation

Every six weeks we [invite members of the team to share ideas](https://github.com/opencollective/opencollective/issues/5330) that are high impact and aligned with the strategic objectives. We discuss these ideas together as a team prior to running a [final prioritisation call](https://us06web.zoom.us/rec/share/hYr660OiNWJsrqn8nl5ELMl9I6X3QdiD56Wbg5r4pvOPS3CGxfeISRLtM8au3zFA.aMXlLRxdNypWaMAQ) where we commit to projects for the next sprint. 

We also run a poll to inform the process you can see the results here:

![Screen Shot 2022-06-01 at 11 44 15 AM](https://user-images.githubusercontent.com/3671070/173815972-11250914-55bc-4243-8509-ee88bcdd93ea.png)
![Screen Shot 2022-06-01 at 11 43 33 AM](https://user-images.githubusercontent.com/3671070/173815982-5cabd645-2189-4356-9a33-f82bfd38d538.png)

## Roadmap and tracking 

Based on this discussion we decided to prioritise the following issues.  You can follow progress on each of the issues above [using our project board](https://github.com/orgs/opencollective/projects/5/views/20).

### Large Projects (4 weeks)

- #3357 Email Notification Management (Simplification / Communication)
- #1660  [Comment](https://github.com/opencollective/opencollective/issues/1660#issuecomment-1151326616) (Interoperatibility)

### Small Projects (4 weeks)

Shaping and MVP building of: 
- #5631 (User experience / Community Growth) 
- #5368  (Compliance)  
- #2682 (Simplification, User Experience)
- #5560 (User Experience)

Designing of:
- #5195  (Governance)

Development of:
-  #5645 (OSC Onboarding)
 
### Papercuts (half a day, pick up as available)

- #4953 (PayOuts)
- #4360 (Money Management / User experience)
- #4165 (Community Growth)
- #3106  (Notifications / Email Management)
- #3875  (Admin / Ops)
- #5516  (OC EU Admin)

## Checklist

This sprint is being facilitated by  @piamancini. 

After prioritization meeting:

- [x] Create/review Projects issue (basic skeleton is fine) for each prioritized project if it's not already created.
- [x] Make sure Engineering and Design people assigned to projects.
- [x] Create sprint meta-issue
  - [x] Pin the issue.
  - [x] Update GitHub homepage
- [x] Communicate prioritization to a wide audience:
  - [x] internally: OC, OSC, OCF teams
  - [ ] externally: Slack General channel

scoping week (first week)
- [x] Make sure that scoping is happening, that team members speak to each others, are meeting each others
- [x] Make sure that scoping is being documented 
- [x] Make sure that scoping are properly written and can be presented on Friday

On Friday after demos:
 - [x] Communicate specifications to a wider audience and ask for final feedback
