### ISSUE TITLE
Onboarding flow - Find a host

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#5672]
## Who is your user?
 - Newly registered Collective admins wanting to find a host

## What are they trying to achieve?
 - Start their financial activities (fundraising and paying expenses) as soon as possible and with little hassle

_When I create a Collective, I want to find the right way to manage my finances, so I can not worry about paperwork_

## How are they currently doing this?
Browsing using the search page, receive invitations/recommendations

## How well understood is this problem?
The research project is documented at #4829 

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [ ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

## Tasks
 - [ ] Get rid of the "For open-source/any community step."
 - [ ] https://github.com/opencollective/opencollective/issues/5628
 - [ ] Implement https://github.com/opencollective/opencollective/issues/4240

**Comment by iamronen** [comment]
Hey @Memo, here are some initial thoughts/reflections/questions to flesh out this need.

## 1: When ... I Want ... So I can 
You stated:
> When I create a Collective, I want to find the right way to manage my finances, so I can not worry about paperwork

re: When
- is this when I create a collective or when I decided that I want to join a fiscal host?
- do I already know what fiscal hosting is, or am I first trying to figure that out?

re: I Want
- do people really want to "manage their finances"? I suspect, that, given the possibility, most people don't want to have to manage their finances at all and would prefer to have someone else do it for them.
- if someone has setup a collective and looking for a fiscal host I think **what they really want is to be able to receive contributions and spend money on the work they want to do** ... and in order to do that they need someone else to help them with the legalities 
- am I looking a "right way to manage my finances" or am I looking for the **right people** to help me?  

re: So I Can
 - generally, if you want to focus on a concern, maybe better to address the ease that comes from it being addressed so instead of "not worry" something like "So I can feel confident that I have the legal and financial backing to focus on the work I want to do" 
 - specifically, I think that in this case there is a more specific outcome "So I can begin to fund raise for the collective." 

## 2: What does the information landscape look like?
 - possible query:  number of hosts per location
 - this may help us understand what kind of challenge are we dealing with - do most locations have one or two hosts or 10-20 hosts? that will help us better understand what users may be facing and how we can help them navigate the choice

## 3: Comparing fiscal hosts
This may be a bit preemptive (before seeing the results of 2 above)  but assuming the user really is facing a challenge of choosing from a list of fiscal hosts then they are facing two challenges:
1. How do I compare hosts - what should I be looking for?
2. Having learned what I should be looking for, how do I narrow down the list of hosts to one or two best options.

The designs I saw in  #4829  defaulted to our familiar "cards" view which is not ideal for comparison. I would experiment with a list view where it is easier to compare hosts with metric such as:
 - Fee
 - Average payment processing time
 - Total money managed in the previous fiscal year
 - number of expenses paid during the last 30 days
 - sum of expenses paid during the last 30 days 
 - who are the people who are going to help me with accounting - icons of the team (to give a sense of how many there are (is it just one or two people, or is this an established team), hover over each for a modal small profile  -  with possibility to link each of them to an extended personal profile 

A list view also serves as a subtle educational tool: the columns expose to me what I can and should be looking for. This is more difficult to grasp in the "cards" view.

## 4: Short List
With a list mechanism it can be possible, as I am browsing the list, to select candidates to make a short list of fiscal hosts that appeal to me and then to act on those.

## 5: What can this look like from the side of the Fiscal Host?
 - Is there a possibility to also drive this process from the host side? 
 - What if I (an admin of a collective seeking a fiscal host) could indicate "I am looking for a host" and the platform could "magically" respond to me with invitations to relevant hosts (unburdening me from "the search")? 
 - Can we gather enough information from the collective to start with a list of "proposed hosts" instead of a blank search?
 - Can we let relevant hosts know about a potentially matching collective and enable them to send out an invitation to the collective?

**Comment by BenJam** [comment]
/me leans in. there's possibly also a fair amount of context in the broader #4829 topic as this is a discrete piece of work that started from there.

**Comment by BenJam** [comment]
just trying to clear up some of these questions @iamronen:

> is this when I create a collective or when I decided that I want to join a fiscal host?

this is at the point that the user decides they want to accept money, the promo is 'who is going to hold you money' and (to your next question) their is some explanation but arguably not as much as there should be. 

> do people really want to "manage their finances"? 

This look like it's couched predominantly as 'accepting contributions' [in the design](https://github.com/opencollective/opencollective/issues/4240#issuecomment-842742076) which I think is a good, practical and understandable context. 

> do most locations have one or two hosts or 10-20 hosts? 

There's a problem here that has been discussed somewhat but perhaps not to the degree that we have an approach: it might be easy to describe where the host is based, but it is very difficult to describe (and provide the freedom to a host to describe) the areas in which they can operate. 

For instance, Open Source Collective can work in any country that's not embargoed by the US but is based in CA, USA, Open Collective EU supports projects operating in the EU but is based in Brussels. Open Collective Foundation is the easy case of based in and only operating in the US. Really what we need here is a region(s) type system. This might be the technical complexity we need to enable collectives to find a host that's operating in a territory they are. 

> Comparing fiscal hosts
> The designs I saw in https://github.com/opencollective/opencollective/issues/4829 defaulted to our familiar "cards" view which is not ideal for comparison. I would experiment with a list view.

I think that's a fair comment. It's possible to compare a small number (and honestly, there are probably a small number right now) but I think it's fair to test this against a more tabulated view. I would perhaps ask collectives what they're looking for in a host rather than guess but I can see some of the suggestions being helpful if there any many choices. 

> Short List

It would be great to have ea problem that requires this solution, but I don't think we're there. 

> Is there a possibility to also drive this process from the host side?
I think the key here is that the process we have today starts with the collective, and maybe we should solve that first. 

> Can we gather enough information from the collective to start with a list of "proposed hosts" instead of a blank search?

This sounds like a good option, maybe we could pre-fill some of the search criteria based on what we already know about the collective? (country and maybe denomination?).

> Can we let relevant hosts know about a potentially matching collective and enable them to send out an invitation to the collective?

again this kinda feels like it's not leaning into the approach we have today. Fine, we could reconisder that, but it's a bigger project and I would (personally) prefer to lean into what we have.

**Comment by BenJam** [comment]
By way of an update, I think @Memo-Es's original plan was to revisit the design for this and write a pitch. Having looked at this I think we should:

- ensure that we continue to consider this project in the context of the larger onboarding https://github.com/opencollective/opencollective/issues/4829 
- look again at the plan for this project and the next steps https://github.com/opencollective/opencollective/issues/4829#issuecomment-1148103264 
- involve engineering in the scoping work for this and other projects in that remit.

I think the goal should be to have a program of work that we're all happy to get started on next sprint.

**Comment by BenJam** [comment]
- [ ] @Memo-Es and @BenJam take a look at future pitches

**Comment by BenJam** [comment]
- [ ] @Memo-Es and @BenJam take a look at future pitches

**Comment by Betree** [comment]
Clarifications from the call with @hdiniz @Memo-Es:

- Featured hosts are the ones recommended based on the category + location. They may not necessarily be internal hosts.
- Verified hosts = what we currently call trusted hosts in the code
- The category is to be clarified with the rest of the team, but likely to be an editorial choice on our side that hosts can opt into by adding some specific tags to their profile.

Engineering will wait on the design flush to start implementation.

**Comment by iamronen** [comment]
thank you for the signal @Betree 

My understanding is different:
 - The entire window is filtered for category + location
 - The hosts in the top section are our 1st party hosts
 - The hosts in the second section are the trusted hosts
 - The hosts in the third section are the rest
 
attn @toomuchinformation 
attn @carolineawoolard for clarifications around terminology we wish to use here.

**Comment by carolineawoolard** [comment]
Happy to hop on a call about this or to join a demo / workshop space to
discuss.

**Comment by Betree** [comment]
For this week:
- [ ] https://github.com/opencollective/opencollective/issues/6501
- [ ] Kickoff implementation of the new page

**Comment by BenJam** [comment]
closing as i think all the issues mentioned here are now resolved (and looks great). Thanks to everyone who worked on this ✌️

![Screenshot 2023-11-10 at 13 44 40](https://github.com/opencollective/opencollective/assets/158833/29c3d109-29bd-4354-aa92-3bd6d71f240a)
