### ISSUE TITLE
Contribution flow improvements [Campaign]

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#5732]
## Overview

We started by prioritizing this issue #4893 and split that issue into 2:
 - A backend solution that helps us improve the URL capabilities of the contribution flow #5631 
 - And research involving users to surface more about what communities experience currently using our contribution features, documented here: https://docs.google.com/document/d/1GrDflqVywY8EubF24fFLPtLSR7K56YpLSVn8wDd9cKQ/edit?usp=sharing

---

This issue aims to track progress with the contribution flow on all fronts and provide an overall context for these different projects. We performed a research phase first with calls with Collective admins and Fiscal Host admins. The results of this phase helped us propose a list of projects to improve the contribution flow in the short and mid-term.

### Issues identified related to the contribution flow:
**Sponsor organizations trying to contribute wrongly create individual accounts while contributing.**
* Easier' sharing' feature
* Sponsor tiers (Only for organizations)
* Better options to customize tiers

**Collective admins need a better way to share the contribution flow with their communities.**
* Share links with specific amounts/periodicity

**There is no clear way for Collective admins to communicate the data from contributions to their communities. That data would mean an important leverage point to legitimate their efforts with their current contributors + get new ones**
* Display better contribution data (How many contributions? Amounts?)
* Automatic message in emails for each tier
* Automatic sharing when someone contributes
* Customizable impact metrics
* Build an email list
* Periodic updates linked to the money spent (Data, photos, visualizations)

### Issues identified related to the Collective page:
**Poor visibility and clarity with the current design. Nothing that helps people focus on something.**
 * Other fundraising apps have a big DONATE button.
 * More and better embedding of sections of the public profile
 * Better accessibility and usability standards

### Identified problems related to projects:
**People don't know they can contribute to a specific project. Or they contribute accidentally.**
* There is no clear way to interact with projects
* Users get confused about having projects and Collectives with the same interface

### Identified problems related to the budget features
**Moving money around inside a Collective's budget is limited and sometimes clumsy.**
* Integrations to account for the money coming from other channels or apps like GitHub sponsors and Eventbrite for events)
* Generate bounties within Collectives
—
* Improve goals feature (Set goals for projects and events)
* Contribution in local currencies
* Shared projects between Collectives with a shared goal
* Distribute funds evenly to Collectives/projects under the same parent

## List of proposed projects

**Contribution tiers revamp**  

- [x] Create/Edit `(Currently scheduled for production)` #3438
- [ ] Improve design (Custom image)
- [ ] Sponsor tiers
- [ ] Bounties tiers

**Improve Collectives' budget feature** 
- [ ] Custom impact metrics
- [x] Improve overview `(Currently scheduled for production)` #5704 
- [x] Include visualizations `(Currently scheduled for production)` #5704 
- [ ] Integrations to account for the money coming from other channels

**Collective page redesign** #5680 
- [ ] Improve visibility of sections and tools
- [ ] Differentiate between Collectives/projects/tiers/events

**Contribution flow revamp** 
- [ ] Improve accessibility
- [ ] Reduce friction to the minimum
- [ ] Visual indicator while contributing of which tier/project/event you are contributing to, and the possibility to swap between them
- [x] Share contribution flow `(Currently scheduled for production)` https://github.com/opencollective/opencollective/issues/5631

**Improve updates feature**
- [ ] Periodic updates linked to the money contributed/spent (Financial data)
- [ ] Automatic sharing
- [ ] Build and maintain an email list

**Embed sections of the Collective page**
- [ ] Budget (Financial overview)
- [ ] Goals
- [ ] Team
- [ ] Leaderboard

**Improve budget management**
- [ ] Improve goals feature
- [ ] Contribution in local currencies
- [ ] Shared projects between Collectives with a shared goal
- [ ] Distribute funds evenly to Collectives/projects under the same parent
- [ ] Set goals for projects and events

[Full documentation here](https://docs.google.com/document/d/1GrDflqVywY8EubF24fFLPtLSR7K56YpLSVn8wDd9cKQ/edit?usp=sharing)

**Comment by iamronen** [comment]
This is impressive work @Memo-Es :)

The work you have outlined goes way beyond contribution flows and feels like it can be formed into a platform development roadmap for the foreseeable future. With that in mind:

1. Framing all of this under the umbrella of "Contribution Flow" (the name of both the document and the issue) is misleading. This may be an outcome of that research, but the scope of work reaches FAR beyond it.
2. I think the next step is to transform this into a sequence of projects (allowing that the sequence may evolve over time).
3. That sequence would help me coordinate with you some things that have come up in OSC and overlap with some of the projects you have pointed to.
4. I think that the first two steps (which effect everything else) are the loggedin/loggedout user experience and the profile revamp project. I'd be happy to make time during the coming 2 weeks to help you develop the first one so that we can pitch it for the next development cycle.

**Comment by kaylarep** [comment]
Hope this is the right place for this: https://github.com/opencollective/opencollective/issues/5832

**Comment by Betree** [comment]
I'd like to suggest adding [Add the ability to require custom information in the contribution flow](https://github.com/opencollective/opencollective/issues/1798), it's a common feature request.

**Comment by Memo-Es** [comment]
Closing this issue in favor of https://github.com/opencollective/opencollective/issues/7199
