### ISSUE TITLE
[Roadmap] Q3S2 (25th July - 2nd Aug)

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#5779]
## Context & Strategic Focus

Open Collective builds our platform in 6-week sprints, with a week-long break every two sprints to review our strategic objectives: 

- #5486 
- #5487 
- #5488 

If you'd like to know more about how we work check out [this document](https://www.figma.com/file/WJev8P6o4zS7NExfAPVhrg/Product-%26-Sprint-Process?node-id=0%3A1) and [this video explainer](https://www.loom.com/share/fd24bf7a664945e0ba577e91f93776bb). 

## Prioritisation

Every six weeks we [invite members of the team to share ideas](https://github.com/opencollective/opencollective/discussions/5665) that are high impact and aligned with the strategic objectives. We discuss these ideas together as a team prior to running a [final prioritisation call](https://around.co/playback/efb18aa8-8da7-45f5-975b-e687e3f5cea1?sharedKey=77808380-82ac-40f5-917b-1b707d80bef6) where we commit to projects for the next sprint. 

We also run a poll to inform the process you can see the results here:

![Screenshot 2022-07-22 at 15 52 54](https://user-images.githubusercontent.com/158833/180465864-e65b23d0-a968-4e3b-9db6-87293db93b94.png)

## Roadmap and tracking 

Based on this discussion we decided to prioritise the following issues.  You can follow progress on each of the issues above [using our project board](https://github.com/orgs/opencollective/projects/5/views/20).

### Large Projects (4 weeks)

- #5704 

### Small Projects (4 weeks)

- #5195 
- #5681 

We proposed that we continue to work on the design for the snowboarding process, scoping with engineering as needed. 

- #3438 
 
### Papercuts (half a day, pick up as available)

- #5426 
- #5435 
- #5407 
- #5171 
- #5341 

We noticed a number of papercut issues were about virtual cards, however with @kewitz out for two weeks this sprint we thought that might not be the best focus, instead we could consider clearing some of the previously identified papercuts around expense workflows:

- #4991 
- #3629 
- #4667 
- #5020 
- #4990 

## Checklist

This sprint is being facilitated by  @piamancini. 

After prioritization meeting:

- [x] Create/review Projects issue (basic skeleton is fine) for each prioritized project if it's not already created.
- [ ] Make sure Engineering and Design people assigned to projects.
- [ ] Create sprint meta-issue
  - [ ] Pin the issue.
  - [ ] Update GitHub homepage
- [ ] Communicate prioritization to a wide audience:
  - [ ] internally: OC, OSC, OCF teams
  - [ ] externally: Slack General channel

scoping week (first week)
- [ ] Make sure that scoping is happening, that team members speak to each others, are meeting each others
- [ ] Make sure that scoping is being documented 
- [ ] Make sure that scoping are properly written and can be presented on Friday

On Friday after demos:
 - [ ] Communicate specifications to a wider audience and ask for final feedback

**Comment by alanna** [comment]
> clearing some of the previously identified papercuts around expense workflows

I can't find the issue for this, but previously we identified that hiding the form fields until the user started typing the title was causing confusion, and that we should show the form fields from the start. Is that going to be addressed in here somewhere?
