### ISSUE TITLE
[Roadmap] Sprint Facilitation Checklist: Q3S1 -> Q3S2

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#5965]
### During previous Sprint

- [x] Launch prioritization discussion https://github.com/opencollective/opencollective/discussions/5741

### On week between sprints

- [x] Schedule prioritization meeting

In prioritization meeting:

 - [x] Pick 4 to 6 Projects

After prioritization meeting:

- [x] Create Projects issue (basic skeleton is fine) for each prioritized project if it's not already created.
- [x] Create project board for the sprint
- [x] Make sure Engineering and Design people assigned to projects.
- [x] Create sprint meta-issue: https://github.com/opencollective/opencollective/issues/5966
  - [ ] Should mention strategic priorities
  - [x] Should mention prioritization process
  - [x] Should give context on prioritized projects
  - [x] Pin the issue.
  - [x] Update GitHub homepage
- [ ] Communicate prioritization to a wide audience:
  - [ ] internally: OC, OSC, OCF teams
  - [ ] externally: Slack General channel, ...

### On Sprint scoping week (first week)

Each day:
- Make sure that scoping is happening, that team members speak to each others, are meeting each others
- Make sure that scoping is being documented 
- Make sure that scoping are properly written and can be presented on Friday

On Friday after demos:
 - [ ] Communicate specifications to a wider audience and ask for final feedback
