### ISSUE TITLE
[Project] Improve taxes support

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#6444]
- [x] https://github.com/opencollective/opencollective/issues/6365
- [x] https://github.com/opencollective/opencollective/issues/6508
- [x] https://github.com/opencollective/opencollective/issues/4492

**Stretch goals**
- [x] #5927 
- [ ] https://github.com/opencollective/opencollective/issues/4493
- [ ] https://github.com/opencollective/opencollective/issues/6496
- [ ] https://github.com/opencollective/opencollective/issues/6497
- [x] https://github.com/opencollective/opencollective/issues/6651

**Comment by Betree** [comment]
For this week:
- [ ] Address https://github.com/opencollective/opencollective/issues/6365
- [ ] Investigate & propose specs for https://github.com/opencollective/opencollective/issues/4492

**Comment by Betree** [comment]
Added two stretch goals from a discussion with @jfdh.

**Comment by Betree** [comment]
For this week:
- [ ] Investigate & propose specs for https://github.com/opencollective/opencollective/issues/4492

**Comment by Betree** [comment]
Last week:
- Created tests to confirm https://github.com/opencollective/opencollective/issues/4492
- Fixed the root issue for https://github.com/opencollective/opencollective/issues/4492

This week:
- [ ] Start to look at the migration to fix past entries

**Comment by Betree** [comment]
Last week was engineering retreat, I did not make progress on this project. For this week:
- [ ] Start to look at the migration to fix past entries
- [ ] Look at https://github.com/opencollective/opencollective/issues/6558

**Comment by Betree** [comment]
For this week:
- [ ] Finish the query to summarize data on impacted hosts and create settlement expenses

**Comment by Betree** [comment]
For this week:
- [ ] Merge https://github.com/opencollective/opencollective/issues/4492 & run the script in production
- [ ] Merge & deploy https://github.com/opencollective/opencollective/issues/5927
- [ ] Look at stretch goals

**Comment by Betree** [comment]
For this week:
- [ ] Stretch goal: https://github.com/opencollective/opencollective/issues/6651
- [ ] Stretch goal: https://github.com/opencollective/opencollective/issues/6497
- [ ] Stretch goal: https://github.com/opencollective/opencollective/issues/6370

**Comment by Betree** [comment]
We achieved pretty much all we wanted to do with this project for this sprint. We'll probably come back at some of the issues (looking at you https://github.com/opencollective/opencollective/issues/4493 :eyes:) soon, but that will be a different project!
