### ISSUE TITLE
Improvements to collective application process

### ISSUE THREAD

**Issue by iamronen** [opencollective/opencollective#6869]
## Friction

> as a host admin it is not possible to indicate that a collective application is under review

> as a host admin its currently impossible for me to tell whether another host admin has communicated with a collective administrator during a collective application.

> as a host admin it is impossible to recall any private communication between host and collective as those messages are sent via email. 

Example of this process working today that does not work privately https://opencollective.com/fplayer/conversations/about-your-application-to-open-source-collective-96nn086d

### Solution

1. Hosts should have access to a third ‘in reivew’ status for collective applications, this status should update the collective admin(s) of the progress being made.
2. Enable hosts to filter collectives based on application statuses
3. Enable hosts to record communications with the collectives using the same conversation pattern used in expenses (public messages, private messages, status changes, attachments, etc.).

![Image](https://github.com/opencollective/opencollective/assets/8337819/0ac3030d-1610-4dde-ba5e-f92fd096f5e5)

![Image](https://github.com/opencollective/opencollective/assets/8337819/b5216afd-0238-4201-a2be-a32d0ad5606f)

**Comment by shannondwray** [comment]
https://github.com/opencollective/opencollective/issues/6837 relevant

**Comment by shannondwray** [comment]
https://github.com/opencollective/opencollective/issues/6610 related :)

**Comment by shannondwray** [comment]
I have had feedback about how disjointed this is from a user/applicant perspective. "I have applied to two fiscal hosts and my applications disappear into the void. There is also no email follow-up about acceptance or declination aside from an automated email saying the application happened. There is also no way to view my application status on the website."

**Comment by BenJam** [comment]
I just wanted to document the conversation that @iamronen and I had about compartmentalizing this project. 

It seems that the way to deliver this would be to split things into:

1) delivering the new status (review) and the filter/tab structure across the top
2) delivering the drawer, and adding the application text to this 
3) delivering the comment flow

**Comment by gustavlrsn** [comment]
### Todo (wip)
- [ ] API: Filter host applications by status
- [ ] Frontend: Add tabs to Pending Applications page in Host Dashboard and rename to "Applications" (?)

**Comment by gustavlrsn** [comment]
> I just wanted to document the conversation that @iamronen and I had about compartmentalizing this project.
> 
> It seems that the way to deliver this would be to split things into:
> 
> 1. delivering the new status (review) and the filter/tab structure across the top
> 2. delivering the drawer, and adding the application text to this
> 3. delivering the comment flow

@BenJam @iamronen I'm proposing to shift this delivery schedule into:

1. delivering the filter/tab structure across the top with existing statuses (the code for this is ready with PRs above)
2. delivering drawer
3. delivering review/comments enhancements:
   - "in review" status
   - a way for applicant to see application **(added scope)**
   - comment flow

I think marking as "In Review" feature can be confusing without the drawer, since the application will move over to the "In Review" tab and disappear from the screen when clicking that button. And it also seems easier to understand together with comments, as then this status can also be triggered by an host admins comment.

And the comment flow seems to require a way for the applicant to see the application and respond to comments. 

Does that make sense?

**Comment by gustavlrsn** [comment]
### This week
- [ ] Add drawer
- [ ] Review/comments enhancements
  - "in review" status
  - a way for applicant to see application
  - comment flow

**Comment by iamronen** [comment]
Today a conversation took place between @gustavlrsn @Betree and @iamronen

The seeds for the conversation was the recognition that:
1. Adding the comment thread has is complex because it involves state-changes, attachments and notifications.
2. Adding the comment thread in the fiscal host admin is not sufficient for this to work because there is currently no way for collective admins to interact with it (pointing back to [the problem](https://github.com/opencollective/opencollective/issues/6869#issuecomment-1682224069) @shannondwray surfaced). 

@Betree demonstrated that when a collective applies for a fiscal host, this is indicated in the collective settings-> fiscal host page. We agreed that this is not a good place for collective admins to interact with the comment thread.

The conversation expanded to a wider perspective of comment-threads on the platform. It touched on other places which can benefit from comment threads which are beyond the scope of this project (including contributions, virtual card requests, expenses and more). This bigger picture inquiry led to questions that we will address in follow-up work. 

For now, we've opted to NOT implement the comment-thread within this project. We will return to it after reviewing how we handle comment-threads more generally on the platform.

@poohlaga and @BenJam since this project is a response to OSC needs, would a notes field be useful to at lest keep an internal record until we do implement the comment thread?

**Comment by gustavlrsn** [comment]
### This week
- [ ] merge tabs + table + drawer: https://github.com/opencollective/opencollective-frontend/pull/9275
- [ ] add "In review" status

**Comment by kaylarep** [comment]
if this is being worked on, here are few more open issues about the application process:

- https://github.com/opencollective/opencollective/issues/6472
- https://github.com/opencollective/opencollective/issues/5862
- https://github.com/opencollective/opencollective/issues/5128
- https://github.com/opencollective/opencollective/issues/4486

**Comment by BenJam** [comment]
thanks @kaylarep, we're not working on this right now as we assumed that some of the issues around accounting and the ledger were more important to Open Collective Foundation. We'll pick this up with you in the next week or two as we can prioritise the next phase for development from 1st Jan.
