### ISSUE TITLE
Edit recurring contribution overhaul

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#6872]
The current update recurring contribution flow and updateOrder mutation are outdated since the implementation of Stripe's intent-based contribution.
The main objective of this issue is to update the API and the frontend so we can:
- Create a single screen allowing users to edit/create the payment method and tier/amount for any recurring order.
- Be able to select any saved payment method for any given recurring order. This can be Stripe's Credit Card, SEPA, us_bank_caccount, BACS, bancontact, PayPal, and Open Collective Gift Cards.

**Caveats**
- PayPal subscriptions are managed by PayPal. When moving to PayPal as the new payment method, we need to use subscriptionStartDate to make sure we don't charge the user twice in the same month.
- None of the Stripe payment methods can be used across hosts. So, if we're offering that to the user, we need to create a new one.
- On Bancontact, the following recurring charges are done with SEPA. We need to check how we store this particular type.
- Payment Intent-based contribution is still behind a feature flag. Maybe we should enable it for everyone?

**Tasks**
- [ ] Add a new flow on the frontend that allows users to add supported payment methods using `setupIntent` [Stripe method](https://stripe.com/docs/payments/accept-a-payment-deferred?platform=web&type=setup).
  - [ ] This should be fully compatible with the existing Stripe customer implementation.
  - [ ] Should expose supported payment methods for the existing Host
- [ ] Create a new API mutation to support this new Stripe flow and later replace the existing `updateOrder` mutation.
- [ ] When updating the Payment Method, we should make sure we're only listing the available payment methods for the specific host. Add a tooltip about missing Payment Methods explaining why.
  - [ ] List legacy payment methods as well, this should be backward compatible.
- [ ] Implemented [redesigned drawer/modal experience](https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/%5BOC-Design%5D-Lab-%F0%9F%A7%AA?node-id=21709%3A124697&mode=dev).

**Comment by SultanaH72** [comment]
> The current update recurring contribution flow and updateOrder mutation are outdated since the implementation of Stripe's intent-based contribution. The main objective of this issue is to update the API and the frontend so we can:
> 
> * Create a single screen allowing users to edit/create the payment method and tier/amount for any recurring order.
> * Be able to select any saved payment method for any given recurring order. This can be Stripe's Credit Card, SEPA, us_bank_caccount, BACS, bancontact, PayPal, and Open Collective Gift Cards.
> 
> **Caveats**
> 
> * PayPal subscriptions are managed by PayPal. When moving to PayPal as the new payment method, we need to use subscriptionStartDate to make sure we don't charge the user twice in the same month.
> * None of the Stripe payment methods can be used across hosts. So, if we're offering that to the user, we need to create a new one.
> * On Bancontact, the following recurring charges are done with SEPA. We need to check how we store this particular type.
> * Payment Intent-based contribution is still behind a feature flag. Maybe we should enable it for everyone?
> 
> **Tasks**
> 
> * [ ]  Add a new flow on the frontend that allows users to add supported payment methods using `setupIntent` [Stripe method](https://stripe.com/docs/payments/accept-a-payment-deferred?platform=web&type=setup).
>   
>   * [ ]  This should be fully compatible with the existing Stripe customer implementation.
>   * [ ]  Should expose supported payment methods for the existing Host
> * [ ]  Create a new API mutation to support this new Stripe flow and later replace the existing `updateOrder` mutation.
> * [ ]  When updating the Payment Method, we should make sure we're only listing the available payment methods for the specific host. Add a tooltip about missing Payment Methods explaining why.
>   
>   * [ ]  List legacy payment methods as well, this should be backward compatible.
> * [ ]  Implemented [redesigned drawer/modal experience](https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/%5BOC-Design%5D-Lab-%F0%9F%A7%AA?node-id=21709%3A124697&mode=dev).

**Comment by BenJam** [comment]
Adding to the current cycle (FY23C6) as part of a general clean up of payment methods functionality as a result of #4974.

**Comment by znarf** [comment]
Notes from Kick Off

- Should we use a drawer that looks like the contribution flow?
  - To use a drawer, maybe we need a detailed view of a contribution first
  - **To update Payment Method**
    - **No drawer**
    - **For now, we can use a modal so we don't introduce a drawer**
    - **The modal should look like the Payment Method picker of the contribution flow**
  - To update Amount + Platform Tip
    - That could be interesting
    - But that doesn't cover tier
    - Absolutely need collaboration with design team to do that

**Comment by BenJam** [comment]
@hdiniz happy to chat about plan here if you're tackling this this week.
