### ISSUE TITLE
[Release]

### ISSUE THREAD

**Issue by Belvedor** [opencollective/opencollective#6921]
### Social Media

```[tasklist]
### Tasks
- [ ] https://github.com/opencollective/opencollective/issues/6646
- [ ] https://github.com/opencollective/opencollective/issues/6911
- [ ] https://github.com/opencollective/opencollective/issues/6908
- [ ] https://github.com/opencollective/opencollective/issues/6870
- [ ] https://github.com/opencollective/opencollective/issues/6767
```
