### ISSUE TITLE
Serve frontend traffic from Vercel

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#6999]
We're almost ready to serve frontend traffic from Vercel in case we see clear benefits.

This is what we have left running on Express and not available on Vercel yet.

### Tasks
- [ ] Helmet
- [ ] Hyperwatch
- [x] Download File Handler
- [ ] Duplicate Handler
- [ ] Rate Limiter
- [ ] Service Limiter
- [x] Legacy widget / banner
- [x] Robots.txt / Robots configuration
- [x] Error Pages

Anything else?

- Prevent traffic from being served directly from vercel.opencollective.com.

**Comment by Betree** [comment]
We may want to customize the default timeout to match our Aspics

![Screenshot_20230921-180717.png](https://github.com/opencollective/opencollective/assets/1556356/f03213cf-a0db-4652-b370-304054b40ffc)

**Comment by Betree** [comment]
Image uploads are not working yet; the form data containing the image somehow isn't forwarded to the API.

I had a try to resolve that a few months ago at https://github.com/opencollective/opencollective-frontend/pull/8980/files#diff-c3b3e49402c59043a6a223c70948fa0f8da0a46895b605d2ff0a0ebb67cf5d3e, but wasn't able to make it work straight away. We'll need to give this more attention.

**Comment by znarf** [comment]
I think image uploads works fine once in production mode (when served behind Cloudflare) but not in preview deploy or when served directly from Vercel?

**Comment by gustavlrsn** [comment]
> Download File Handler
This should work on Vercel unless there is some bug, it's implemented both in the Express server but also as a serverless function in `/pages/api/download-file.js`

**Comment by Betree** [comment]
On Heroku, [this non-existing URL](https://opencollective.com/xxxxxxxxxxx/transactions) gives me a proper error (though [it should be a 404](https://github.com/opencollective/opencollective/issues/7097), not "Unexpected Error"):

![image](https://github.com/opencollective/opencollective/assets/1556356/335e70d0-f115-42fd-a375-5692712e5d44)

On Vercel, I get a scary system message:

![image](https://github.com/opencollective/opencollective/assets/1556356/269bac0b-9e16-4b3d-a228-c1eabfafbabc)

**Comment by Betree** [comment]
API routes for connected accounts do not seem ready; I'm getting a 404 when trying to connect a Stripe account. BTW, we're missing error reporting on that "Connect {service}" button.

![image](https://github.com/opencollective/opencollective/assets/1556356/4085ea78-ce43-4d2e-9e85-6e5085567594)

**Comment by Betree** [comment]
> API routes for connected accounts do not seem ready; I'm getting a 404 when trying to connect a Stripe account. BTW, we're missing error reporting on that "Connect {service}" button.

Pushed a fix for this in https://github.com/opencollective/opencollective-frontend/pull/9818/files#diff-cc80e68aab79dfdff3bfc628143b61213f26f9828a1c7d4a99446f1b90e2fbc9, along with some error and loading states handling.

**Comment by Betree** [comment]
OAuth not working (related to missing `/api/*` routes)

**Comment by Betree** [comment]
On proxying: https://vercel.com/fluid (shared by @gustavlrsn)
