### ISSUE TITLE
Expense submission redesign

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#7103]

**Comment by iamronen** [comment]
This project continues #6867

During this cycle we wish to:
1. Complete the designs.
2. Collect internal feedback.
3. Collect external feedback (demo'ing and interviewing a few users)
4. Pitch the project for implementation during next cycle.

**Comment by iamronen** [comment]
The intentions for this week are:
- [ ] Complete designs (including exceptions such as vendors and invite expense)
- [ ] Review with engineering of the new designs.
- [ ] Identify interview candidates - 2 users who are regular expense submitters and 2 users who are occasional/new expense submitters - @Memo-Es will coordinate with @aerugo

**Comment by iamronen** [comment]
On November 24th design ( @aminakazi and @Memo-Es ) demo'ed the progress to engineering (represented by @gustavlrsn and @Betree ) who provided both helpful feedback and a general thumbs-up to progress with this project.

Our objective for this week is to conclude the week with a demo to the wider team (OC Inc and 1st party hosts). Amina is leading the design effort and Gustav has offered to provide feedback during the week. The upcoming demo is an invitation for feedback and to check if there are blockers to moving forward with this project into implementation.

Open issues (beyond smaller issues which Amina noted during the call)
 - [ ] Clarifying the "Who is getting paid" step to make it easier to recognize and interact with the available options.
 - [ ]  Design flow for editing an expense
 - [ ] Expanding the instructions to reflect: collective policy, host instructions (based on initial selection: invoice, reimbursement, vendor) + accounting-category specific instructions. 
 - [ ] Design for "missing legal name" scenario + in-flow resolution
 - [ ] Design for payment method & payee information mismatch error checking ... with guidance for resolution. 
 - [ ] Design flow for invite expense
 - [ ] Design flow for vendor expense
 - [ ] Reveal "recurring expense" information and action in summary screen

When discussing the road to implementation we realized that this may be too much for one cycle and that we may wish to approach this in two cycles:
 - Cycle 1: Initial work and UX research (to address questions such as modal/non-modal design and integration with collective profile pages.
 - Cycle 2: Completion and rollout.

If we do approach this as a two-cycle project, I would like to aim to complete the 1st cycle with something that can be released internally for feedback and testing.

**Comment by iamronen** [comment]
Week 4 is going to be about research. We want to research two directions:
1. Getting feedback about the new step-by-step designs by demo'ing and getting feedback from users:
 - [ ] Interview a couple of expense submitters who submit expenses regularly.
 - [ ] Interview a couple of expense submitters who submit expenses rarely/occasionaly
 - [ ] Interview collective admins and ask how they feel about this user experience both personally (for themselves) and for  other expense submitters related to the collectives / new expense submiitters. 
2. Inquiring into the usecase brought up by @poohlaga where a fiscal host admins needs to be able to rapidly enter multiple expenses and the the step-by-step process can slow them down.
 - [ ] Conduct an interview with Lauren to learn more about the usecase (please record).
 - [ ] Consider conducting a user interview with other host admins to see if they have have similar needs
 - [ ] If applicable, wireframe a "Quick expense" flow dedicated to fiscal host admins within the "Hosted Collectives" redesign effort.

**Comment by Memo-Es** [comment]
## Design update

I'm publishing here the results of the design explorations and a couple of rounds of feedback with internal members of the Open Collective team.

### Phase 1

We started  these series of design rounds with the goal of embedding the expense submission flow in the new dashboard. For that end we first added a "Create +" button from the personal dashboard expenses page. Our original idea was to open this new flow inside a modal: 

| Personal Dashboard | Modal |
|--------------------|-------|
|    ![Image](https://github.com/opencollective/opencollective/assets/49539954/81b78d57-eac7-4d77-9118-f5540ec0f4bd)      |   ![Image](https://github.com/opencollective/opencollective/assets/49539954/45aee90b-2a8e-44c9-b1d0-7cb97bf5e343)    |

Parallely, we started to flesh out all the details of the steps that this new flow was going to be based on:

| Step 1 | Step 2 | Step 3 |  Step 6 | Step 7 | Step 8 | Step 9 | Step 10 |
|--------|--------|--------|--------|--------|--------|--------|---------|
|  ![Image](https://github.com/opencollective/opencollective/assets/49539954/ec3f19b0-bd9a-4877-b7fe-81b013a3f0f1)    |   ![Image](https://github.com/opencollective/opencollective/assets/49539954/3bc1c086-35a0-4fa1-be51-eb5d67b3a498)     |   ![Image](https://github.com/opencollective/opencollective/assets/49539954/ff36dd5e-454a-44a2-bf44-c75187f893ae)    |   ![Image](https://github.com/opencollective/opencollective/assets/49539954/8300685c-211c-4a4d-a2a1-dff3eaee1907)     |  ![Image](https://github.com/opencollective/opencollective/assets/49539954/5fd64196-de07-41d8-93e0-44f8f3604966)      |   ![Image](https://github.com/opencollective/opencollective/assets/49539954/fc5cccdd-375f-446a-b569-6a93629f0f0a)    |   ![Image](https://github.com/opencollective/opencollective/assets/49539954/597a4a67-2d17-4e4e-9c0f-35bbf8d57bd7)  |   ![Image](https://github.com/opencollective/opencollective/assets/49539954/88cad260-f58d42e8-a249-1130361b2075)  |

### Phase 2 

After the first round of feedback and analysis, we started to consider a different UI pattern to present the expense flow. Instead of a dialog modal, that would make it hard for users to follow-up with a complex process like that from a small window modal, we tried with a full-page overlay that takes over the entire screen.

![Image](https://github.com/opencollective/opencollective/assets/49539954/769892c3-978c-47bc-ac1c-7ac0e6078d7d)

### Phase 3

In a new effor to add further aid to the submission process, and to be able to remove the summary step. We added a preview mechanism that lets the user preview the expense while they are submitting it.

![Image](https://github.com/opencollective/opencollective/assets/49539954/ffb00ab6-23f2-491a-bfea-8475246fcb9b)

### Phase 4

We finalize these series of rounds with a couple of updates. Since the preview features created a 3-column layout, we changed the steps component from a sidebar to a top step toolbar, helping us simplify the layout design to a 2-column one.

![Image](https://github.com/opencollective/opencollective/assets/49539954/d0172e2d-64fc-474c-8206-a0ea8d6a697b)


### Mobile reference

| Landing | After scroll | Preview |
|---------|--------------|---------|
|     ![Image](https://github.com/opencollective/opencollective/assets/49539954/a988b164-945d-489e-ad77-e8f4d5f1c5e0)    |        ![Image](https://github.com/opencollective/opencollective/assets/49539954/ea9882ef-4594-4983-91b9-c958b6ada7fd)    |    ![Image](https://github.com/opencollective/opencollective/assets/49539954/bf0ab5bd-fd1b-4480-9b19-5a59fce51d46)     |

### Expense submission for Fiscal Hosts (Included in #7105)

| Step 1 | Step 2 |
|--------|--------|
|    ![Image](https://github.com/opencollective/opencollective/assets/49539954/cfb38d2f-13bd-4a07-8903-51984b97ea15)    |   ![Image](https://github.com/opencollective/opencollective/assets/49539954/d1bdc7dd-697b-47b7-b77a-a86e8fec1ca0)     |
