### ISSUE TITLE
Chart of accounts enhancements

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#7197]
```[tasklist]
### Tasks
- [ ] https://github.com/opencollective/opencollective/issues/7087
- [ ] https://github.com/opencollective/opencollective/issues/7227
- [ ] https://github.com/opencollective/opencollective/issues/7207
- [ ] https://github.com/opencollective/opencollective/issues/7209
- [ ] https://github.com/opencollective/opencollective/issues/7206
- [ ] https://github.com/opencollective/opencollective/issues/7208
- [ ] https://github.com/opencollective/opencollective/issues/7053
```

**Comment by iamronen** [comment]
Kickoff meeting summary with @Betree @hdiniz and myself

## Accounting-category change notifications:
1. What: Reminding ourselves that these notifications represent an **educational edge-case scenario**: informing an expense submitter and/or collective admin when they select (according to a fiscal host admin) an incorrect expense category so that in the future they be more likely to select a correct expense category.
2. When: We don't have a clearly defined event regarding when these notifications should be sent since a fiscal host admin can pay an expense without categorizing it and can change the expense category after an expense was paid. So:
   - We are opting to perform a **daily job** of scanning for **paid expenses** 
   - That were **paid during the last 7 days** - this means that if a fiscal host paid an expense but only categorized it a few days later this process will still work (but beyond 7 days, we won't be sending out notifications "remember that expense you paid a while back ... well ... ")
   - for which the **fiscal host selected a different accounting category**
   - and for which **notifications have not been sent** - which means that if a fiscal host chose an accounting category that caused notifications to be sent and then the accounting category again, new notifications will not be sent.

## Chart of Accounts
1. Updated UI designs (table + drawer) are ready to go.
2. Adding an accounting category "type" selector with (for now) two options: expense, contribution.
3. Setting the default values for existing accounting categories to "Expense"
4. Adding an "instructions" field per accounting category.
5. ADDED SCOPE: add the accounting-category instructions to the existing expense flow (since we are still far from having the new expense flow in production).
6. Checking with fiscal hosts about the need to indicate for an accounting category something like "For fiscal hosts only" to hide some categories from expense submitters and collective admins.

## Categorizing contributions
1. The scope of this project does not cover crowdfunding contributions (which will be handled either separately or as part of the ongoing accounting effort).
2. This scope only makes it possible to assign accounting categories to added funds (and the pending contributions that precede them).

**Comment by Betree** [comment]
For this week:
- [ ] https://github.com/opencollective/opencollective/issues/7207 @hdiniz 
- [ ] https://github.com/opencollective/opencollective/issues/7053 @Betree 
- [ ] https://github.com/opencollective/opencollective/issues/7207 @Betree (API part only)

**Comment by iamronen** [comment]
I have confirmation from OCF that the "Fiscal Host Only" option is something that they still need which means:
1. Adding it with default values of false (unselected).
2. This may create a ripple with notifications - because if a fiscal host can choose an expense category that is not visible to expense submitters or collective admins then (I think) no notification should be sent.

**Comment by hdiniz** [comment]
Updates from weekly sync:

- [ ] Add confirmation dialog before deleting an accounting category, informing host admin if the category is used / what is the consequence of deleting the category.
- [ ] Add options to sort categories by name, hostOnly

![image](https://github.com/opencollective/opencollective/assets/5448927/0f6391ed-a507-4264-a6bf-607a66135df7)

![image](https://github.com/opencollective/opencollective/assets/5448927/809774c1-43e5-4071-85fc-13f1900af338)

![image](https://github.com/opencollective/opencollective/assets/5448927/492d005a-d906-4307-afd0-ebde3ecb20ad)

**Comment by iamronen** [comment]
Thank you for adding the accounting category to the export however it should be split into two fields:
1. Accounting Category Name
2. Accounting Category Code

(confirmed also by feedback from OCF)

**Comment by Betree** [comment]
For this week (to be edited):
- [ ] https://github.com/opencollective/opencollective/issues/7253
- [ ] https://github.com/opencollective/opencollective/issues/7053
- [ ] https://github.com/opencollective/opencollective/issues/7207

**Comment by Betree** [comment]
This week: complete the two goals left from last week
- [ ]https://github.com/opencollective/opencollective/issues/7053
- [ ] https://github.com/opencollective/opencollective/issues/7207

**Comment by Betree** [comment]
Project completed & released

**Comment by shannondwray** [comment]
Now that contributions are included in the COA should the title for Expense Types be changed to Types?

**Comment by shannondwray** [comment]
When I open the create category module the x button in the top right hand corner doesn't work for me

**Comment by shannondwray** [comment]
Has the I don't know expense category been removed?

**Comment by Betree** [comment]
> Has the I don't know expense category been removed? 

No. We're currently discussing allowing that option for host admins too, but I'm not aware of any plans to remove it.

**Comment by Betree** [comment]
> Now that contributions are included in the COA should the title for Expense Types be changed to Types?

Not for now, as there's no filtering on "Contribution Type". In the table, for contributions, this column simply displays a `-`.

> When I open the create category module the x button in the top right hand corner doesn't work for me

Thanks for the report, I've created https://github.com/opencollective/opencollective/issues/7293.
