### ISSUE TITLE
[Project] Internalize the tax forms process

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7216]
We want to move out of Dropbox forms (see https://github.com/opencollective/opencollective/issues/6262 for the reasons and historical context). Among the potential solutions, we've identified building our own integration as the most convincing one going forward. The expected benefits are:
1. To make it more scalable
2. To have full control over the flow, and therefore, the UX and branding
3. To build a foundation for:
   - https://github.com/opencollective/opencollective/issues/6863
   - https://github.com/opencollective/opencollective/issues/7136
   - https://github.com/opencollective/opencollective/issues/6948

---

```[tasklist]
### Tasks
- [ ] https://github.com/opencollective/opencollective/issues/7218
- [ ] https://github.com/opencollective/opencollective/issues/7217
- [ ] https://github.com/opencollective/opencollective/issues/7220
- [ ] https://github.com/opencollective/opencollective-security/issues/135
- [ ] https://github.com/opencollective/opencollective/issues/7299
- [ ] https://github.com/opencollective/opencollective/issues/7300
- [ ] https://github.com/opencollective/opencollective/issues/7362
```

**Comment by Betree** [comment]
We have figured out the different aspects to resolve this and updated the individual issues to reflect the solutions to implement. This project is now mature and ready to be tackled but needs to be prioritized (this sprint was just about exploration).

**Comment by iamronen** [comment]
As an expense submitter:
1. If I have already filled out a tax form for one fiscal host and I get asked to fill out another one for another fiscal host - what happens? Can I, for example, indicate "use the same tax form"? Or do I have to fill out another one?
2. Is there a way for me to access my own tax form? If not, is there a way for me to make a request **on the platform** to have my tax form resent to me?

**Comment by Betree** [comment]
> If I have already filled out a tax form for one fiscal host and I get asked to fill out another one for another fiscal host - what happens? Can I, for example, indicate "use the same tax form"? Or do I have to fill out another one?

Presently, you're only being asked for one tax form. If you submit an expense for OSC, but already provided a valid tax form for OCF, we will automatically use the existing tax form and make it accessible to OSC. The system won't ask for anything.

This may change in the future as we're discussing encrypting tax forms with the host's keys, but that's not on the menu yet.

> Is there a way for me to access my own tax form? If not, is there a way for me to make a request on the platform to have my tax form resent to me?

HelloWorks/Dropbox Forms send you the PDF by email after completion. We will likely do the same thing here for feature parity. We could let users download them from the interface once we enable it in https://github.com/opencollective/opencollective/issues/6863.

**Comment by Memo-Es** [comment]
## Design proposal

@Betree encompassing all requirements I collected from the issues you put up above. cc @iamronen 

https://www.loom.com/share/ce3c7789bdff44f3baa08bc5e29ca0f5?sid=a8967faa-52ff-4a01-b7af-60ec1d557a3b

**Comment by Betree** [comment]
Feedback on early demo:
- We could adapt the fields in the W9 tax form depending on whether it's an organization or an individual
- It would be great to link to IRS help page somewhere
- We could add some documentation for each field, to help fill out the form:
  - Link to docs page (if available)
  - In-context PDF overview tooltip (preview the field in the PDF)

**Comment by Betree** [comment]
This week:
- [ ] Continue https://github.com/opencollective/opencollective/issues/7218
- [ ] Start https://github.com/opencollective/opencollective/issues/7300

**Comment by Betree** [comment]
**Status**
We've merged the base feature, but it's not enabled yet.

**This week**
- [ ] Look at https://github.com/opencollective/opencollective/issues/7362 items and polish the feature to get it ready for release

**Comment by Betree** [comment]
**This week**
- [ ] Complete the two small tech debt items left in https://github.com/opencollective/opencollective/issues/7300
- [ ] https://github.com/opencollective/opencollective/issues/7299
