### ISSUE TITLE
Expenses: Fix Batch Payment inconsistencies and other improvements

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#7323]
## Problem
We have implemented two batch expense payment UX, one for PayPal Payouts and another for Wise. They look similar in how we present information about the batch, but they don't work the same way.

For PayPal:
- This only works for PayPal Payouts;
- It forces the user to "Schedule for Payment" when, in reality, this is not a requirement (we could pay a single expense directly with PayPal Payouts);
- The user has no way to manually pay for a batch. Batches are automatically paid every turn of an hour;
- It requires OC's 2FA validation when "Scheduling for Payment";

For Wise:
- This is only available for European countries that require Wise's SCA flow;
- It forces the user to "Schedule for Payment", even tho we could implement a direct payment flow for a single expense without batching as well;
- The user is required to manually pay for a batch, since Wise will request the user for its 2FA token validation;
- We do not require OC's 2FA for paying or scheduling;
- Request to pay batch is synchronous and can timeout when adding too many expenses;
- Batch expires whenever one of the expenses' quote expires, thus causing the whole batch to fail;

In both cases:
- There's always a single Batch available for a Host to work with, multiple users working at the same time will add/remove expenses from the same batch, which can cause issues;

#### Still to be discussed/verified
- Should batching be isolated on the user level and not shared?

### Desired outcomes
- Users should be able to pay for a single Expense without having to batch it first;
- Batches shouldn't expire, they should be created at payment time;
  - Wise batches should not expire;
- Batch payment should be async to accommodate all requests that are required when creating/batching payments;
  - UI/UX should inform the progress of the process with a waiting screen;
- Failure should be isolated on the expense level: If a single expense fails, the batch should be paid without it.

### Phase 1: Tweaks
- [ ] Deprecate Cron-based PayPal Payouts batch payment in favor of "Pay Batch" banner
  - [ ] Require 2FA when paying for Batch
- [ ] Design: Redesign Expense batch experience

### Phase 2: Internals Refactor
- [ ] Pay a single expense on Wise or PayPal without "Scheduling for Payment"
- [ ] Refactor: Make batching/scheduling internal only and refactor "Pay Batch" to be async (virtual batching: marking expenses for payment without quoting on Wise)
  - [ ] Requires UI update for Pay Batch Modal and actions
  - [ ] Make batches recover if one of the Expenses throws

### Phase 3: UI update
- [ ] Implement redesigned UI for batching expenses
