### ISSUE TITLE
[Project] Dashboard Transactions followup

### ISSUE THREAD

**Issue by gustavlrsn** [opencollective/opencollective#7343]
### Purpose

Improve and extend capabilities of the dashboard transactions tool

https://coda.io/d/Make-Open-Collective_dnHLKv7oLV0/All-Projects_sud_a#Projects_tusx8/r161&view=modal (private link)

```[tasklist]
### Tasks
- [x] Merge effective date filter https://github.com/opencollective/opencollective-frontend/pull/10093
- [ ] https://github.com/opencollective/opencollective/issues/7352
- [ ] https://github.com/opencollective/opencollective/issues/7355
- [ ] https://github.com/opencollective/opencollective/issues/7363
- [ ] https://github.com/opencollective/opencollective/issues/7353
- [ ] https://github.com/opencollective/opencollective/issues/7365
- [ ] https://github.com/opencollective/opencollective/issues/7356
- [ ] https://github.com/opencollective/opencollective/issues/7354
- [ ] https://github.com/opencollective/opencollective/issues/7396
- [x] Verify searching for transaction ID
- [ ] https://github.com/opencollective/opencollective/issues/7361
- [ ] https://github.com/opencollective/opencollective/issues/7357
- [ ] https://github.com/opencollective/opencollective/issues/7364
- [ ] https://github.com/opencollective/opencollective/issues/7360
- [ ] https://github.com/opencollective/opencollective/issues/7370
```

**Comment by gustavlrsn** [comment]
### First priority this week:
- https://github.com/opencollective/opencollective/issues/7353
- https://github.com/opencollective/opencollective/issues/7354

**Comment by gustavlrsn** [comment]
### This week
- Finalize the date column display toggle to switch between Date and Effective Date, and use Effective Date sorting when displaying that field
- Fixes on transaction details drawer
  - Simplify and clean up drawer design
  - Add new data fields
  - Start establishing a general drawer + actions pattern that can be used on other pages

**Comment by gustavlrsn** [comment]
### This week
- Finalize & merge PRs
  - https://github.com/opencollective/opencollective-frontend/pull/10357
  - https://github.com/opencollective/opencollective-frontend/pull/10346
  - https://github.com/opencollective/opencollective-frontend/pull/10353
  - https://github.com/opencollective/opencollective-frontend/pull/10351

**Comment by gustavlrsn** [comment]
### This week
- https://github.com/opencollective/opencollective/issues/7357
- https://github.com/opencollective/opencollective/issues/7361
- https://github.com/opencollective/opencollective/issues/7364
