### ISSUE TITLE
[Project] Tax Forms Admin

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7346]
## Overview 
As a follow-up on https://github.com/opencollective/opencollective/issues/7216, we're going to examine the host admins' experience managing tax forms in the dashboard.

## Issues

```[tasklist]
### To do
- [ ] https://github.com/opencollective/opencollective/issues/7136
- [ ] https://github.com/opencollective/opencollective/issues/6863
- [ ] https://github.com/opencollective/opencollective/issues/7134
- [ ] https://github.com/opencollective/opencollective/issues/7375
- [ ] https://github.com/opencollective/opencollective/issues/7392
- [ ] https://github.com/opencollective/opencollective-frontend/pull/10368
- [ ] https://github.com/opencollective/opencollective/issues/7391
```

## Not considered
- https://github.com/opencollective/opencollective/issues/6126: we needed this because the Dropbox Forms email was the only entry point for payees to start the tax form flow. With it being integrated into the main interface, it doesn't look necessary anymore - we can directly redirect them to their dashboard.
- https://github.com/opencollective/opencollective/issues/7374: we have until January 2025 to figure that out
- https://github.com/opencollective/opencollective/issues/6225 (see [this comment](https://github.com/opencollective/opencollective/issues/6225#issuecomment-2077005151))

## Context
We acknowledge that this enables https://github.com/opencollective/opencollective/issues/6948, but we won't be promoting it actively since the pricing is still unclear.

## Ownership

**Product:** @aerugo 
**Engineering:** @Betree 
**2nd Engineer:** @znarf

**Comment by Betree** [comment]
We've identified one item that will need to be clarified along the way: today, we don't record any link between a tax form and the expenses that triggered its request. The tax form is only attached to the account. At the end of the year, when it's time to produce the exports, we look back at all expenses that required a tax form and attach the corresponding PDFs.

While this worked great for the past few years, it might be a limitation to surface the documents nicely on the host dashboard, as re-figuring this link each time we load the page could be expensive. We plan to implement the base feature without solving this, look at the results, and eventually iterate by recording this link in the database.

**Comment by Betree** [comment]
**This week**
- [ ] Make a first proposal for https://github.com/opencollective/opencollective/issues/7136
- [ ] https://github.com/opencollective/opencollective/issues/6863

**Comment by Betree** [comment]
**This week**
- [ ] Merge first proposal for https://github.com/opencollective/opencollective/issues/7136
- [ ] Test performances in production
- [ ] Start looking at #7134 / #6225

**Comment by Betree** [comment]
**This week**
- [ ] Complete https://github.com/opencollective/opencollective/issues/7375
- [ ] https://github.com/opencollective/opencollective/issues/7392

**Comment by Betree** [comment]
All done & released. Pinged fiscal host admins in https://opencollective.slack.com/archives/GST5GVCQ7/p1714644757092949 and sent an email to NFSC admin, I'll follow up with them directly if needed.
