### ISSUE TITLE
Sunsetting Dropbox Forms

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7378]
```[tasklist]
### Tasks
- [ ] https://github.com/opencollective/opencollective/issues/7362
- [ ] https://github.com/opencollective/opencollective/issues/7299
- [ ] Make sure we don't have any pending tax form requests on Dropbox forms anymore
- [ ] Remove all code from the API
- [ ] Make a final backup of all the data on the account (see the script below)
- [ ] Close the account
``` 

To backup data from Dropbox Forms:

```bash
start_date="2019-01-01T00:00:00.000Z"
end_date="2019-05-01T23:59:59.000Z"
end_loop_date=$(date -u +"%Y-%m-%dT00:00:00.000Z")
interval="4 months"
workflows="&guid[]=MfmOZErmhz1qPgMp&guid[]=qdUbX5nw8sMZzykz&guid[]=MkFBvG39RIA61OnD"

# Download
while [[ "$start_date" < "$end_loop_date" ]]; do
  # Calculate the end date for this period
  period_end_date=$(date -d "$start_date + $interval" "+%Y-%m-%dT%H:%M:%S.000Z")

  # Call the curl command with the current date range
  # curl "http://my-url.com?start_date=$start_date&end_date=$period_end_date"
  curl --output result-$start_date-$period_end_date.zip "https://portal.helloworks.com/workflow/transactions/detail/?mode=live&$worflows&start_date=$start_date&end_date=$period_end_date"

  # Update the start date for the next period
  start_date=$(date -d "$period_end_date + 1 second" "+%Y-%m-%dT%H:%M:%S.000Z")
done

# Extract all CSV files from the zip files
for f in *.zip; do unzip -B -j "$f" "*.csv"; done

# Merge all CSV files into one
csvstack Open*.csv* >all.csv
```
