### ISSUE TITLE
UI: Update Transaction details drawer

### ISSUE THREAD

**Issue by gustavlrsn** [opencollective/opencollective#7396]
```[tasklist]
### Tasks
- [x] Use internal/legacy ID instead of UUID as main identifier
- [x] Improve readability of data list
- [x] Add new payment method fields (service + type)
- [x] Add merchant ID
- [x] Add accounting category
```
