### ISSUE TITLE
Allow to add invoices from external vendors (without bothering them)

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#7470]
The entire process of paying the expense of a vendor is really problematic.
When you receive an invoice, the vendor has other things to do than register on open collective.

As a collective admin, I want to be able to add the invoice of any vendor. 
I shouldn't have to invite them to the platform. It's an unnecessary step.

In the meantime, can you please mark this expense as verified so that we can pay it asap?
https://opencollective.com/regen-village/expenses/211138

Thank you.

- [x] mark expense [#211138](https://opencollective.com/regen-village/expenses/211138) as verified 
- [x] mark expense [#211135](https://opencollective.com/regen-village/expenses/211135) as verified 
- [x] mark expense [#211665](https://opencollective.com/regen-village/expenses/211665) as verified 
- [ ] allow host admins to pay expenses that are approved even if they have not been verified

**Comment by shannondwray** [comment]
Hey Xavier, 

We have a deployed solution for this: Vendors: https://docs.opencollective.com/help/fiscal-hosts/fiscal-host-dashboard/vendors

If you want collective admins to be able to utilize vendors, you will need to ensure this is turned on in your policies section. 

We are yet to build the functionality for collective admins to add vendors. For now this process is done by a Fiscal Host admin by request of a collective. 

Please let me know if you have any questions about this feature.

**Comment by xdamman** [comment]
Ah, I saw vendors but only when adding funds. Didn't know I had to activate it (I'm an admin of the fiscal host so it looks like a bug might be hidden there).

Update: I've activated it but I still can't create a vendor when submitting an invoice: 
<img width="755" alt="Screenshot 2024-07-17 at 4 29 56 PM" src="https://github.com/user-attachments/assets/017c36db-32aa-41b2-b995-4ec54f64f21f">

I tried to log out and log in again, same issue. What am I missing?

Any chance the expenses listed above could be marked as ready to be paid? Otherwise we have to reject them all (which will notifiy the vendor) and submit again.

Thanks.

**Comment by shannondwray** [comment]
Please read the documentation on how to create vendors: https://docs.opencollective.com/help/fiscal-hosts/fiscal-host-dashboard/vendors

You can just delete the expenses and resubmit them once you have the vendors set up, this won't reinvite the users and they'll be payable as soon as they have been approved

**Comment by xdamman** [comment]
Got it. I created the vendors and edited the expenses. Thank for the support.

There is still an UX issue: people should be able to add a vendor in the context of selecting "who is going to be paid for this expense", in the same way that they can invite someone new right from there.

**Comment by iamronen** [comment]
There are some potential complications we need to sort out on the fiscal host side (reviewing expenses and managing vendors) in order to make it possible to create new vendors within the expense submission flow. Once we have a plan of action we will try to prioritize this.

**Comment by xdamman** [comment]
Not sure I follow this reasoning. If it is already allowed to add vendors somewhere else, then surely it should be allowed to add them from that other place (or at the very list, add a note with a link: "to add a vendor, go here").

Anyway, I'm reopening this because I'm hitting another bug.
As you can see, I've created a `lu.ma` vendor and I was able to add funds on their behalf (ticket sales).

<img width="828" alt="Screenshot 2024-08-01 at 12 36 03 PM" src="https://github.com/user-attachments/assets/ffa12b3f-1fba-405b-8b31-5012939ef510">

But when I try to upload the subscription for their premium plan, I can't find it in the list.
(Yes, I'm an admin of the collective and of the fiscal host)

<img width="771" alt="Screenshot 2024-08-01 at 12 36 20 PM" src="https://github.com/user-attachments/assets/37cbc194-b18d-4bb8-b8d2-8f641ba644dd">

Any clue?

**Comment by shannondwray** [comment]
For a vendor to function with expenses a payout method need to be added to their vendor profile. Does the Luma Vendor have a payout method attached?

**Comment by xdamman** [comment]
Just wanted to say thank you for helping with this 🙏
