### ISSUE TITLE
[Project] Collective Export and Import

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#7475]
To push forward decentralization, user independence and GDPR compliance, we want  to allow users to export data from their collective and import it in a different instance of our open source software.

```[tasklist]
### Engineering plan for this sprint
- [ ] https://github.com/opencollective/opencollective/issues/7487
- [ ] https://github.com/opencollective/opencollective/issues/7489
- [ ] https://github.com/opencollective/opencollective/issues/7494
```

```[tasklist]
### Extra
- [ ] https://github.com/opencollective/opencollective/issues/7488
- [ ] https://github.com/opencollective/opencollective/issues/7491
- [ ] https://github.com/opencollective/opencollective/issues/7493
```

```[tasklist]
### Follow-ups
- [ ] https://github.com/opencollective/opencollective/issues/7490
- [ ] Export uploaded files (legal documents, expense items, ...etc)
- [ ] Export legal documents data (low priority)
```

_Edit by @Betree: updated issue with the plan._

**Comment by Betree** [comment]
The engineering team has decided on a plan for this project. Some assumptions first:
- Passwords will **never** be exported. Users will have to re-confirm their email on the new platform.
- The first solution will take the shape of simple import/export scripts meant to be used by engineers only
- We want to use standard, human-readable, GDPR-compliant formats (JSON, JSONL)
- We won't assume users will be starting with a fresh instance (avoid collisions of IDs)
- In the future, we may want to be aware of other instances (i.e. need to identify a transaction in a network of instances)

Based on that, 3 approaches were discussed:
1. **GraphQL approach**
   - Format: defined by the queries
   - Pros:
     - Re-use permission logic to filter out data (e.g. a payment method)
     - Simple export implementation
     - Format is consistent with our public API
   - Cons:
     - Business cost is moved to import (need to map entities from GraphQL to DB)
     - GraphQL will need adaptations to work properly (e.g. surface `data`, hack limits)
     - Not everything is exposed today on GraphQL, and we may not want to expose everything
     - Limited control over performances
     - Will eventually lead to enormous exports (lot of duplication)
Many tables not represented today (histories, legal docs, paypal plans, paypal products)
The best guarantee that the platform will continue to work is to have everything
A query to get everything would actually be quite complex
2. **Query the data directly**
   - Format: JSONL, one file per table, 1 row per entry
   - Risk: Not implementing permissions correctly => security issues
   - Pros:
     - Simplified import
     - Guarantee that all data is there
     - We can build upon @kewitz's existing work
3. **Use pg_dump/pg_restore**
   - Risks: Not filtering enough => exporting too much (security)
   - Pros:
     - Simple export & import
   - Cons:
     - Non-standard format
     - Auto-increment ID conflict issues

Based on engineering discussions, we have decided to build upon @kewitz's existing work which took the 2nd approach. However, we reckon that the comments made on security risks are valid concerns and special attention will be given to make sure we don't export more than we should. Whenever possible, we'll try to re-use and put in common the permission libraries used by GraphQL.

**Comment by Betree** [comment]
**This week**
- [ ] Start looking at https://github.com/opencollective/opencollective/issues/7487 (@Betree)

**Comment by Betree** [comment]
**This week**
- [ ] https://github.com/opencollective/opencollective/issues/7487 (@Betree)
- [ ] https://github.com/opencollective/opencollective/issues/7489 (@hdiniz)

**Comment by Betree** [comment]
**Last week**
- @hdiniz did zip file implementation

**This week**
- [ ] Add tests and put for review https://github.com/opencollective/opencollective/issues/7487 (@Betree)
- [ ] Review https://github.com/opencollective/opencollective/issues/7489 (@hdiniz)
- [ ] Start looking at https://github.com/opencollective/opencollective/issues/7488 (@kewitz)

**Comment by Betree** [comment]
**This week**
- [ ] Start looking at https://github.com/opencollective/opencollective/issues/7488 (@kewitz)
- [ ] Figure a recipe to use a test with prod data (@kewitz)
- [ ] https://github.com/opencollective/opencollective/issues/7493 (@Betree)

**Comment by kewitz** [comment]
**This week**
- [ ] Tackle https://github.com/opencollective/opencollective/issues/7488
