### ISSUE TITLE
[Project] Add comment threads to applications

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#7480]
[Coda Link :lock:](https://coda.io/d/_dnHLKv7oLV0#CurrentProjects_tu75U/r134&view=modal)

We want to update the host experience and allow them to discuss through comments in the application process. 

This will replace current communication per email and support system.

> Enable host-collective communications via an application comment thread

```[tasklist]
### Desired Outcomes
- [x] Fiscal hosts admins and collective admins can communicate with each other on the platform about a collective application
- [x] Collective admins have access to their application comment thread.
- [x] Collective admins receive an email notification when a fiscal host admin leaves a comment on their application comment thread, the notification includes a link to the application comment thread in the collective dashboard.
- [x] Fiscal host admins have an “inbox” option added to the pipeline that surfaces new comments from collective admins on applications.
```

```[tasklist]
### Tasks
- [x] Send comment notification to collective admins only
- [x] Remove USER lastCommentBy filter option
- [x] Apply new comment thread design
- [x] Refactor drawer actions to use new table actions component
- [x] Add withdraw action to collective application drawer view
- [ ] Apply new thread layout to existing dashboard entities (Expenses, Updates)
- [ ] Add option ascending/descending prop to thread component
```

**Comment by Betree** [comment]
**This week**
- [ ] Sync with design @hdiniz 
- [ ] Kickoff API @hdiniz

**Comment by Betree** [comment]
**This week**
- [ ] On hold until sync with Amina @hdiniz 
- [ ] Figure out what we want to do for Inbox @hdiniz

**Comment by Betree** [comment]
**This week**
- [ ] On hold until sync with Amina @hdiniz 
- [ ] Figure out what we want to do for Inbox @hdiniz 
- [ ] Continue implementing the Inbox pattern

**Comment by hdiniz** [comment]
## This week
- [ ] Apply new comment thread design
- [ ] Add withdraw action to collective application drawer view
- [ ] Review
- [ ] Release

**Comment by hdiniz** [comment]
## This week

- [ ] Add the new thread component to dashboard expenses

**Comment by hdiniz** [comment]
### This week (follow up)
- [ ] Add option of submitting private notes to host application thread

**Comment by Betree** [comment]
This is done & released
