### ISSUE TITLE
[Project] Enable Fiscal Hosts to pause contributions

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#7481]
Sometime Fiscal Hosts wants to pause recurring contributions on a specific collective, because they need extra information, need to get some paperwork done or are in the process of unhosting the collective.
```[tasklist]
### Tasks
- [ ] https://github.com/opencollective/opencollective/issues/7512
- [ ] https://github.com/opencollective/opencollective/issues/7513
```

**Comment by Betree** [comment]
**This week**
- [ ] Finish implementing https://github.com/opencollective/opencollective-api/pull/10249

**Comment by Betree** [comment]
**This week**
- [ ] Review https://github.com/opencollective/opencollective-api/pull/10261 @gustavlrsn 
- [ ] Finish https://github.com/opencollective/opencollective-frontend/pull/10612 @Betree
