### ISSUE TITLE
[Project] PCI DSS Compliance

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#7532]
While we avoid full PCI compliance by never seeing or storing credit card data, we're currently reviewing Stripe and PCI policies and want to improve in a few areas.

Coda link (private):
https://coda.io/d/Make-Open-Collective_dnHLKv7oLV0/Currently_suSgoFhs#CurrentProjects_tuTeF75U/r268&view=modal
```[tasklist]
### Tasks
- [ ] Remove all credit card expiration dates from our database
- [ ] Stop recording credit cards expiration dates
- [ ] Adapt frontend to make sure we're still displaying cards properly
- [ ] Build an alternative mechanism for credit card expiration email notice
```
