### ISSUE TITLE
Implementing Keyboard shortcuts

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#7566]
```[tasklist]
### Tasks
- [x] j/k to travese list
- [x] p to pay
- [x] right/enter to 'click' into expense
- [x] s to open security warnings
- [x] esc/left arrow to click out
- [x] e to edit
- [x] h to hold
- [x] i for incomplete
- [x] page up/down to progress to next/prev page
```
