### ISSUE TITLE
Debt not directly collected when using a gift card

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7592]
[This contribution](https://opencollective.com/mastodonworld/contributions/795458) was made using a gift card. Because it's backed by a credit card as a `SourcePaymentMethodId`, we expect the tip to be collected directly but the ledger says it's not (there's a platform tip debt).

![image](https://github.com/user-attachments/assets/d1b738a2-0a30-4b8c-9b23-72a67edcc494)

```[tasklist]
### Tasks
- [ ] Check on Stripe whether we've collected the tip or not
- [ ] Fix the code: tips should be collected directly when source payment method supports it
- [ ] Check past data and eventually fix if the collected amount were wrong
```
