### ISSUE TITLE
[Project] Export Hosted Collectives data

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#7594]
## Overview 
Emulate the export pattern we’ve evolved and refined for ledger transactions and apply it to hosted collectives:

1. Provide an export tool for hosted collectives which includes a useful default setting (”one click export”) and an ability to customize export sets.
2. Provide a list of fields that can support host reporting and decision making around collective history, status, financials, expenses and contributions. 
3. Enable host admins to export both a full set of data for all collectives AND for the set of collectives defined by the filters provided in the hosted collectives tool. 

## Ownership

**Owner:** 
@iamronen 

**Engineering:** 
@kewitz @hdiniz 

## Project

**Risks**
- Some of the new stat resolvers could affect the overall performance of the export and render the whole export useless.
  - A proper benchmark will be done after implementing resolvers with real-world data.

```[tasklist]
### Tasks
- [ ] https://github.com/opencollective/opencollective/issues/7595
- [ ] https://github.com/opencollective/opencollective/issues/7596
- [ ] https://github.com/opencollective/opencollective/issues/7625
- [x] Implement resolvers for time-domain analysis (averages, etc..)
- [x] Benchmark export collectives with production data
- [x] Open release
- [x] Make sure currencies are consistent
- [ ] Implement pending fields
- [ ] [Extend] Add newly created resolvers to Hosted Collective drawer details
```

**Comment by Betree** [comment]
**Last week** 
- Prototype done

**This week**
- [ ] Submit prototype (with existing fields) for review

**Comment by Betree** [comment]
**This week**
- [ ] Start implementing missing fields / queries

**Comment by Betree** [comment]
**This week**
- [ ] Merge & deploy
- [ ] Project review: what's (not) implemented, are we satisfied?

**Comment by Betree** [comment]
Done & released
