### ISSUE TITLE
[Project] Upgrade goals infrastructure

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7605]
## Overview

Goals are currently a 2nd class citizen on the platform (stored as 2nd hand information in JSON fields). Goals are going to to be given a more prominent place on the platform in the crowdfunding redesign. We need to create the infrastructure to make this possible. 

## Ownership

@iamronen @aminakazi @gustavlrsn @hdiniz 

_Note: Project owner responsibilities include coordinating all the different people that need to contribute to the project, defining specs and goals, communicating project progress, being the point person for decisions, QA, documentation, and a plan for ongoing maintenance. If the project owner can't continue, they need to hand the role over to another person explicitly._

## Desired Outcomes

![Image](https://github.com/user-attachments/assets/3dd0d8ba-4cf2-4b32-a072-56e55d438fe8)

## Tasks

```[tasklist]
### Tasks
- [ ] Finalize UI prototype
- [ ] Define GraphQL API
- [ ] Add database model, add resolvers + mutations
- [ ] Build/integrate goal frontend components from prototype
```

## Context & related issues

- https://coda.io/d/Make-Open-Collective_dnHLKv7oLV0/Currently_suSgoFhs#CurrentProjects_tuTeF75U/r237&view=modal

**Comment by Betree** [comment]
**Last week**
- Kicked off project

**This week**
- [ ] New call to define a smaller set of goals

**Comment by gustavlrsn** [comment]
### Last week
- Reduced scope features from stacked goals to single goal at a time
- Started on UI prototype

### This week
- [ ] Finalize UI prototype
- [ ] Define GraphQL API
- [ ] Start adding model, building API

**Comment by gustavlrsn** [comment]
Updated UI prototype after sync this week to further simplify the first iteration:

![Image](https://github.com/user-attachments/assets/caa8a200-e20e-49f1-a3a0-393fee106da7)

**Comment by iamronen** [comment]
look good @gustavlrsn 

Proposed review of "Preview Text":
 - If there are no existing contributions: "Goal progress preview"  
 - If there are existing contributions: "Goal progress preview (based on existing contributions)

**Comment by gustavlrsn** [comment]
Proposal for GraphQL API:

```graphql
type Account {
   ...
  goal: Goal
}

type Goal {
  """
  The type of the goal (per month, per year or all time)
  """
  type: GoalType

  """
  The amount of the goal
  """
  amount: Amount

  """
  The progress of the goal in percentage
  """
  progress: Int
  contributors(
    """
    The number of results to fetch (default 10, max 1000)
    """
    limit: Int! = 10

    """
    The offset to use to fetch
    """
    offset: Int! = 0
  ): AccountCollection
}

"""
All supported goal types
"""
enum GoalType {
  """
  Total contributions
  """
  ALL_TIME

  """
  Contributions per month
  """
  MONTHLY

  """
  Contributions per year
  """
  YEARLY
}

```

**Comment by Betree** [comment]
**This week**
- [ ] Discuss `contributors` implementation
- [ ] Migration form (from old goals)
- [ ] Synchronize on direction

**Comment by Betree** [comment]
Based on latest meeting:
- We want to experiment with a Calendar view in addition to the rolling window approach. We'll implement a flag to easily switch between the two modes during an experimental phase.
- In order to work properly, the calendar view will require collectives to define their timezones (we don't need to solve that now).
- We want to make sure we surface both received funds (aka. transactions) and pledged funds (aka. recurring contributions that haven't been charged yet but will be later in the period).

![Image](https://github.com/user-attachments/assets/e364668e-5256-4bb1-a89c-1b867c528de6)

![Image](https://github.com/user-attachments/assets/5d2a2f49-1b4a-4ac9-86b0-b431f10fdb36)

**Comment by Betree** [comment]
# New iteration specs

## API

- Add `CALENDAR_MONTHLY` and `CALENDAR_YEARLY` as possible values for the `GoalType`
- Rename `MONTHLY` AND `YEARLY` types to `MONTHLY_BUDGET` and `YEARLY_BUDGET`
- Add an `overrideType` argument to the `Goal` resolver to allow overriding the type with a query param
- Add an `includePledgeContributions` argument to the `contributors` field to include pledge contributions
- Add a `pledgesTimeSeries` field to `AccountStats`: a forecast of future pledges. Accept a "timeUnit" to specify intervals. `dateTo` should always have a max (to be defined) to avoid fetching infinity. Look at active orders + interval, without already charged, nextChargeDate.

## Frontend

- Support new `GoalType` values in the form
- Add support for an `overrideGoalType` query param
- Implement the progress bar for Calendar goals:
  - Adapt title: `{Month/Year} fundraising goal`
  - Show the total amount received (`totalAmountReceivedTimeSeries`, compare with what we have on the host/account reports to make sure they match. The account report shows the type, which would help to debug.)
  - Show the pledged amount (`pledgesTimeSeries`)
  - Display labels (chart legend)
  - Tooltip for pledges to explain what it is + that it's an estimation
- Implement the calendar chart:
  - Show the total amount received (`totalAmountReceivedTimeSeries`)
  - Show the pledged amount (`pledgesTimeSeries`)

# Future follow-ups & ideas

- Include expected funds in pledges
- For monthly budget: how many contribs. you have (how the budget is made)
- On the timeseries graph, show details on orders cancelled/errored, new contirbutions vs recurring...etc

# Identified challenges
- Should we include yearly pledges in monthly calendar goals?
- Pledged amount will not be displayed net / the metric will be imprecise (arguably solved by the tooltip)
- Future pledges in the timeseries graph: it's not clear how to best display them.

**Comment by iamronen** [comment]
re: MONTHLY_BUDGET and YEARLY_BUDGET 
I suggest steering away from using the word budget, and reserving it for implementing actual budget-related tools.

**Comment by Betree** [comment]
- [ ] API: Review, merge & deploy pledge timeseries query @hdiniz 
- [ ] API: `includePledgeContributions` @hdiniz
- [ ] Update frontend components to support new goal types (form + display) @gustavlrsn 
- [ ] Add a monthly budget field on the API

**Comment by Betree** [comment]
**This week**
- [ ] API: Iterate, merge & deploy pledge timeseries query @hdiniz 
- [ ] API: `includePledgeContributions` @hdiniz
- [ ] New iteration on frontend components to support new goal types @gustavlrsn

**Comment by kewitz** [comment]
**This week**
- [ ] Merge frontend and integrate into fundraising profiles
- [ ] API: Figure out how to do `includePledgeContributions`
