### ISSUE TITLE
[Project] New expense submission V2

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7606]
## Overview

Complete and release the new expense submission and have it replace the legacy expenses submission flow.

## Ownership

@iamronen @hdiniz @aminakazi @gustavlrsn 

_Note: Project owner responsibilities include coordinating all the different people that need to contribute to the project, defining specs and goals, communicating project progress, being the point person for decisions, QA, documentation, and a plan for ongoing maintenance. If the project owner can't continue, they need to hand the role over to another person explicitly._

## Desired Outcomes

![Image](https://github.com/user-attachments/assets/ae61822a-bc28-4a94-b55e-f633d9c9ab3f)

## Tasks

```[tasklist]
### Tasks
- [ ] Design iteration on collective picker in expense flow
- [x] Add expanded view of payout methods picker
- [x] Add edit/delete payout method options
- [x] Add vendor picker option
- [x] Connect update legal name actions to API
- [x] Add option to upload expense attachments via graphql
- [x] Add animation for completed steps in step list
- [x] Add ability to edit draft expense in current expense flow
- [x] Add summary and sucess pages at end of expense flow
- [ ] Add cookies for acknowledged expense policies
```

## Context & related issues

- https://coda.io/d/Make-Open-Collective_dnHLKv7oLV0/Currently_suSgoFhs#CurrentProjects_tuTeF75U/r230&view=modal

**Comment by Betree** [comment]
**Last week**
- Iterated on UI components

**This week**
- [ ] Kickoff project
- [ ] Put up a plan for implementation/release
- [ ] Iterate & discuss on UI components

**Comment by Betree** [comment]
**This week**
- [x] Design sync: discuss UI alternatives
- [ ] Finalize functionality
  - [ ] manage payout methods
  - [ ] submit form

**Comment by Betree** [comment]
**This week**
- [ ] Decisions on UX/UI
- [ ] Schedule workshops for finetuning colors/spacing/...
- [ ] Edit payout methods

**Comment by Betree** [comment]
**This week**
- [ ] Error handling/displaying
- [ ] Review (and eventually implement invoice generation) (see https://github.com/opencollective/opencollective/issues/3865)
- [ ] UI tweaks
- [ ] Fix test pipelines

**Comment by kewitz** [comment]
**This week**
- [ ] Review UI tweaks

**Comment by Betree** [comment]
This is done, but we still need https://github.com/opencollective/opencollective/issues/7683 and a significant QA pass before we can release it more broadly.
