### ISSUE TITLE
[PROJECT] Consolidate transactions migrations

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7639]
## Overview

Over the past few years, we've made significant changes to our ledger structure:
- Split payment processor fees transactions
- Split tax transactions
- Split host fees
- Split host fees shares

To make it safe, we've only migrated transactions from a certain date. It helped with the migration, but we now have complex rules and conditions in our budget metric to compute stats. In order to simplify the ledger and the code that rely on it, we're thinking about consolidating all this and migrate old transactions as well.

There are three main challenges with this project:
1. We need to ensure the metrics consistency: migrating should not have any impact on the balances.
2. We're going to create **many** transactions (processor fees, host fees). We need to make sure that the performances of existing queries are not too impacted.
3. The migrations themselves will be heavy, we need to make sure that we can run them without degrading our services.

In order to move on safely with the project, we will therefore need to build a suite of test & tools to guarantee the ledger consistency and performance. These tools will serve us later on.

## Desired Outcomes

- Ledger consistency
- Simplified ledger
- Simplified metric queries
- More safety when deploying ledger changes (thanks to new tests)

## Tasks

```[tasklist]
### Experiment
- [ ] Develop a test suite for ledger consistency based on prod data (_get the dump, run a migration, make sure the numbers match_).
- [ ] Develop a benchmark for ledger performance that records the time to process metrics.
- [ ] Try and migrate older transactions on a prod dump
- [ ] Ensure consistency, iterate if not consistent
```

If consistency is achievable, we can release to prod with some additional steps:

```[tasklist]
### Release
- [ ] Ensure speed
- [ ] Migrate production
- [ ] Remove legacy compatibility code
```

If consistency is **not** achievable, we will have implemented a robust test suite for us to deploy ledger changes more confidently in the future.
