### ISSUE TITLE
Remove the concept of "Subscription.quantity"

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7644]
API has a concept of "Subscription.quantity" introduced a while ago, supposedly to allow charging a contribution only `n` times, but it doesn't seems to be used for real scenarios anywhere.

```[tasklist]
### Tasks
- [ ] Remove `Subscription.quantity` from the model (incl. migration)
- [ ] Remove `hasReachedQuantity` from `server/lib/recurring-contributions.js`
- [ ] Look for additional references
```
