### ISSUE TITLE
Update the Dashboard for Twitter deprecation

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7665]
```[tasklist]
### Tasks
- [x] Prevent connecting new accounts
- [ ] Show a warning in the overview (@aminakazi to propose a design)
- [x] Show a warning in Settings > Socials
- [x] Hide Settings > Social Accounts if Twitter is not connected
```
