### ISSUE TITLE
Remove Twitter integration from emails

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7669]
```[tasklist]
### Tasks
- [x] `api/templates/emails/github.signup.hbs`
- [x] `api/templates/emails/onboarding.day2.opensource.hbs`
- [x] `api/templates/emails/onboarding.day3.hbs`
- [x] `api/templates/emails/onboarding.day21.noTwitter.hbs`
```
