### ISSUE TITLE
Implement protected uploaded files in the API

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7675]
```[tasklist]
### Tasks
- [x] Implementing a route to download files that (temporarily) redirects to the authenticated S3 URL
- [x] URL like opencollective.com/api/files/...
- [x] Ensure the S3 URLs expire after a certain delay.
```

**Comment by Betree** [comment]
Implemented in https://github.com/opencollective/opencollective-api/pull/10500
