### ISSUE TITLE
Adapt frontend for authenticated file links

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7676]
In the frontend, whenever expense files are protected (see https://github.com/opencollective/opencollective/issues/7675 > `file.isProtected`), adapt the logic of the components to use the safe download process by calling the API.

We must also make sure that all places implementing this logic handle the possible exceptions:
- Unauthorized (please sign in)
- Forbidden (you don't have access)
- The link has expired (re-generate automatically)
- 404

```[tasklist]
### Tasks
- [x] Update the expense summary (both for the expense page & dashboard)
- [x] Update the file preview in the drawer
- [ ] Update the expense edit
- [ ] Make sure the new expense edit is ready for this
```
