### ISSUE TITLE
Migrate legacy uploaded files to a safe URL

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7677]
This is necessary to make sure all files will be protected by https://github.com/opencollective/opencollective/issues/7673.

```[tasklist]
### Tasks
- [x] Exporte a table snapshot CSV for all files we're going to move
- [x] Create a script to copy the file to the new safe location
- [x] Run the script to copy files
- [x] Make sure the new files are safe and downloadable
- [ ] Delete the old files (use the backup file to identify them)
```

**Comment by Betree** [comment]
Copied the files to their new location successfully, the only bit left is to trash the legacy files. I'll be working on a script for that.

**Comment by Betree** [comment]
Trashed all legacy files (101368) using `scripts/uploaded-files/trash-legacy-files-in-s3.ts`.
