### ISSUE TITLE
Cleanup OCF debt in code

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7679]
Many places still have some dedicated code related to OCF. We will soon be able to cleanup everything.

# API

```[tasklist]
### Tasks
- [ ] Scripts in `scripts/ocf`
- [ ] OCF custom email templates + special treatments in `server/lib/email.ts` and `server/lib/onboarding.js` and `server/lib/notifications/email.ts`
``` 

# Frontend

- [x] Custom apply flow
- [ ] OCF closing migration banner
- [ ] OCF closing migration in Dashboard > Host
- [ ] `components/AccountingCategorySelect.tsx`

**Comment by Betree** [comment]
All done
