### ISSUE TITLE
Remove the Twitter integration entirely

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7684]
Follow-up on https://github.com/opencollective/opencollective/issues/7663

```[tasklist]
### Tasks
- [ ] Remove all API code 
- [ ] Delete relevant connected accounts
- [ ] Remove all Frontend code 
```

**Comment by Betree** [comment]
Looking at some Twitter searches, it looks like nothing has been posted via the app since June 2023:
- https://x.com/search?q=%22Become%20a%20financial%20contributor!%20%F0%9F%98%83%22&src=typed_query&f=live
- https://x.com/search?q=%22Our%20current%20balance%20is%22%20%22Top%20financial%20contributors%22&src=typed_query&f=live
- https://x.com/search?q=%22Latest%20update%20from%20the%20collective%22&src=typed_query&f=live
