### ISSUE TITLE
Elastic search: internal release

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7690]
```[tasklist]
### Tasks
- [x] Add rate limiting
- [x] Remove the root limitations on the `search` query
- [x] Release the feature preview for 1st party hosts
```
