### ISSUE TITLE
[Project] New Expense flow QA, testing & beta release

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7726]
## Overview

In its current state, the new expense flow is not ready to be released - even as a public beta. There are significant blocking bugs that need to be addressed first. Besides, the flow is not covered by a single end-to-end test, which is not acceptable for such a critical feature. If we want to ship this project, we should therefore:

1. Document all bugs in a central place (ideally GIthub)
2. Prioritize them & work on all the blocking ones
3. Increase E2E tests coverage to an acceptable ratio
4. Have more internal tests
5. Once we’re satisfied with the rest, open to public beta

## Ownership

**Ownership:** @Betree 

_Note: Project owner responsibilities include coordinating all the different people that need to contribute to the project, defining specs and goals, communicating project progress, being the point person for decisions, QA, documentation, and a plan for ongoing maintenance. If the project owner can't continue, they need to hand the role over to another person explicitly._

## Desired Outcomes

- The new expense flow meets our quality & performance expectations
- Test coverage for the new expense flow meets our expectations
- We're able to release the new expense flow as an internal beta

## Tasks

```[tasklist]
### Missing features
- [x] [Add a flag in expenses data to track which ones were submitted with the new flow](https://oficonsortium.slack.com/archives/C05KG5KB80P/p1729668289858429)
- [ ] https://github.com/opencollective/opencollective/issues/7759
- [ ] Invoice attachment saved as a distinct "invoice" file type
- [x] Missing option to set invite note
- [ ] Remember submitter policy acknowledgements
```

```[tasklist]
### Bugs
- [ ] https://github.com/opencollective/opencollective/issues/7712
- [ ] https://github.com/opencollective/opencollective/issues/7744
- [ ] https://github.com/opencollective/opencollective/issues/7745
- [ ] https://github.com/opencollective/opencollective/issues/7746
- [ ] https://github.com/opencollective/opencollective/issues/7754
- [ ] https://github.com/opencollective/opencollective/issues/7747
- [ ] https://github.com/opencollective/opencollective/issues/7748
- [ ] https://github.com/opencollective/opencollective/issues/7749
- [ ] https://github.com/opencollective/opencollective/issues/7750
- [ ] https://github.com/opencollective/opencollective/issues/7751
- [ ] https://github.com/opencollective/opencollective/issues/7752
- [ ] https://github.com/opencollective/opencollective/issues/7753
- [ ] https://github.com/opencollective/opencollective/issues/7755
- [ ] https://github.com/opencollective/opencollective/issues/7771
- [ ] https://github.com/opencollective/opencollective/issues/7766
- [x] Expense success screen header says "Invoice 124 has been .." despite it being an reimbursement
- [x] Can't add Expense title before touching expense items
- [x] Missing "invite note" input when inviting existing account
```

```[tasklist]
### Testing
- [x] Cover the create expense behavior with E2e tests
- [x] Cover the invite expense behavior with E2e tests
- [ ] ~Cover the edit expense behaviors with E2e tests~ to be completed separately
- [x] Test on mobile
```

```[tasklist]
### Polishing
- [x] [When I swap currency, I don't need the error message telling me the value should not be zero](https://oficonsortium.slack.com/archives/C05KG5KB80P/p1720074190950569)
- [ ] [Invite expense: you have to define whether there is an invoice or if you would like them generated. This should be optional and left for the invitee to fill in. Same with other fields like description and title.](https://oficonsortium.slack.com/archives/C05KG5KB80P/p1734031251025149)
- [ ] https://github.com/opencollective/opencollective/issues/7787
- [ ] https://github.com/opencollective/opencollective/issues/7761
- [ ] https://github.com/opencollective/opencollective/issues/7762
- [ ] https://github.com/opencollective/opencollective/issues/7763
- [x] Performance is not great, any work to make the form faster is welcome.
- [ ] https://github.com/opencollective/opencollective/issues/7760
- [x] Missing loading state on submit
- [ ] https://github.com/opencollective/opencollective/issues/7772
- [ ] https://github.com/opencollective/opencollective/issues/7810
- [ ] https://github.com/opencollective/opencollective/issues/7825
- [x] Update UI of expense invite message box
- [ ] https://github.com/opencollective/opencollective/issues/7854
- [ ] https://github.com/opencollective/opencollective/issues/7853
- [ ] https://github.com/opencollective/opencollective/issues/7852
```

```[tasklist]
### Release
- [ ] https://github.com/opencollective/opencollective/issues/7764
```

## Context & related issues

- https://github.com/opencollective/opencollective/issues/7606
- https://github.com/opencollective/opencollective/issues/7683

**Comment by Betree** [comment]
**This week**
- [ ] Solve more issues

**Comment by Betree** [comment]
**This week**
- [ ] Wrap up payout method input @gustavlrsn 
- [ ] Loading states, jumping blocks & other minor UI enhancements @gustavlrsn 
- [ ] Implement invite submission in the new expense flow @hdiniz 
- [ ] Sync & go over the design, check the "signed out" experience
- [ ] Still working on perfs @hdiniz

**Comment by Betree** [comment]
- [ ] Differentiation between invoice attachments
- [ ] Add a flag to track if the expense was submitted in the new flow
- [ ] E2e tests
- [ ] Look at Slack feedback

**Comment by Mahmoudhanfy2949** [comment]
Open source

**Comment by Betree** [comment]
**This week**
- [ ] Differentiation between invoice attachments
- [ ] Look at E2e tests
- [ ] Merge payout method name iteration
- [x] Sync with design to review smaller fixes
- [ ] Implement small design fixes
